//BASTARD SWORD +1 - 1500mo//
COPY "rick_bigg_mod/items/SW1H02.itm" "override"
	SAY NAME1 "Bastard Sword"
	SAY UNIDENTIFIED_DESC "Also known as the hand-and-a-half sword, the bastard sword derives its name from the fact that it is halfway between the two-handed sword and the long sword. The bastard sword has a double-edged blade and a long grip, which can accommodate both hands if preferred. The overall length of the bastard sword ranges between four feet and four feet ten inches.

STATISTICS:

Damage: 2d4+1 (slashing)
Speed Factor: 8
Proficiency Type: Bastard Sword
Type: One-handed
Requires:
 15 Strength

Weight: 10"

	SAY NAME2 "Bastard Sword +1"
	SAY DESC "Not only has a smith made this sword so that it is better balanced and more durable than a standard blade, powerful enchantments have also been placed on it. It is faster, more accurate, and hits for far more damage than the standard of its type. 

STATISTICS:

THAC0: +1
Damage: 2d4+2 (slashing)
Speed Factor: 7
Proficiency Type: Bastard Sword
Type: One-handed
Requires:
 15 Strength

Weight: 9"
















//BASTARD SWORD +2 - 2500mo//
COPY "rick_bigg_mod/items/SW1H42.itm" "override"
	SAY NAME1 "Bastard Sword"
	SAY UNIDENTIFIED_DESC "Also known as the hand-and-a-half sword, the bastard sword derives its name from the fact that it is halfway between the two-handed sword and the long sword. The bastard sword has a double-edged blade and a long grip, which can accommodate both hands if preferred. The overall length of the bastard sword ranges between four feet and four feet ten inches.

STATISTICS:

Damage: 2d4+1 (slashing)
Speed Factor: 8
Proficiency Type: Bastard Sword
Type: One-handed
Requires:
 15 Strength

Weight: 10"

	SAY NAME2 "Bastard Sword +2"
	SAY DESC "Not only has a smith made this sword so that it is better balanced and more durable than a standard blade, powerful enchantments have also been placed on it. It is faster, more accurate, and hits for far more damage than the standard of its type. 

STATISTICS:

THAC0: +2
Damage: 2d4+3 (slashing)
Speed Factor: 6
Proficiency Type: Bastard Sword
Type: One-handed
Requires:
 15 Strength

Weight: 8"






//KONDAR +2 - 5000mo//
COPY "rick_bigg_mod/items/TB#KOND.itm" "override"
	SAY NAME1 "Bastard Sword"
	SAY UNIDENTIFIED_DESC "Also known as the hand-and-a-half sword, the bastard sword derives its name from the fact that it is halfway between the two-handed sword and the long sword. The bastard sword has a double-edged blade and a long grip, which can accommodate both hands if preferred. The overall length of the bastard sword ranges between four feet and four feet ten inches.

STATISTICS:

Damage: 2d4+1 (slashing)
Speed Factor: 8
Proficiency Type: Bastard Sword
Type: One-handed
Requires:
 15 Strength

Weight: 10"

	SAY NAME2 "Kondar +2"
	SAY DESC "At a first glance, this sword appears much like any other. In the presence of any shapeshifting creature, however, the blade becomes warm as its power stirs. Its namesake was the original owner of the weapon, and his tale, though mostly long forgotten, was wrought with treachery and deceit. Rumors persist that he paid a fearsome price for this blade, but with it he revealed the true identities of those that sought to betray him. Their names and crimes however, are long since lost to history.

STATISTICS:

THAC0: +2, +4 vs. shapeshifters
Damage: 2d4+3, +5 vs. shapeshifters
Speed Factor: 6
Proficiency Type: Bastard Sword
Type: One-handed
Requires:
 15 Strength

Weight: 8"











//SWORD OF BALDURAN +2 - 8000mo//
COPY "rick_bigg_mod/items/SW1H18.itm" "override"
	SAY NAME1 "Bastard Sword"
	SAY UNIDENTIFIED_DESC "Also known as the hand-and-a-half sword, the bastard sword derives its name from the fact that it is halfway between the two-handed sword and the long sword. The bastard sword has a double-edged blade and a long grip, which can accommodate both hands if preferred. The overall length of the bastard sword ranges between four feet and four feet ten inches.

STATISTICS:

Damage: 2d4+1 (slashing)
Speed Factor: 8
Proficiency Type: Bastard Sword
Type: One-handed
Requires:
 15 Strength

Weight: 10"

	SAY NAME2 "Sword of Balduran +2"
	SAY DESC "This mighty weapon is the legendary sword of the hero Balduran. Made entirely of gold, yet stronger than steel, this sword is imbued with a great magical power. It accompanied the hero through all his battles, including his final, sad adventure.

STATISTICS:

Equipped abilities:
– Save vs. Wand: +2
- Lore: +40

Charge abilities:
- Cast True Strike twice per day

THAC0: +2, +3 vs. Monsters
Damage: 2d4+3, +4 vs. Monsters
Damage type: Slashing
Speed Factor: 6
Proficiency Type: Bastard Sword
Type: One-handed
Requires:
 15 Strength

Weight: 7"






//DAYSTAR +2 - valore 10000mo - no evil//
COPY "rick_bigg_mod/items/SW1H31.itm" "override"
	SAY NAME1 "Bastard Sword"
	SAY UNIDENTIFIED_DESC "Also known as the hand-and-a-half sword, the bastard sword derives its name from the fact that it is halfway between the two-handed sword and the long sword. The bastard sword has a double-edged blade and a long grip, which can accommodate both hands if preferred. The overall length of the bastard sword ranges between four feet and four feet ten inches.

STATISTICS:

Damage: 2d4+1 (slashing)
Speed Factor: 8
Proficiency Type: Bastard Sword
Type: One-handed
Requires:
 15 Strength

Weight: 10"

	SAY NAME2 "Daystar +2"
	SAY DESC "Whether created specifically for use in the service of Torm or appropriated at some point in the long history of the church, paladins of the Loyal Fury have made good use of Daystar in their battles against evil undead. Through magic or blessing it is empowered with the Sunray, a force of pure life energy so potent that it slays both living and unliving.

STATISTICS:

Charge abilities:
– Sunray once per day
 Damage: 3d6 (Save vs. Spell or be blinded for 1 turn)
 Undead: An additional 1d6 points of damage per level of caster (Save vs. Spell or be destroyed)
 Range: 20 ft.
 Area: 15-ft. radius

THAC0: +2, +4 vs. evil creatures
Damage: 2d4+3, +4 vs. evil creatures, does double damage against undead
Damage type: Slashing
Speed Factor: 6
Proficiency Type: Bastard Sword
Type: One-handed
Requires:
 15 Strength

Weight: 8
"




//PERIDAN +3 - valore 8000mo//
COPY "rick_bigg_mod/items/SW1H32.itm" "override"
	SAY NAME1 "Bastard Sword"
	SAY UNIDENTIFIED_DESC "Also known as the hand-and-a-half sword, the bastard sword derives its name from the fact that it is halfway between the two-handed sword and the long sword. The bastard sword has a double-edged blade and a long grip, which can accommodate both hands if preferred. The overall length of the bastard sword ranges between four feet and four feet ten inches.

STATISTICS:

Damage: 2d4+1 (slashing)
Speed Factor: 8
Proficiency Type: Bastard Sword
Type: One-handed
Requires:
 15 Strength

Weight: 10"

	SAY NAME2 "Peridan +3"
	SAY DESC "Few dare to create items such as this, for who does not fear the wrath of dragons, and what action would more tempt their reckoning? Yet, at a time lost in Faerûn's past, there was a need, and this sword was forged in answer. Tempered by a wizard's skill, this blade protects the wielder from the fear they should rightly feel while staring down a dragon's maw. It also bolsters with regeneration, and protects against dragon's breath.

STATISTICS:

Equipped abilities: 
– Immunity to fear
– Regenerate 1 Hit Point every 1 turn

Charge abilities:
– Protection from the Elements once per day

THAC0: +3
Damage: 2d4+4, +5 against dragons
Damage type: Slashing
Speed Factor: 5
Proficiency Type: Bastard Sword
Type: One-handed
Requires:
 15 Strength

Weight: 7"








//BRASS BLADE +3 - valore 8000mo //
COPY "rick_bigg_mod/items/OHDSW03.itm" "override"
	SAY NAME1 "Bastard Sword"
	SAY UNIDENTIFIED_DESC "Also known as the hand-and-a-half sword, the bastard sword derives its name from the fact that it is halfway between the two-handed sword and the long sword. The bastard sword has a double-edged blade and a long grip, which can accommodate both hands if preferred. The overall length of the bastard sword ranges between four feet and four feet ten inches.

STATISTICS:

Damage: 2d4+1 (slashing)
Speed Factor: 8
Proficiency Type: Bastard Sword
Type: One-handed
Requires:
 15 Strength

Weight: 10"

	SAY NAME2 "Brass Blade +3"
	SAY DESC "This flaming, magical bastard sword was forged in the Elemental Plane of Fire's City of Brass. It was stolen from the city many centuries ago, leaving a long trail of dead behind it as the sultan who oversaw its construction attempted to hunt it down. Over time, his anger cooled and his memory faded, and the sword was left to continually change hands between mortals.

STATISTICS:

Equipped Abilities:
– Fire Resistance: +30%

THAC0: +3
Damage: 2d4+4, +3 fire damage
Damage type: Slashing
Speed Factor: 5
Proficiency Type: Bastard Sword
Type: One-handed
Requires:
 15 Strength

Weight: 7
"






//JHOR THE BLEEDER + 4 - valore 9000mo //
COPY "rick_bigg_mod/items/SW1H38.itm" "override"
	SAY NAME1 "Bastard Sword"
	SAY UNIDENTIFIED_DESC "Also known as the hand-and-a-half sword, the bastard sword derives its name from the fact that it is halfway between the two-handed sword and the long sword. The bastard sword has a double-edged blade and a long grip, which can accommodate both hands if preferred. The overall length of the bastard sword ranges between four feet and four feet ten inches.

STATISTICS:

Damage: 2d4+1 (slashing)
Speed Factor: 8
Proficiency Type: Bastard Sword
Type: One-handed
Requires:
 15 Strength

Weight: 10"

	SAY NAME2 "Jhor the Bleeder +4"
	SAY DESC "This blade belonged to Ho Mang, a traveler from Kara-Tur who accepted dubious service at courts throughout Faerûn. Skilled in 'persuasion',he would use this sword to perform the 'Death Of A Thousand Cuts', an ancient ritual from his homeland involving a lengthy series of small, painful incisions. The properties of the blade prevent blood from clotting, and the victim slowly bleeds to death. The sword was stolen, and its whereabouts have been a mystery until now.

STATISTICS:

Combat abilities:
– 2 extra damage every round until 10 Hit Points of damage done

THAC0: +4
Damage: 2d4+5 (slashing)
Speed Factor: 4
Proficiency Type: Bastard Sword
Type: One-handed
Requires:
 15 Strength

Weight: 5
"





//VIPER'S EDGE +4 - valore 12000mo - no good//
COPY "rick_bigg_mod/items/SW1P01.itm" "override"
	SAY NAME1 "Bastard Sword"
	SAY UNIDENTIFIED_DESC "Also known as the hand-and-a-half sword, the bastard sword derives its name from the fact that it is halfway between the two-handed sword and the long sword. The bastard sword has a double-edged blade and a long grip, which can accommodate both hands if preferred. The overall length of the bastard sword ranges between four feet and four feet ten inches.

STATISTICS:

Damage: 2d4+1 (slashing)
Speed Factor: 8
Proficiency Type: Bastard Sword
Type: One-handed
Requires:
 15 Strength

Weight: 10"

	SAY NAME2 "Viper's Edge +4"
	SAY DESC "This immensely powerful relic is just as strongly enchanted as it is cursed. Its blade shimmers in a slick, intoxicating tinge of green, likely literally as well as metaphorically. The sword's grip and hilt are lined by curved thorns which make it hard to see how this weapon could be effectively wielded in battle. Judging by the dried crusts around them, many have still tried, and you cannot deny feeling a tempting curiosity on your part. Said to be originally the weapon of a medusa queen of a long forgotten age bestowed to whom by the gods of old themselves, the exact origins of this blade have been lost to time. Whatever its provenance, it has since traveled through many hands (albeit the majority not of the living persuasion). The common thread running through all these encounters was that their eventual end was rarely of a voluntary nature and nothing good ever came from them.

STATISTICS:

Cursed:
– Constitution: -2
– Maximum Hit Points: -10%
– Intolerance to common healing potions

Equipped abilities:
– Dexterity: +2
– +1 attack per round
– Regeneration on critical health (below 10% health)

Combat abilities:
0-5 Petrify target (Save vs Petrify -4)
6-25 Paralyze target for 7 seconds (Save vs Wand -4)
26-70 Poison target (1 damage per second for twenty seconds)
71-86 Poison self (1 damage per second for twenty seconds)
86-95 Paralyze self for 7 seconds (Save vs Wand -4)
96-100 Petrify self (Save vs Petrify -4)

STATISTICS:

THAC0: +4 bonus
Damage: 2d4+5 (slashing)
Speed Factor: 4
Proficiency Type: Bastard Sword
Type: One-handed
Requires:
 15 Strength

Weight: 6
"






//ANGURVADAL +4 - valore 9000mo//
COPY "rick_bigg_mod/items/SW1H60.itm" "override"
	SAY NAME1 "Bastard Sword"
	SAY UNIDENTIFIED_DESC "Also known as the hand-and-a-half sword, the bastard sword derives its name from the fact that it is halfway between the two-handed sword and the long sword. The bastard sword has a double-edged blade and a long grip, which can accommodate both hands if preferred. The overall length of the bastard sword ranges between four feet and four feet ten inches.

STATISTICS:

Damage: 2d4+1 (slashing)
Speed Factor: 8
Proficiency Type: Bastard Sword
Type: One-handed
Requires:
 15 Strength

Weight: 10"

	SAY NAME2 "Angurvadal +4"
	SAY DESC "Also known as the Stream of Anguish, this is the legendary corrosive blade of Frithiof. 

STATISTICS:

THAC0: +4
Damage: 2d4+5, +1d6 acid damage
Damage type: Slashing
Speed Factor: 4
Proficiency Type: Bastard Sword
Type: One-handed
Requires:
 15 Strength

Weight: 7"




//ANGURVADAL +5 - valore 21000mo//
COPY "rick_bigg_mod/items/SW1H61.itm" "override"
	SAY NAME1 "Bastard Sword"
	SAY UNIDENTIFIED_DESC "Also known as the hand-and-a-half sword, the bastard sword derives its name from the fact that it is halfway between the two-handed sword and the long sword. The bastard sword has a double-edged blade and a long grip, which can accommodate both hands if preferred. The overall length of the bastard sword ranges between four feet and four feet ten inches.

STATISTICS:

Damage: 2d4+1 (slashing)
Speed Factor: 8
Proficiency Type: Bastard Sword
Type: One-handed
Requires:
 15 Strength

Weight: 10"

	SAY NAME2 "Angurvadal +5"
	SAY DESC "Also known as the Stream of Anguish, this is the legendary corrosive blade of Frithiof. 
	The true power of this sword has been unleashed by the Liquid Mercury.

STATISTICS:

Combat abilities:
- 5% chance cast Black Dragon's Breath (24d4+12 acid damage save vs. Breath for half, enemies only)

THAC0: +5
Damage: 2d4+6, +2d6 acid damage
Damage type: Slashing
Speed Factor: 3
Proficiency Type: Bastard Sword
Type: One-handed
Requires:
 15 Strength

Weight: 7"






//ANDURIL +5 - no evil - valore 17000mo//
COPY "rick_bigg_mod/items/SW1H65.itm" "override"
	SAY NAME1 "Bastard Sword"
	SAY UNIDENTIFIED_DESC "Also known as the hand-and-a-half sword, the bastard sword derives its name from the fact that it is halfway between the two-handed sword and the long sword. The bastard sword has a double-edged blade and a long grip, which can accommodate both hands if preferred. The overall length of the bastard sword ranges between four feet and four feet ten inches.

STATISTICS:

Damage: 2d4+1 (slashing)
Speed Factor: 8
Proficiency Type: Bastard Sword
Type: One-handed
Requires:
 15 Strength

Weight: 10"

	SAY NAME2 "Anduril +5"
	SAY DESC "This sword belonged to a line of great kings from another world. Shattered and then reforged, it retained its power through the centuries and contributed to the victory over the Dark Lord of Mordor.

STATISTICS:

Equipped abilities:
– Magic resistance: +10%
- Critical hit chance: +10% (only with this weapon)

Combat abilities:
- On a critical hit deals 10 Magic damage

THAC0: +5
Damage: 2d4+6
Damage type: Slashing
Speed Factor: 3
Proficiency Type: Bastard Sword
Type: One-handed
Requires:
 15 Strength

Weight: 5"