//CHAIN MAIL +1 - 2000mo//
COPY "rick_bigg_mod/items/CHAN02.itm" "override"
	SAY NAME1 "Chain Mail"
	SAY UNIDENTIFIED_DESC "Chain mail is made of interlocking metal rings. It is always worn over a layer of padded fabric or soft leather to prevent chafing and lessen the impact of blows. 

STATISTICS:

Armor Class: 5 (3 vs. slashing, 4 vs. piercing and missile)
Speed Factor: -2
Requires:
 9 Strength

Weight: 40
"

	SAY NAME2 "Chain Mail +1"
	SAY DESC "Chain mail is made of interlocking metal rings. It is always worn over a layer of padded fabric or soft leather to prevent chafing and lessen the impact of blows.  Extra protection is given by magical enchantments placed on this armor.

STATISTICS:

Armor Class: 4 (2 vs. slashing, 3 vs. piercing and missile)
Speed Factor: -2
Requires:
 9 Strength

Weight: 20
"


//CHAIN MAIL +2 - 4000mo//
COPY "rick_bigg_mod/items/CHAN08.itm" "override"
	SAY NAME1 "Chain Mail"
	SAY UNIDENTIFIED_DESC "Chain mail is made of interlocking metal rings. It is always worn over a layer of padded fabric or soft leather to prevent chafing and lessen the impact of blows. 

STATISTICS:

Armor Class: 5 (3 vs. slashing, 4 vs. piercing and missile)
Speed Factor: -2
Requires:
 9 Strength

Weight: 40
"

	SAY NAME2 "Chain Mail +2"
	SAY DESC "Chain mail is made of interlocking metal rings. It is always worn over a layer of padded fabric or soft leather to prevent chafing and lessen the impact of blows.  Extra protection is given by magical enchantments placed on this armor.

STATISTICS:

Armor Class: 3 (1 vs. slashing, 2 vs. piercing and missile)
Speed Factor: -2
Requires:
 9 Strength

Weight: 15
"






//MAIL OF THE DEAD +2 - 6000mo//
COPY "rick_bigg_mod/items/TB#CHAN.itm" "override"
	SAY NAME1 "Chain Mail"
	SAY UNIDENTIFIED_DESC "Chain mail is made of interlocking metal rings. It is always worn over a layer of padded fabric or soft leather to prevent chafing and lessen the impact of blows. 

STATISTICS:

Armor Class: 5 (3 vs. slashing, 4 vs. piercing and missile)
Speed Factor: -2
Requires:
 9 Strength

Weight: 40
"

	SAY NAME2 "Mail of the Dead +2"
	SAY DESC "A mage can make an extremely effective assassin, as Vorusta illustrated over four hundred years ago. He would create skeleton warriors equipped with this enchanted armor and a powerful blade, and give their circlet of power to the target as a friendly gift. When the killing machine was through with its work, Vorusta retrieved the equipment and started the entire process over.

STATISTICS:

Equipped abilities:
- Magic Resistance: +10%
- Slashing Resistance: +5%
- Piercing Resistance: +5%
- Missile Resistance: +5%
- Crushing Resistance: -5%

Armor Class: 3 (1 vs. slashing, 2 vs. piercing and missile)
Speed Factor: -2
Requires:
 9 Strength

Weight: 15
"




//DARKMAIL +3 - 6500mo//
COPY "rick_bigg_mod/items/CHAN09.itm" "override"
	SAY NAME1 "Chain Mail"
	SAY UNIDENTIFIED_DESC "Chain mail is made of interlocking metal rings. It is always worn over a layer of padded fabric or soft leather to prevent chafing and lessen the impact of blows. 

STATISTICS:

Armor Class: 5 (3 vs. slashing, 4 vs. piercing and missile)
Speed Factor: -2
Requires:
 9 Strength

Weight: 40
"

	SAY NAME2 "Darkmail +3"
	SAY DESC "Whether by design or through exposure to intense heat in battle, the chain links of this armor are coal black throughout. While legends usually speak of knights in shining armor facing great beasts, the fire resistant enchantment on this suit suggests equally great, if unheralded, battles with fire-breathing creatures.

STATISTICS:

Equipped abilities:
– Fire Resistance: +30%

Armor Class: 2 (0 vs. slashing, 1 vs. piercing and missile)
Speed Factor: -2
Requires:
 9 Strength

Weight: 10
"





//COMMANDER CHAIN MAIL +3 - 7500mo//
COPY "rick_bigg_mod/items/BDCHAN04.itm" "override"
	SAY NAME1 "Chain Mail"
	SAY UNIDENTIFIED_DESC "Chain mail is made of interlocking metal rings. It is always worn over a layer of padded fabric or soft leather to prevent chafing and lessen the impact of blows. 

STATISTICS:

Armor Class: 5 (3 vs. slashing, 4 vs. piercing and missile)
Speed Factor: -2
Requires:
 9 Strength

Weight: 40"

	SAY NAME2 "Commander Chain Mail +3"
	SAY DESC "As soon as you put it on, this chain mail exudes a powerful aura of confidence and courage that immediately influences all allies at your side. Its origins are uncertain, but it appears to have belonged to a great Tethyrian leader.

STATISTICS:

Equipped abilities:
– Charisma: +1
– The wearer and any allies within <PRO_HISHER> visual radius are immune to fear and morale failure

Armor Class: 2 (0 vs. slashing, 1 vs. piercing and missile)
Speed Factor: -2
Requires:
 9 Strength

Weight: 10
"





//ASHEN CHAIN +3 - 7000mo//
COPY "rick_bigg_mod/items/CHAN17.itm" "override"
	SAY NAME1 "Chain Mail"
	SAY UNIDENTIFIED_DESC "Chain mail is made of interlocking metal rings. It is always worn over a layer of padded fabric or soft leather to prevent chafing and lessen the impact of blows. 

STATISTICS:

Armor Class: 5 (3 vs. slashing, 4 vs. piercing and missile)
Speed Factor: -2
Requires:
 9 Strength

Weight: 40"

	SAY NAME2 "Ashen Chain +3"
	SAY DESC "Instead of metal strips, this armor uses wyvern scales bound to a chain backing by means of a magical fire. The resulting armor is ash-gray in color and more flexible than standard chain mail. A ranger, Usher Skacan, made this armor after slaying several wyverns that were killing all the deer and elk in his forest.

STATISTICS:

Equipped abilities:
– Poison damage resistance: +50%

Armor Class: 2 (0 vs. slashing, 1 vs. piercing and missile)
Speed Factor: -1
Requires:
 9 Strength

Weight: 10
"



//JESTER'S CHAIN +3 - solo bardi - 9000mo//
COPY "rick_bigg_mod/items/CHAN10.itm" "override"
	SAY NAME1 "Chain Mail"
	SAY UNIDENTIFIED_DESC "Chain mail is made of interlocking metal rings. It is always worn over a layer of padded fabric or soft leather to prevent chafing and lessen the impact of blows. 

STATISTICS:

Armor Class: 5 (3 vs. slashing, 4 vs. piercing and missile)
Speed Factor: -2
Requires:
 9 Strength

Weight: 40
"

	SAY NAME2 "Jester's Chain +3"
	SAY DESC "Friends of Dekirh Fasthands, a bard who insisted on playing the rowdiest towns on the Sword Coast, gave him this suit of magical chain as a gift. The chain mail was given to protect Dekirh from the drunken spectators who often threw rotting produce, chairs, and even knives at Dekirh. The bard appreciated the gift but painted it with wild colors to better fit into his show.

STATISTICS:

Equipped abilities:
- Protection from missiles

Armor Class: 2 (0 vs. slashing, 1 vs. piercing and missile)
Speed Factor: -2
Requires:
 9 Strength

Weight: 10
"



//MITHRIL CHAIN MAIL +5 - 14000mo//
COPY "rick_bigg_mod/items/CHAN06.itm" "override"
	SAY NAME1 "Chain Mail"
	SAY UNIDENTIFIED_DESC "Chain mail is made of interlocking metal rings. It is always worn over a layer of padded fabric or soft leather to prevent chafing and lessen the impact of blows. 

STATISTICS:

Armor Class: 5 (3 vs. slashing, 4 vs. piercing and missile)
Speed Factor: -2
Requires:
 9 Strength

Weight: 40
"

	SAY NAME2 "Mithril Chain Mail +5"
	SAY DESC "This is the personal armor of Drizzt, the famous dark elf Ranger. It was forged for him by his friend Bruenor.

STATISTICS:

Equipped abilities:
– Open Locks: -5%
– Find Traps: -5%
– Pick Pockets: -20%
– Move Silently: -10%
- Hide in Shadows: -10%
– Spellcasting is not disabled

Armor Class: 0 (-2 vs. slashing, -1 vs. piercing, -4 vs. missile)
Requires:
 9 Strength

Weight: 10
"


//CRIMSON CHAIN +4 - 12000mo//
COPY "rick_bigg_mod/items/CHAN11.itm" "override"
	SAY NAME1 "Chain Mail"
	SAY UNIDENTIFIED_DESC "Chain mail is made of interlocking metal rings. It is always worn over a layer of padded fabric or soft leather to prevent chafing and lessen the impact of blows. 

STATISTICS:

Armor Class: 5 (3 vs. slashing, 4 vs. piercing and missile)
Speed Factor: -2
Requires:
 9 Strength

Weight: 40"

	SAY NAME2 "Crimson Chain +4"
	SAY DESC "The dark red metal used to make this chain is said to come from a hidden mine in the Cloudpeaks. At one time the Bloodway, a band of evil adventurers, all wore armor of this kind, but the other suits have long been lost.

STATISTICS:

Equipped abilities:
- Crushing Damage Resistance: +20%

Armor Class: 1 (-1 vs. slashing, -0 vs. piercing and missile)
Speed Factor: -2
Requires:
 9 Strength

Weight: 10
"







//WHITE DRAGON SCALE - 14000mo//
COPY "rick_bigg_mod/items/CHAN20.itm" "override"
	SAY NAME1 "Chain Mail"
	SAY UNIDENTIFIED_DESC "Chain mail is made of interlocking metal rings. It is always worn over a layer of padded fabric or soft leather to prevent chafing and lessen the impact of blows. 

STATISTICS:

Armor Class: 5 (3 vs. slashing, 4 vs. piercing and missile)
Speed Factor: -2
Requires:
 9 Strength

Weight: 40"

	SAY NAME2 "White Dragon Scale"
	SAY DESC "Not surprisingly, this armor created from the scales of a young ice dragon provides the wearer with protection from cold and ice.

STATISTICS:

Equipped abilities:
– Cold Resistance: +40%

Armor Class: 0 (-2 vs. slashing, -1 vs. piercing, -3 vs. missile)
Speed Factor: -2
Requires:
 10 Strength

Weight: 15
"








//ELVEN CHAIN MAIL +1 - 5000mo//
COPY "rick_bigg_mod/items/CHAN12.itm" "override"
	SAY NAME1 "Chain Mail"
	SAY UNIDENTIFIED_DESC "This chainmail clearly bears the hand of a great elvensmith, with their typical beauty and delicate sturdy craftsmanship.

STATISTICS:

Armor Class: 5 (3 vs. slashing, 4 vs. piercing and missile)
Requires:
 5 Strength

Weight: 8
"

	SAY NAME2 "Elven Chain Mail +1"
	SAY DESC "The delicate yet sturdy craftsmanship of the elven races allows them to design many beautiful yet utilitarian goods. Among these is elven chain mail, which is so finely wrought that it can be worn under normal clothing without revealing its presence. This and its lightness allows it to be worn by Thieves and Fighter/Mages with few restrictions. Extra protection is given by magical enchantments placed on this armor.

STATISTICS:

Equipped abilities:
– Open Locks: -5%
– Find Traps: -5%
– Pick Pockets: -20%
– Move Silently: -10%
- Hide in Shadows: -10%

Armor Class: 4 (2 vs. slashing, 3 vs. piercing and missile)
Requires:
 5 Strength

Weight: 8
"





//ELVEN CHAIN MAIL +2 - 5000mo//
COPY "rick_bigg_mod/items/CHAN13.itm" "override"
	SAY NAME1 "Chain Mail"
	SAY UNIDENTIFIED_DESC "This chainmail clearly bears the hand of a great elvensmith, with their typical beauty and delicate sturdy craftsmanship.

STATISTICS:

Armor Class: 5 (3 vs. slashing, 4 vs. piercing and missile)
Requires:
 5 Strength

Weight: 8
"

	SAY NAME2 "Elven Chain Mail +2"
	SAY DESC "The delicate yet sturdy craftsmanship of the elven races allows them to design many beautiful yet utilitarian goods. Among these is elven chain mail, which is so finely wrought that it can be worn under normal clothing without revealing its presence. This and its lightness allows it to be worn by Thieves and Fighter/Mages with few restrictions. Extra protection is given by magical enchantments placed on this armor.

STATISTICS:

Equipped abilities:
– Open Locks: -5%
– Find Traps: -5%
– Pick Pockets: -20%
– Move Silently: -10%
- Hide in Shadows: -10%

Armor Class: 3 (1 vs. slashing, 2 vs. piercing and missile)
Requires:
 5 Strength

Weight: 6
"




//MELODIC CHAIN +2 - 8000mo//
COPY "rick_bigg_mod/items/CHAN15.itm" "override"
	SAY NAME1 "Chain Mail"
	SAY UNIDENTIFIED_DESC "This chainmail clearly bears the hand of a great elvensmith, with their typical beauty and delicate sturdy craftsmanship.

STATISTICS:

Armor Class: 5 (3 vs. slashing, 4 vs. piercing and missile)
Requires:
 5 Strength

Weight: 8
"

	SAY NAME2 "Melodic Chain +2"
	SAY DESC "The Bards of Melody were a small band of half-elf bardic warriors who entertained and defended scattered elven communities throughout Calimshan. Enchantments allowed only minstrels to wear their armor, the magical links sliding together to produce beautiful melodies as they danced or fought. Unfortunately, the Bards of Melody were disbanded hundreds of years ago, and the secret of 'playing' the armor faded with them.

STATISTICS:

Equipped abilities:
– Open Locks: -5%
– Find Traps: -5%
– Pick Pockets: -20%
– Move Silently: -10%
- Hide in Shadows: -10%

Combat abilities:
- On hit the attacker takes -1 penalty to Luck for 1 round (non-cumulative)

Armor Class: 3 (1 vs. slashing, 2 vs. piercing and missile)
Requires:
 5 Strength

Weight: 6
"







//BLADESINGER CHAIN +3 - 13000mo//
COPY "rick_bigg_mod/items/CHAN16.itm" "override"
	SAY NAME1 "Chain Mail"
	SAY UNIDENTIFIED_DESC "This chainmail clearly bears the hand of a great elvensmith, with their typical beauty and delicate sturdy craftsmanship.

STATISTICS:

Armor Class: 5 (3 vs. slashing, 4 vs. piercing and missile)
Requires:
 5 Strength

Weight: 8
"

	SAY NAME2 "Bladesinger Chain +3"
	SAY DESC "Forged by master elven smiths for the legendary Bladesingers, this armor moves with fluid grace, humming a soft, harmonic melody during combat. Its links are magically bound to effortlessly deflect aggressive sword strokes, making it the pinnacle of elven craft and a truly blessed item.

STATISTICS:

Equipped abilities:
– Open Locks: -5%
– Find Traps: -5%
– Pick Pockets: -20%
– Move Silently: -10%
- Hide in Shadows: -10%

Armor Class: 2 (-3 vs. slashing, -2 vs. piercing, 1 vs. missile)
Requires:
 5 Strength

Weight: 5
"






//SYLVAN CHAIN +3 - 12000mo//
COPY "rick_bigg_mod/items/CHAN14.itm" "override"
	SAY NAME1 "Chain Mail"
	SAY UNIDENTIFIED_DESC "This chainmail clearly bears the hand of a great elvensmith, with their typical beauty and delicate sturdy craftsmanship.

STATISTICS:

Armor Class: 5 (3 vs. slashing, 4 vs. piercing and missile)
Requires:
 5 Strength

Weight: 8
"

	SAY NAME2 "Sylvan Chain +3"
	SAY DESC "This light but strong mail is of sylvan elf construction, and therefore its elegance is only exceeded by its rarity. Normally granted only to especially brave elves, seldom is this armor be found outside of a wood elf tribe, and rarer still on someone not of elven lineage.

STATISTICS:

Equipped abilities:
– Open Locks: -5%
– Find Traps: -5%
– Pick Pockets: -20%
- Dexterity: +2

Armor Class: 2 (0 vs. slashing, 1 vs. piercing and missile)
Requires:
 5 Strength

Weight: 5
"



//ASLYFERUND ELVEN CHAIN +3 - 15000mo//
COPY "rick_bigg_mod/items/CHAN19.itm" "override"
	SAY NAME1 "Chain Mail"
	SAY UNIDENTIFIED_DESC "This chainmail clearly bears the hand of a great elvensmith, with their typical beauty and delicate sturdy craftsmanship.

STATISTICS:

Armor Class: 5 (3 vs. slashing, 4 vs. piercing and missile)
Requires:
 5 Strength

Weight: 8
"

	SAY NAME2 "Aslyferund Elven Chain +3"
	SAY DESC "Crafted in exile after the fall of Myth Drannor, this magnificent suit of elven chainmail is the tragic masterpiece of the elven smith Aslyferund. Driven by a desire to surpass his peers, he discovered a secret method to gild traditional mithral links with a rare, enchanted gold alloy, binding them with heavy layers of abjuration magic.The resulting armor offers unparalleled protection against elemental and magical forces while still allowing the casting of spells. Sadly, Aslyferund’s refusal to share his secret led to his brutal murder by a jealous rival. The secret died with him, leaving this armor as the only one of its kind in Faerûn.

STATISTICS:

Equipped abilities:
– Open Locks: -5%
– Find Traps: -5%
– Pick Pockets: -20%
– Move Silently: -10%
- Hide in Shadows: -10%
- All non physical damage resistances: +20%

Armor Class: 2 (0 vs. slashing, 1 vs. piercing and missile)
Requires:
 5 Strength

Weight: 5
"