//CLOAK OF PROTECTION +1 - valore 3000mo//
COPY "rick_bigg_mod/items/CLCK01.itm" "override"
	SAY NAME1 "Cloak"
	SAY UNIDENTIFIED_DESC "The cloak can be made in every possible shape with just about every type of fabric. The most common forms are a circular piece of fabric with a hole in the center for the head, and fabric draped from neck, connected by a chain, brooch, cord, or pins.

STATISTICS:

Weight: 3"

	SAY NAME2 "Cloak of Protection +1"
	SAY DESC "This simple cloak has been imbued with magical properties to help protect its wearer. It does so by affecting both Saving Throws and Armor Class. It is ideal for Mages and others who cannot wear bulkier or more restrictive types of armor.

STATISTICS:

Equipped abilities:
– Armor Class: +1
– Saving Throws: +1

Weight: 3"




//CLOAK OF PROTECTION +2 - valore 7000mo//
COPY "rick_bigg_mod/items/CLCK02.itm" "override"
	SAY NAME1 "Cloak"
	SAY UNIDENTIFIED_DESC "The cloak can be made in every possible shape with just about every type of fabric. The most common forms are a circular piece of fabric with a hole in the center for the head, and fabric draped from neck, connected by a chain, brooch, cord, or pins.

STATISTICS:

Weight: 3"

	SAY NAME2 "Cloak of Protection +2"
	SAY DESC "This simple cloak has been imbued with powerful magical properties to help protect its wearer. It does so by affecting both Saving Throws and Armor Class. It is ideal for Mages and others who cannot wear bulkier or more restrictive types of armor.

STATISTICS:

Equipped abilities:
– Armor Class: +2
– Saving Throws: +2

Weight: 3"



//CLOAK OF PROTECTION +3 - valore 15000mo//
COPY "rick_bigg_mod/items/CLCK31.itm" "override"
	SAY NAME1 "Cloak"
	SAY UNIDENTIFIED_DESC "The cloak can be made in every possible shape with just about every type of fabric. The most common forms are a circular piece of fabric with a hole in the center for the head, and fabric draped from neck, connected by a chain, brooch, cord, or pins.

STATISTICS:

Weight: 3"

	SAY NAME2 "Cloak of Protection +3"
	SAY DESC "This simple cloak has been imbued with powerful magical properties to help protect its wearer. It does so by affecting both Saving Throws and Armor Class. It is ideal for Mages and others who cannot wear bulkier or more restrictive types of armor.
	
	Now that it has been enhanced from its previous state, its defensive capabilities are stronger than ever before.

STATISTICS:

Equipped abilities:
– Armor Class: +3
– Saving Throws: +3

Weight: 3"



//CLOAK OF DISPLACEMENT - 4000mo//
COPY "rick_bigg_mod/items/CLCK03.itm" "override"
	SAY NAME1 "Cloak"
	SAY UNIDENTIFIED_DESC "The cloak can be made in every possible shape with just about every type of fabric. The most common forms are a circular piece of fabric with a hole in the center for the head, and fabric draped from neck, connected by a chain, brooch, cord, or pins.

STATISTICS:

Weight: 3"

	SAY NAME2 "Cloak of Displacement"
	SAY DESC "This cloak is a magical item woven from shimmering, illusionary threads that cause subtle shifts in the image of its wearer. It has the power to actually bend light and space, shifting an individual's physical image by as much as six inches in any direction from their actual location. This continuous distortion leaves enemies striking at empty air, making it an invaluable defense in the heat of battle.

STATISTICS:

Equipped abilities:
– Armor Class: +4 vs. missile attacks
– Save vs. Breath: +4

Weight: 3"





//CLOAK OF THE WOLF - valore 5000mo//
COPY "rick_bigg_mod/items/CLCK04.itm" "override"
	SAY NAME1 "Cloak"
	SAY UNIDENTIFIED_DESC "The cloak can be made in every possible shape with just about every type of fabric. The most common forms are a circular piece of fabric with a hole in the center for the head, and fabric draped from neck, connected by a chain, brooch, cord, or pins.

STATISTICS:

Weight: 3"

	SAY NAME2 "Cloak of the Wolf"
	SAY DESC "A great amount of irony surrounds the creation of this magical cloak. Relair was a mage who overestimated the amount of control he had over magic, and in the course of creating this garment, he apparently inflicted lycanthropy upon himself. The wearer can change form whenever <PRO_HESHE> wishes. Relair was not so lucky.

STATISTICS:

Equipped abilities:
- Armor Class: +1

Charge abilities:
– Polymorph into a Werewolf once per day
  Duration: 2 turns

Weight: 3"



//CLOAK OF BALDURAN - 12000mo//
COPY "rick_bigg_mod/items/CLCK05.itm" "override"
	SAY NAME1 "Cloak"
	SAY UNIDENTIFIED_DESC "The cloak can be made in every possible shape with just about every type of fabric. The most common forms are a circular piece of fabric with a hole in the center for the head, and fabric draped from neck, connected by a chain, brooch, cord, or pins.

STATISTICS:

Weight: 3"

	SAY NAME2 "Cloak of Balduran"
	SAY DESC "Woven from heavy storm-grey fabric and fine silver thread, this majestic mantle radiates a subtle aura of absolute authority. It belonged to Balduran, the legendary founder of Baldur's Gate, who united the early factions and built the foundations of the city.
	The enchanted threads create a passive shield around the wearer, deflecting both physical blades and hostile magic before they can strike.

STATISTICS:

Equipped abilities:
– Armor Class: +1
– Saving Throws: +1
– Magic Resistance: +20%

Weight: 3"




//CLOAK OF NON-DETECTION - solo ladri e ranger - 2000mo//
COPY "rick_bigg_mod/items/CLCK06.itm" "override"
	SAY NAME1 "Cloak"
	SAY UNIDENTIFIED_DESC "The cloak can be made in every possible shape with just about every type of fabric. The most common forms are a circular piece of fabric with a hole in the center for the head, and fabric draped from neck, connected by a chain, brooch, cord, or pins.

STATISTICS:

Weight: 3"

	SAY NAME2 "Cloak of Non-Detection"
	SAY DESC "Reportedly created for a lineage of the greatest burglars ever to walk the night, this cloak was apparently a success. No record exists of previous owners.

STATISTICS:

Equipped abilities:
– While hidden or invisible, the wearer is non-detectable by magical means such as Detect Invisibility and scrying
- Hide in Shadows: +15%

Weight: 3"





//NYMPH CLOAK - 4500mo//
COPY "rick_bigg_mod/items/CLCK07.itm" "override"
	SAY NAME1 "Cloak"
	SAY UNIDENTIFIED_DESC "The cloak can be made in every possible shape with just about every type of fabric. The most common forms are a circular piece of fabric with a hole in the center for the head, and fabric draped from neck, connected by a chain, brooch, cord, or pins.

STATISTICS:

Weight: 3"

	SAY NAME2 "Nymph Cloak"
	SAY DESC "The fabled Nymph Cloak is renowned for its ability to increase the Charisma of even the most surly dwarf. A Cormyrean noble hoping to make her politically convenient marriage more palatable apparently went to great expense to obtain one for herself and another for her husband.

STATISTICS:

Equipped abilities:
– Charisma: +1

Charge abilities:
– Charm Creature once per day (Save vs. Wand negates)
  Range: Touch
  Duration: 12 hours
  Area of Effect: 1 creature

Weight: 3"




//CLOAK OF ATONMENT - 2500mo//
COPY "rick_bigg_mod/items/OHRCLCK3.itm" "override"
	SAY NAME1 "Cloak"
	SAY UNIDENTIFIED_DESC "The cloak can be made in every possible shape with just about every type of fabric. The most common forms are a circular piece of fabric with a hole in the center for the head, and fabric draped from neck, connected by a chain, brooch, cord, or pins.

STATISTICS:

Weight: 3"

	SAY NAME2 "Cloak of Atonment"
	SAY DESC "Atonement involves making reparations, paying a price. The Cloak of Atonement takes this requirement literally. In exchange for protection and safety, it will leech the health of its wearer to power itself.

STATISTICS:

Charge abilities:
- Atonement once per day 
  Effects: Constitution: -2, Saving throws: +2, Armor class: +2
  Duration: 8 hours
  Area of Effect: self

Weight: 3"




//GARGOYLE CLOAK - 5000mo//
COPY "rick_bigg_mod/items/BDCLCK05.itm" "override"
	SAY NAME1 "Cloak"
	SAY UNIDENTIFIED_DESC "The cloak can be made in every possible shape with just about every type of fabric. The most common forms are a circular piece of fabric with a hole in the center for the head, and fabric draped from neck, connected by a chain, brooch, cord, or pins.

STATISTICS:

Weight: 3"

	SAY NAME2 "Gargoyle Cloak"
	SAY DESC "Woven from heavy, stone-spun threads, this slate-gray cloak imbues its wearer with the legendary resilience of a gargoyle. The elemental magic within its fabric permanently shields vital organs from lethal critical strikes. Furthermore, when the wearer is heavily wounded and facing death, the cloak reacts violently—hardening into an invisible wall of granite that effortlessly deflects incoming blades, clubs, and missiles.

STATISTICS:

Equipped abilities:
– Protects against critical hits

Combat abilities:
- User gets +3 AC vs. Slashing, Piercing and Missile if they drop below 25% HP for 5 rounds

Weight: 3"





//CLOAK OF DEFIANCE - 5000mo//
COPY "rick_bigg_mod/items/BDCLCK06.itm" "override"
	SAY NAME1 "Cloak"
	SAY UNIDENTIFIED_DESC "The cloak can be made in every possible shape with just about every type of fabric. The most common forms are a circular piece of fabric with a hole in the center for the head, and fabric draped from neck, connected by a chain, brooch, cord, or pins.

STATISTICS:

Weight: 3"

	SAY NAME2 "Cloak of Defiance"
	SAY DESC "Woven during the Fall of Netheril by the mage Vaelen, this cloak was designed to survive the cataclysmic duels of rival arcanists.During the Siege of Voron-Dis, the mantle flared with silver light, absorbing a lethal barrage of disintegration beams and saving Vaelen's life. Though the intense feedback permanently burned out most of its original power, the residual magic within the threads remains fiercely stubborn.Once per day, the wearer can force the cloak to recall its ancient form, temporarily reconstructing an absolute barrier that turns devastating spells into harmless sparks.

STATISTICS:

Charge abilities:
– Set Magic Resistance to 50% once per day
  Duration: 1 turn

Weight: 3"




//MATICK'S SHROUD  - solo maghi e bardi - 6500mo//
COPY "rick_bigg_mod/items/CLCK20.itm" "override"
	SAY NAME1 "Cloak"
	SAY UNIDENTIFIED_DESC "The cloak can be made in every possible shape with just about every type of fabric. The most common forms are a circular piece of fabric with a hole in the center for the head, and fabric draped from neck, connected by a chain, brooch, cord, or pins.

STATISTICS:

Weight: 3"

	SAY NAME2 "Matick's Shroud"
	SAY DESC "This cloak was crafted by the legendary archmage Matick, the brilliant wizard credited with inventing the ubiquitous Magic Missile spell. During his research into raw Evocation, Matick became terrified that his own deadly creation would be turned against him by jealous rivals.To safeguard his life, he spent decades weaving this shroud to perfectly ground out the specific frequencies of his signature spell. Ironically, the master of offensive magic created the ultimate defensive garment, ensuring no apprentice could ever destroy the teacher with his own creation.

STATISTICS:

Equipped abilities:
– Immunity to Magic Missile
- Saving throws vs. Evocation: +4
- Fire Resistance: +20%
- Cold Resistance: +20%
- Electricity Resistance: +20%
- Magical Damage Resistance: +20%

Weight: 3"




//CLOAK OF THE SEWERS - 4500mo//
COPY "rick_bigg_mod/items/CLCK27.itm" "override"
	SAY NAME1 "Cloak"
	SAY UNIDENTIFIED_DESC "The cloak can be made in every possible shape with just about every type of fabric. The most common forms are a circular piece of fabric with a hole in the center for the head, and fabric draped from neck, connected by a chain, brooch, cord, or pins.

STATISTICS:

Weight: 3"

	SAY NAME2 "Cloak of the Sewers"
	SAY DESC "For a sewer-dweller like Ivan, survival meant going where others refused. Hiding from thugs, Ivan went so deep into the sewers beneath Atkhatla that he found natural caves, some of which opened to the ocean. Within one cave, Ivan discovered what he thought was a ruined cloak, all torn and stained. He tossed it into the fire he started, but it would not burn. Curious, he donned it, and with some prying, he discovered its hidden abilities. With the right command, he could shift into a mustard jelly.

STATISTICS:

Equipped abilities:
– Immunity to disease

Charge abilities:
– Polymorph into a Mustard Jelly once per day
  Duration: 2 turns
"






//CLOAK OF THE STRANGE BEAST - 3000mo//
COPY "rick_bigg_mod/items/BDLOINCL.itm" "override"
	SAY NAME1 "Cloak"
	SAY UNIDENTIFIED_DESC "The cloak can be made in every possible shape with just about every type of fabric. The most common forms are a circular piece of fabric with a hole in the center for the head, and fabric draped from neck, connected by a chain, brooch, cord, or pins.

STATISTICS:

Weight: 3"

	SAY NAME2 "Cloak of the Strange Beast"
	SAY DESC "This thick pelt can be worn as a cloak by human-sized creatures, or a loincloth by larger creatures. The beast that contributed its hide for this item is a mystery, but long slashes in skin indicate it was stabbed to death with sharp objects. Due to its enchanted nature, a faint pulse of ancient life force still courses through the thick fur, knitting the wearer's wounds and gradually restoring their vitality over time. However, its crude and monstrous appearance makes the wearer look deeply unsettling, severely hindering their social interactions.

STATISTICS:

Equipped abilities:
– Regenerate 1 Hit Point every round
– Charisma: -2

Weight: 3
"




//SABLE CLOAK - 4000mo//
COPY "rick_bigg_mod/items/BDCLCK02.itm" "override"
	SAY NAME1 "Cloak"
	SAY UNIDENTIFIED_DESC "The cloak can be made in every possible shape with just about every type of fabric. The most common forms are a circular piece of fabric with a hole in the center for the head, and fabric draped from neck, connected by a chain, brooch, cord, or pins.

STATISTICS:

Weight: 3"

	SAY NAME2 "Sable Cloak"
	SAY DESC "An intrepid explorer commissioned this luxurious sable cloak before venturing into the perilous Spine of the World, where an ancient white dragon was rumored to hunt. Woven with protective abjurations, the dark fur shielded her perfectly from the dragon's icy breath and the numbing winds of the north. After returning safely to the warmth of the south, she sold the magical garment, claiming she no longer had use for the cold.

STATISTICS:

Equipped abilities:
– Cold Resistance: +40%
– Immunity to slow

Weight: 3
"




//CLOAK OF THE STARS - 4000mo//
COPY "rick_bigg_mod/items/CLCK25.itm" "override"
	SAY NAME1 "Cloak"
	SAY UNIDENTIFIED_DESC "The cloak can be made in every possible shape with just about every type of fabric. The most common forms are a circular piece of fabric with a hole in the center for the head, and fabric draped from neck, connected by a chain, brooch, cord, or pins.

STATISTICS:

Weight: 3"

	SAY NAME2 "Cloak of the Stars"
	SAY DESC "Created by ancient elven astrologers during a rare alignment of the Tears of Selûne, this celestial relic is permanently infused with the protective essence of the night sky. The silver constellation patterns along the trim hold a defensive enchantment linked directly to the cosmos, causing the fabric to flash with a sharp burst of astral energy whenever the wearer is struck in combat.
	
Equipped abilities:
– Magic resistance: +5%

Combat abilities:
- 10% chance when hit to deal 10 magic damage to attacker

Weight: 3
"





//CLOAK OF INVULNERABILITY - 8500mo//
COPY "rick_bigg_mod/items/CLCK26.itm" "override"
	SAY NAME1 "Cloak"
	SAY UNIDENTIFIED_DESC "The cloak can be made in every possible shape with just about every type of fabric. The most common forms are a circular piece of fabric with a hole in the center for the head, and fabric draped from neck, connected by a chain, brooch, cord, or pins.

STATISTICS:

Weight: 3"

	SAY NAME2 "Cloak of Invulnerability"
	SAY DESC "Though it feels much like normal cloth, this shimmering cloak has on occasion been described as 'woven water'. Its true enchantment becomes apparent when the wearer is attacked directly by magic, and all damage caused by spell effects is deflected harmlessly away.

STATISTICS:

Charge abilities:
– Deflects all spell damage. This includes offensive spells like Magic Missile, but not disabling (non-damage) spells such as Hold Person once per day
   Duration: 1 turn

Weight: 3
"




//CLOAK OF REFLECTION - 5000mo//
COPY "rick_bigg_mod/items/CLCK24.itm" "override"
	SAY NAME1 "Cloak"
	SAY UNIDENTIFIED_DESC "The cloak can be made in every possible shape with just about every type of fabric. The most common forms are a circular piece of fabric with a hole in the center for the head, and fabric draped from neck, connected by a chain, brooch, cord, or pins.

STATISTICS:

Weight: 3"

	SAY NAME2 "Cloak of Reflection"
	SAY DESC "Vorn Druidslayer crafted this cloak and used it with great success in his campaign to eliminate the druids from all the woods south of Baldur's Gate. His campaign ended abruptly when he encountered a flock of wyverns, who were attracted by the cloak's sheen. They killed Vorn and used the cloak to cover their nest, serving to protect their young during Electricity storms.

STATISTICS:

Equipped abilities:
– Electricity Resistance: 40%
– Reflects all Electricity damage back to the source

Weight: 3
"



//CLOAK OF ELVENKIND - 4500mo - solo ladri e ranger//
COPY "rick_bigg_mod/items/CLCK23.itm" "override"
	SAY NAME1 "Cloak"
	SAY UNIDENTIFIED_DESC "The cloak can be made in every possible shape with just about every type of fabric. The most common forms are a circular piece of fabric with a hole in the center for the head, and fabric draped from neck, connected by a chain, brooch, cord, or pins.

STATISTICS:

Weight: 3"

	SAY NAME2 "Cloak of Elvenkind"
	SAY DESC "This green cloak resembles a normal cloak. Wearing it makes any person able to hide in shadows with astonishing ability. Its enchanted fabric also hardens against incoming strikes, deflecting blows with ease. As per the Thief ability though, the moment the wearer attacks or otherwise makes his/her presence known, the wearer must leave the shadows.

STATISTICS:

Equipped abilities:
– Hide In Shadows: +40%
- Armor Class: +1

Weight: 3
"



//CLOAK OF THE DARK MOON - 5500mo - no buoni//
COPY "rick_bigg_mod/items/OHRCLCK4.itm" "override"
	SAY NAME1 "Cloak"
	SAY UNIDENTIFIED_DESC "The cloak can be made in every possible shape with just about every type of fabric. The most common forms are a circular piece of fabric with a hole in the center for the head, and fabric draped from neck, connected by a chain, brooch, cord, or pins.

STATISTICS:

Weight: 3"

	SAY NAME2 "Cloak of the Dark Moon"
	SAY DESC "Those who worship Shar, the Mistress of the Night, often draw upon their dark goddess's absolute void to craft artifacts of silencing power. This cloak is whispered to have been woven by the Order of the Dark Moon, an elite sect of monastic assassins operating in her shadow. At first glance, the fabric seems to actively devour the light, appearing as a formless tear in reality. Only under closer inspection does the garment reveal an endlessly shifting texture, mimicking the cold, silent depths of the Shadowfell. When donned, the fabric shifts and resizes instantly, molding itself perfectly to the wearer's form like a second skin of living shadow.

STATISTICS:

Equipped abilities (at night):
– Armor Class: +2 
– Saving Throws: +2 
- Magic Resistance: +10% 
– Immunity to blindness
- Infravision

Charge abilities:
– Cloak of Fear once per day

Weight: 3
"



//CLOAK OF BRAVERY - 9500mo - no good//
COPY "rick_bigg_mod/items/CLCK30.itm" "override"
	SAY NAME1 "Cloak"
	SAY UNIDENTIFIED_DESC "The cloak can be made in every possible shape with just about every type of fabric. The most common forms are a circular piece of fabric with a hole in the center for the head, and fabric draped from neck, connected by a chain, brooch, cord, or pins.

STATISTICS:

Weight: 3"

	SAY NAME2 "Cloak of Bravery"
	SAY DESC "This cloak is an evil thing, albeit powerful. Woven from the poorly stitched together skin of innocent nymphs, the garment still carries the tragic echoes of its victims' final moments. The vile nature of its creation forces an unnatural coldness upon the wearer, effectively freezing their emotions and purging all capacity for terror.  Despite its horrific origins, the macabre magic binding the flesh infuses the host with a surge of raw, unyielding vitality, enhancing their physical capabilities beyond normal limits.

STATISTICS:

Equipped abilities:
– Immunity to fear and panic
- Strength: +1
- Dexterity: +1
- Constitution: +1

Weight: 3"





//ARMOR CLOAK - 7500mo//
COPY "rick_bigg_mod/items/CLCK29.itm" "override"
	SAY NAME1 "Cloak"
	SAY UNIDENTIFIED_DESC "The cloak can be made in every possible shape with just about every type of fabric. The most common forms are a circular piece of fabric with a hole in the center for the head, and fabric draped from neck, connected by a chain, brooch, cord, or pins.

STATISTICS:

Weight: 3"

	SAY NAME2 "Armor Cloak"
	SAY DESC "This robe was created by your apprentices, working busily away within the planar sphere. Despite their clear inexperience, the young mages managed to craft an incredibly powerful garment. By weaving defensive wards and planar energies into the fabric, they created an item that offers remarkable protection against both physical attacks and hostile magic.

STATISTICS:

Equipped abilities:
– Armor Class: 4
- Saving Throws: +1
- Magic Resistance: +5%

Weight: 3"





//RANGER CLOAK - 4500mo - solo ranger//
COPY "rick_bigg_mod/items/COMPON16.itm" "override"
	SAY NAME1 "Cloak"
	SAY UNIDENTIFIED_DESC "The cloak can be made in every possible shape with just about every type of fabric. The most common forms are a circular piece of fabric with a hole in the center for the head, and fabric draped from neck, connected by a chain, brooch, cord, or pins.

STATISTICS:

Weight: 3"

	SAY NAME2 "Ranger Shroud"
	SAY DESC "This cloak was once worn by Galathil, a legendary elven ranger who spent centuries patrolling the deadliest depths of the Forest of Tethyr. Treated with the protective sap of ancient ironwood trees, the enchanted fabric possesses a natural elasticity that subtly misdirects incoming projectiles, slowing down arrows before they can strike.

STATISTICS:

Equipped abilities:
– Armor Class: +1
- Saving Throws: +1
- Missile Resistance: +20%

Weight: 3"



//WHIRLWIND SHROUD - 12000mo - solo ranger//
COPY "rick_bigg_mod/items/CLCK32.itm" "override"
	SAY NAME1 "Cloak"
	SAY UNIDENTIFIED_DESC "The cloak can be made in every possible shape with just about every type of fabric. The most common forms are a circular piece of fabric with a hole in the center for the head, and fabric draped from neck, connected by a chain, brooch, cord, or pins.

STATISTICS:

Weight: 3"

	SAY NAME2 "Whirlwind Shroud"
	SAY DESC "This cloak was once worn by Galathil, a legendary elven ranger who spent centuries patrolling the deadliest depths of the Forest of Tethyr. Treated with the protective sap of ancient ironwood trees, the enchanted fabric possesses a natural elasticity that subtly misdirects incoming projectiles, slowing down arrows before they can strike.
	
	Fastened with a clasp blessed by Aerdrie Faenya, the elven goddess of the air, the garment now reveals its true power.

STATISTICS:

Equipped abilities:
– Armor Class: +2
- Saving Throws: +2
- Missile Resistance: +60%

Charge abilities:
– Improved Haste three times per day (double movement, attack per round and some effects)
  Duration: 5 rounds
  Area of Effect: the user

Weight: 3"




//LIFE SHROUD - 10000mo - solo chierici no evil//
COPY "rick_bigg_mod/items/BDCLCK03.itm" "override"
	SAY NAME1 "Cloak"
	SAY UNIDENTIFIED_DESC "The cloak can be made in every possible shape with just about every type of fabric. The most common forms are a circular piece of fabric with a hole in the center for the head, and fabric draped from neck, connected by a chain, brooch, cord, or pins.

STATISTICS:

Weight: 3"

	SAY NAME2 "Life Shroud"
	SAY DESC "Fashioned by the high clerics of the Morninglord during the catastrophic Siege of Tulanth, this cloak was consecrated for a single purpose: to survive the wrath of the infamous necromancer Abi-Dalzim. As the mage’s horrific wilting spells turned entire armies into dust, the lightbringers channeled their collective divine essence into this garment, creating an absolute shield against arcane necromancy. Infused with pure holy energy, the shroud amplifies its wearer's divine spellcasting and burns undead horrors with radiant fury. Because it is bound to the magic of absolute light, the cloak becomes heavy as lead and entirely useless in the hands of any neutral or evil being.

STATISTICS:

Equipped abilities:
- Turn Undead: +3
- Immunity to arcane necromancy

Charge abilities:
- Turn Undead three times per day
  Duration: 3 rounds

Weight: 3"
