//CLOACK OF PROTECTION +1 - valore 3500mo//
COPY "rick_bigg_mod/items/CLCK01.itm" "override"
	SAY NAME1 "Cloack"
	SAY UNIDENTIFIED_DESC "The cloak can be made in every possible shape with just about every type of fabric. The most common forms are a circular piece of fabric with a hole in the center for the head, and fabric draped from neck, connected by a chain, brooch, cord, or pins.

STATISTICS:

Weight: 3"

	SAY NAME2 "Cloack of Protection +1"
	SAY DESC "This simple cloak has been imbued with magical properties to help protect its wearer. It does so by affecting both Saving Throws and Armor Class. It is ideal for Mages and others who cannot wear bulkier or more restrictive types of armor.

STATISTICS:

Equipped abilities:
– Armor Class: +1
– Saving Throws: +1

Weight: 3"




//CLOAK OF DISPLACEMENT - 4000mo//
COPY "rick_bigg_mod/items/CLCK03.itm" "override"
	SAY NAME1 "Cloak"
	SAY UNIDENTIFIED_DESC "The cloak can be made in every possible shape with just about every type of fabric. The most common forms are a circular piece of fabric with a hole in the center for the head, and fabric draped from neck, connected by a chain, brooch, cord, or pins.

STATISTICS:

Weight: 3"

	SAY NAME2 "Cloak of Displacement"
	SAY DESC "This cloak is a magical item woven from shimmering, illusionary threads that cause subtle shifts in the image of its wearer. It has the power to actually bend light and space, shifting an individual's physical image by as much as six inches in any direction from their actual location. This continuous distortion leaves enemies striking at empty air, making it an invaluable defense in the heat of battle.

STATISTICS:

Equipped abilities:
– Armor Class: +4 vs. missile attacks
– Save vs. Breath: +4

Weight: 3"





//CLOACK OF THE WOLF - valore 5000mo//
COPY "rick_bigg_mod/items/CLCK04.itm" "override"
	SAY NAME1 "Cloack"
	SAY UNIDENTIFIED_DESC "The cloak can be made in every possible shape with just about every type of fabric. The most common forms are a circular piece of fabric with a hole in the center for the head, and fabric draped from neck, connected by a chain, brooch, cord, or pins.

STATISTICS:

Weight: 3"

	SAY NAME2 "Cloack of the Wolf"
	SAY DESC "A great amount of irony surrounds the creation of this magical cloak. Relair was a mage who overestimated the amount of control he had over magic, and in the course of creating this garment, he apparently inflicted lycanthropy upon himself. The wearer can change form whenever <PRO_HESHE> wishes. Relair was not so lucky.

STATISTICS:

Charge abilities:
– Polymorph into a Werewolf once per day

Weight: 3"



//CLOAK OF BALDURAN - 12000mo//
COPY "rick_bigg_mod/items/CLCK05.itm" "override"
	SAY NAME1 "Cloak"
	SAY UNIDENTIFIED_DESC "The cloak can be made in every possible shape with just about every type of fabric. The most common forms are a circular piece of fabric with a hole in the center for the head, and fabric draped from neck, connected by a chain, brooch, cord, or pins.

STATISTICS:

Weight: 3"

	SAY NAME2 "Cloak of Balduran"
	SAY DESC "Woven from heavy storm-grey fabric and fine silver thread, this majestic mantle radiates a subtle aura of absolute authority. It belonged to Balduran, the legendary founder of Baldur's Gate, who united the early factions and built the foundations of the city.
	The enchanted threads create a passive shield around the wearer, deflecting both physical blades and hostile magic before they can strike.

STATISTICS:

Equipped abilities:
– Armor Class: +1
– Saving Throws: +1
– Magic Resistance: +20%

Weight: 3"




//CLOAK OF NON-DETECTION - solo ladri e ranger - 2000mo//
COPY "rick_bigg_mod/items/CLCK06.itm" "override"
	SAY NAME1 "Cloak"
	SAY UNIDENTIFIED_DESC "The cloak can be made in every possible shape with just about every type of fabric. The most common forms are a circular piece of fabric with a hole in the center for the head, and fabric draped from neck, connected by a chain, brooch, cord, or pins.

STATISTICS:

Weight: 3"

	SAY NAME2 "Cloak of Non-Detection"
	SAY DESC "Reportedly created for a lineage of the greatest burglars ever to walk the night, this cloak was apparently a success. No record exists of previous owners.

STATISTICS:

Equipped abilities:
– While hidden or invisible, the wearer is non-detectable by magical means such as Detect Invisibility and scrying
- Hide in Shadows: +15%

Weight: 3"





//NYMPH CLOAK - 4500mo//
COPY "rick_bigg_mod/items/CLCK07.itm" "override"
	SAY NAME1 "Cloak"
	SAY UNIDENTIFIED_DESC "The cloak can be made in every possible shape with just about every type of fabric. The most common forms are a circular piece of fabric with a hole in the center for the head, and fabric draped from neck, connected by a chain, brooch, cord, or pins.

STATISTICS:

Weight: 3"

	SAY NAME2 "Nymph Cloak"
	SAY DESC "The fabled Nymph Cloak is renowned for its ability to increase the Charisma of even the most surly dwarf. A Cormyrean noble hoping to make her politically convenient marriage more palatable apparently went to great expense to obtain one for herself and another for her husband.

STATISTICS:

Equipped abilities:
– Charisma: +1

Charge abilities:
– Charm Creature once per day (Save vs. Wand negates)
  Range: Touch
  Duration: 12 hours
  Area of Effect: 1 creature

Weight: 3"




//CLOAK OF ATONMENT - 2500mo//
COPY "rick_bigg_mod/items/OHRCLCK3.itm" "override"
	SAY NAME1 "Cloak"
	SAY UNIDENTIFIED_DESC "The cloak can be made in every possible shape with just about every type of fabric. The most common forms are a circular piece of fabric with a hole in the center for the head, and fabric draped from neck, connected by a chain, brooch, cord, or pins.

STATISTICS:

Weight: 3"

	SAY NAME2 "Cloak of Atonment"
	SAY DESC "Atonement involves making reparations, paying a price. The Cloak of Atonement takes this requirement literally. In exchange for protection and safety, it will leech the health of its wearer to power itself.

STATISTICS:

Charge abilities:
- Atonement once per day 
  Effects: Constitution: -2, Saving throws: +2, Armor class: +2
  Duration: 8 hours
  Area of Effect: self

Weight: 3"




//GARGOYLE CLOAK - 5000mo//
COPY "rick_bigg_mod/items/BDCLCK05.itm" "override"
	SAY NAME1 "Cloak"
	SAY UNIDENTIFIED_DESC "The cloak can be made in every possible shape with just about every type of fabric. The most common forms are a circular piece of fabric with a hole in the center for the head, and fabric draped from neck, connected by a chain, brooch, cord, or pins.

STATISTICS:

Weight: 3"

	SAY NAME2 "Gargoyle Cloak"
	SAY DESC "Woven from heavy, stone-spun threads, this slate-gray cloak imbues its wearer with the legendary resilience of a gargoyle. The elemental magic within its fabric permanently shields vital organs from lethal critical strikes. Furthermore, when the wearer is heavily wounded and facing death, the cloak reacts violently—hardening into an invisible wall of granite that effortlessly deflects incoming blades, clubs, and missiles.

STATISTICS:

Equipped abilities:
– Protects against critical hits

Combat abilities:
- User gets +3 AC vs. Slashing, Piercing and Missile if they drop below 25% HP for 5 rounds

Weight: 3"





//CLOAK OF DEFIANCE - 5000mo//
COPY "rick_bigg_mod/items/BDCLCK06.itm" "override"
	SAY NAME1 "Cloak"
	SAY UNIDENTIFIED_DESC "The cloak can be made in every possible shape with just about every type of fabric. The most common forms are a circular piece of fabric with a hole in the center for the head, and fabric draped from neck, connected by a chain, brooch, cord, or pins.

STATISTICS:

Weight: 3"

	SAY NAME2 "Cloak of Defiance"
	SAY DESC "Woven during the Fall of Netheril by the mage Vaelen, this cloak was designed to survive the cataclysmic duels of rival arcanists.During the Siege of Voron-Dis, the mantle flared with silver light, absorbing a lethal barrage of disintegration beams and saving Vaelen's life. Though the intense feedback permanently burned out most of its original power, the residual magic within the threads remains fiercely stubborn.Once per day, the wearer can force the cloak to recall its ancient form, temporarily reconstructing an absolute barrier that turns devastating spells into harmless sparks.

STATISTICS:

Charge abilities:
– Set Magic Resistance to 50% once per day
  Duration: 1 turn

Weight: 3"




//MATICK'S SHROUD  - solo maghi e bardi - 6500mo//
COPY "rick_bigg_mod/items/CLCK20.itm" "override"
	SAY NAME1 "Cloak"
	SAY UNIDENTIFIED_DESC "The cloak can be made in every possible shape with just about every type of fabric. The most common forms are a circular piece of fabric with a hole in the center for the head, and fabric draped from neck, connected by a chain, brooch, cord, or pins.

STATISTICS:

Weight: 3"

	SAY NAME2 "Matick's Shroud"
	SAY DESC "This heavy, shimmering cloak was crafted by the legendary archmage Matick, the brilliant wizard credited with inventing the ubiquitous Magic Missile spell. During his research into raw Evocation, Matick became terrified that his own deadly creation would be turned against him by jealous rivals.To safeguard his life, he spent decades weaving this shroud to perfectly ground out the specific frequencies of his signature spell. Ironically, the master of offensive magic created the ultimate defensive garment, ensuring no apprentice could ever destroy the teacher with his own creation.

STATISTICS:

Equipped abilities:
– Immunity to Magic Missile
- Saving throws vs. Evocation: +4
- Fire Resistance: +20%
- Cold Resistance: +20%
- Electricity Resistance: +20%
- Magical Damage Resistance: +20%

Weight: 3"