//PRIDE OF THE LEGION +2 - 10000mo//
COPY "rick_bigg_mod/items/PLAT15.itm" "override"
	SAY NAME1 "Full Plate Mail"
	SAY UNIDENTIFIED_DESC "Full plate armor is the best armor a warrior can buy, both in appearance and protection. The perfectly fitted, interlocking plates are specially angled to deflect arrows and blows, and the entire suit is carefully adorned with rich engraving and embossed detail.

STATISTICS:

Armor Class: 1 (-3 vs. slashing, -2 vs. piercing and missile)
Requires:
 15 Strength

Weight: 70"

	SAY NAME2 "Pride of the Legion +2"
	SAY DESC "Captain Fallorain, leader of Calimshan's 12th cavalry brigade, wore this enchanted armor for the last time during the Battle of the Spider Swamp. There he lost his life and army trying to rid an unrecorded evil from the area. 

Equipped abilities:
– Saving Throws vs Death bonus: +2

STATISTICS:

Armor Class: -2 (-6 vs. slashing, -5 vs. piercing and missile)
Requires:
 15 Strength

Weight: 45
"





//ARMOR OF THE HEART +3 - no evil - 16000mo//
COPY "rick_bigg_mod/items/PLAT16.itm" "override"
	SAY NAME1 "Full Plate Mail"
	SAY UNIDENTIFIED_DESC "Full plate armor is the best armor a warrior can buy, both in appearance and protection. The perfectly fitted, interlocking plates are specially angled to deflect arrows and blows, and the entire suit is carefully adorned with rich engraving and embossed detail.

STATISTICS:

Armor Class: 1 (-3 vs. slashing, -2 vs. piercing and missile)
Requires:
 15 Strength

Weight: 70"

	SAY NAME2 "Armor of the Heart +3"
	SAY DESC "Few suits of armor in all the realms are the equal of this full plate. All that remains of the origin of the Hart are folktales and legends. The most popular of these is that an impossible battle was once fought against an army of orcs surging through the Three Trees Pass. Arngor of the Oak led the armies of men and elves, and it is said that he dueled with the orc commander till the sun set and the land was bathed in a bloody mist. Finally the orc fell, but Arngor had sustained wounds too vast for any to save him. His blood soaked through the armor he wore, infusing it with his courage and nobility. Thus the Armor of the Hart became known to men.

STATISTICS:

Equipped Abilities:
- Strength: +1
- Immunity to fear and panic

Armor Class: -2 (-6 vs. slashing, -5 vs. piercing and missile)
Requires:
 15 Strength

Weight: 45
"









//FALLORAIN'S PLATE + 3 - 14000mo//
COPY "rick_bigg_mod/items/PLAT17.itm" "override"
	SAY NAME1 "Full Plate Mail"
	SAY UNIDENTIFIED_DESC "Full plate armor is the best armor a warrior can buy, both in appearance and protection. The perfectly fitted, interlocking plates are specially angled to deflect arrows and blows, and the entire suit is carefully adorned with rich engraving and embossed detail.

STATISTICS:

Armor Class: 1 (-3 vs. slashing, -2 vs. piercing and missile)
Requires:
 15 Strength

Weight: 70"

	SAY NAME2 "Fallorain's Plate +3"
	SAY DESC "Captain Fallorain, leader of Calimshan's 12th cavalry brigade, wore this enchanted armor for the last time during the Battle of the Spider Swamp. There he lost his life and army trying to rid an unrecorded evil from the area. 

Equipped abilities:
– Protection from evil
– Immunity to poison and disease

STATISTICS:

Armor Class: -2 (-6 vs. slashing, -5 vs. piercing and missile)
Requires:
 15 Strength

Weight: 45
"








//MAGMA BULWARK +4 - 18000mo//
COPY "rick_bigg_mod/items/TB#PLAT1.itm" "override"
	SAY NAME1 "Full Plate Mail"
	SAY UNIDENTIFIED_DESC "Full plate armor is the best armor a warrior can buy, both in appearance and protection. The perfectly fitted, interlocking plates are specially angled to deflect arrows and blows, and the entire suit is carefully adorned with rich engraving and embossed detail.

STATISTICS:

Armor Class: 1 (-3 vs. slashing, -2 vs. piercing and missile)
Requires:
 15 Strength

Weight: 70"

	SAY NAME2 "Magma Bulwark +4"
	SAY DESC "Forged by the fire giant Varboti as a gift for a Cormyrian general who made peace with his clan, this red-and-black armor lends its wearer a molten aspect while providing protection against all but the most powerful blows and fire damage. Due to its incredibly strong but thin material, it also weighs far less than ordinary plate mail.

STATISTICS:

Equipped Abilities:
- Fire damage resistance: +40%
- Crushing damage resistance: +10%

Armor Class: -3 (-7 vs. slashing, -6 vs. piercing and missile)
Requires:
 15 Strength

Weight: 40
"





//SHURUPPAK'S PLATE +5 - 20000mo//
COPY "rick_bigg_mod/items/PLAT22.itm" "override"
	SAY NAME1 "Full Plate Mail"
	SAY UNIDENTIFIED_DESC "Full plate armor is the best armor a warrior can buy, both in appearance and protection. The perfectly fitted, interlocking plates are specially angled to deflect arrows and blows, and the entire suit is carefully adorned with rich engraving and embossed detail.

STATISTICS:

Armor Class: 1 (-3 vs. slashing, -2 vs. piercing and missile)
Requires:
 15 Strength

Weight: 70"

	SAY NAME2 "Shuruppak's Plate +5"
	SAY DESC "Shuruppak, the infamous right hand of the now dead god Gilgeam, earned the title of 'Reaper' for his savage butchery of any who opposed him... an identity the bloodthirsty madman eagerly embraced. Before Gilgeam's destruction, the god presented Shuruppak with an enchanted suit of armor, to better enable the Reaper to slaughter his foes.

Shuruppak's plate is surprisingly light and grants the wearer an unnatural quickness and grace. It is not known how Shuruppak lost this treasured item, but one could safely assume he is still looking for it... 
 
STATISTICS:

Equipped abilities:
– Dexterity: +1
– Doubles movement rate
- Free action

Armor Class: -4 (-8 vs. slashing, -7 vs. piercing and missile)
Requires:
 15 Strength

Weight: 30
"