//FULL PLATE MAIL +1 - 7500mo//
COPY "rick_bigg_mod/items/PLAT14.itm" "override"
	SAY NAME1 "Full Plate Mail"
	SAY UNIDENTIFIED_DESC "Full plate armor is the best armor a warrior can buy, both in appearance and protection. The perfectly fitted, interlocking plates are specially angled to deflect arrows and blows, and the entire suit is carefully adorned with rich engraving and embossed detail.

STATISTICS:

Armor Class: 1 (-2 vs. slashing, -1 vs. piercing and missile)
Speed Factor: -3
Requires:
 16 Strength

Weight: 70"

	SAY NAME2 "Full Plate Mail +1"
	SAY DESC "Full plate armor is the best armor a warrior can buy, both in appearance and protection. The perfectly fitted, interlocking plates are specially angled to deflect arrows and blows, and the entire suit is carefully adorned with rich engraving and embossed detail. 
	With its magical enchantments, this suit of full plate is ideal for warriors.
	
STATISTICS:

Armor Class: 0 (-3 vs. slashing, -2 vs. piercing and missile)
Speed Factor: -3
Requires:
 16 Strength

Weight: 50
"




//FULL PLATE MAIL +1 - 9000mo//
COPY "rick_bigg_mod/items/WA2PLAT.itm" "override"
	SAY NAME1 "Full Plate Mail"
	SAY UNIDENTIFIED_DESC "Full plate armor is the best armor a warrior can buy, both in appearance and protection. The perfectly fitted, interlocking plates are specially angled to deflect arrows and blows, and the entire suit is carefully adorned with rich engraving and embossed detail.

STATISTICS:

Armor Class: 1 (-2 vs. slashing, -1 vs. piercing and missile)
Speed Factor: -3
Requires:
 16 Strength

Weight: 70"

	SAY NAME2 "Full Plate Mail +1"
	SAY DESC "This plate was worn by the famous hero Balduran. It was lost at sea on Balduran's last voyage.
	
STATISTICS:

Equipped abilities:
- Constitution: +1
- Immunity to fatigue

Armor Class: 0 (-3 vs. slashing, -2 vs. piercing and missile)
Speed Factor: -3
Requires:
 16 Strength

Weight: 50
"




//FULL PLATE MAIL +2 - 9000mo//
COPY "rick_bigg_mod/items/PLAT23.itm" "override"
	SAY NAME1 "Full Plate Mail"
	SAY UNIDENTIFIED_DESC "Full plate armor is the best armor a warrior can buy, both in appearance and protection. The perfectly fitted, interlocking plates are specially angled to deflect arrows and blows, and the entire suit is carefully adorned with rich engraving and embossed detail.

STATISTICS:

Armor Class: 1 (-2 vs. slashing, -1 vs. piercing and missile)
Speed Factor: -3
Requires:
 16 Strength

Weight: 70"

	SAY NAME2 "Full Plate Mail +2"
	SAY DESC "Full plate armor is the best armor a warrior can buy, both in appearance and protection, and the enchantments on this suit are particularly powerful. 
	The intricate engraving and spectacular embossing adorning the suit are of indeterminate origin, as is the armor itself. 
	
STATISTICS:

Armor Class: -1 (-4 vs. slashing, -3 vs. piercing and missile)
Speed Factor: -3
Requires:
 16 Strength

Weight: 50
"








//PRIDE OF THE LEGION +2 - 10000mo//
COPY "rick_bigg_mod/items/PLAT15.itm" "override"
	SAY NAME1 "Full Plate Mail"
	SAY UNIDENTIFIED_DESC "Full plate armor is the best armor a warrior can buy, both in appearance and protection. The perfectly fitted, interlocking plates are specially angled to deflect arrows and blows, and the entire suit is carefully adorned with rich engraving and embossed detail.

STATISTICS:

Armor Class: 1 (-2 vs. slashing, -1 vs. piercing and missile)
Speed Factor: -3
Requires:
 16 Strength

Weight: 70"

	SAY NAME2 "Pride of the Legion +2"
	SAY DESC "Captain Fallorain, leader of Calimshan's 12th cavalry brigade, wore this enchanted armor for the last time during the Battle of the Spider Swamp. There he lost his life and army trying to rid an unrecorded evil from the area. 

Equipped abilities:
– Saving Throws vs Death bonus: +2

STATISTICS:

Armor Class: -1 (-4 vs. slashing, -3 vs. piercing and missile)
Speed Factor: -3
Requires:
 16 Strength

Weight: 45
"





//ARMOR OF THE HEART +2 - no evil - 16000mo//
COPY "rick_bigg_mod/items/PLAT16.itm" "override"
	SAY NAME1 "Full Plate Mail"
	SAY UNIDENTIFIED_DESC "Full plate armor is the best armor a warrior can buy, both in appearance and protection. The perfectly fitted, interlocking plates are specially angled to deflect arrows and blows, and the entire suit is carefully adorned with rich engraving and embossed detail.

STATISTICS:

Armor Class: 1 (-2 vs. slashing, -1 vs. piercing and missile)
Speed Factor: -3
Requires:
 16 Strength

Weight: 70"

	SAY NAME2 "Armor of the Heart +2"
	SAY DESC "Few suits of armor in all the realms are the equal of this full plate. All that remains of the origin of the Hart are folktales and legends. The most popular of these is that an impossible battle was once fought against an army of orcs surging through the Three Trees Pass. Arngor of the Oak led the armies of men and elves, and it is said that he dueled with the orc commander till the sun set and the land was bathed in a bloody mist. Finally the orc fell, but Arngor had sustained wounds too vast for any to save him. His blood soaked through the armor he wore, infusing it with his courage and nobility. Thus the Armor of the Hart became known to men.

STATISTICS:

Equipped Abilities:
- Immunity to fear and panic

Armor Class: -1 (-4 vs. slashing, -3 vs. piercing and missile)
Speed Factor: -3
Requires:
 16 Strength

Weight: 45
"






//PLATE OF THE DARK +3 - no good - 15000mo//
COPY "rick_bigg_mod/items/TB#PLATD.itm" "override"
	SAY NAME1 "Full Plate Mail"
	SAY UNIDENTIFIED_DESC "Full plate armor is the best armor a warrior can buy, both in appearance and protection. The perfectly fitted, interlocking plates are specially angled to deflect arrows and blows, and the entire suit is carefully adorned with rich engraving and embossed detail.

STATISTICS:

Armor Class: 1 (-2 vs. slashing, -1 vs. piercing and missile)
Speed Factor: -3
Requires:
 16 Strength

Weight: 70"

	SAY NAME2 "Plate of the Dark +3"
	SAY DESC "Dark Lord Hertious, undead Warlord of Bane, wore this piece of armor for over five hundred years. During this time he was rumored to dwell in a castle somewhere within the Earthfast Mountains. How his armor moved to other lands without him is not certain, though the separation of the two was surely unpleasant.

STATISTICS:

Equipped Abilities:
- +5% Magic Resistance
- 20% chance to drain one level from attackers (save vs. Death at -4 negates)

Armor Class: -2 (-5 vs. slashing, -4 vs. piercing and missile)
Speed Factor: -3
Requires:
 16 Strength

Weight: 35
"






//FALLORAIN'S PLATE +3 - 14000mo//
COPY "rick_bigg_mod/items/PLAT17.itm" "override"
	SAY NAME1 "Full Plate Mail"
	SAY UNIDENTIFIED_DESC "Full plate armor is the best armor a warrior can buy, both in appearance and protection. The perfectly fitted, interlocking plates are specially angled to deflect arrows and blows, and the entire suit is carefully adorned with rich engraving and embossed detail.

STATISTICS:

Armor Class: 1 (-2 vs. slashing, -1 vs. piercing and missile)
Speed Factor: -3
Requires:
 16 Strength

Weight: 70"

	SAY NAME2 "Fallorain's Plate +3"
	SAY DESC "Captain Fallorain, leader of Calimshan's 12th cavalry brigade, wore this enchanted armor for the last time during the Battle of the Spider Swamp. There he lost his life and army trying to rid an unrecorded evil from the area. 

STATISTICS:

Equipped abilities:
– Protection From Evil
– Immunity to poison and disease

Armor Class: -2 (-5 vs. slashing, -4 vs. piercing and missile)
Speed Factor: -3
Requires:
 16 Strength

Weight: 45
"








//MAGMA BULWARK +4 - 18000mo//
COPY "rick_bigg_mod/items/TB#PLAT1.itm" "override"
	SAY NAME1 "Full Plate Mail"
	SAY UNIDENTIFIED_DESC "Full plate armor is the best armor a warrior can buy, both in appearance and protection. The perfectly fitted, interlocking plates are specially angled to deflect arrows and blows, and the entire suit is carefully adorned with rich engraving and embossed detail.

STATISTICS:

Armor Class: 1 (-2 vs. slashing, -1 vs. piercing and missile)
Speed Factor: -3
Requires:
 16 Strength

Weight: 70"

	SAY NAME2 "Magma Bulwark +4"
	SAY DESC "Forged by the fire giant Varboti as a gift for a Cormyrian general who made peace with his clan, this red-and-black armor lends its wearer a molten aspect while providing protection against all but the most powerful blows and fire damage. Due to its incredibly strong but thin material, it also weighs far less than ordinary plate mail.

STATISTICS:

Equipped Abilities:
- Fire damage resistance: +20%
- Crushing damage resistance: +10%

Armor Class: -3 (-6 vs. slashing, -5 vs. piercing and missile)
Speed Factor: -3
Requires:
 16 Strength

Weight: 40
"





//SHURUPPAK'S PLATE +5 - 20000mo//
COPY "rick_bigg_mod/items/PLAT22.itm" "override"
	SAY NAME1 "Full Plate Mail"
	SAY UNIDENTIFIED_DESC "Full plate armor is the best armor a warrior can buy, both in appearance and protection. The perfectly fitted, interlocking plates are specially angled to deflect arrows and blows, and the entire suit is carefully adorned with rich engraving and embossed detail.

STATISTICS:

Armor Class: 1 (-2 vs. slashing, -1 vs. piercing and missile)
Speed Factor: -3
Requires:
 16 Strength

Weight: 70"

	SAY NAME2 "Shuruppak's Plate +5"
	SAY DESC "Shuruppak, the infamous right hand of the now dead god Gilgeam, earned the title of 'Reaper' for his savage butchery of any who opposed him... an identity the bloodthirsty madman eagerly embraced. Before Gilgeam's destruction, the god presented Shuruppak with an enchanted suit of armor, to better enable the Reaper to slaughter his foes.

Shuruppak's plate is surprisingly light and grants the wearer an unnatural quickness and grace. It is not known how Shuruppak lost this treasured item, but one could safely assume he is still looking for it... 
 
STATISTICS:

Equipped abilities:
– Dexterity: +1
– Doubles movement rate
- Free action

Armor Class: -4 (-7 vs. slashing, -6 vs. piercing and missile)
Speed Factor: -1
Requires:
 16 Strength

Weight: 15
"