//HALBERD +2- 3000mo//
COPY "rick_bigg_mod/items/HALB07.itm" "override"
	SAY NAME1 "Halberd"
	SAY UNIDENTIFIED_DESC "By far the oldest and most often used polearm, the halberd consists of a cleaver-like axe blade mounted on a staff averaging six feet in length. The axe blade is balanced at the rear with a fluke and surmounted by a sharp spike, usually of quadrangular design. The fluke is sometimes replaced by a hook used to dismount cavalry. A halberd can be best described as a cross between a spear and an axe.

STATISTICS:

Damage: 1d10 (piercing or slashing)
Speed Factor: 9
Proficiency Type: Halberd
Type: Two-handed
Requires:
 13 Strength

Weight: 15"


	SAY NAME2 "Halberd +2"
	SAY DESC "Like others of its type, this halberd consists of a cleaver-like axe blade mounted on a staff approximately six feet in length. Magic has been used to forge this particular weapon, gifting it with enhanced abilities to slaughter foes.

STATISTICS:

THAC0: +2
Damage: 1d10+2 (piercing or slashing)
Speed Factor: 7
Proficiency Type: Halberd
Type: Two-handed
Requires:
 13 Strength

Weight: 12" 





//COLD FURY +2 - 4500mo//
COPY "rick_bigg_mod/items/BDHALB03.itm" "override"
	SAY NAME1 "Halberd"
	SAY UNIDENTIFIED_DESC "By far the oldest and most often used polearm, the halberd consists of a cleaver-like axe blade mounted on a staff averaging six feet in length. The axe blade is balanced at the rear with a fluke and surmounted by a sharp spike, usually of quadrangular design. The fluke is sometimes replaced by a hook used to dismount cavalry. A halberd can be best described as a cross between a spear and an axe.

STATISTICS:

Damage: 1d10 (piercing or slashing)
Speed Factor: 9
Proficiency Type: Halberd
Type: Two-handed
Requires:
 13 Strength

Weight: 15"


	SAY NAME2 "Cold Fury +2"
	SAY DESC "This weapon was forged by the ice salamanders, and was stolen by a group of Waterdeep adventurers decades ago. Chilly blue frost trails like fog off the blade of this halberd. A palpable aura of cold surrounds the weapon, dealing frost damage to every enemies hit.

STATISTICS:

THAC0: +2
Damage: 1d10+2, +2 cold damage
Damage Type: Slashing or piercing, whichever is better
Speed Factor: 7
Proficiency Type: Halberd
Type: Two-handed
Requires:
 13 Strength

Weight: 12" 







//BLACKMIST +2 - 6000mo//
COPY "rick_bigg_mod/items/HALB06.itm" "override"
	SAY NAME1 "Halberd"
	SAY UNIDENTIFIED_DESC "By far the oldest and most often used polearm, the halberd consists of a cleaver-like axe blade mounted on a staff averaging six feet in length. The axe blade is balanced at the rear with a fluke and surmounted by a sharp spike, usually of quadrangular design. The fluke is sometimes replaced by a hook used to dismount cavalry. A halberd can be best described as a cross between a spear and an axe.

STATISTICS:

Damage: 1d10 (piercing or slashing)
Speed Factor: 9
Proficiency Type: Halberd
Type: Two-handed
Requires:
 13 Strength

Weight: 15"


	SAY NAME2 "Blackmist +2"
	SAY DESC "This was the weapon of Dominique Harl, a sightless paladin who frequently traveled Faerûn. When attacked, Dominique would unleash the black mist that is this halberd's namesake, potentially blinding all within 5 feet. This often gave him the advantage, for he lived in darkness all his life, seeing only with the inner light of faith. Dominique eventually fell, his body found in a dark forest, slain by a creature of the night even more at home in the shadows than he.

STATISTICS:

Charge abilities:
– Blindness two times per day (Save vs. Wand negates)
  Duration: 2 hours
  Area of Effect: 5-ft. radius

THAC0: +2
Damage: 1d10+2 (piercing)
Speed Factor: 7
Proficiency Type: Halberd
Type: Two-handed
Requires:
 13 Strength

Weight: 12" 




//DUSKBLADE +3 - valore 7500mo - no good//
COPY "rick_bigg_mod/items/HALB08.itm" "override"
	SAY NAME1 "Halberd"
	SAY UNIDENTIFIED_DESC "By far the oldest and most often used polearm, the halberd consists of a cleaver-like axe blade mounted on a staff averaging six feet in length. The axe blade is balanced at the rear with a fluke and surmounted by a sharp spike, usually of quadrangular design. The fluke is sometimes replaced by a hook used to dismount cavalry. A halberd can be best described as a cross between a spear and an axe.

STATISTICS:

Damage: 1d10 (piercing or slashing)
Speed Factor: 9
Proficiency Type: Halberd
Type: Two-handed
Requires:
 13 Strength

Weight: 15"


	SAY NAME2 "Duskblade +3"
	SAY DESC "Though once a simple halberd, this weapon spent many hundreds of years in a tomb next to the soul phylactery of a powerful lich. The creature was eventually erased from existence, purportedly by another of its kind, but such close proximity to that concentrated evil has imbued this blade with the very essence of night and the chill of darkness, energy that becomes deadly in combat. It is a foul weapon, and a warrior should use it with caution. 

STATISTICS:

Combat abilities:
– 15% chance per hit of draining 1 level from the target

THAC0: +3
Damage: 1d10+3
Damage type: Piercing
Speed Factor: 6
Proficiency Type: Halberd
Type: Two-handed
Requires:
 13 Strength

Weight: 12" 




//DRAGON'S BANE +3 - valore 7000mo//
COPY "rick_bigg_mod/items/HALB04.itm" "override"
	SAY NAME1 "Halberd"
	SAY UNIDENTIFIED_DESC "By far the oldest and most often used polearm, the halberd consists of a cleaver-like axe blade mounted on a staff averaging six feet in length. The axe blade is balanced at the rear with a fluke and surmounted by a sharp spike, usually of quadrangular design. The fluke is sometimes replaced by a hook used to dismount cavalry. A halberd can be best described as a cross between a spear and an axe.

STATISTICS:

Damage: 1d10 (piercing or slashing)
Speed Factor: 9
Proficiency Type: Halberd
Type: Two-handed
Requires:
 13 Strength

Weight: 15"


	SAY NAME2 "Dragon's Bane +3"
	SAY DESC "This was the weapon of Thorvin Dukal, one of seven self-proclaimed Dragonslayers who spent years railing against what they called an insidious dragon infestation that threatened Faerûn. Thorvin had this weapon enchanted at great expense and used it on many occasions, though of dragons only a single white has fallen to it. The Dragonslayers met their match in a cantankerous ancient red who slew the entire group in an epic battle. This weapon did not end up in the beast's hoard, however, as the creature returned to its lair to recuperate and when it emerged, the field of combat was well scavenged.

STATISTICS:

THAC0: +3
Damage: 1d10+3, +6 extra damage vs. dragons
Damage type: Piercing
Speed Factor: 6
Proficiency Type: Halberd
Type: Two-handed
Requires:
 13 Strength

Weight: 12" 





//DRAGON'S BREATH +5 - 9000mo//
COPY "rick_bigg_mod/items/HALB05.itm" "override"
	SAY NAME1 "Halberd"
	SAY UNIDENTIFIED_DESC "By far the oldest and most often used polearm, the halberd consists of a cleaver-like axe blade mounted on a staff averaging six feet in length. The axe blade is balanced at the rear with a fluke and surmounted by a sharp spike, usually of quadrangular design. The fluke is sometimes replaced by a hook used to dismount cavalry. A halberd can be best described as a cross between a spear and an axe.

STATISTICS:

Damage: 1d10 (piercing or slashing)
Speed Factor: 9
Proficiency Type: Halberd
Type: Two-handed
Requires:
 13 Strength

Weight: 15"


	SAY NAME2 "Dragon's Breath +5"
	SAY DESC "Trying to profit from the strength of greater beings, many years ago the mage Ullion founded a dragon-worshipping cult under the moniker Son of Drago. Attracting followers with promises of conquest, he sought to secure his authority by enchanting this symbolic weapon for his bodyguard, Jaramor Bold. When the Dragon's Breath strikes an opponent, it releases the harsh flames of a red dragon, the poisonous vapor of the green dragon, the blue dragon's lightning bolt, a spray of a black dragon's acid, and the white dragon's penetrating cold. Unfortunately, Ullion was the first to feel its effects, slain by the ambitious Jaramor, who sought to rule. There was no real power to be had without the mage, so the entire organization soon collapsed on itself. 

STATISTICS:

THAC0: +5
Damage: 1d10
Elemental damage: +1 cold damage, +1 fire damage, +1 Electricity damage, +1 acid damage, +1 poison damage (bypass MR)
Damage type: Piercing
Speed Factor: 4
Proficiency Type: Halberd
Type: Two-handed
Requires:
 13 Strength

Weight: 10" 




//WAVE +4 - 12000mo//
COPY "rick_bigg_mod/items/HALB09.itm" "override"
	SAY NAME1 "Halberd"
	SAY UNIDENTIFIED_DESC "By far the oldest and most often used polearm, the halberd consists of a cleaver-like axe blade mounted on a staff averaging six feet in length. The axe blade is balanced at the rear with a fluke and surmounted by a sharp spike, usually of quadrangular design. The fluke is sometimes replaced by a hook used to dismount cavalry. A halberd can be best described as a cross between a spear and an axe.

STATISTICS:

Damage: 1d10 (piercing or slashing)
Speed Factor: 9
Proficiency Type: Halberd
Type: Two-handed
Requires:
 13 Strength

Weight: 15"


	SAY NAME2 "Wave +4"
	SAY DESC "Forged in antiquity by a cult devoted to the goddess Umberlee, this weapon of vengeance was designed to aid the cult's champion in retrieving a holy artifact from the fire giants of the Storm Horn Mountains. That was a lot of hope to place in one champion, and unfortunately the Wave had been lost ever since.

STATISTICS:

Combat abilities:  
– 25% chance of draining the victim of water (+15 cold damage, bypass MR)
– Slays fire elementals, efreet, and salamanders

THAC0: +4
Damage: 1d10+4 (piercing)
Speed Factor: 5
Proficiency Type: Halberd
Type: Two-handed
Requires:
 13 Strength

Weight: 11" 



//RAVAGER +4 - 10000mo - no good//
COPY "rick_bigg_mod/items/HALB10.itm" "override"
	SAY NAME1 "Halberd"
	SAY UNIDENTIFIED_DESC "By far the oldest and most often used polearm, the halberd consists of a cleaver-like axe blade mounted on a staff averaging six feet in length. The axe blade is balanced at the rear with a fluke and surmounted by a sharp spike, usually of quadrangular design. The fluke is sometimes replaced by a hook used to dismount cavalry. A halberd can be best described as a cross between a spear and an axe.

STATISTICS:

Damage: 1d10 (piercing or slashing)
Speed Factor: 9
Proficiency Type: Halberd
Type: Two-handed
Requires:
 13 Strength

Weight: 15"


	SAY NAME2 "Ravager +4"
	SAY DESC "The Ravager is a weapon of singular, terrifying purpose. Its name is not merely a title, but a literal description of its effect on the battlefield. Forged in the depths of the Abyss by master smiths whose names are now forgotten, this halberd was designed to be the ultimate harvester of souls. The blade is forged from a dense, light-absorbing obsidian alloy, etched with pulsating crimson runes that glow with a malevolent light whenever blood is drawn.

STATISTICS:

Combat abilities:
– 15% chance of decapitating opponent with each successful attack (Save vs. Death -4 negates)

THAC0: +4
Damage: 1d10+4 (piercing)
Speed Factor: 5
Proficiency Type: Halberd
Type: Two-handed
Requires:
 13 Strength

Weight: 11" 





//RAVAGER +6 - 20000mo - no good//
COPY "rick_bigg_mod/items/HALB11.itm" "override"
	SAY NAME1 "Halberd"
	SAY UNIDENTIFIED_DESC "By far the oldest and most often used polearm, the halberd consists of a cleaver-like axe blade mounted on a staff averaging six feet in length. The axe blade is balanced at the rear with a fluke and surmounted by a sharp spike, usually of quadrangular design. The fluke is sometimes replaced by a hook used to dismount cavalry. A halberd can be best described as a cross between a spear and an axe.

STATISTICS:

Damage: 1d10 (piercing or slashing)
Speed Factor: 9
Proficiency Type: Halberd
Type: Two-handed
Requires:
 13 Strength

Weight: 15"


	SAY NAME2 "Ravager +6"
	SAY DESC "The Ravager is a weapon of singular, terrifying purpose. Its name is not merely a title, but a literal description of its effect on the battlefield. Forged in the depths of the Abyss by master smiths whose names are now forgotten, this halberd was designed to be the ultimate harvester of souls. The blade is forged from a dense, light-absorbing obsidian alloy, etched with pulsating crimson runes that glow with a malevolent light whenever blood is drawn.
	
	Combined with the Serpent Shaft, this dark halberd has become one of the deadliest weapons in the Realms.

STATISTICS:

Combat abilities:
– Hit target suffer 3d6 points of poison damage (no save, bypass MR)
– 15% chance of decapitating opponent with each successful attack (no save)

THAC0: +6
Damage: 1d10+6 (piercing)
Speed Factor: 3
Proficiency Type: Halberd
Type: Two-handed
Requires:
 13 Strength
 
Weight: 9
"
