//WAR HAMMER +2 - valore 2500mo//
COPY "rick_bigg_mod/items/HAMM08.itm" "override"
	SAY NAME1 "Hammer"
	SAY UNIDENTIFIED_DESC "Mounted knights cannot effectively use long pole weapons while on horseback and, as a result, many weapons have been fitted with shorter shafts so they may be wielded with just one hand. Maces and flails are two examples of this—the war hammer is another. The horseman's war hammer is the descendent of the Lucerne hammer. It is made entirely of steel, with rondels protecting and strengthening the grip. (Rondels are small disks of metal, often shaped into decorative designs.) The shaft is about eighteen inches long.

STATISTICS:

Damage: 2d3+1 (crushing)
Speed Factor: 6
Proficiency Type: War Hammer
Type: One-handed
Requires:
 13 Strength

Weight: 6"

	SAY NAME2 "War Hammer +2"
	SAY DESC "Mounted knights cannot effectively use pole arms while on horseback, and as a result, many weapons have been altered so they may be used one-handed. The horseman's war hammer is made entirely of steel and has a shaft about eighteen inches long. Powerful magical energy flows through this weapon, though its origins are nondescript.

STATISTICS:

THAC0: +2
Damage: 2d3+3
Damage type: Crushing
Speed Factor: 4
Proficiency Type: War Hammer
Type: One-handed
Requires:
 13 Strength

Weight: 6"





//THE KNEECAPPER +2 - valore 6000mo//
COPY "rick_bigg_mod/items/HAMM04.itm" "override"
	SAY NAME1 "Hammer"
	SAY UNIDENTIFIED_DESC "A massive warhammer inscribed with dwarven runes.

STATISTICS:

Damage: 2d3+1 (crushing)
Speed Factor: 6
Proficiency Type: War Hammer
Type: One-handed
Requires:
 13 Strength

Weight: 9"

	SAY NAME2 "The Kneecapper +2"
	SAY DESC "The Kneecapper, or The Capper as it is affectionately known in dwarven circles, is rumored to have been forged by Clangeddin himself. He gave it to a small clan of homeless dwarves that they might carve a place for themselves amongst the giants and ogres in their area. The hammer has been passed from hero to hero, occasionally finding its way into non-dwarven hands.

STATISTICS:

THAC0: +2, +4 vs. giant humanoids
Damage: 2d3+3, +5 vs. giant humanoids
Damage type: Crushing
Speed Factor: 5
Proficiency Type: War Hammer
Type: One-handed
Requires:
 15 Strength

Weight: 9"







//BOROK'S FIST +2 - 4500mo//
COPY "rick_bigg_mod/items/HAMM05.itm" "override"
	SAY NAME1 "Hammer"
	SAY UNIDENTIFIED_DESC "Mounted knights cannot effectively use pole arms while on horseback, and as a result, many weapons have been altered so they may be used one-handed. The horseman's war hammer is made entirely of steel and has a shaft about eighteen inches long. Powerful magical energy flows through this weapon, though its origins are nondescript.

STATISTICS:

Damage: 2d3+1 (crushing)
Speed Factor: 6
Proficiency Type: War Hammer
Type: One-handed
Requires:
 13 Strength

Weight: 6"

	SAY NAME2 "Borok's Fist +2"
	SAY DESC "Borok was a human hero that led several campaigns against orc and goblin that had plagued his people in a number of their communities. This hammer was his blessed weapon, which his elven allies called his 'little iron fist'.

STATISTICS:

Equipped abilities:
– Critical hit chance: +5% with this weapon 

THAC0: +2
Damage: 2d3+3
Damage type: Crushing
Speed Factor: 4
Proficiency Type: War Hammer
Type: One-handed
Requires:
 13 Strength

Weight: 4"










//HAMMER OF THUNDERBOLTS +3 - 7500mo//
COPY "rick_bigg_mod/items/HAMM07.itm" "override"
	SAY NAME1 "Hammer"
	SAY UNIDENTIFIED_DESC "A massive warhammer inscribed with dwarven runes.

STATISTICS:

Damage: 2d3+1 (crushing)
Speed Factor: 6
Proficiency Type: War Hammer
Type: One-handed
Requires:
 15 Strength

Weight: 9"

	SAY NAME2 "Hammer of Thunderbolts +3"
	SAY DESC "A dwarven smith, Silverblade, forged this hammer and two other items: a girdle of frost giant strength and a pair of gauntlets of ogre power. His intention was to gift them to his son, who was then a high officer in the dwarven armies, fighting the giant and ogre tribes of the area. Unfortunately, Silverblade's son died just after the completion of the three items and before they could be gifted to him. In grief, Silverblade himself donned the girdle and the gauntlets. Taking up the Hammer of Thunderbolts, he went to battle against the giant folk. He died valiantly.

STATISTICS:

THAC0: +3
Damage: 2d3+4, +3 Electricity 
Damage type: Crushing
Speed Factor: 3
Proficiency Type: War Hammer
Type: One-handed
Requires:
 18 Strength

Weight: 9"








//AEGIS-FANG +3 - valore 13000mo//
COPY "rick_bigg_mod/items/AEGIS.itm" "override"
	SAY NAME1 "Hammer"
	SAY UNIDENTIFIED_DESC "A massive warhammer inscribed with dwarven runes.

STATISTICS:

Damage: 2d3+1 (crushing)
Speed Factor:6
Proficiency Type: War Hammer
Type: One-handed
Requires:
 15 Strength

Weight: 9"

	SAY NAME2 "Aegis-Fang +3"
	SAY DESC "This weapon was made specifically for Wulfgar by Bruenor Battlehammer, and the strongest of its enchantments only function while in the young warrior's hands. Anyone else wields Aegis-Fang as a war hammer +3.

STATISTICS:

Equipped abilities:
– Critical hit chance: +10% with this weapon (only with ranged attack)

Combat abilities (thrown):
– On critical hit opponent is knocked back and stunned for a round (save vs. Rod at -4)

THAC0: +3
Damage: 2d3+4 (crushing)
Speed Factor: 3
Proficiency Type: War Hammer
Type: One-handed
Requires:
 18 Strength

Weight: 9"

COPY_EXISTING "AEGIS.ITM" "override/AEGIS2.ITM"

	
	
	
	
	
	
//CROM FAEYR +5 - valore 20000mo//
COPY "rick_bigg_mod/items/HAMM09.itm" "override"
	SAY NAME1 "Hammer"
	SAY UNIDENTIFIED_DESC "A massive warhammer inscribed with dwarven runes.

STATISTICS:

Damage: 2d3+1 (crushing)
Speed Factor: 6
Proficiency Type: War Hammer
Type: One-handed
Requires:
 15 Strength

Weight: 9"

	SAY NAME2 "Crom Faeyr +5"
	SAY DESC "This is the true name that the dwarven weaponsmith, Silverblade, gave to the weapon he intended to create for his son. Alas, his son died before the weapon was ever completed, but here it stands complete... forged from the combined magic of the original hammer with the gauntlets of ogre power and a girdle of frost giant strength. Crom Faeyr gifts its users with all the powers of the original Hammer of Thunderbolts, in addition to enormous strength and the ability to kill golems, ettins, and trolls in one blow.

STATISTICS:

Equipped abilities:
– Strength: 25

Combat abilities:
– Slays flesh golems, stone golems and clay golems

THAC0: +5
Damage: 2d3+6, +5 Electricity
Damage type: Crushing
Speed Factor: 1
Proficiency Type: War Hammer
Type: One-handed
Requires:
 18 Strength

Weight: 9"




//RUNEHAMMER +4 - valore 9000mo - no evil//
COPY "rick_bigg_mod/items/HAMM10.itm" "override"
	SAY NAME1 "Hammer"
	SAY UNIDENTIFIED_DESC "A massive warhammer inscribed with dwarven runes.

STATISTICS:

Damage: 2d3+1 (crushing)
Speed Factor: 6
Proficiency Type: War Hammer
Type: One-handed
Requires:
 15 Strength

Weight: 9"

	SAY NAME2 "Runehammer +4"
	SAY DESC "The Runehammer is an ancient relic blessed by Clangeddin, forged in the deepest vaults of the Spine of the World. Unlike weapons that rely on brute enchantments, the power of this warhammer is derived from the complex network of glowing sigils etched across its cold-forged mithril head. These are not merely decorative engravings; they are 'Living Runes' of the high dwarven tongue, each one bound to a specific aspect of protection and purification.
	
	However, these runes must be activated in some way to reveal the hammer's true power.

STATISTICS:

Equipped abilities:
– Immunity to Level Drain 

THAC0: +4
Damage: 2d3+5 (crushing)
Speed Factor: 2
Proficiency Type: War Hammer
Type: One-handed
Requires:
 18 Strength

Weight: 9"





//RUNEHAMMER +5 - valore 18000mo - no evil//
COPY "rick_bigg_mod/items/HAMM11.itm" "override"
	SAY NAME1 "Hammer"
	SAY UNIDENTIFIED_DESC "A massive warhammer inscribed with dwarven runes.

STATISTICS:

Damage: 2d3+1 (crushing)
Speed Factor: 6
Proficiency Type: War Hammer
Type: One-handed
Requires:
 15 Strength

Weight: 9"

	SAY NAME2 "Runehammer +5"
	SAY DESC "The Runehammer is an ancient relic blessed by Clangeddin, forged in the deepest vaults of the Spine of the World. Unlike weapons that rely on brute enchantments, the power of this warhammer is derived from the complex network of glowing sigils etched across its cold-forged mithril head. These are not merely decorative engravings; they are 'Living Runes' of the high dwarven tongue, each one bound to a specific aspect of protection and purification.
	
	The rune of Clangeddin is now inscribed on the head of this hammer, and activate all others runes, revealing the true power of the weapon.

STATISTICS:

Equipped abilities
– Immunity to Level Drain

Combat abilities:
– On hit activate the following spells:
	- 3% Sunray
	- 6% Mass Cure
	- 6% Magic Circle against Evil
	- 6% Defensive Harmony
	- 9% Holy Smite

THAC0: +5
Damage: 2d3+6 (crushing)
Speed Factor: 1
Proficiency Type: War Hammer
Type: One-handed
Requires:
 18 Strength

Weight: 9"
