//LEATHER ARMOR +1 - 1200mo//
COPY "rick_bigg_mod/items/LEAT02.itm" "override"
	SAY NAME1 "Leather Armor"
	SAY UNIDENTIFIED_DESC "Basic armor made of thick, wax or water-hardened leather. It is sturdy protection, not supple like boots or a cloak. Soft garment leathers like that would offer no more protection than common clothing. 

STATISTICS:

Armor Class: 9 (7 vs. slashing, 8 vs. crushing)
Requires:
 5 Strength

Weight: 15
"

	SAY NAME2 "Leather Armor +1"
	SAY DESC "Basic armor made of thick, wax or water-hardened leather. It is sturdy protection, not supple like boots or a cloak. Soft garment leathers like that would offer no more protection than common clothing. Magical enchantments have improved the protective abilities of this particular suit.

STATISTICS:

Armor Class: 8 (6 vs. slashing, 7 vs. crushing)
Requires:
 5 Strength

Weight: 10"