//KATANA +1 - 2000mo//
COPY "rick_bigg_mod/items/SW1H44.itm" "override"
	SAY NAME1 "Katana"
	SAY UNIDENTIFIED_DESC "The katana is a single-edged, slightly curved sword that ends with a chisel point. The katana is perhaps one of the finest swords ever made, the steps to its creation a long and secret process that is more art form than anything else. This blade is an important facet of Kara-Turan culture. To touch or wield a samurai's katana is to insult the samurai and to incite his wrath. For a gaijin, or foreigner, to own such a blade is a rare occurrence. Either the gaijin is a greatly honored friend of an important minister, or the gaijin has murdered a samurai.

STATISTICS:

Damage: 1d8 (slashing)
Speed Factor: 4
Proficiency Type: Katana
Type: One-handed
Requires:
 9 Strength

Weight: 6"

	SAY NAME2 "Katana +1"
	SAY DESC "To enchant a katana is no simple process. To improve it usually requires a sacrifice, perhaps a dying samurai might beg a Wu Jen to infuse his fighting spirit into the spirit of the katana. The wielder of an enchanted katana, such as this one, must respect the customs of Kara-Tur and of the samurai who once carried this blade into battle. Not doing so could drastically change one's luck for the worse.

STATISTICS:

THAC0: +1
Damage: 1d8+1 (slashing)
Speed Factor: 3
Proficiency Type: Katana
Type: One-handed
Requires:
 9 Strength

Weight: 5"






//KATANA +2 - 3000mo//
COPY "rick_bigg_mod/items/SW1H55.itm" "override"
	SAY NAME1 "Katana"
	SAY UNIDENTIFIED_DESC "The katana is a single-edged, slightly curved sword that ends with a chisel point. The katana is perhaps one of the finest swords ever made, the steps to its creation a long and secret process that is more art form than anything else. This blade is an important facet of Kara-Turan culture. To touch or wield a samurai's katana is to insult the samurai and to incite his wrath. For a gaijin, or foreigner, to own such a blade is a rare occurrence. Either the gaijin is a greatly honored friend of an important minister, or the gaijin has murdered a samurai.

STATISTICS:

Damage: 1d8 (slashing)
Speed Factor: 4
Proficiency Type: Katana
Type: One-handed
Requires:
 9 Strength

Weight: 6"

	SAY NAME2 "Katana +2"
	SAY DESC "To enchant a katana is no simple process. Unlike conventional weapons. To improve it usually requires a sacrifice, perhaps a dying samurai might beg a Wu Jen to infuse his fighting spirit into the spirit of the katana. The wielder of an enchanted katana, such as this one, must respect the customs of Kara-Tur and of the samurai who once carried this blade into battle. Not doing so could drastically change one's luck for the worse.

STATISTICS:

THAC0: +2
Damage: 1d8+2 (slashing)
Speed Factor: 2
Proficiency Type: Katana
Type: One-handed
Requires:
 9 Strength

Weight: 4"









//MALAKAR +2 - 4000mo//
COPY "rick_bigg_mod/items/SW1H45.itm" "override"
	SAY NAME1 "Katana"
	SAY UNIDENTIFIED_DESC "The katana is a single-edged, slightly curved sword that ends with a chisel point. The katana is perhaps one of the finest swords ever made, the steps to its creation a long and secret process that is more art form than anything else. This blade is an important facet of Kara-Turan culture. To touch or wield a samurai's katana is to insult the samurai and to incite his wrath. For a gaijin, or foreigner, to own such a blade is a rare occurrence. Either the gaijin is a greatly honored friend of an important minister, or the gaijin has murdered a samurai.

STATISTICS:

Damage: 1d8 (slashing)
Speed Factor: 4
Proficiency Type: Katana
Type: One-handed
Requires:
 9 Strength

Weight: 6"

	SAY NAME2 "Malakar +2"
	SAY DESC "This sleek katana radiates magical energy when carried. The Malakar, or Dueling Steel, was used by a less-than-honorable samurai during duels against other samurai. As if of its own volition, it will swoop down and deflect the slashing attacks of other weapons. It is perfect for the warrior concerned about defense as well as offense.

STATISTICS:

Equipped abilities:
– Armor Class: +3 vs. slashing weapons

THAC0: +2
Damage: 1d8+2 (slashing)
Speed Factor: 2
Proficiency Type: Katana
Type: One-handed
Requires:
 9 Strength

Weight: 4"




//CRIMSON DAWN +2 - 5500mo//
COPY "rick_bigg_mod/items/BDSW1H01.itm" "override"
	SAY NAME1 "Katana"
	SAY UNIDENTIFIED_DESC "The katana is a single-edged, slightly curved sword that ends with a chisel point. The katana is perhaps one of the finest swords ever made, the steps to its creation a long and secret process that is more art form than anything else. This blade is an important facet of Kara-Turan culture. To touch or wield a samurai's katana is to insult the samurai and to incite his wrath. For a gaijin, or foreigner, to own such a blade is a rare occurrence. Either the gaijin is a greatly honored friend of an important minister, or the gaijin has murdered a samurai.

STATISTICS:

Damage: 1d8 (slashing)
Speed Factor: 4
Proficiency Type: Katana
Type: One-handed
Requires:
 9 Strength

Weight: 6"

	SAY NAME2 "Crimson Dawn +2"
	SAY DESC "Legend tells that this elegant blade appeared at the moment the sun rose over the eastern horizon. As the dawn's rosy light flooded the forest, the blade shimmered into being atop a flat stone. Local foresters, even warriors, were afraid to touch the weapon lest it was cursed. Finally, a brave old man who had been a fighter in his youth grasped the hilt and claimed the blade as its own. Terrifying beasts sprang at him a moment later, creatures of red mist and fangs and claws. The old man clung to his courage and lay about him with the sword. He grew faster with every monster he killed until finally the clearing was empty. The old man was feasted in the village for days and then set off to live his final years seeking adventure on the road.

STATISTICS:

Equipped abilities: 
– Critical Hit Chance: +5% (with this weapon only)

Combat abilities:
– 15% chance per kill of hasting the wielder for 3 rounds

THAC0: +2
Damage: 1d8+2 (slashing)
Speed Factor: 2
Proficiency Type: Katana
Type: One-handed
Requires:
 9 Strength

Weight: 4"





//USUNO'S BLADE +3 - 8000mo//
COPY "rick_bigg_mod/items/SW1H67.itm" "override"
	SAY NAME1 "Katana"
	SAY UNIDENTIFIED_DESC "The katana is a single-edged, slightly curved sword that ends with a chisel point. The katana is perhaps one of the finest swords ever made, the steps to its creation a long and secret process that is more art form than anything else. This blade is an important facet of Kara-Turan culture. To touch or wield a samurai's katana is to insult the samurai and to incite his wrath. For a gaijin, or foreigner, to own such a blade is a rare occurrence. Either the gaijin is a greatly honored friend of an important minister, or the gaijin has murdered a samurai.

STATISTICS:

Damage: 1d8 (slashing)
Speed Factor: 4
Proficiency Type: Katana
Type: One-handed
Requires:
 9 Strength

Weight: 6"

	SAY NAME2 "Usuno's Blade +3"
	SAY DESC "The daughter of a high ranking official within the bureaucratic society of Kara-Tur, Usuno rejected her family's station and carved a legend for herself among the yakuza of the underworld. The blade of this enchanted katana drips acid.

STATISTICS:

Combat abilities: 
– Target takes 1 extra point of acid damage per round during the next 3 rounds

THAC0: +3
Damage: 1d8+3, +1 acid
Speed Factor: 1
Proficiency Type: Katana
Type: One-handed
Requires:
 9 Strength

Weight: 3"






//YAMATO +4 - 10000mo//
COPY "rick_bigg_mod/items/SW1H66.itm" "override"
	SAY NAME1 "Katana"
	SAY UNIDENTIFIED_DESC "The katana is a single-edged, slightly curved sword that ends with a chisel point. The katana is perhaps one of the finest swords ever made, the steps to its creation a long and secret process that is more art form than anything else. This blade is an important facet of Kara-Turan culture. To touch or wield a samurai's katana is to insult the samurai and to incite his wrath. For a gaijin, or foreigner, to own such a blade is a rare occurrence. Either the gaijin is a greatly honored friend of an important minister, or the gaijin has murdered a samurai.

STATISTICS:

Damage: 1d8 (slashing)
Speed Factor: 4
Proficiency Type: Katana
Type: One-handed
Requires:
 9 Strength

Weight: 6"

	SAY NAME2 "Yamato +4"
	SAY DESC "The name of the mighty Wu Jen who fashioned this katana is long forgotten. However, the name Yamato, loosely translated, means 'Guardian' or 'Defender'.

STATISTICS:

Combat abilities:
- 20% chance to improve your AC by 2 for 2 rounds

THAC0: +4
Damage: 1d8+4 (slashing)
Speed Factor: 0
Proficiency Type: Katana
Type: One-handed
Requires:
 9 Strength

Weight: 2"




//CELESTIAL FURY +4 - 13000mo//
COPY "rick_bigg_mod/items/SW1H51.itm" "override"
	SAY NAME1 "Katana"
	SAY UNIDENTIFIED_DESC "The katana is a single-edged, slightly curved sword that ends with a chisel point. The katana is perhaps one of the finest swords ever made, the steps to its creation a long and secret process that is more art form than anything else. This blade is an important facet of Kara-Turan culture. To touch or wield a samurai's katana is to insult the samurai and to incite his wrath. For a gaijin, or foreigner, to own such a blade is a rare occurrence. Either the gaijin is a greatly honored friend of an important minister, or the gaijin has murdered a samurai.

STATISTICS:

Damage: 1d8 (slashing)
Speed Factor: 4
Proficiency Type: Katana
Type: One-handed
Requires:
 9 Strength

Weight: 6"

	SAY NAME2 "Celestial Fury +4"
	SAY DESC "Many centuries ago, a trumpet archon named Chin Yi fell in love with a mortal man in Shou Lung and swore to protect him from enemies should he ever ride to war. When that time came, however, Chin Yi's patron goddess Kwan Ying forbade her to intervene, not wishing to contribute to the bloodshed. When Chin Yi's beloved was cut down by a yuan-ti warlord, her grief was terrible and her wrath immediate: Ignoring Kwan Ying's warnings, she flew onto the battlefield and took up her beloved's katana, using the blade to cut down the warlord and all those who served him. She continued the slaughter of the yuan-ti army until Kwan Ying herself appeared before her, arms open and eyes full of sympathy. 'If it will stop this slaughter, I will ease your pain and end your suffering.'

'I do not wish to end my suffering,' replied Chin Yi. 'I wish for my fury to sound throughout the ages, now and forever.' Wanting to help her servant, but not wishing to unleash such powerful fury on the world, Kwan Ying bound Chin Yi's spirit to the blade of the man she had failed to protect and then hid the weapon in a warrior's tomb. The tomb was later infiltrated and the weapon stolen, and although Chin Yi's cries could no longer be heard through the steel of the blade, her vengeance was as brutal as ever.

STATISTICS:

Combat abilities:
– Booming Thunder: Hit target must save vs. Wand or be stunned for 1 round
– Shocking Blow: 20% chance of an extra 20 electrical damage to hit target

Charge abilities:
– Lightning Strike two times per day (10d6 electricity damage, save vs. Wand for half)

THAC0: +4
Damage: 1d8+4 (slashing)
Speed Factor: 0
Proficiency Type: Katana
Type: One-handed
Requires:
 9 Strength

Weight: 2"





//HINDO'S DOOM +3 - 8000mo - NO EVIL//
COPY "rick_bigg_mod/items/SW1H70.itm" "override"
	SAY NAME1 "Katana"
	SAY UNIDENTIFIED_DESC "The katana is a single-edged, slightly curved sword that ends with a chisel point. The katana is perhaps one of the finest swords ever made, the steps to its creation a long and secret process that is more art form than anything else. This blade is an important facet of Kara-Turan culture. To touch or wield a samurai's katana is to insult the samurai and to incite his wrath. For a gaijin, or foreigner, to own such a blade is a rare occurrence. Either the gaijin is a greatly honored friend of an important minister, or the gaijin has murdered a samurai.

STATISTICS:

Damage: 1d8 (slashing)
Speed Factor: 4
Proficiency Type: Katana
Type: One-handed
Requires:
 9 Strength

Weight: 6"

	SAY NAME2 "Hindo's Doom +3"
	SAY DESC "This elegant yet intimidating katana belonged to the legendary Prince Hindo of Tu Lung. A master of both the blade and the spirit, Hindo was a man of unwavering discipline who sought to protect his kingdom from the encroaching shadows of the Kara-Tur underworld. However, the sword earned its dark moniker—Hindo’s Doom—not from any flaw in its steel, but from the tragic fate of its master. 

STATISTICS:

Equipped abilities:
– Magic Resistance: +10%

Charge abilities:
– Lesser Restoration once per day
  Range: Touch
  Area of Effect: 1 creature

THAC0: +3
Damage: 1d8+3, +3 vs evil (slashing)
Speed Factor: 1
Proficiency Type: Katana
Type: One-handed
Requires:
 9 Strength

Weight: 3"





//HINDO'S DOOM +5 - 17000mo - NO EVIL//
COPY "rick_bigg_mod/items/SW1H71.itm" "override"
	SAY NAME1 "Katana"
	SAY UNIDENTIFIED_DESC "The katana is a single-edged, slightly curved sword that ends with a chisel point. The katana is perhaps one of the finest swords ever made, the steps to its creation a long and secret process that is more art form than anything else. This blade is an important facet of Kara-Turan culture. To touch or wield a samurai's katana is to insult the samurai and to incite his wrath. For a gaijin, or foreigner, to own such a blade is a rare occurrence. Either the gaijin is a greatly honored friend of an important minister, or the gaijin has murdered a samurai.

STATISTICS:

Damage: 1d8 (slashing)
Speed Factor: 4
Proficiency Type: Katana
Type: One-handed
Requires:
 9 Strength

Weight: 6"

	SAY NAME2 "Hindo's Doom +5"
	SAY DESC "This elegant yet intimidating katana belonged to the legendary Prince Hindo of Tu Lung. A master of both the blade and the spirit, Hindo was a man of unwavering discipline who sought to protect his kingdom from the encroaching shadows of the Kara-Tur underworld. However, the sword earned its dark moniker—Hindo’s Doom—not from any flaw in its steel, but from the tragic fate of its master.
	
	Reunited with the hand of its original owner, Hindo's Doom is a katana worthy of the greatest of samurai. 

STATISTICS:

Equipped abilities:
– Magic Resistance: +20%
– Immunity to all forms of death magic
- Magic circle against evil always active

Charge abilities:
– Greater Restoration once per day
  Area of Effect: 1 creature

THAC0: +5
Damage: 1d8+5, +5 vs evil (slashing)
Speed Factor: 0
Proficiency Type: Katana
Type: One-handed
Requires:
 9 Strength

Weight: 2"