//ARDULIA'S FALL +2 - 5500mo//
COPY "rick_bigg_mod/items/BLUN20.itm" "override"
	SAY NAME1 "Mace"
	SAY UNIDENTIFIED_DESC "The mace is a direct descendant of the basic club, being nothing more than a wooden shaft with a stone or iron head mounted on the end. The head design varies: Some are spiked, others flanged, and still others have pyramidal knobs.

STATISTICS:

Damage: 1d6+1 (crushing)
Speed Factor: 6
Proficiency Type: Mace
Type: One-handed
Requires:
 11 Strength

Weight: 10"

	SAY NAME2 "Ardulia's Fall +2"
	SAY DESC "Ardulia the Agile was a man whose speed and skill at knife play made him exceptionally lethal in battle, and he repeatedly proved it by leading raids on settlements along the Sword Coast. He would often challenge the village leader for possession of the town, and with his speed, the duels were always quickly decided in his favor. Ardulia met his match one spring morn however, when he battled the priest Itgan, who wielded this mace. Ardulia seemed to stagger under each blow, slowing his pace to recoup and regain his breath. Without his speed, Ardulia was lost, and fell to the measured attacks of Itgan.

STATISTICS:

Combat abilities:
– Hit target must save vs. Polymorph or be slowed for 2 rounds

THAC0: +2
Damage: 1d6+3 (crushing)
Speed Factor: 4
Proficiency Type: Mace
Type: One-handed
Requires:
 11 Strength

Weight: 7"







//MAULER'S ARM +2 - 4000mo//
COPY "rick_bigg_mod/items/BLUN19.itm" "override"
	SAY NAME1 "Mace"
	SAY UNIDENTIFIED_DESC "The mace is a direct descendant of the basic club, being nothing more than a wooden shaft with a stone or iron head mounted on the end. The head design varies: Some are spiked, others flanged, and still others have pyramidal knobs.

STATISTICS:

Damage: 1d6+1 (crushing)
Speed Factor: 6
Proficiency Type: Mace
Type: One-handed
Requires:
 11 Strength

Weight: 10"

	SAY NAME2 "Mauler's Arm +2"
	SAY DESC "Jurrg the Mauler was proud chieftain of a northern tribe, but feared he would be the last of his family to lead. His son Kullen was sickly and clearly couldn't meet the traditional requirements of strength for a chieftain. Jurrg knew that wise leadership took more than brawn, however, so he bargained to enchant this mace such that it would cover Kullen's weakness. Who Jurrg made the deal with is unknown, but the cost was apparently high. Kullen came to rule soon after.

STATISTICS:

Equipped Ability:
– Strength: 18/75

THAC0: +2
Damage: 1d6+3 (crushing)
Speed Factor: 4
Proficiency Type: Mace
Type: One-handed

Weight: 7"







//SKULLACRASHER +3 - 5000mo//
COPY "rick_bigg_mod/items/BLUN18.itm" "override"
	SAY NAME1 "Mace"
	SAY UNIDENTIFIED_DESC "The mace is a direct descendant of the basic club, being nothing more than a wooden shaft with a stone or iron head mounted on the end. The head design varies: Some are spiked, others flanged, and still others have pyramidal knobs.

STATISTICS:

Damage: 1d6+1 (crushing)
Speed Factor: 6
Proficiency Type: Mace
Type: One-handed
Requires:
 11 Strength

Weight: 10"

	SAY NAME2 "Skullcrasher +3"
	SAY DESC "This mace is permanently bloodstained, a telltale trace of its many years spent bashing heads. The weapon would have been the bane of humanoids throughout its history, but those that wielded it seem to have been purposely left out of historic record.

STATISTICS:

THAC0: +3
Damage: 1d6+4, +5 extra vs. humanoids
Damage type: Crushing
Speed Factor: 3
Proficiency Type: Mace
Type: One-handed
Requires:
 11 Strength

Weight: 6"



//JERROD'S MACE +3 - valore 9000mo//
COPY "rick_bigg_mod/items/WAMACE.itm" "override"
	SAY NAME1 "Mace"
	SAY UNIDENTIFIED_DESC "The mace is a direct descendant of the basic club, being nothing more than a wooden shaft with a stone or iron head mounted on the end. The head design varies: Some are spiked, others flanged, and still others have pyramidal knobs.

STATISTICS:

Damage: 1d6+1 (crushing)
Speed Factor: 6
Proficiency Type: Mace
Type: One-handed
Requires:
 11 Strength

Weight: 10"

	SAY NAME2 "Jerrod's Mace +3"
	SAY DESC "This was the favored weapon of the priest of Tempus named Jerrod. Jerrod sacrificed his life to save the town of Easthaven from the powerful devil known as Belhifet.

STATISTICS:

Equipped abilities:
– The wearer and any allies within their visual radius are immune to fear and morale failure

THAC0: +3, +5 vs. demons and devils
Damage: 1d6+4, +6 vs. demons and devils
Damage type: Crushing
Speed Factor: 3
Proficiency Type: Mace
Type: One-handed
Requires:
 11 Strength

Weight: 6"





//MACE OF DISRUPTION +3 - valore 8000mo//
COPY "rick_bigg_mod/items/BLUN12.itm" "override"
	SAY NAME1 "Mace"
	SAY UNIDENTIFIED_DESC "The mace is a direct descendant of the basic club, being nothing more than a wooden shaft with a stone or iron head mounted on the end. The head design varies: Some are spiked, others flanged, and still others have pyramidal knobs.

STATISTICS:

Damage: 1d6+1 (crushing)
Speed Factor: 6
Proficiency Type: Mace
Type: One-handed
Requires:
 11 Strength

Weight: 10"

	SAY NAME2 "Mace of Disruption +3"
	SAY DESC "This heavy mace was created for a very specific purpose: to slay undead. Any such creature hit by it not only feels the sting of the weapon, but also has a chance of being simply blasted from existence. There are legends that speak of a priest so holy a single glancing touch could send a vampire to oblivion, but whether the weapon empowered her or she empowered it is a topic for theologians.

STATISTICS:

Equipped abilities:
- Immunity to hold

Combat abilities: 
– Undead must save vs. Death at -2 or be utterly destroyed

THAC0: +3
Damage: 1d6+4, +5 magical extra vs. undead
Damage type: Crushing
Speed Factor: 3
Proficiency Type: Mace
Type: One-handed
Requires:
 11 Strength

Weight: 6"





//MACE OF DISRUPTION +4 - valore 12000mo//
COPY "rick_bigg_mod/items/BLUN25.itm" "override"
	SAY NAME1 "Mace"
	SAY UNIDENTIFIED_DESC "The mace is a direct descendant of the basic club, being nothing more than a wooden shaft with a stone or iron head mounted on the end. The head design varies: Some are spiked, others flanged, and still others have pyramidal knobs.

STATISTICS:

Damage: 1d6+1 (crushing)
Speed Factor: 6
Proficiency Type: Mace
Type: One-handed
Requires:
 11 Strength

Weight: 10"

	SAY NAME2 "Mace of Disruption +4"
	SAY DESC "This heavy mace was created for a very specific purpose: to slay undead. Any such creature hit by it not only feels the sting of the weapon, but also has a chance of being simply blasted from existence. There are legends that speak of a priest so holy a single glancing touch could send a vampire to oblivion, but whether the weapon empowered her or she empowered it is a topic for theologians.

Now that the mace has been coated with illithium, it is even more potent, conferring to its user immunity to the life-draining powers of the more powerful undead.

STATISTICS:

Equipped abilities:
- Immunity to Hold
– Immunity to Level Drain

Combat abilities:
– Undead must save vs. Death at -4 or be utterly destroyed

THAC0: +4
Damage: 1d6+5, +10 magical damage extra vs. undead
Damage type: Crushing
Speed Factor: 2
Proficiency Type: Mace
Type: One-handed
Requires:
 11 Strength

Weight: 6"



//ROD OF ATROPHY +5 - valore 10000mo//
COPY "rick_bigg_mod/items/RODS02.itm" "override"
	SAY NAME1 "Rod"
	SAY UNIDENTIFIED_DESC "Rods are about three feet long and as thick as your thumb. They are normally found in cases or similar storage places. Rods can be fashioned from metal, wood, ivory, or bone. They can be plain or decorated and carved, tipped, or not. Rods are powered by charges, unless noted otherwise in the description of a particular rod. Each time the rod is used, one or more charge may be expended.

STATISTICS:

Weight: 3"

	SAY NAME2 "Rod of Atrophy +5"
	SAY DESC "This mace, forged from a strange, translucent alloy that seems to hum with an unsettling vibration, was never intended for traditional warfare. Legends say it was crafted by a cabal of wizard-smiths who sought a weapon that could strike the spirit rather than the flesh. The head of the mace does not truly hit its target in the physical sense; instead, it passes through armor and bone like a ghostly mist, discharging a surge of pure arcane energy directly into the victim's life force. While it leaves no bruises or broken bones, those struck by the Ethereal Lash feel their very essence beginning to unravel, leaving them fragile and drained as the weapon systematically deconstructs their magical and physical defenses.

STATISTICS:

Combat abilities:
- On hit target suffers Ray of Enfeeblement

THAC0: +5
Damage: 10d4 (save vs. Wand for half), no Strength bonus
Damage type: Magical
Speed Factor: 0
Proficiency Type: Mace
Type: One-handed
Range: 1 yard
Requires:
 3 Strength

Weight: 1"





//STORM STAR +4 - valore 8000mo//
COPY "rick_bigg_mod/items/BLUN28.itm" "override"
	SAY NAME1 "Mace"
	SAY UNIDENTIFIED_DESC "The mace is a direct descendant of the basic club, being nothing more than a wooden shaft with a stone or iron head mounted on the end. The head design varies: Some are spiked, others flanged, and still others have pyramidal knobs.

STATISTICS:

Damage: 1d6+1 (crushing)
Speed Factor: 6
Proficiency Type: Mace
Type: One-handed
Requires:
 11 Strength

Weight: 10"

	SAY NAME2 "Storm Star +4"
	SAY DESC "The Storm Star is a weapon born of the tempest, forged in a place where the Elemental Plane of Air bleeds into the Material Plane. Legend has it that the first of these maces was gifted by Akadi, Queen of the Air, to a mortal champion who defended her shrines. The head of the mace is crafted from a strange, silver-blue alloy that crackles with spectacular arcs of lightning when wielded.

STATISTICS:

THAC0: +4
Damage: 1d6+5, +2 electricity damage
Damage type: Crushing
Speed Factor: 2
Proficiency Type: Mace
Type: One-handed
Requires:
 11 Strength

Weight: 5"






//STORM STAR +5 - valore 15000mo//
COPY "rick_bigg_mod/items/BLUN29.itm" "override"
	SAY NAME1 "Mace"
	SAY UNIDENTIFIED_DESC "The mace is a direct descendant of the basic club, being nothing more than a wooden shaft with a stone or iron head mounted on the end. The head design varies: Some are spiked, others flanged, and still others have pyramidal knobs.

STATISTICS:

Damage: 1d6+1 (crushing)
Speed Factor: 6
Proficiency Type: Mace
Type: One-handed
Requires:
 11 Strength

Weight: 10"

	SAY NAME2 "Storm Star +5"
	SAY DESC "The Storm Star is a weapon born of the tempest, forged in a place where the Elemental Plane of Air bleeds into the Material Plane. Legend has it that the first of these maces was gifted by Akadi, Queen of the Air, to a mortal champion who defended her shrines. The head of the mace is crafted from a strange, silver-blue alloy that crackles with spectacular arcs of lightning when wielded.
	
	Infused with the otherworldly starfall ore, the powers of this already formidable weapon are greatly enhanced.

STATISTICS:

Combat abilities:
– 15% chance of casting Chain Lightning (at level 12) at the target with each successful attack

THAC0: +5
Damage: 1d6+6, +4 electricity damage
Damage type: Crushing
Speed Factor: 1
Proficiency Type: Mace
Type: One-handed
Requires:
 11 Strength

Weight: 4"