//PLATE MAIL +1 - 4000mo//
COPY "rick_bigg_mod/items/PLAT10.itm" "override"
	SAY NAME1 "Plate Mail"
	SAY UNIDENTIFIED_DESC "Plate mail is a combination of chain armor with metal plates covering the vital areas such as the chest, abdomen, and groin. Similar in construction to bronze plate mail, true plate mail comprises chain and leather.

STATISTICS:

Armor Class: 3 (0 vs. slashing, 2 vs. piercing and missile)
Speed Factor: -3
Requires:
 13 Strength

Weight: 50"

	SAY NAME2 "Plate Mail +1"
	SAY DESC "Plate mail is a combination of chain armor with metal plates covering the vital areas such as the chest, abdomen and groin. Similar in construction to bronze plate mail, true plate mail comprises chain and leather. 
	In addition, this suit of plate mail is enchanted and gives additional bonuses to the wearer's Armor Class.

STATISTICS:

Armor Class: 2 (-1 vs. slashing, 1 vs. piercing and missile)
Speed Factor: -3
Requires:
 13 Strength

Weight: 40
"




//PLATE MAIL +2 - 5500mo//
COPY "rick_bigg_mod/items/OHPLAT50.itm" "override"
	SAY NAME1 "Plate Mail"
	SAY UNIDENTIFIED_DESC "Plate mail is a combination of chain armor with metal plates covering the vital areas such as the chest, abdomen, and groin. Similar in construction to bronze plate mail, true plate mail comprises chain and leather.

STATISTICS:

Armor Class: 3 (0 vs. slashing, 2 vs. piercing and missile)
Speed Factor: -3
Requires:
 13 Strength

Weight: 50"

	SAY NAME2 "Plate Mail +2"
	SAY DESC "Plate mail is a combination of chain armor with metal plates covering the vital areas such as the chest, abdomen and groin. Similar in construction to bronze plate mail, true plate mail comprises chain and leather. 
	In addition, this suit of plate mail is enchanted and gives additional bonuses to the wearer's Armor Class.

STATISTICS:

Armor Class: 1 (-2 vs. slashing, 0 vs. piercing and missile)
Speed Factor: -3
Requires:
 13 Strength

Weight: 30
"










//ANKHEG SCALE - 6000mo//
COPY "rick_bigg_mod/items/PLAT06_.itm" "override"
	SAY NAME1 "Plate Mail"
	SAY UNIDENTIFIED_DESC "Plate mail is a combination of chain armor with metal plates covering the vital areas such as the chest, abdomen, and groin. Similar in construction to bronze plate mail, true plate mail comprises chain and leather.

STATISTICS:

Armor Class: 3 (0 vs. slashing, 2 vs. piercing and missile)
Speed Factor: -3
Requires:
 13 Strength

Weight: 50"

	SAY NAME2 "Ankheg Scale"
	SAY DESC "This plate mail has been expertly crafted by Taerom Fuiruim of Beregost. Sheathed in the chitinous scales of the ankheg, it provides a greater degree of protection than traditional plate mail and is not susceptible to rust. As any world-weary adventurer will tell you, however, the best appreciated aspect of ankheg mail is its light weight and low encumbrance. Monsters come and go, but fatigue is a constant enemy.

STATISTICS:

Armor Class: 3 (1 vs. slashing, 2 vs. piercing and missile)
Speed Factor: -2
Requires:
 9 Strength

Weight: 20
"






//ANKHEG SCALE - 6000mo//
COPY "rick_bigg_mod/items/PLAT06.itm" "override"
	SAY NAME1 "Plate Mail"
	SAY UNIDENTIFIED_DESC "Plate mail is a combination of chain armor with metal plates covering the vital areas such as the chest, abdomen, and groin. Similar in construction to bronze plate mail, true plate mail comprises chain and leather.

STATISTICS:

Armor Class: 3 (0 vs. slashing, 2 vs. piercing and missile)
Speed Factor: -3
Requires:
 13 Strength

Weight: 50"

	SAY NAME2 "Ankheg Scale"
	SAY DESC "This plate mail has been expertly crafted. Sheathed in the chitinous scales of the ankheg, it provides a greater degree of protection than traditional plate mail and is not susceptible to rust. As any world-weary adventurer will tell you, however, the best appreciated aspect of ankheg mail is its light weight and low encumbrance. 
	Monsters come and go, but fatigue is a constant enemy.
	
STATISTICS:

Armor Class: 3 (1 vs. slashing, 2 vs. piercing and missile)
Speed Factor: -2
Requires:
 9 Strength

Weight: 20
"




//THE PRACTICAL DEFENSE + 2 - 7500mo//
COPY "rick_bigg_mod/items/PLAT08.itm" "override"
	SAY NAME1 "Plate Mail"
	SAY UNIDENTIFIED_DESC "Plate mail is a combination of chain armor with metal plates covering the vital areas such as the chest, abdomen, and groin. Similar in construction to bronze plate mail, true plate mail comprises chain and leather.

STATISTICS:

Armor Class: 3 (0 vs. slashing, 2 vs. piercing and missile)
Speed Factor: -3
Requires:
 13 Strength

Weight: 50"

	SAY NAME2 "The Practical Defense +2"
	SAY DESC %
The traveling adventurer could ask for no better a suit of armor in all the land. Specially commissioned by Bolhur "Thunderaxe" at GREAT expense, this suit was his most prized, even if not his most ornate. Eminently practical, Bolhur demanded armor that would offer superior protection while hampering him in the least. By "hampering" he did not just mean in movement or weight, though this suit is just over one-third the weight of normal plate mail: His ideal suit should also be able to withstand the rigors of his wanderings with little maintenance. This is not to say that Bolhur "Thunderaxe" neglected his armors (to say as such would get your ears boxed) but the regime of spit and polish required for a "gentleman's" suit was beyond his caring. Save the tassels and gilding of full plate for kings and heads of state; a working dwarf cares more for utility than looks.

STATISTICS:

Equipped abilities:
- +1 Charisma

Armor Class: 2 (-2 vs. slashing, 0 vs. piercing and missile)
Speed Factor: -1
Requires:
 10 Strength

Weight: 18
%




//DELVER'S PLATE MAIL +2 - solo berserk - 7500mo//
COPY "rick_bigg_mod/items/PLAT11.itm" "override"
	SAY NAME1 "Plate Mail"
	SAY UNIDENTIFIED_DESC "Plate mail is a combination of chain armor with metal plates covering the vital areas such as the chest, abdomen, and groin. Similar in construction to bronze plate mail, true plate mail comprises chain and leather.

STATISTICS:

Armor Class: 3 (0 vs. slashing, 2 vs. piercing and missile)
Speed Factor: -3
Requires:
 13 Strength

Weight: 50"

	SAY NAME2 "Delver's Plate Mail +2"
	SAY DESC "This unique plate armor is a masterpiece of ancient magic, best remembered as the bulwark of Kaelen Vance—a legendary warrior whose unstoppable momentum in battle became the stuff of bards' tales. The intricate runes etched inside the steel remain dormant until the wearer enters a battle rage. Once awakened, the armor draws upon this surge of inner conviction, weaving a field of continuous physical restoration that knits flesh and mends bone while the fury lasts. 
	
STATISTICS:

Equipped abilities:
– When enraged, regenerate 1 HP every 3 seconds

Armor Class: 1 (-2 vs. slashing, 0 vs. piercing and missile)
Speed Factor: -3
Requires:
 13 Strength

Weight: 25
"




//DOOMPLATE +3 - 8000mo//
COPY "rick_bigg_mod/items/PLAT12.itm" "override"
	SAY NAME1 "Plate Mail"
	SAY UNIDENTIFIED_DESC "Plate mail is a combination of chain armor with metal plates covering the vital areas such as the chest, abdomen, and groin. Similar in construction to bronze plate mail, true plate mail comprises chain and leather.

STATISTICS:

Armor Class: 3 (0 vs. slashing, 2 vs. piercing and missile)
Speed Factor: -3
Requires:
 13 Strength

Weight: 50"

	SAY NAME2 "Doomplate +3"
	SAY DESC "Named by Adarius Shin, the Doomplate is deserving of its foreboding title. He had hoped to strike fear in his enemies, but Adarius set a grim precedent when he mysteriously died soon after donning the suit, just as every adventurer who has worn it since has done. It might be said, however, that most adventurers die in their armor and are not known for their longevity.

STATISTICS:

Equipped abilities:
- -1 Luck
- 20% chance to cast Cloak of Fear when hit

Armor Class: 0 (-3 vs. slashing, -1 vs. piercing and missile)
Speed Factor: -3
Requires:
 13 Strength

Weight: 27
"





//GORGON PLATE +3 - 10000mo//
COPY "rick_bigg_mod/items/PLAT13.itm" "override"
	SAY NAME1 "Plate Mail"
	SAY UNIDENTIFIED_DESC "Plate mail is a combination of chain armor with metal plates covering the vital areas such as the chest, abdomen, and groin. Similar in construction to bronze plate mail, true plate mail comprises chain and leather.

STATISTICS:

Armor Class: 3 (0 vs. slashing, 2 vs. piercing and missile)
Speed Factor: -3
Requires:
 13 Strength

Weight: 50"

	SAY NAME2 "Gorgon Plate +3"
	SAY DESC "Hunting gorgons is a highly dangerous drow sport. Often, after a successful hunt, the blood of the gorgon is taken and used in the creation of a new suit of plate. This special type of drow plate is actually able to withstand the light of the surface world. 

STATISTICS:

Equipped abilities:
- Immunity to petrification
– Acid Resistance: +20%

Armor Class: 0 (-3 vs. slashing, -1 vs. piercing and missile)
Speed Factor: -3
Requires:
 13 Strength

Weight: 30
"





//FALLORAIN'S PLATE +4 - 14000mo//
COPY "rick_bigg_mod/items/PLAT17.itm" "override"
	SAY NAME1 "Plate Mail"
	SAY UNIDENTIFIED_DESC "FPlate mail is a combination of chain armor with metal plates covering the vital areas such as the chest, abdomen, and groin. Similar in construction to bronze plate mail, true plate mail comprises chain and leather.

STATISTICS:

Armor Class: 3 (0 vs. slashing, 2 vs. piercing and missile)
Speed Factor: -3
Requires:
 13 Strength

Weight: 50"

	SAY NAME2 "Fallorain's Plate +4"
	SAY DESC "Captain Fallorain, leader of Calimshan's 12th cavalry brigade, wore this enchanted armor for the last time during the Battle of the Spider Swamp. There he lost his life and army trying to rid an unrecorded evil from the area. 

STATISTICS:

Equipped abilities:
– Protection From Evil
– Immunity to poison and disease

Armor Class: -1 (-4 vs. slashing, -2 vs. piercing and missile)
Speed Factor: -3
Requires:
 13 Strength

Weight: 25
"





//MAGMA BULWARK +4 - 15000mo//
COPY "rick_bigg_mod/items/TB#PLAT1.itm" "override"
	SAY NAME1 "Full Plate Mail"
	SAY UNIDENTIFIED_DESC "Full plate armor is the best armor a warrior can buy, both in appearance and protection. The perfectly fitted, interlocking plates are specially angled to deflect arrows and blows, and the entire suit is carefully adorned with rich engraving and embossed detail.

STATISTICS:

Armor Class: 3 (0 vs. slashing, 2 vs. piercing and missile)
Speed Factor: -3
Requires:
 13 Strength

Weight: 50"

	SAY NAME2 "Magma Bulwark +4"
	SAY DESC "Forged by the fire giant Varboti as a gift for a Cormyrian general who made peace with his clan, this red-and-black armor lends its wearer a molten aspect while providing protection against all but the most powerful blows and fire damage. Due to its incredibly strong but thin material, it also weighs far less than ordinary plate mail.

STATISTICS:

Equipped Abilities:
- Fire damage resistance: +20%
- Crushing damage resistance: +10%

Armor Class: -1 (-4 vs. slashing, -2 vs. piercing and missile)
Speed Factor: -3
Requires:
 13 Strength

Weight: 35
"






//ENKIDU'S PLATE +5 - 17000mo//
COPY "rick_bigg_mod/items/PLAT21.itm" "override"
	SAY NAME1 "Plate Mail"
	SAY UNIDENTIFIED_DESC "Plate mail is a combination of chain armor with metal plates covering the vital areas such as the chest, abdomen, and groin. Similar in construction to bronze plate mail, true plate mail comprises chain and leather.

STATISTICS:

Armor Class: 3 (0 vs. slashing, 2 vs. piercing and missile)
Speed Factor: -3
Requires:
 13 Strength

Weight: 50"

	SAY NAME2 "Enkidu's Plate +5"
	SAY DESC "This armor was created for Enkidu, a famed warrior from Kara-Tur. While none dared challenge him in fair combat, Enkidu was often subject to cowardly sneak attacks from assassins, ninjas and Wu-Jen.

STATISTICS:

Equipped abilities:
– Piercing damage resistance: +10%
– Immunity to Backstab

Armor Class: -2 (-5 vs. slashing, -3 vs. piercing and missile)
Speed Factor: -3
Requires:
 13 Strength

Weight: 30
"