//THE PRACTICAL DEFENSE + 2 - 7500mo//
COPY "rick_bigg_mod/items/PLAT08.itm" "override"
	SAY NAME1 "Plate Mail"
	SAY UNIDENTIFIED_DESC "Plate mail is a combination of chain armor with metal plates covering the vital areas such as the chest, abdomen, and groin. Similar in construction to bronze plate mail, true plate mail comprises chain and leather.

STATISTICS:

Armor Class: 3 (0 vs. slashing, 1 vs. piercing and missile)
Speed Factor: -3

Requires:
 14 Strength

Weight: 50"

	SAY NAME2 "The Practical Defense +2"
	SAY DESC %
The traveling adventurer could ask for no better a suit of armor in all the land. Specially commissioned by Bolhur "Thunderaxe" at GREAT expense, this suit was his most prized, even if not his most ornate. Eminently practical, Bolhur demanded armor that would offer superior protection while hampering him in the least. By "hampering" he did not just mean in movement or weight, though this suit is just over one-third the weight of normal plate mail: His ideal suit should also be able to withstand the rigors of his wanderings with little maintenance. This is not to say that Bolhur "Thunderaxe" neglected his armors (to say as such would get your ears boxed) but the regime of spit and polish required for a "gentleman's" suit was beyond his caring. Save the tassels and gilding of full plate for kings and heads of state; a working dwarf cares more for utility than looks.

STATISTICS:

Equipped abilities:
- +1 Charisma

Armor Class: 1 (-2 vs. slashing, -1 vs. piercing and missile)
Speed Factor: -1

Requires:
 14 Strength

Weight: 18
%






//DOOMPLATE +3 - 8500mo//
COPY "rick_bigg_mod/items/PLAT12.itm" "override"
	SAY NAME1 "Plate Mail"
	SAY UNIDENTIFIED_DESC "Plate mail is a combination of chain armor with metal plates covering the vital areas such as the chest, abdomen, and groin. Similar in construction to bronze plate mail, true plate mail comprises chain and leather.

STATISTICS:

Armor Class: 3 (0 vs. slashing, 1 vs. piercing and missile)
Speed Factor: -3

Requires:
 14 Strength

Weight: 50"

	SAY NAME2 "Doomplate +3"
	SAY DESC "Named by Adarius Shin, the Doomplate is deserving of its foreboding title. He had hoped to strike fear in his enemies, but Adarius set a grim precedent when he mysteriously died soon after donning the suit, just as every adventurer who has worn it since has done. It might be said, however, that most adventurers die in their armor and are not known for their longevity.

STATISTICS:

Equipped abilities:
- +2 all Saving Throws
- -1 Luck
- 20% chance to cast Cloak of Fear when hit

Armor Class: 0 (-3 vs. slashing, -2 vs. piercing and missile)
Speed Factor: -3

Requires:
 14 Strength

Weight: 27
"