//POTION OF STRENGTH - valore 300mo//
COPY "rick_bigg_mod/items/POTN03.itm" "override"
	SAY NAME1 "Potion"
	SAY UNIDENTIFIED_DESC "Potions are typically found in ceramic, crystal, glass, or metal flasks or vials. Flasks or other containers generally contain enough fluid to provide one person with one complete dose to achieve the effects of the potion.

STATISTICS:

Weight: 1"


	SAY NAME2 "Potion of Strength"
	SAY DESC "This potion increases the strength of the user. When it is consumed, the individual gains great strength and bonuses to hit and damage while using any hand-held or thrown weapon. The effect lasts for 2 hours.

STATISTICS:

Strength: 18
Duration: 3 hours

Weight: 1" 





//POTION OF EXCEPTIONAL STRENGTH - valore 350mo//
COPY "rick_bigg_mod/items/POTN12.itm" "override"
	SAY NAME1 "Potion"
	SAY UNIDENTIFIED_DESC "Potions are typically found in ceramic, crystal, glass, or metal flasks or vials. Flasks or other containers generally contain enough fluid to provide one person with one complete dose to achieve the effects of the potion.

STATISTICS:

Weight: 1"


	SAY NAME2 "Potion of Exceptional Strength"
	SAY DESC "This potion increases the strength of the user. When it is consumed, the individual gains great strength and bonuses to hit and damage while using any hand-held or thrown weapon. The effect lasts for 2 hours.

STATISTICS:

Strength: 18/50
Duration: 3 hours

Weight: 1" 





//POTION OF EXTRAORDINARY STRENGTH - 400mo//
COPY "rick_bigg_mod/items/POTN04.itm" "override"
	SAY NAME1 "Potion"
	SAY UNIDENTIFIED_DESC "Potions are typically found in ceramic, crystal, glass, or metal flasks or vials. Flasks or other containers generally contain enough fluid to provide one person with one complete dose to achieve the effects of the potion.

STATISTICS:

Weight: 1"


	SAY NAME2 "Potion of Extraordinary Strength"
	SAY DESC "This potion increases the strength of the user. When it is consumed, the individual gains great strength and bonuses to hit and damage while using any hand-held or thrown weapon. The effect lasts for 2 hours.

STATISTICS:

Strength: 18/75
Duration: 3 hours

Weight: 1" 








//POTION OF SUPERIOR STRENGTH - valore 450mo//
COPY "rick_bigg_mod/items/POTN05.itm" "override"
	SAY NAME1 "Potion"
	SAY UNIDENTIFIED_DESC "Potions are typically found in ceramic, crystal, glass, or metal flasks or vials. Flasks or other containers generally contain enough fluid to provide one person with one complete dose to achieve the effects of the potion.

STATISTICS:

Weight: 1"


	SAY NAME2 "Potion of Superior Strength"
	SAY DESC "This potion increases the strength of the user. When it is consumed, the individual gains great strength and bonuses to hit and damage while using any hand-held or thrown weapon. The effect lasts for 2 hours.

STATISTICS:

Strength: 18/90
Duration: 3 hours

Weight: 1" 







//POTION OF PHENOMENAL STRENGTH - 500mo//
COPY "rick_bigg_mod/items/POTN06.itm" "override"
	SAY NAME1 "Potion"
	SAY UNIDENTIFIED_DESC "Potions are typically found in ceramic, crystal, glass, or metal flasks or vials. Flasks or other containers generally contain enough fluid to provide one person with one complete dose to achieve the effects of the potion.

STATISTICS:

Weight: 1"


	SAY NAME2 "Potion of Phenomenal Strength"
	SAY DESC "This potion increases the strength of the user. When it is consumed, the individual gains great strength and bonuses to hit and damage while using any hand-held or thrown weapon. The effect lasts for 2 hours.

STATISTICS:

Strength: 18/99
Duration: 3 hours

Weight: 1" 








//POTION OF OGRE STRENGTH - 600mo//
COPY "rick_bigg_mod/items/POTN07.itm" "override"
	SAY NAME1 "Potion"
	SAY UNIDENTIFIED_DESC "Potions are typically found in ceramic, crystal, glass, or metal flasks or vials. Flasks or other containers generally contain enough fluid to provide one person with one complete dose to achieve the effects of the potion.

STATISTICS:

Weight: 1"


	SAY NAME2 "Potion of Ogre Strength"
	SAY DESC "This potion increases the strength of the user. When it is consumed, the individual gains great strength and bonuses to hit and damage while using any hand-held or thrown weapon. The effect lasts for 2 hours.

STATISTICS:

Strength: 18/00
Duration: 3 hours

Weight: 1" 





//POTION OF GENIUS - valore 500mo//
COPY "rick_bigg_mod/items/POTN29.itm" "override"
	SAY NAME1 "Potion"
	SAY UNIDENTIFIED_DESC "Potions are typically found in ceramic, crystal, glass, or metal flasks or vials. Flasks or other containers generally contain enough fluid to provide one person with one complete dose to achieve the effects of the potion.

STATISTICS:

Weight: 1"


	SAY NAME2 "Potion of Genius"
	SAY DESC "Very much as the name implies, this potion will increase the Intelligence of the imbiber to 18. The effect will last the full duration, which is 3 hours, or until dispelled.

STATISTICS:

Intelligence: 18
Duration: 3 hours

Weight: 1" 








//POTION OF INSIGHT - 500mo//
COPY "rick_bigg_mod/items/POTN43.itm" "override"
	SAY NAME1 "Potion"
	SAY UNIDENTIFIED_DESC "Potions are typically found in ceramic, crystal, glass, or metal flasks or vials. Flasks or other containers generally contain enough fluid to provide one person with one complete dose to achieve the effects of the potion.

STATISTICS:

Weight: 1"


	SAY NAME2 "Potion of Insight"
	SAY DESC "It will be as if a higher being had stepped into the drinker's head, filling it with intuitive thoughts and amazing insights. The effect is to set the Wisdom of the person to 18 for approximately 3 hours or until dispelled.

STATISTICS:

Wisdom: 18
Duration: 3 hours

Weight: 1" 




//POTION OF AGILITY - 500mo//
COPY "rick_bigg_mod/items/POTN19.itm" "override"
	SAY NAME1 "Potion"
	SAY UNIDENTIFIED_DESC "Potions are typically found in ceramic, crystal, glass, or metal flasks or vials. Flasks or other containers generally contain enough fluid to provide one person with one complete dose to achieve the effects of the potion.

STATISTICS:

Weight: 1"


	SAY NAME2 "Potion of Agility"
	SAY DESC "This potion will set the Dexterity score of the imbiber to 18, affecting Armor Class and missile attack adjustment for the duration of the effect, in this case 3 hours.

STATISTICS:

Dexterity: 18
Duration: 3 hours

Weight: 1" 




//POTION OF FORTITUDE - 500mo//
COPY "rick_bigg_mod/items/POTN28.itm" "override"
	SAY NAME1 "Potion"
	SAY UNIDENTIFIED_DESC "Potions are typically found in ceramic, crystal, glass, or metal flasks or vials. Flasks or other containers generally contain enough fluid to provide one person with one complete dose to achieve the effects of the potion.

STATISTICS:

Weight: 1"


	SAY NAME2 "Potion of Fortitude"
	SAY DESC "Once consumed, this potion will cause a surge of energy to travel through the body, setting the drinker's Constitution to 18. This provides all the bonuses of having a high Constitution—such as Hit Points—for the duration of the effect, which is 3 hours.

STATISTICS:

Constitution: 18
Duration: 3 hours

Weight: 1" 





//POTION OF FREEDOM - 400mo//
COPY "rick_bigg_mod/items/POTN45.itm" "override"
	SAY NAME1 "Potion"
	SAY UNIDENTIFIED_DESC "Potions are typically found in ceramic, crystal, glass, or metal flasks or vials. Flasks or other containers generally contain enough fluid to provide one person with one complete dose to achieve the effects of the potion.

STATISTICS:

Weight: 1"


	SAY NAME2 "Potion of Freedom"
	SAY DESC "This potion acts like the spell Free Action when consumed. The drinker becomes completely immune to any effects that influence action or movement, whether it is magical in origin or not. The duration of the potion is 2 hours.

STATISTICS:

Special: Free Action
Duration: 2 hours

Weight: 1" 





//POTION OF MIND FOCUSING - 300mo//
COPY "rick_bigg_mod/items/POTN37.itm" "override"
	SAY NAME1 "Potion"
	SAY UNIDENTIFIED_DESC "Potions are typically found in ceramic, crystal, glass, or metal flasks or vials. Flasks or other containers generally contain enough fluid to provide one person with one complete dose to achieve the effects of the potion.

STATISTICS:

Weight: 1"


	SAY NAME2 "Potion of Mind Focusing"
	SAY DESC "This potion will grant whoever drinks it the ability to focus their mind unerringly and be quicker and more efficient in battle.

STATISTICS:

Speed Factor: +5
THAC0: +3

Duration: 10 turns

Weight: 1" 







//POTION OF ELEMENTAL ABSORPTION//
COPY "rick_bigg_mod/items/POTN18.itm" "override"
	SAY NAME1 "Potion"
	SAY UNIDENTIFIED_DESC "Potions are typically found in ceramic, crystal, glass, or metal flasks or vials. Flasks or other containers generally contain enough fluid to provide one person with one complete dose to achieve the effects of the potion.

STATISTICS:

Weight: 1"


	SAY NAME2 "Potion of Elemental Absorption"
	SAY DESC "This potion, as would be expected, will partially absorb all elemental damage. The effect will last 2 hours. 

STATISTICS:

Fire Resistance: +50%
Cold Resistance: +50%
Electrical Resistance: +50%
Acid Resistance: +50%
Poison Resistance: +50%

Duration: 10 turns

Weight: 1" 







//POTION OF HEROISM - 800mo - solo guerrieri//
COPY "rick_bigg_mod/items/POTN09.itm" "override"
	SAY NAME1 "Potion"
	SAY UNIDENTIFIED_DESC "Potions are typically found in ceramic, crystal, glass, or metal flasks or vials. Flasks or other containers generally contain enough fluid to provide one person with one complete dose to achieve the effects of the potion.

STATISTICS:

Weight: 1"


	SAY NAME2 "Potion of Heroism"
	SAY DESC "This potion is imbued with a powerful enchantment that will give a temporary increase of power. The effect lasts for 2 hours, which makes this potion a powerful ally in a melee combat. 

STATISTICS:

Hit Points: +15
THAC0: +2
Damage: +4

Duration: 5 turns

Weight: 1" 





//POTION OF INVULNERABILITY - 800mo//
COPY "rick_bigg_mod/items/POTN11.itm" "override"
	SAY NAME1 "Potion"
	SAY UNIDENTIFIED_DESC "Potions are typically found in ceramic, crystal, glass, or metal flasks or vials. Flasks or other containers generally contain enough fluid to provide one person with one complete dose to achieve the effects of the potion.

STATISTICS:

Weight: 1"


	SAY NAME2 "Potion of Invulnerability"
	SAY DESC "This potion confers very high resistance to all attacks while giving bonuses to all Saving Throws. The effects of the elixir last for 5 turns.

STATISTICS:

Armor Class: +3
Saving Throws: +3
Duration: 5 turns

Weight: 1" 




//POTION OF INFRAVISION - 100mo//
COPY "rick_bigg_mod/items/POTN30.itm" "override"
	SAY NAME1 "Potion"
	SAY UNIDENTIFIED_DESC "Potions are typically found in ceramic, crystal, glass, or metal flasks or vials. Flasks or other containers generally contain enough fluid to provide one person with one complete dose to achieve the effects of the potion.

STATISTICS:

Weight: 1"


	SAY NAME2 "Potion of Infravision"
	SAY DESC "This potion will grant the person drinking it the ability to see in the infrared spectrum up to 120 feet, namely infravision. It will also raise precision in battle. The effect will last for 4 hours or until dispelled. 

STATISTICS:

Special: Infravision
THAC0: +1
Duration: 4 hours

Weight: 1" 




//POTION OF MAGIC PROTECTION - 1000mo//
COPY "rick_bigg_mod/items/POTN34.itm" "override"
	SAY NAME1 "Potion"
	SAY UNIDENTIFIED_DESC "Potions are typically found in ceramic, crystal, glass, or metal flasks or vials. Flasks or other containers generally contain enough fluid to provide one person with one complete dose to achieve the effects of the potion.

STATISTICS:

Weight: 1"


	SAY NAME2 "Potion of Magic Protection"
	SAY DESC "This potion will raise drinker's magic resistance by 30%. The effect will last for 5 turns or until dispelled.

STATISTICS:

Magic Resistance: +30%
Duration: 5 turns

Weight: 1" 







//POTION OF MAGIC SHIELDING - 1000mo//
COPY "rick_bigg_mod/items/POTN35.itm" "override"
	SAY NAME1 "Potion"
	SAY UNIDENTIFIED_DESC "Potions are typically found in ceramic, crystal, glass, or metal flasks or vials. Flasks or other containers generally contain enough fluid to provide one person with one complete dose to achieve the effects of the potion.

STATISTICS:

Weight: 1"


	SAY NAME2 "Potion of Magic Shielding"
	SAY DESC "This powerful elixir imbues the drinker with 50% resistance to all forms of magical damage and raises saving throws. The effect lasts for 5 turns, making this potion slightly more battle specific.

STATISTICS:

Damage Resistance: +50% against all forms of magical damage
Saving Throws: +5
Duration: 5 turns

Weight: 1" 








//POTION OF PERSUASIVENESS - 500mo//
COPY "rick_bigg_mod/items/POTN60.itm" "override"
	SAY NAME1 "Potion"
	SAY UNIDENTIFIED_DESC "Potions are typically found in ceramic, crystal, glass, or metal flasks or vials. Flasks or other containers generally contain enough fluid to provide one person with one complete dose to achieve the effects of the potion.

STATISTICS:

Weight: 1"


	SAY NAME2 "Potion of Persuasiveness"
	SAY DESC "Very much as the name implies, this potion will increase the Charisma to 18. The effect will last the full duration, which is 3 hours, or until dispelled.

STATISTICS:

Charisma: 18
Duration: 3 hours

Weight: 1" 






//POTION OF REGENERATION - 500mo//
COPY "rick_bigg_mod/items/POTN42.itm" "override"
	SAY NAME1 "Potion"
	SAY UNIDENTIFIED_DESC "Potions are typically found in ceramic, crystal, glass, or metal flasks or vials. Flasks or other containers generally contain enough fluid to provide one person with one complete dose to achieve the effects of the potion.

STATISTICS:

Weight: 1"


	SAY NAME2 "Potion of Regeneration"
	SAY DESC "This is a powerful elixir that imbues the drinker with the regeneration ability similar to that of a troll, wounds literally closing over and healing as you watch. The effect, which lasts for 5 turns, is to regenerate 1 Hit Point every 3 seconds.

STATISTICS:

Special: Regenerate 1 Hit Points / 3 seconds
Duration: 5 turns

Weight: 1" 







//VITRIOL GRANADE - 500mo//
COPY "rick_bigg_mod/items/POTN26.itm" "override"
	SAY NAME1 "Potion"
	SAY UNIDENTIFIED_DESC "Potions are typically found in ceramic, crystal, glass, or metal flasks or vials. Flasks or other containers generally contain enough fluid to provide one person with one complete dose to achieve the effects of the potion.

STATISTICS:

Weight: 1"
	SAY NAME2 "Vitriol Granade"
	SAY DESC "Once throwed, a glowing orb of emerald acid explodes in a 15-foot radius. Each creature in the area takes 5d4 acid damage and 1d4 acid damage at the end of its next 2 rounds. There is no save.


STATISTICS:

Damage: 5d4 - 1d4 acid damage at the end of its next 2 rounds
Area of Effect: 15-ft. radius

Weight: 1" 




//POTION OF MURDER - 900mo - solo ladri e assassini//
COPY "rick_bigg_mod/items/POTN41.itm" "override"
	SAY NAME1 "Potion"
	SAY UNIDENTIFIED_DESC "Potions are typically found in ceramic, crystal, glass, or metal flasks or vials. Flasks or other containers generally contain enough fluid to provide one person with one complete dose to achieve the effects of the potion.

STATISTICS:

Weight: 1"


	SAY NAME2 "Potion of Murder"
	SAY DESC "This powerful elixir is one of the most deadly weapons for assassins. It first makes you invisible to your enemy, and then makes backstabbing even more deadly. The effect lasts for 10 turns.

STATISTICS:
THAC0: +2
Damage: +2
Backstab bonus: +1
Hide in shadows: +40%
Move silently: +40%
Duration: 10 turns

Weight: 1" 




//POTION OF MAGIC POWER - 1500mo - solo maghi e bardi//
COPY "rick_bigg_mod/items/POTN33.itm" "override"
	SAY NAME1 "Potion"
	SAY UNIDENTIFIED_DESC "Potions are typically found in ceramic, crystal, glass, or metal flasks or vials. Flasks or other containers generally contain enough fluid to provide one person with one complete dose to achieve the effects of the potion.

STATISTICS:

Weight: 1"


	SAY NAME2 "Potion of Magic Power"
	SAY DESC "This powerful elixir enhances the wizard's abilities: first it increases the casting level, the casting speed factor and then adds 25% damage to each magical attack performed. The effect lasts for 10 turns.

STATISTICS:
Caster level: +4
Casting speed factor: +4
Magic Damage: +25%
Duration: 10 turns

Weight: 1" 






//POTION OF MISSILE PROTECTION - 300mo//
COPY "rick_bigg_mod/items/POTN44.itm" "override"
	SAY NAME1 "Potion"
	SAY UNIDENTIFIED_DESC "Potions are typically found in ceramic, crystal, glass, or metal flasks or vials. Flasks or other containers generally contain enough fluid to provide one person with one complete dose to achieve the effects of the potion.

STATISTICS:

Weight: 1"


	SAY NAME2 "Potion of Missile Protection"
	SAY DESC "This elixir grants protection against all missile attacks. The effect lasts for 10 turns.

STATISTICS:
Armor Class vs Missile: +5
Missile Damage Resistance: +25%
Duration: 10 turns

Weight: 1" 




//POTION OF FIRE BREATH - 300mo//
COPY "rick_bigg_mod/items/POTN27.itm" "override"
	SAY NAME1 "Potion"
	SAY UNIDENTIFIED_DESC "Potions are typically found in ceramic, crystal, glass, or metal flasks or vials. Flasks or other containers generally contain enough fluid to provide one person with one complete dose to achieve the effects of the potion.

STATISTICS:

Weight: 1"


	SAY NAME2 "Potion of Fire Breath"
	SAY DESC "The potion of firebreath magically transforms the throat so that it is capable of a giant breath of fire spewing forth in an arc. The user does not drink this potion, but instead uses it on an enemy. The effect does 3d10 damage to the target.

STATISTICS:

Damage: 3d10 (fire)

Weight: 1" 





//OIL OF FIERY BURNING - 300mo//
COPY "rick_bigg_mod/items/POTN13.itm" "override"
	SAY NAME1 "Potion"
	SAY UNIDENTIFIED_DESC "Potions are typically found in ceramic, crystal, glass, or metal flasks or vials. Flasks or other containers generally contain enough fluid to provide one person with one complete dose to achieve the effects of the potion.

STATISTICS:

Weight: 1"


	SAY NAME2 "Potion of Fiery Burning"
	SAY DESC "Once exposed to air, this oil will immediately burst into flame, inflicting 3d6 points of damage to all within the immediate area around the potion. It can be hurled up to around 40 ft., at which point it hits the ground and immediately explodes into a ball of fire.

STATISTICS:

Damage: 3d6 (fire)

Weight: 1" 