//RING OF PROTECTION +1 - 2500mo//
COPY "rick_bigg_mod/items/RING06.itm" "override"
	SAY NAME1 "Ring"
	SAY DESC "A ring is a small band of precious metal that is used as jewelry. Some rare rings have had enchantments placed upon them that confer various magical abilities. These rings are highly sought after, especially by those of the adventuring profession.

STATISTICS:

Weight: 0"

	SAY NAME2 "Ring of Protection +1"
	SAY DESC "This magic ring improves the wearer's Armor Class and Saving Throws versus all forms of attack. The magical properties of the ring prevent it from being worn with other magical items of protection like amulets and cloaks.

STATISTICS:

Equipped abilities:
– Armor Class: +1
– Saving Throws: +1

Weight: 0"



//RING OF PROTECTION +2 - 6000mo//
COPY "rick_bigg_mod/items/RING07.itm" "override"
	SAY NAME1 "Ring"
	SAY DESC "A ring is a small band of precious metal that is used as jewelry. Some rare rings have had enchantments placed upon them that confer various magical abilities. These rings are highly sought after, especially by those of the adventuring profession.

STATISTICS:

Weight: 0"

	SAY NAME2 "Ring of Protection +2"
	SAY DESC "This powerful magic ring improves the wearer's Armor Class and Saving Throws versus all forms of attack. The magical properties of the ring prevent it from being worn with other magical items of protection like amulets and cloaks.

STATISTICS:

Equipped abilities:
– Armor Class: +2
– Saving Throws: +2

Weight: 0"




//RING OF PROTECTION +3 - 14000mo//
COPY "rick_bigg_mod/items/RING41.itm" "override"
	SAY NAME1 "Ring"
	SAY DESC "A ring is a small band of precious metal that is used as jewelry. Some rare rings have had enchantments placed upon them that confer various magical abilities. These rings are highly sought after, especially by those of the adventuring profession.

STATISTICS:

Weight: 0"

	SAY NAME2 "Ring of Protection +3"
	SAY DESC "This godly magic ring improves the wearer's Armor Class and Saving Throws versus all forms of attack. The magical properties of the ring prevent it from being worn with other magical items of protection like amulets and cloaks.

STATISTICS:

Equipped abilities:
– Armor Class: +3
– Saving Throws: +3

Weight: 0"







//RING OF INFRAVISION - 900mo//
COPY "rick_bigg_mod/items/RING21.itm" "override"
	SAY NAME1 "Ring"
	SAY DESC "A ring is a small band of precious metal that is used as jewelry. Some rare rings have had enchantments placed upon them that confer various magical abilities. These rings are highly sought after, especially by those of the adventuring profession.

STATISTICS:

Weight: 0"

	SAY NAME2 "Ring of Infravision"
	SAY DESC "Merchants that dare the risks of trading with the drow of the Great Rift are often given these items to aid in their movements underground. 

STATISTICS:

Equipped abilities:
– Infravision up to 120 ft.
- +1 THAC0

Weight: 0"





//RING OF FIRE RESISTANCE - 1500mo//
COPY "rick_bigg_mod/items/RING02.itm" "override"
	SAY NAME1 "Ring"
	SAY DESC "A ring is a small band of precious metal that is used as jewelry. Some rare rings have had enchantments placed upon them that confer various magical abilities. These rings are highly sought after, especially by those of the adventuring profession.

STATISTICS:

Weight: 0"

	SAY NAME2 "Ring of Fire Resistance"
	SAY DESC "The grand mage Batalista intended this item to aid in his travels in the Plane of Fire, and it is said he repeatedly summoned a salamander from that realm to aid in the construction. Salamanders not being known for their patience, it is likely he should not have pestered his "instructor" quite so much. The finger bearing the finished ring was indeed untouched by the inferno that claimed his tower. Had that finger still been attached, Batalista himself might have fared better.

STATISTICS:

Equipped abilities:
– Fire Resistance: +40%

Weight: 0"






//RING OF CLUMSINESS - 1500mo//
COPY "rick_bigg_mod/items/RING04.itm" "override"
	SAY NAME1 "Ring"
	SAY UNIDENTIFIED_DESC "A ring is a small band of precious metal that is used as jewelry. Some rare rings have had enchantments placed upon them that confer various magical abilities. These rings are highly sought after, especially by those of the adventuring profession.

STATISTICS:

Weight: 0"

	SAY NAME2 "Ring of Clumsiness"
	SAY DESC "The most notorious owner of this ring made a substantial living exploiting its cursed nature. Gregoria the Fool, a jester by trade, used his incomparable sleight of hand to switch this ring with one belonging to a patsy chosen from his audience. The rest of his performance involved mocking the newly clumsy individual, much to the delight of their comrades. The ring was removed (by a method known only to the wily jester) only after the stooge promised no reprisals for the treatment they had received, though Gregoria frequently still had to make a hasty retreat. What he didn't know was that the ring also held hidden abilities, which were revealed by an angry mage during his final performance at Zhentil Keep...


STATISTICS:

Equipped abilities:
– Dexterity: -50% penalty
– May only be removed with a Remove Curse spell

Charge abilities twice a day:
- Lighting Bolt (6d6 Electricity Damage, save vs. Wand for half) two times per day

Weight: 0"








//RING OF INVISIBILITY - 4500mo//
COPY "rick_bigg_mod/items/RING05.itm" "override"
	SAY NAME1 "Ring"
	SAY UNIDENTIFIED_DESC "A ring is a small band of precious metal that is used as jewelry. Some rare rings have had enchantments placed upon them that confer various magical abilities. These rings are highly sought after, especially by those of the adventuring profession.

STATISTICS:

Weight: 0"

	SAY NAME2 "Ring of Invisibility"
	SAY DESC "Held by a master Thief for the better part of a generation, this ring was put to bold use in the markets of Waterdeep. Working a crowd in broad daylight, the rogue would steal countless numbers of purses from nobles, replacing them with bags of sand so the theft would go unnoticed. His identity was never known, but the name "Sandthief" was cursed loudly in its stead. It is rumored he retired, and now lives among the nobles he used to rob.

STATISTICS:

Charge abilities:
– Invisibility three per day
  Duration: 12 hours
  Area of Effect: The wearer

Weight: 0"





//RING OF HOLYNESS - solo chierici - 3500mo//
COPY "rick_bigg_mod/items/RING22.itm" "override"
	SAY NAME1 "Ring"
	SAY DESC "A ring is a small band of precious metal that is used as jewelry. Some rare rings have had enchantments placed upon them that confer various magical abilities. These rings are highly sought after, especially by those of the adventuring profession.

STATISTICS:

Weight: 0"

	SAY NAME2 "Ring of Holyness"
	SAY DESC "Rings of this type were given to faithful priests who demonstrated actions of astounding integrity and kindness. They serve as a holy symbol of divine devotion, granted only to those whose spirits are truly pure.

STATISTICS:

Equipped abilities:
– Can memorize one extra divine spell of each level from 1st to 5th

Weight: 0"




//RING OF ANTI-VENOM - 2500mo//
COPY "rick_bigg_mod/items/RING46.itm" "override"
	SAY NAME1 "Ring"
	SAY DESC "A ring is a small band of precious metal that is used as jewelry. Some rare rings have had enchantments placed upon them that confer various magical abilities. These rings are highly sought after, especially by those of the adventuring profession.

STATISTICS:

Weight: 0"

	SAY NAME2 "Ring of Anti-Venom"
	SAY DESC "This ring is an unadorned silver band. However, its plain appearance belies the powerful magic within. A Ring of Anti-Venom is eagerly sought after by royalty, influential political figures, and other potential assassination targets. 

STATISTICS:

Equipped abilities:
– Immunity to poison

Weight: 0"




//RING OF FREE ACTION - 4500mo//
COPY "rick_bigg_mod/items/RING09.itm" "override"
	SAY NAME1 "Ring"
	SAY DESC "A ring is a small band of precious metal that is used as jewelry. Some rare rings have had enchantments placed upon them that confer various magical abilities. These rings are highly sought after, especially by those of the adventuring profession.

STATISTICS:

Weight: 0"

	SAY NAME2 "Ring of Free Action"
	SAY DESC "This ring was given to the reef scavenger and hunter known only as Edventar by a group of aquatic elves long his friends. His help in routing the "Pirate Queen" Yenandra of Dambrath was instrumental in their survival, though Yenandra continues to be feared anywhere the water meets land.

STATISTICS:

Equipped abilities:
– The wearer is immune to all magical and non-magical effects that adversely affect movement, such as web, entangle, slow, and paralysis. Beneficial movement effects, including Haste, are unaffected.

Weight: 0"







//RING OF ANIMAL FRIENDSHIP - solo druidi e ranger - 1800mo//
COPY "rick_bigg_mod/items/RING03.itm" "override"
	SAY NAME1 "Ring"
	SAY DESC "A ring is a small band of precious metal that is used as jewelry. Some rare rings have had enchantments placed upon them that confer various magical abilities. These rings are highly sought after, especially by those of the adventuring profession.

STATISTICS:

Weight: 0"

	SAY NAME2 "Ring of Animal Friendship"
	SAY DESC "A druid order in Cormanthor is said to cautiously guard the secret to the construction of these rings, which have never been seen in the possession of anyone outside their immediate membership.  How this particular ring escaped the protection of their forest is unknown, but there are rumors that an outcast could have brought it into exile with him.  

STATISTICS:

Charge abilities:
– Charm animal (Save vs. Wand negates)
  Range: 30 ft.
  Duration: 2 hours
  Area of Effect: 30 ft. radius

Weight: 0"






//RING OF HUMAN INFLUENCE - 5000mo//
COPY "rick_bigg_mod/items/RING30.itm" "override"
	SAY NAME1 "Ring"
	SAY DESC "A ring is a small band of precious metal that is used as jewelry. Some rare rings have had enchantments placed upon them that confer various magical abilities. These rings are highly sought after, especially by those of the adventuring profession.

STATISTICS:

Weight: 0"

	SAY NAME2 "Ring of Human Influence"
	SAY DESC "For seven years, Count Fisfnilt searched the realms for a suitable bride for his son Ewnin. Unfortunately, all the women that Fisfnilt found were not up to the standards set by Ewnin, an impossibly spoiled man. Desiring an heir and impatient with his son, the Count had the court mage fashion this ring. He gifted the ring to a woman of no small courtly influence and Ewnin was instantly smitten. They wed three weeks later.

STATISTICS:

Equipped abilities:
– Charisma +1

Charge abilities:
– Charm Person three times per day (Save vs. Wand negates)
  Range: 60 ft.
  Duration: 100 seconds
  Area of Effect: 1 creature

Weight: 0"





//RING OF FOLLY - solo maghi - 1500mo//
COPY "rick_bigg_mod/items/RING23.itm" "override"
	SAY NAME1 "Ring"
	SAY UNIDENTIFIED_DESC "A ring is a small band of precious metal that is used as jewelry. Some rare rings have had enchantments placed upon them that confer various magical abilities. These rings are highly sought after, especially by those of the adventuring profession.

STATISTICS:

Weight: 0"

SAY NAME2 "Ring of Folly"
	SAY DESC "Often the bane of careless mages, this ring was actually used to promote humility. Hergat Norin, a grand wizard of Narfell, would give this ring, also known as the Discipliner, to his most skilled yet laziest students. Drastically weakening their learning abilities, the ring required all their willpower to unleash its true potential.

STATISTICS:

Equipped abilities:
- Casting level: +4
- Casting speed: +2
– Intelligence: -50% penalty
- Wisdom: -50% penalty
- The wearer can memorize one fewer spell per level
– May only be removed with a Remove Curse spell

Weight: 0" 






//RING OF WIZARDRY - solo maghi - 7500mo//
COPY "rick_bigg_mod/items/RING40.itm" "override"
	SAY NAME1 "Ring"
	SAY DESC "A ring is a small band of precious metal that is used as jewelry. Some rare rings have had enchantments placed upon them that confer various magical abilities. These rings are highly sought after, especially by those of the adventuring profession.

STATISTICS:

Weight: 0"

	SAY NAME2 "Ring of Wizardry"
	SAY DESC "Long ago, a grand wizard from Amn was rumored to have defied Mystra's limitations on the magical arts. Legends spoke of this wizard being able to cast spells without the limitation of standard memorization. In the end, it was found that his powers stemmed from several magical rings that he had made for himself. His proclaimed "everlasting memory" was a hoax, though his rings continue to be some of the most sought-after items across the Realms. This masterpiece expands the wearer's mental capacity across a vast spectrum of arcane circles, granting unparalleled flexibility in battle.

STATISTICS:

Equipped abilities:
– The wearer can memorize 1 extra spell per level from 1st to 5th

Weight: 0"





//RING OF ENERGY - 5000mo//
COPY "rick_bigg_mod/items/RING20.itm" "override"
	SAY NAME1 "Ring"
	SAY DESC "A ring is a small band of precious metal that is used as jewelry. Some rare rings have had enchantments placed upon them that confer various magical abilities. These rings are highly sought after, especially by those of the adventuring profession.

STATISTICS:

Weight: 0"

	SAY NAME2 "Ring of Energy"
	SAY DESC "Crafted by drow mages of the Underdark, this weapon was used in an arranged battle between two rival houses. Each combatant was allowed to use a single magic item to aid his efforts. This ring was the weapon used by the victor of the contest, though he never laid hands on it. It was worn by his sibling and fired from the crowd, striking his opponent squarely in the back. Everyone witnessing agreed it was a brilliant interpretation of the rules.

STATISTICS:

Charge abilities:
– Ray of Energy three times per day
– Damage: 2d6
  Range: 100 ft.
  Area of Effect: 2-ft. by 100-ft. jet

Weight: 0"






//RING OF GAXX - solo maghi - solo malvagi - 18000mo//
COPY "rick_bigg_mod/items/RING39.itm" "override"
	SAY NAME1 "Ring"
	SAY DESC "A ring is a small band of precious metal that is used as jewelry. Some rare rings have had enchantments placed upon them that confer various magical abilities. These rings are highly sought after, especially by those of the adventuring profession.

STATISTICS:

Weight: 0"

	SAY NAME2 "Ring of Gaxx"
	SAY DESC "This ring is relatively unadorned, but the vile magic within radiates intense evil. Indeed, its creator, Kangaxx, was no less evil himself, even before millennia of undeath honed his power. It is said that a cadre of Netherese mages fought and imprisoned the demilich once, but being unable to truly destroy him, they became liches themselves to stand guard over his remains. The construction of the ring may have led to their enmity, as each of the gem's nine facets was supposedly empowered by sacrifice and death.

STATISTICS:

Equipped abilities:
– Armor Class: +2
– Saving Throws: +2
– Magic Resistance: +10%
– Immunity to disease and poison

Combat abilities:
- On kill restore one arcane spell of level 5 or lower

Weight: 0"







//RING OF THE RAM - 9500mo//
COPY "rick_bigg_mod/items/RING33.itm" "override"
	SAY NAME1 "Ring"
	SAY DESC "A ring is a small band of precious metal that is used as jewelry. Some rare rings have had enchantments placed upon them that confer various magical abilities. These rings are highly sought after, especially by those of the adventuring profession.

STATISTICS:

Weight: 0"

	SAY NAME2 "Ring of the Ram"
	SAY DESC "Also known as the Breaker of Castles, with one word, this ring can unleash fantastic and deadly powers. When it is triggered, a barely discernible, ram-like shape billows forth from the ring. This force can potentially knock opponents off of walls, destroy castle gates, or crush enemies, but it is damaging as well in its own right.

STATISTICS:

Charge abilities:
– Ram once per day
  Damage: 3d6 magic and 3d6 crushing
  Special: Pushes target away from user
  Range: 60 ft.
  Area of Effect: 1 creature

Weight: 0"





//RING OF TRAPMASTER - solo ladri generalist - 2500mo//
COPY "rick_bigg_mod/items/RING35.itm" "override"
	SAY NAME1 "Ring"
	SAY DESC "A ring is a small band of precious metal that is used as jewelry. Some rare rings have had enchantments placed upon them that confer various magical abilities. These rings are highly sought after, especially by those of the adventuring profession.

STATISTICS:

Weight: 0"

	SAY NAME2 "Ring of Trapmaster"
	SAY DESC "Derek Drak, one of the most deadly sappers in the Shadow Thieves' guild, wore this ring on many of his dangerous infiltrations. The ring enhanced Derek's uncanny ability to spot deadly mechanisms and turn them against his enemies. In the city of Athkatla, there wasn't a tripwire he couldn't see or a pressure plate he couldn't rig. To activate the ring, the proper command word must be known, at which point the garnet stone on the ring will polymorph into a liquid-like resin, flowing into a trap's gears to either jam them solid or perfectly prime its trigger.

STATISTICS:

Equipped abilities:
– Find Traps: +25%
– Set Traps: +25%

Weight: 0"





//RING OF DJINNI SUMMONING - 5000mo//
COPY "rick_bigg_mod/items/RING35.itm" "override"
	SAY NAME1 "Ring"
	SAY DESC "A ring is a small band of precious metal that is used as jewelry. Some rare rings have had enchantments placed upon them that confer various magical abilities. These rings are highly sought after, especially by those of the adventuring profession.

STATISTICS:

Weight: 0"

	SAY NAME2 "Ring of Djinni Summoning"
	SAY DESC "An item out of fables, the Ring of Djinni Summoning is highly sought after. Once a day, the wearer of this beautiful ring can summon a djinni who will do as the ring wearer commands. If the djinni should die while in the service of its master, the ring will be destroyed.

STATISTICS:

Charge abilities:
– Summon Djinni once per day
  Range: 20 ft.
  Duration: 1 turn

Weight: 0"





//RING OF REGENERATION - 4500mo//
COPY "rick_bigg_mod/items/RING31.itm" "override"
	SAY NAME1 "Ring"
	SAY DESC "A ring is a small band of precious metal that is used as jewelry. Some rare rings have had enchantments placed upon them that confer various magical abilities. These rings are highly sought after, especially by those of the adventuring profession.

STATISTICS:

Weight: 0"

	SAY NAME2 "Ring of Regeneration"
	SAY DESC "A lowly-ranked Red Wizard named Huhhus is said to have discovered the perfect way to distill troll flesh to make a potion that provided the same regenerative ability as that of the troll. Few were willing to drink the vile liquid, however, and decades later a student of Huhhus created this ring by building upon the foundations of knowledge laid by Huhhus. Within the hollow cavity of the jade ring floats the ichor and brains of a troll, providing a limited regenerative capability to the wearer.

STATISTICS:

Equipped abilities: 
– Regenerate 1 Hit Point per round

Weight: 0"






//RING OF REGENERATION - 3500mo//
COPY "rick_bigg_mod/items/RING34.itm" "override"
	SAY NAME1 "Ring"
	SAY DESC "A ring is a small band of precious metal that is used as jewelry. Some rare rings have had enchantments placed upon them that confer various magical abilities. These rings are highly sought after, especially by those of the adventuring profession.

STATISTICS:

Weight: 0"

	SAY NAME2 "Ring of Regeneration"
	SAY DESC "A lowly-ranked Red Wizard named Huhhus is said to have discovered the perfect way to distill troll flesh to make a potion that provided the same regenerative ability as that of the troll. Few were willing to drink the vile liquid, however, and decades later a student of Huhhus created this ring by building upon the foundations of knowledge laid by Huhhus. Within the hollow cavity of the jade ring floats the ichor and brains of a troll, providing a limited regenerative capability to the wearer.

STATISTICS:

Equipped abilities: 
– Regenerate 1 Hit Point per round

Weight: 0"





//RING OF AIR CONTROL - solo maghi, bardi e druidi - 6000mo//
COPY "rick_bigg_mod/items/RING28.itm" "override"
	SAY NAME1 "Ring"
	SAY DESC "A ring is a small band of precious metal that is used as jewelry. Some rare rings have had enchantments placed upon them that confer various magical abilities. These rings are highly sought after, especially by those of the adventuring profession.

STATISTICS:

Weight: 0"

	SAY NAME2 "Ring of Air Control"
	SAY DESC "Air elementals make for powerful foes, but with this ring, they can become valuable allies. Dark tales tell of groups of Red Wizards, all with rings of elemental command, descending upon small villages with no warning and destroying every living thing in sight. Although the truth of these rumors is questionable, the fact remains that a ring of this power in the wrong hands is dangerous.

STATISTICS:

Equipped abilities:
- Electricity resistance: +30%

Charge abilities:
– Charm Air Elemental once per day (Save vs. Wand at -4 negates)
  Range: Touch
  Duration: 45 seconds
  Area of Effect: 1 air elemental

– Improved Invisibility once per day
  Range: Touch
  Duration: 1 turn
  Area of Effect: 1 creature

Weight: 0"



//RING OF FIRE CONTROL - solo maghi, bardi e druidi - 6000mo//
COPY "rick_bigg_mod/items/RING27.itm" "override"
	SAY NAME1 "Ring"
	SAY DESC "A ring is a small band of precious metal that is used as jewelry. Some rare rings have had enchantments placed upon them that confer various magical abilities. These rings are highly sought after, especially by those of the adventuring profession.

STATISTICS:

Weight: 0"

	SAY NAME2 "Ring of Fire Control"
	SAY DESC "This burnished, red ring is engraved with depictions of flames and lava coils. Mages and other planar travelers use these rings to protect themselves while visiting the Elemental Plane of Fire and to command fire elementals to do their bidding.

STATISTICS:

Equipped abilities:
– Fire Resistance: +30%

Charge abilities:
– Charm Fire Elemental once per day (Save vs. Wand at -4 negates)
  Range: Touch
  Duration: 45 seconds
  Area of Effect: 1 fire elemental

– Flamestrike once per day
  Damage: 10d6 fire (Save vs. Wand at -4 for half)
  Range: visual range of the user
  Area of Effect: 1 creature

Weight: 0"





//RING OF EARTH CONTROL - solo maghi, bardi e druidi - 6000mo//
COPY "rick_bigg_mod/items/RING29.itm" "override"
	SAY NAME1 "Ring"
	SAY DESC "A ring is a small band of precious metal that is used as jewelry. Some rare rings have had enchantments placed upon them that confer various magical abilities. These rings are highly sought after, especially by those of the adventuring profession.

STATISTICS:

Weight: 0"

	SAY NAME2 "Ring of Earth Control"
	SAY DESC "If the songs of bards are correct, all one must do is wear this ring and they will gain the ability to control earth elementals at will. Of course, earth elementals are not easily controlled and care must be taken when commanding one. An angry earth elemental can make short work of an inept adventurer.
 
STATISTICS:

Equipped abilities:
– Armor Class: +1

Charge abilities:
– Charm Earth Elemental once per day (Save vs. Wand at -4 negates)
  Range: Touch
  Duration: 45 seconds
  Area of Effect: 1 earth elemental

– Stoneskin once per day 
  Number of skins: 5
  Duration: 8 hours
  Area of Effect: self

Weight: 0"





//RING OF WATER CONTROL - solo maghi, bardi e druidi - 6000mo//
COPY "rick_bigg_mod/items/TB#RIWAT.itm" "override"
	SAY NAME1 "Ring"
	SAY DESC "A ring is a small band of precious metal that is used as jewelry. Some rare rings have had enchantments placed upon them that confer various magical abilities. These rings are highly sought after, especially by those of the adventuring profession.

STATISTICS:

Weight: 0"

	SAY NAME2 "Ring of Water Control"
	SAY DESC "Forged in the crushing depths of the Sea of Fallen Stars, this sapphire ring allows its wearer to command the fickle spirits of the deep. Yet, freezing currents and crushing waves are notoriously difficult to bind to a mortal's will. A single slip of concentration can drown an arrogant mage in seconds.
 
STATISTICS:

Equipped abilities:
– Magic Resistance: +10%

Charge abilities:
– Charm Earth Water Elemental once per day (Save vs. Wand at -4 negates)
  Range: Touch
  Duration: 45 seconds
  Area of Effect: 1 water elemental

– Lower Resistance once per day 
  Magic Resistance: -20%
  Range: visual range of the user
  Duration: 10 rounds
  Area of Effect: 1 creature

Weight: 0"












































