//MAGE ROBE OF COLD RESISTANCE - valore 800mo//
COPY "rick_bigg_mod/items/CLCK09.itm" "override"
	SAY NAME1 "Mage Robe"
	SAY UNIDENTIFIED_DESC "Since the age of Netheril, mages have learned to bestow a wide variety of magical properties upon the everyday objects that surround them. A favorite item of such enchantment is the common robe. It is lightweight, affordable, and holds its enchantment well, thereby making it ideal equipment for a mage. Due to their magical heritage, however, only single-, dual-, and multi-class mages may wear these enchanted robes.

STATISTICS:

Weight: 3"

	SAY NAME2 "Mage Robe of Cold Resistance"
	SAY DESC "These are a common sight in the Sword Coast region, especially as one travels north toward Neverwinter and the Icewind Dales. Many young mages receive it as a gift from their instructors upon successfully completing their first five years of study. As with other such robes, they can only be worn by those of the wizardly profession.

STATISTICS:

Equipped abilities:
- Armor Class: 9
– Cold Resistance: +25%

Weight: 3"




//MAGE ROBE OF FIRE RESISTANCE - valore 800mo//
COPY "rick_bigg_mod/items/CLCK10.itm" "override"
	SAY NAME1 "Mage Robe"
	SAY UNIDENTIFIED_DESC "Since the age of Netheril, mages have learned to bestow a wide variety of magical properties upon the everyday objects that surround them. A favorite item of such enchantment is the common robe. It is lightweight, affordable, and holds its enchantment well, thereby making it ideal equipment for a mage. Due to their magical heritage, however, only single-, dual-, and multi-class mages may wear these enchanted robes.

STATISTICS:

Weight: 3"

	SAY NAME2 "Mage Robe of Fire Resistance"
	SAY DESC "Due to the extremely volatile nature of most magics, Mage Robes of Fire Resistance are not uncommon among young acolytes and their wizardly tutors. As with other such robes, they cannot be worn except by wizards.

STATISTICS:

Equipped abilities:
- Armor Class: 9
– Fire Resistance: +25%

Weight: 3"





//MAGE ROBE OF ELECTRIC RESISTANCE - valore 800mo//
COPY "rick_bigg_mod/items/CLCK11.itm" "override"
	SAY NAME1 "Mage Robe"
	SAY UNIDENTIFIED_DESC "Since the age of Netheril, mages have learned to bestow a wide variety of magical properties upon the everyday objects that surround them. A favorite item of such enchantment is the common robe. It is lightweight, affordable, and holds its enchantment well, thereby making it ideal equipment for a mage. Due to their magical heritage, however, only single-, dual-, and multi-class mages may wear these enchanted robes.

STATISTICS:

Weight: 3"

	SAY NAME2 "Mage Robe of Electric Resistance"
	SAY DESC "While seen with less frequency than some other mage robes, those of Electrical Resistance can hardly be considered a rarity. Some are worn by paranoiacs seeking protection from a ragged mountain storm, but many more are worn by mages seeking to protect themselves from the intrigues of others of their kind. As with all such robes, a Mage Robe of Electrical Resistance can only be worn by those of the wizardly profession.

STATISTICS:

Equipped abilities:
- Armor Class: 9
– Electricity Resistance: +25%

Weight: 3"




//KNAVE'S ROBE - valore 1200mo//
COPY "rick_bigg_mod/items/CLCK12.itm" "override"
	SAY NAME1 "Mage Robe"
	SAY UNIDENTIFIED_DESC "Since the age of Netheril, mages have learned to bestow a wide variety of magical properties upon the everyday objects that surround them. A favorite item of such enchantment is the common robe. It is lightweight, affordable, and holds its enchantment well, thereby making it ideal equipment for a mage. Due to their magical heritage, however, only single-, dual-, and multi-class mages may wear these enchanted robes.

STATISTICS:

Weight: 3"

	SAY NAME2 "Knave's Robe"
	SAY DESC "A favorite among Mage/Thieves, the Knave's Robe has been enchanted to shield its wearer from the knifes and poisons of any darkened alley. As with others of its type, however, its use is restricted to students of the arcane.

STATISTICS:

Equipped abilities:
- Armor Class: +1 vs. piercing and missile attacks
– Save vs. Death: +2

Weight: 4"




//TRAVELER'S ROBE - valore 1200mo//
COPY "rick_bigg_mod/items/CLCK13.itm" "override"
	SAY NAME1 "Mage Robe"
	SAY UNIDENTIFIED_DESC "Since the age of Netheril, mages have learned to bestow a wide variety of magical properties upon the everyday objects that surround them. A favorite item of such enchantment is the common robe. It is lightweight, affordable, and holds its enchantment well, thereby making it ideal equipment for a mage. Due to their magical heritage, however, only single-, dual-, and multi-class mages may wear these enchanted robes.

STATISTICS:

Weight: 3"

	SAY NAME2 "Traveler's Robe"
	SAY DESC "This mage robe has been perfected for use by any rambling, itinerant mage that travels from town to town. Its enchantments provide protection from the bandit's blades and from the jealous mage that lies in ambush with his Stinking Cloud. As with other robes of its kind, the Traveler's Robe can only be worn by wizards. 

STATISTICS:

Equipped abilities:
- Armor Class: 8
– Armor Class: +1 vs. slashing and missile attacks
– Save vs. Breath: +2

Weight: 4"




//ADVENTURER'S ROBE - valore 1200mo//
COPY "rick_bigg_mod/items/CLCK14.itm" "override"
	SAY NAME1 "Mage Robe"
	SAY UNIDENTIFIED_DESC "Since the age of Netheril, mages have learned to bestow a wide variety of magical properties upon the everyday objects that surround them. A favorite item of such enchantment is the common robe. It is lightweight, affordable, and holds its enchantment well, thereby making it ideal equipment for a mage. Due to their magical heritage, however, only single-, dual-, and multi-class mages may wear these enchanted robes.

STATISTICS:

Weight: 3"

	SAY NAME2 "Adventurer's Robe"
	SAY DESC "This robe has been specially enchanted to meet the eclectic needs of the adventuring mage. Aside from shielding the wearer from various forms of crushing damage, it also provides protection from the basilisk's petrifying gaze and polymorphing powers of rival mages. As with other such robes, the Adventurer's Robe can only be worn by those engaged in the wizardly profession.

STATISTICS:

Equipped abilities:
- Armor Class: 8
– Armor Class: +1 vs. crushing and missile attacks
– Save vs. Petrification/Polymorph: +2

Weight: 4"




//ROBE OF THE GOOD ARCHMAGI - solo maghi puri - valore 10000mo//
COPY "rick_bigg_mod/items/CLCK15.itm" "override"
	SAY NAME1 "Mage Robe"
	SAY UNIDENTIFIED_DESC "Since the age of Netheril, mages have learned to bestow a wide variety of magical properties upon the everyday objects that surround them. A favorite item of such enchantment is the common robe. It is lightweight, affordable, and holds its enchantment well, thereby making it ideal equipment for a mage. Due to their magical heritage, however, only single-, dual-, and multi-class mages may wear these enchanted robes.

STATISTICS:

Weight: 3"

	SAY NAME2 "Robe of the Good Archmagi"
	SAY DESC "This powerful mage robe offers protection from all forms of physical attack while at the same time increasing one's Magic Resistance and Saving Throws. Due to the nature of its enchantment, it can only be worn by wizards of good alignment.

STATISTICS:

Equipped abilities:
– Armor Class: 6
– Saving Throws: +1
– Magic Resistance: +10%
- Casting Level: +2

Weight: 6"






//ROBE OF THE NEUTRAL ARCHMAGI - solo maghi puri - valore 10000mo//
COPY "rick_bigg_mod/items/CLCK16.itm" "override"
	SAY NAME1 "Mage Robe"
	SAY UNIDENTIFIED_DESC "Since the age of Netheril, mages have learned to bestow a wide variety of magical properties upon the everyday objects that surround them. A favorite item of such enchantment is the common robe. It is lightweight, affordable, and holds its enchantment well, thereby making it ideal equipment for a mage. Due to their magical heritage, however, only single-, dual-, and multi-class mages may wear these enchanted robes.

STATISTICS:

Weight: 3"

	SAY NAME2 "Robe of the Neutral Archmagi"
	SAY DESC "This powerful mage robe offers protection from all forms of physical attack while at the same time increasing one's Magic Resistance and Saving Throws. Due to the nature of its enchantment, it can only be worn by wizards of neutral alignment.

STATISTICS:

Equipped abilities:
– Armor Class: 6
– Saving Throws: +1
– Magic Resistance: +10%
- Casting Level: +2

Weight: 6"





//ROBE OF THE EVIL ARCHMAGI - solo maghi puri - valore 10000mo//
COPY "rick_bigg_mod/items/CLCK17.itm" "override"
	SAY NAME1 "Mage Robe"
	SAY UNIDENTIFIED_DESC "Since the age of Netheril, mages have learned to bestow a wide variety of magical properties upon the everyday objects that surround them. A favorite item of such enchantment is the common robe. It is lightweight, affordable, and holds its enchantment well, thereby making it ideal equipment for a mage. Due to their magical heritage, however, only single-, dual-, and multi-class mages may wear these enchanted robes.

STATISTICS:

Weight: 3"

	SAY NAME2 "Robe of the Evil Archmagi"
	SAY DESC "This powerful mage robe offers protection from all forms of physical attack while at the same time increasing one's Magic Resistance and Saving Throws. Due to the nature of its enchantment, it can only be worn by wizards of evil alignment.

STATISTICS:

Equipped abilities:
– Armor Class: 6
– Saving Throws: +1
– Magic Resistance: +10%
- Casting Level: +2

Weight: 6"





//ROBE OF THE RED FLAMES - solo maghi - valore 5500mo//
COPY "rick_bigg_mod/items/BDROBE05.itm" "override"
	SAY NAME1 "Mage Robe"
	SAY UNIDENTIFIED_DESC "Since the age of Netheril, mages have learned to bestow a wide variety of magical properties upon the everyday objects that surround them. A favorite item of such enchantment is the common robe. It is lightweight, affordable, and holds its enchantment well, thereby making it ideal equipment for a mage. Due to their magical heritage, however, only single-, dual-, and multi-class mages may wear these enchanted robes.

STATISTICS:

Weight: 3"

	SAY NAME2 "Robe of the Red Flames"
	SAY DESC "This heavy crimson robe trimmed in gold signifies the importance of the wearer. Once the property of Edwin Odesseiron, Red Wizard of Thay, the robe was designed to further enhance his already significant magical prowess. Anyone who dons the Robe of Red Flames will deal additional damage whenever they use fire-based magic and will be less likely hurt by it.

STATISTICS:

Equipped abilities:
- Armor Class: 7
– Fire Resistance: +40%
– All fire damage inflicted by the wearer is increased by 20%

Weight: 4"



//ROBE OF ELEMENTAL ABSORPTION - solo maghi - valore 2500mo//
COPY "rick_bigg_mod/items/ohnrobe2.itm" "override"
	SAY NAME1 "Mage Robe"
	SAY UNIDENTIFIED_DESC "Since the age of Netheril, mages have learned to bestow a wide variety of magical properties upon the everyday objects that surround them. A favorite item of such enchantment is the common robe. It is lightweight, affordable, and holds its enchantment well, thereby making it ideal equipment for a mage. Due to their magical heritage, however, only single-, dual-, and multi-class mages may wear these enchanted robes.

STATISTICS:

Weight: 3"

	SAY NAME2 "Robe of Elemental Absorption"
	SAY DESC "Crafted by the eccentric Dragon Coast mage, Evard of Westgate, this silken vestment was designed to endure the chaotic elemental clashes of local spell-duels. Infused with crushed residue of minor mephit hearts, the cloth acts as a grounding sponge for raw natural energies, dulling the bite of sudden sparks, freezing gales, and searing flames alike. While it lacks the reality-bending power of archmage regalia, it provides a reliable, steady ward for any traveling scholar navigating the hazardous roads of the Heartlands.

STATISTICS:

Equipped abilities:
- Armor Class: 8
– Fire Resistance: +25%
– Cold Resistance: +25%
– Electrical Resistance: +25%
- Saving Throws: +1

Weight: 4"







//DIVINER'S VEST - solo maghi - valore 6000mo//
COPY "rick_bigg_mod/items/BDROBE04.itm" "override"
	SAY NAME1 "Mage Robe"
	SAY UNIDENTIFIED_DESC "Since the age of Netheril, mages have learned to bestow a wide variety of magical properties upon the everyday objects that surround them. A favorite item of such enchantment is the common robe. It is lightweight, affordable, and holds its enchantment well, thereby making it ideal equipment for a mage. Due to their magical heritage, however, only single-, dual-, and multi-class mages may wear these enchanted robes.

STATISTICS:

Weight: 3"

	SAY NAME2 "Diviner's Vest"
	SAY DESC "Created by Vaelen, a paranoid master seer from Luskan, this enchanted silk garment infuses the wearer's mind with cosmic awareness. By granting a constant state of Clairvoyance, it instantly reveals the layout of unknown regions. This supernatural foresight allows the wearer to anticipate danger before it strikes—granting uncanny luck against deadly hazards and completely eliminating the threat of unseen backstabs.

STATISTICS:

Equipped abilities:
– Armor Class: 7
- Save vs. Breath: +2
- Luck: +1
– Immunity to Backstab

Weight: 4"








//ROBE OF THE SHATTERED ONE - solo maghi puri - valore 18000mo//
COPY "rick_bigg_mod/items/BDROBE01.itm" "override"
	SAY NAME1 "Mage Robe"
	SAY UNIDENTIFIED_DESC "Since the age of Netheril, mages have learned to bestow a wide variety of magical properties upon the everyday objects that surround them. A favorite item of such enchantment is the common robe. It is lightweight, affordable, and holds its enchantment well, thereby making it ideal equipment for a mage. Due to their magical heritage, however, only single-, dual-, and multi-class mages may wear these enchanted robes.

STATISTICS:

Weight: 3"

	SAY NAME2 "Robe of the Shattered One"
	SAY DESC "This flowing vestment once belonged to Jon Irenicus. Embroidered across the chest is a broken circle in faded elven gold runes, symbolizing his exile from Suldanessellar and his severed connection to the Tree of Life. The robe emanates an aura of cold arrogance and immense power, visibly distorting reality around the wearer. The corrupted essence imprinted within the fabric protects the user from any form of spiritual manipulation and spatial banishment, leaving the wearer's magic untethered and amplified.

STATISTICS:

Equipped abilities:
– Armor Class: 6
– Saving Throws: +1
– Magic Resistance: +10%
- Casting Level: +2
- Immunity to Imprisonment and Maze
- Immunity to Level Drain

Weight: 6"





//ROBE OF VECNA - solo maghi puri - valore 25000mo//
COPY "rick_bigg_mod/items/WA2ROBE.itm" "override"
	SAY NAME1 "Mage Robe"
	SAY UNIDENTIFIED_DESC "Since the age of Netheril, mages have learned to bestow a wide variety of magical properties upon the everyday objects that surround them. A favorite item of such enchantment is the common robe. It is lightweight, affordable, and holds its enchantment well, thereby making it ideal equipment for a mage. Due to their magical heritage, however, only single-, dual-, and multi-class mages may wear these enchanted robes.

STATISTICS:

Weight: 3"

	SAY NAME2 "Robe of Vecna"
	SAY DESC "Born as a simple garment worn by the powerful lich, this robe absorbed centuries of leaking arcane radiation during the Whispered One's darkest rituals. The fabric now hums with a terrifying, absolute authority, serving as a direct conduit to Vecna's godlike genius and boundless intellect. It wraps the wearer in an impenetrable shield against hostile sorcery, completely isolating them from deathly energies. Yet, such supreme mental clarity demands a heavy toll, as the artifact slowly drains the physical vitality of any mortal ambitious enough to claim its power.

STATISTICS:

Equipped abilities:
– Armor Class: 6
- Saving Throws: +1
– Magic Resistance: +20%
– Casting Speed: +2
- Casting Level: +4
- Intelligence: 25
- Immunity to Level Drain
- Strength, Dexterity and Constitution: -1

Weight: 3"



