//SCIMITAR +1 - 1500mo//
COPY "rick_bigg_mod/items/SW1H22.itm" "override"
	SAY NAME1 "Scimitar"
	SAY UNIDENTIFIED_DESC "The long, curved, single-edged blade is characteristic of both the saber and the scimitar, even though their origins lie in different parts of Faerûn. Whereas the saber was intended chiefly for horsemen, mainly due to its versatility, the scimitar has a heavier oriental influence. The 'shamshir', as it was originally called, is larger, more highly curved, and tapered to an elongated, sharp point. This makes the weapon slightly slower but more effective and deadly in combat.

STATISTICS:

Damage: 2d4 (slashing)
Speed Factor: 6
Proficiency Type: Scimitar/Wakizashi/Ninjatō
Type: One-handed
Requires:
 11 Strength

Weight: 4"

	SAY NAME2 "Scimitar +1"
	SAY DESC "The scimitar, or 'shamshir' as it was originally called, has a single-edged blade with a significant curve and is tapered to an elongated, sharp point. It is perhaps slower than other weapons of the same type, though it compensates by the amount of damage it is capable of. 
	This particular weapon has been enhanced magically to complement the skill of the wielder.

STATISTICS:

THAC0: +1
Damage: 2d4+1 (slashing)
Speed Factor: 5
Proficiency Type: Scimitar/Wakizashi/Ninjatō
Type: One-handed
Requires:
 11 Strength

Weight: 3"





//SCIMITAR +2 - 2500mo//
COPY "rick_bigg_mod/items/BDSW1H23.itm" "override"
	SAY NAME1 "Scimitar"
	SAY UNIDENTIFIED_DESC "The long, curved, single-edged blade is characteristic of both the saber and the scimitar, even though their origins lie in different parts of Faerûn. Whereas the saber was intended chiefly for horsemen, mainly due to its versatility, the scimitar has a heavier oriental influence. The 'shamshir', as it was originally called, is larger, more highly curved, and tapered to an elongated, sharp point. This makes the weapon slightly slower but more effective and deadly in combat.

STATISTICS:

Damage: 2d4 (slashing)
Speed Factor: 6
Proficiency Type: Scimitar/Wakizashi/Ninjatō
Type: One-handed
Requires:
 11 Strength

Weight: 4"

	SAY NAME2 "Scimitar +2"
	SAY DESC "The scimitar, or 'shamshir' as it was originally called, has a single-edged blade with a significant curve and is tapered to an elongated, sharp point. It is perhaps slower than other weapons of the same type, though it compensates by the amount of damage it is capable of. 
	This particular weapon has been enhanced magically to complement the skill of the wielder.

STATISTICS:

THAC0: +2
Damage: 2d4+2 (slashing)
Speed Factor: 4
Proficiency Type: Scimitar/Wakizashi/Ninjatō
Type: One-handed
Requires:
 11 Strength

Weight: 3"






//HAWKSIGHT +2 - 5000mo//
COPY "rick_bigg_mod/items/OHRSW1H1.itm" "override"
	SAY NAME1 "Scimitar"
	SAY UNIDENTIFIED_DESC "The long, curved, single-edged blade is characteristic of both the saber and the scimitar, even though their origins lie in different parts of Faerûn. Whereas the saber was intended chiefly for horsemen, mainly due to its versatility, the scimitar has a heavier oriental influence. The 'shamshir', as it was originally called, is larger, more highly curved, and tapered to an elongated, sharp point. This makes the weapon slightly slower but more effective and deadly in combat.

STATISTICS:

Damage: 2d4 (slashing)
Speed Factor: 6
Proficiency Type: Scimitar/Wakizashi/Ninjatō
Type: One-handed
Requires:
 11 Strength

Weight: 4"

	SAY NAME2 "Hawksight +2"
	SAY DESC "This scimitar has been magically enhanced to give it greater accuracy in combat. Any wielder who picks up the sword immediately feels their senses becoming keener, their reflexes sharper.

STATISTICS:

Equipped abilities:
- THAC0: +2

THAC0: +2
Damage: 2d4+2 (slashing)
Speed Factor: 4
Proficiency Type: Scimitar/Wakizashi/Ninjatō
Type: One-handed
Requires:
 11 Strength

Weight: 3"






//TWINKLE +3 - 9000mo//
COPY "rick_bigg_mod/items/SW1H16.itm" "override"
	SAY NAME1 "Scimitar"
	SAY UNIDENTIFIED_DESC "The long, curved, single-edged blade is characteristic of both the saber and the scimitar, even though their origins lie in different parts of Faerûn. Whereas the saber was intended chiefly for horsemen, mainly due to its versatility, the scimitar has a heavier oriental influence. The 'shamshir', as it was originally called, is larger, more highly curved, and tapered to an elongated, sharp point. This makes the weapon slightly slower but more effective and deadly in combat.

STATISTICS:

Damage: 2d4 (slashing)
Speed Factor: 6
Proficiency Type: Scimitar/Wakizashi/Ninjatō
Type: One-handed
Requires:
 11 Strength

Weight: 4"

	SAY NAME2 "Twinkle +3"
	SAY DESC "This is the magical scimitar +3 that bears the name Twinkle. It is one of the personal weapons of Drizzt. Due to its magical nature, only those pure of heart can use it.

STATISTICS:

Equipped abilities:
– Armor Class: +2

THAC0: +3
Damage: 2d4+3 (slashing)
Speed Factor: 3
Proficiency type: Scimitar/Wakizashi/Ninjatō
Type: One-handed
Requires:
 11 Strength

Weight: 4"




//ICINGDEATH +3 - 8500mo//
COPY "rick_bigg_mod/items/SW1H15.itm" "override"
	SAY NAME1 "Scimitar"
	SAY UNIDENTIFIED_DESC "The long, curved, single-edged blade is characteristic of both the saber and the scimitar, even though their origins lie in different parts of Faerûn. Whereas the saber was intended chiefly for horsemen, mainly due to its versatility, the scimitar has a heavier oriental influence. The 'shamshir', as it was originally called, is larger, more highly curved, and tapered to an elongated, sharp point. This makes the weapon slightly slower but more effective and deadly in combat.

STATISTICS:

Damage: 2d4 (slashing)
Speed Factor: 6
Proficiency Type: Scimitar/Wakizashi/Ninjatō
Type: One-handed
Requires:
 11 Strength

Weight: 4"

	SAY NAME2 "Icingdeath +3"
	SAY DESC "This is the Frostbrand scimitar Icingdeath. It is one of Drizzt's personal weapons.

STATISTICS:

Equipped abilities:
– Fire Resistance: +50%

THAC0: +3
Damage: 2d4+3, +2d10 against cold damage against fire creatures
Damage Type: slashing
Speed Factor: 3
Proficiency Type: Scimitar/Wakizashi/Ninjatō
Type: One-handed
Requires:
 11 Strength

Weight: 4"





//BELM +3 - 8000mo//
COPY "rick_bigg_mod/items/SW1H30.itm" "override"
	SAY NAME1 "Scimitar"
	SAY UNIDENTIFIED_DESC "The long, curved, single-edged blade is characteristic of both the saber and the scimitar, even though their origins lie in different parts of Faerûn. Whereas the saber was intended chiefly for horsemen, mainly due to its versatility, the scimitar has a heavier oriental influence. The 'shamshir', as it was originally called, is larger, more highly curved, and tapered to an elongated, sharp point. This makes the weapon slightly slower but more effective and deadly in combat.

STATISTICS:

Damage: 2d4 (slashing)
Speed Factor: 6
Proficiency Type: Scimitar/Wakizashi/Ninjatō
Type: One-handed
Requires:
 11 Strength

Weight: 4"

	SAY NAME2 "Belm +3"
	SAY DESC "This enchanted scimitar bears the mark of Taka Kobe, an honored swordsmith of Kara-Tur, though how it came to be here is unknown. Perfectly balanced, it affords quick recovery in combat and even allows the wielder time for an additional attack.

STATISTICS:

Combat abilities:
– 20% chance to gain one extra attack for two rounds

THAC0: +3
Damage: 2d4+3 (slashing)
Speed Factor: 0
Proficiency Type: Scimitar/Wakizashi/Ninjatō
Type: One-handed
Requires:
 11 Strength

Weight: 2"




//SOUL REAVER +4//
COPY "rick_bigg_mod/items/SW2H08.itm" "override"
	SAY NAME1 "Scimitar"
	SAY UNIDENTIFIED_DESC "The long, curved, single-edged blade is characteristic of both the saber and the scimitar, even though their origins lie in different parts of Faerûn. Whereas the saber was intended chiefly for horsemen, mainly due to its versatility, the scimitar has a heavier oriental influence. The 'shamshir', as it was originally called, is larger, more highly curved, and tapered to an elongated, sharp point. This makes the weapon slightly slower but more effective and deadly in combat.

STATISTICS:

Damage: 2d4 (slashing)
Speed Factor: 6
Proficiency Type: Scimitar/Wakizashi/Ninjatō
Type: One-handed
Requires:
 11 Strength

Weight: 4"

	SAY NAME2 "Soul Reaver +4"
	SAY DESC "This blade was carried by Vaelen, a legendary duelist who famously never lost a drop of blood in a hundred matches. His secret lay not in his defense, but in the blade's horrific enchantment: each strike subtly detached the victim's soul from their physical body. Opponents would quickly find their coordination shattering, their blades swinging wildly at empty air as their martial prowess dissolved. Vaelen was eventually executed when judges realized his flawless victories were fueled by this gradual, invisible theft of his rivals' fighting spirits.

STATISTICS:

Combat abilities:
- 30% chance that the target receive a cumulative 1 point penalty to their THAC0 for 4 rounds

THAC0: +4
Damage: 2d4+4 (slashing)
Speed Factor: 2
Proficiency Type: Scimitar/Wakizashi/Ninjatō
Type: One-handed
Requires:
 11 Strength

Weight: 2"






//SPECTRAL BRAND +4 - no good - 9500mo/
COPY "rick_bigg_mod/items/SW1H68.itm" "override"
	SAY NAME1 "Scimitar"
	SAY UNIDENTIFIED_DESC "The long, curved, single-edged blade is characteristic of both the saber and the scimitar, even though their origins lie in different parts of Faerûn. Whereas the saber was intended chiefly for horsemen, mainly due to its versatility, the scimitar has a heavier oriental influence. The 'shamshir', as it was originally called, is larger, more highly curved, and tapered to an elongated, sharp point. This makes the weapon slightly slower but more effective and deadly in combat.

STATISTICS:

Damage: 2d4 (slashing)
Speed Factor: 6
Proficiency Type: Scimitar/Wakizashi/Ninjatō
Type: One-handed
Requires:
 11 Strength

Weight: 4"

	SAY NAME2 "Spectral Brand +4"
	SAY DESC "This scimitar crackles with a cold, malevolent energy. Forged in the depths of the Underdark by a drow bladesinger who bartered his soul to a demon lord, the weapon drinks the warmth of its victims. The blade itself is semi-translucent, flickering like a dying shadow, and it whispers dark promises of power to whoever holds it. 
	
STATISTICS:

Charge abilities: 
– Summon Spectral Blade once per day
  This dancing sword fights on behalf of the one who wields Spectral Brand for 1 turn, as if wielded by a level 20 fighter:
	THAC0: -6
	Damage 2d4+8, +2 cold damage
	Damage type: Slashing
	Attacks per round: 3
	HP: 80
	Immunity to all damage except magical

THAC0: +4
Damage: 2d4+4, +2 cold damage
Damage type: Slashing
Speed Factor: 2
Proficiency Type: Scimitar/Wakizashi/Ninjatō
Type: One-handed
Requires:
 11 Strength

Weight: 2"





//SPECTRAL BRAND +5 - no good - 16000mo//
COPY "rick_bigg_mod/items/SW1H69.itm" "override"
	SAY NAME1 "Scimitar"
	SAY UNIDENTIFIED_DESC "The long, curved, single-edged blade is characteristic of both the saber and the scimitar, even though their origins lie in different parts of Faerûn. Whereas the saber was intended chiefly for horsemen, mainly due to its versatility, the scimitar has a heavier oriental influence. The 'shamshir', as it was originally called, is larger, more highly curved, and tapered to an elongated, sharp point. This makes the weapon slightly slower but more effective and deadly in combat.

STATISTICS:

Damage: 2d4 (slashing)
Speed Factor: 6
Proficiency Type: Scimitar/Wakizashi/Ninjatō
Type: One-handed
Requires:
 11 Strength

Weight: 4"

	SAY NAME2 "Spectral Brand +5"
	SAY DESC "This scimitar crackles with a cold, malevolent energy. Forged in the depths of the Underdark by a drow bladesinger who bartered his soul to a demon lord, the weapon drinks the warmth of its victims. The blade itself is semi-translucent, flickering like a dying shadow, and it whispers dark promises of power to whoever holds it. 
	
	Drawing on the necromancy of the Skull of the Lich, Spectral Brand now unleash is real dark power.

STATISTICS:

Charge abilities: 
– Summon Spectral Blade once per day
  This dancing sword fights on behalf of the one who wields Spectral Brand for 5 rounds, as if wielded by a level 20 fighter:
	THAC0: -6
	Damage 2d4+8, +2 cold damage
	Damage type: Slashing
	Attacks per round: 3
	HP: 80
	Immunity to all damage except magical
	
Combat abilities:
– Each hit makes the target receive a non-cumulative 20% penality to their Slashing Resistance and Cold Resistance for 2 rounds

THAC0: +5
Damage: 2d4+5, +4 cold damage
Damage type: Slashing
Speed Factor: 1
Proficiency Type: Scimitar/Wakizashi/Ninjatō
Type: One-handed
Requires:
 11 Strength

Weight: 2"