//SHORTBOW +1 - 1200mo//
COPY "rick_bigg_mod/items/BOW06.itm" "override"
	SAY NAME1 "Boots"
	SAY UNIDENTIFIED_DESC "Shortbows were the first bows to be developed, although they were not called such. This is more of a default term that refers to anything which is not a longbow. Shortbow staves are about five feet long on the average. As the years passed, attempts were made to increase bow ranges. Bows were either given longer staves or flexibility was increased with no change to the length. The former resulted in what is now called the longbow.

STATISTICS:

Speed Factor: 6
Proficiency Type: Shortbow
Type: Two-handed
Requires:
 3 Strength

Weight: 2"

	SAY NAME2 "Shortbow +1"
	SAY DESC "Shortbows were the first bows to be developed, although they were not called such. This is more of a default term that refers to anything which is not a longbow. This is more of a default term that refers to anything which is not a longbow. Shortbow staves are about five feet long on the average. As the years passed, attempts were made to increase bow ranges. Bows were either given longer staves or flexibility was increased with no change to the length. The former resulted in what is now called the longbow. 
	This is a magical shortbow, giving the user an additional +1 to hit and damage.

STATISTICS:

THAC0: +1
Damage: +1
Speed Factor: 5
Proficiency Type: Shortbow
Type: Two-handed
Requires:
 3 Strength

Weight: 2"