//SPEAR +1 - 1250mo//
COPY "rick_bigg_mod/items/SPER02.itm" "override"
	SAY NAME1 "Spear"
	SAY UNIDENTIFIED_DESC "One of the earliest weapons, dating back to the most primitive of times, the first spears were simply wooden poles or sticks sharpened at one end. When the civilized races mastered metals, spearheads were made from iron and steel. Having reached this end, weaponsmiths began experimenting with different types of spearheads, thus leading to the development of certain polearm types.

STATISTICS:

Damage: 1d8 (piercing)
Speed Factor: 6
Proficiency Type: Spear
Type: Two-handed
Requires:
 7 Strength

Weight: 5"


	SAY NAME2 "Spear +1"
	SAY DESC "One of the earliest weapons, dating back to the most primitive of times, the first spears were simply wooden poles or sticks sharpened at one end. When the civilized races mastered metals, spearheads were made from iron and steel. Having reached this end, weaponsmiths began experimenting with different types of spearheads, thus leading to the development of certain polearm types. This spear is slightly different though, as it has been imbued with certain magical properties.

STATISTICS:

THAC0: +1
Damage: 1d8+1 (piercing)
Speed Factor: 5
Proficiency Type: Spear
Type: Two-handed
Requires:
 7 Strength

Weight: 5"







//SPEAR +2 - 2500mo//
COPY "rick_bigg_mod/items/SPER05.itm" "override"
	SAY NAME1 "Spear"
	SAY UNIDENTIFIED_DESC "One of the earliest weapons, dating back to the most primitive of times, the first spears were simply wooden poles or sticks sharpened at one end. When the civilized races mastered metals, spearheads were made from iron and steel. Having reached this end, weaponsmiths began experimenting with different types of spearheads, thus leading to the development of certain polearm types.

STATISTICS:

Damage: 1d8 (piercing)
Speed Factor: 6
Proficiency Type: Spear
Type: Two-handed
Requires:
 7 Strength

Weight: 5"


	SAY NAME2 "Spear +2"
	SAY DESC "One of the earliest weapons, dating back to the most primitive of times, the first spears were simply wooden poles or sticks sharpened at one end. When the civilized races mastered metals, spearheads were made from iron and steel. Having reached this end, weaponsmiths began experimenting with different types of spearheads, thus leading to the development of certain polearm types. Another line of tinkering led to the integration of magic with spears. Tribal shamans would enchant the spears so that they would hit more often and do greater damage to their wielder's opponents.

STATISTICS:

THAC0: +2
Damage: 1d8+2 (piercing)
Speed Factor: 4
Proficiency Type: Spear 
Type: Two-handed
Requires:
 7 Strength

Weight: 3"







//SPEAR OF THE UNICORN +2 - 5500mo - no evil//
COPY "rick_bigg_mod/items/SPER07.itm" "override"
	SAY NAME1 "Spear"
	SAY UNIDENTIFIED_DESC "One of the earliest weapons, dating back to the most primitive of times, the first spears were simply wooden poles or sticks sharpened at one end. When the civilized races mastered metals, spearheads were made from iron and steel. Having reached this end, weaponsmiths began experimenting with different types of spearheads, thus leading to the development of certain polearm types.

STATISTICS:

Damage: 1d8 (piercing)
Speed Factor: 6
Proficiency Type: Spear
Type: Two-handed
Requires:
 7 Strength

Weight: 5"


	SAY NAME2 "Spear of the Unicorn +2"
	SAY DESC "This graceful spear is carved to resemble the elongated horn of the unicorn. Wielders of this spear are immune to charm and hold spells, just as a unicorn might be. Whether the horn is or isn't an actual unicorn horn is the subject of much debate.

STATISTICS:

Equipped abilities: 
– Immunity to charm and hold
– Save vs. Death: +2

THAC0: +2
Damage: 1d8+2 (piercing)
Speed Factor: 4
Proficiency Type: Spear
Type: Two-handed
Requires:
 7 Strength

Weight: 3" 




//HALCYON +2//
COPY "rick_bigg_mod/items/SPER09.itm" "override"
	SAY NAME1 "Spear"
	SAY UNIDENTIFIED_DESC "One of the earliest weapons, dating back to the most primitive of times, the first spears were simply wooden poles or sticks sharpened at one end. When the civilized races mastered metals, spearheads were made from iron and steel. Having reached this end, weaponsmiths began experimenting with different types of spearheads, thus leading to the development of certain polearm types.

STATISTICS:

Damage: 1d8 (piercing)
Speed Factor: 6
Proficiency Type: Spear
Type: Two-handed
Requires:
 7 Strength

Weight: 5"


	SAY NAME2 "Halcyon +2"
	SAY DESC "The electrum-plated shaft of this weapon hums with magical power. Occasionally, blue bolts of energy run down the length of the spear, charging it. In battle when it hits an opponent, it strikes for additional electricity damage.

STATISTICS:

THAC0: +2
Damage: 1d8+2, +2 Electricity damage
Damage type: Piercing
Speed Factor: 5
Proficiency Type: Spear
Type: Two-handed
Requires:
 7 Strength

Weight: 3" 






//IMPALER +3 - 8000mo//
COPY "rick_bigg_mod/items/SPER08.itm" "override"
	SAY NAME1 "Spear"
	SAY UNIDENTIFIED_DESC "One of the earliest weapons, dating back to the most primitive of times, the first spears were simply wooden poles or sticks sharpened at one end. When the civilized races mastered metals, spearheads were made from iron and steel. Having reached this end, weaponsmiths began experimenting with different types of spearheads, thus leading to the development of certain polearm types.

STATISTICS:

Damage: 1d8 (piercing)
Speed Factor: 6
Proficiency Type: Spear
Type: Two-handed
Requires:
 7 Strength

Weight: 5"


	SAY NAME2 "Impaler +3"
	SAY DESC "The Impaler radiates a palpable, thrumming aura of magic—a silent testament to the weapon's sheer, unadulterated brutality. It is easy to see why this spear was the prized possession of several legendary orc chieftains, leaders who valued raw devastation above all else. When the spear strikes, its massive enchantment drives the point forward with terrifying, supernatural force. Victims are not merely wounded; they are violently run through, as the weapon's savage magic tears through armor and bone alike to complete its grim work.

STATISTICS:

THAC0: +3
Damage: 1d8+10 (piercing)
Speed Factor: 3
Proficiency Type: Spear
Type: Two-handed
Requires:
 7 Strength

Weight: 3" 




//SPEAR OF WITHERING +4 - no druidi e no buoni - valore 10000mo//
COPY "rick_bigg_mod/items/SPER10.itm" "override"
	SAY NAME1 "Spear"
	SAY UNIDENTIFIED_DESC "One of the earliest weapons, dating back to the most primitive of times, the first spears were simply wooden poles or sticks sharpened at one end. When the civilized races mastered metals, spearheads were made from iron and steel. Having reached this end, weaponsmiths began experimenting with different types of spearheads, thus leading to the development of certain polearm types.

STATISTICS:

Damage: 1d8 (piercing)
Speed Factor: 6
Proficiency Type: Spear
Type: Two-handed
Requires:
 7 Strength

Weight: 5"


	SAY NAME2 "Spear of Withering +4"
	SAY DESC "Carved from the heart of a rotten treant, this spear smells of death. When held in your hands, it groans a little, as if reluctant to allow a living thing to touch it. In battle, the Spear of Withering spits a foul poison into its target upon each successful hit.

STATISTICS:

Combat abilities:
- 15% chance on hit to poison target
  Damage: 4d4 (no save) + 1 every 4 seconds (Save vs. Rod at -2 for half)
  Duration: 1 turn

THAC0: +4
Damage: 1d8+4, +2 poison damage
Damage type: Piercing
Speed Factor: 2
Proficiency Type: Spear
Type: Two-handed
Requires:
 7 Strength

Weight: 5" 


//SPEAR OF KULDAHAR +4 - valore 14000mo//
COPY "rick_bigg_mod/items/WASPEAR.itm" "override"
	SAY NAME1 "Spear"
	SAY UNIDENTIFIED_DESC "One of the earliest weapons, dating back to the most primitive of times, the first spears were simply wooden poles or sticks sharpened at one end. When the civilized races mastered metals, spearheads were made from iron and steel. Having reached this end, weaponsmiths began experimenting with different types of spearheads, thus leading to the development of certain polearm types.

STATISTICS:

Damage: 1d8 (piercing)
Speed Factor: 6
Proficiency Type: Spear
Type: Two-handed
Requires:
 7 Strength

Weight: 5"


	SAY NAME2 "Spear of Kuldahar +4"
	SAY DESC "This spear was forged by the druids who dwelt close to the great tree of Kuldahar. It was meant to be used by the warrior who was appointed as Kuldahar's defender.

STATISTICS:

Equipped abilities:
– Armor Class: +3
- Save vs. Necromancy: +4

THAC0: +4
Damage: 1d8+4 (piercing)
Speed Factor: 2
Proficiency Type: Spear 
Type: Two-handed
Requires:
 7 Strength

Weight: 3" 



//IXIL'S NAIL +5 - valore 10000mo//
COPY "rick_bigg_mod/items/SPER11.itm" "override"
	SAY NAME1 "Spear"
	SAY UNIDENTIFIED_DESC "One of the earliest weapons, dating back to the most primitive of times, the first spears were simply wooden poles or sticks sharpened at one end. When the civilized races mastered metals, spearheads were made from iron and steel. Having reached this end, weaponsmiths began experimenting with different types of spearheads, thus leading to the development of certain polearm types.

STATISTICS:

Damage: 1d8 (piercing)
Speed Factor: 6
Proficiency Type: Spear
Type: Two-handed
Requires:
 7 Strength

Weight: 5"


	SAY NAME2 "Ixil's Nail +5"
	SAY DESC "This spear is a weapon of terrifying elegance, crafted from a single, seamless rod of blackened obsidian, while the head is a jagged, crystalline spike known as the 'Nail of Ixil'—a fragment of an ancient, sentient mountain that was shattered by a divine blow.
	
	For many generations, this magical shaft has been separated from Ixil's Spike, the enchanted head of this legendary spear. However, even incomplete, this artifact is still a weapon of great power. 

STATISTICS:

THAC0: +5
Damage: 1d8+5 (piercing)
Speed Factor: 1
Proficiency Type: Spear 
Type: Two-handed
Requires:
 7 Strength

Weight: 2" 




//IXIL'S NAIL +5 - 18000mo//
COPY "rick_bigg_mod/items/SPER12.itm" "override"
	SAY NAME1 "Spear"
	SAY UNIDENTIFIED_DESC "One of the earliest weapons, dating back to the most primitive of times, the first spears were simply wooden poles or sticks sharpened at one end. When the civilized races mastered metals, spearheads were made from iron and steel. Having reached this end, weaponsmiths began experimenting with different types of spearheads, thus leading to the development of certain polearm types.

STATISTICS:

Damage: 1d8 (piercing)
Speed Factor: 6
Proficiency Type: Spear
Type: Two-handed
Requires:
 7 Strength

Weight: 5"


	SAY NAME2 "Ixil's Nail +5"
	SAY DESC "This spear is a weapon of terrifying elegance, crafted from a single, seamless rod of blackened obsidian, while the head is a jagged, crystalline spike known as the 'Nail of Ixil'—a fragment of an ancient, sentient mountain that was shattered by a divine blow.
	
	With shaft and tip reunited, Ixil's Spike is a fearsome weapon. During the battle, the head can detach to pin opponents to the ground even as a new head magically reforms on the end of the spear.

STATISTICS:

Equipped abilities:
– 1 extra attack per round

Combat abilities:
– Hit target is pinned for 3 rounds and takes an additional 1d4+6 piercing damage each round (Save vs. Wand -4 negates)

THAC0: +5
Damage: 1d8+5 (piercing)
Speed Factor: 1 
Proficiency Type: Spear 
Type: Two-handed
Requires:
 7 Strength

Weight: 2" 