//BACKBITER SPEAR +3 - 2000mo//
COPY "rick_bigg_mod/items/SPER03.itm" "override"
	SAY NAME1 "Spear"
	SAY UNIDENTIFIED_DESC "One of the earliest weapons, dating back to the most primitive of times, the first spears were simply wooden poles or sticks sharpened at one end. When the civilized races mastered metals, spearheads were made from iron and steel. Having reached this end, weaponsmiths began experimenting with different types of spearheads, thus leading to the development of certain polearm types.

STATISTICS:

Damage: 1d8 (piercing)
Speed Factor: 6
Proficiency Type: Spear
Type: Two-handed
Requires:
 5 Strength

Weight: 5"


	SAY NAME2 "Backbiter Spear +3"
	SAY DESC "This weapon will appear as a magical spear; however when a combat situation arises, the wielder will attack an enemy and Backbiter will attack the wielder. For every attack made, there's a chance Backbiter will attack the foe and also the wielder. This is a powerful spear, but one must ask if it is worth it in the end.

STATISTICS:

Combat abilities:
– 20% Chance the wielder receives 3 points of damage (piercing) by the spear upon every successful hit

THAC0: +3
Damage: 1d8+3 (piercing)
Speed Factor: 3
Proficiency Type: Spear
Type: Two-handed
Requires:
 5 Strength

Weight: 2" 



//SPEAR OF THE UNICORN +2 - 5500mo - no evil//
COPY "rick_bigg_mod/items/SPER07.itm" "override"
	SAY NAME1 "Spear"
	SAY UNIDENTIFIED_DESC "One of the earliest weapons, dating back to the most primitive of times, the first spears were simply wooden poles or sticks sharpened at one end. When the civilized races mastered metals, spearheads were made from iron and steel. Having reached this end, weaponsmiths began experimenting with different types of spearheads, thus leading to the development of certain polearm types.

STATISTICS:

Damage: 1d6 (piercing)
Speed Factor: 6
Proficiency Type: Spear
Type: Two-handed
Requires:
 5 Strength

Weight: 5"


	SAY NAME2 "Spear of the Unicorn +2"
	SAY DESC "This graceful spear is carved to resemble the elongated horn of the unicorn. Wielders of this spear are immune to charm and hold spells, just as a unicorn might be. Whether the horn is or isn't an actual unicorn horn is the subject of much debate.

STATISTICS:

Equipped abilities: 
– Immunity to charm and hold
– Save vs. Death: +2

THAC0: +2
Damage: 1d6+2 (piercing)
Speed Factor: 4
Proficiency Type: Spear
Type: Two-handed
Requires:
 5 Strength

Weight: 3" 




//HALCYON +2//
COPY "rick_bigg_mod/items/SPER09.itm" "override"
	SAY NAME1 "Spear"
	SAY UNIDENTIFIED_DESC "One of the earliest weapons, dating back to the most primitive of times, the first spears were simply wooden poles or sticks sharpened at one end. When the civilized races mastered metals, spearheads were made from iron and steel. Having reached this end, weaponsmiths began experimenting with different types of spearheads, thus leading to the development of certain polearm types.

STATISTICS:

Damage: 1d8 (piercing)
Speed Factor: 6
Proficiency Type: Spear
Type: Two-handed
Requires:
 5 Strength

Weight: 5"


	SAY NAME2 "Halcyon +2"
	SAY DESC "The electrum-plated shaft of this weapon hums with magical power. Occasionally, blue bolts of energy run down the length of the spear, charging it. In battle when it hits an opponent, it strikes for additional electricity damage.

STATISTICS:

THAC0: +2
Damage: 1d8+2, +2 electrical damage
Damage type: Piercing
Speed Factor: 5
Proficiency Type: Spear
Type: Two-handed
Requires:
 5 Strength

Weight: 3" 






//IMPALER +3 - no good - 8000mo//
COPY "rick_bigg_mod/items/SPER08.itm" "override"
	SAY NAME1 "Spear"
	SAY UNIDENTIFIED_DESC "One of the earliest weapons, dating back to the most primitive of times, the first spears were simply wooden poles or sticks sharpened at one end. When the civilized races mastered metals, spearheads were made from iron and steel. Having reached this end, weaponsmiths began experimenting with different types of spearheads, thus leading to the development of certain polearm types.

STATISTICS:

Damage: 1d8 (piercing)
Speed Factor: 6
Proficiency Type: Spear
Type: Two-handed
Requires:
 5 Strength

Weight: 5"


	SAY NAME2 "Impaler +3"
	SAY DESC "The Impaler has a palpable aura of magic that hints at the vicious nature of the weapon and why it has been a favorite of several powerful orc chieftains in the past. When a victim is struck they are, as one would guess, very nearly impaled, run through as the massive enchantment does its dirty work. 

STATISTICS:

THAC0: +3
Damage: 1d8+3, +7 piercing damage
Damage type: Piercing
Speed Factor: 3
Proficiency Type: Spear
Type: Two-handed
Requires:
 5 Strength

Weight: 3" 




//SPEAR OF WITHERING +4 - no druidi - valore 10000mo//
COPY "rick_bigg_mod/items/SPER10.itm" "override"
	SAY NAME1 "Spear"
	SAY UNIDENTIFIED_DESC "One of the earliest weapons, dating back to the most primitive of times, the first spears were simply wooden poles or sticks sharpened at one end. When the civilized races mastered metals, spearheads were made from iron and steel. Having reached this end, weaponsmiths began experimenting with different types of spearheads, thus leading to the development of certain polearm types.

STATISTICS:

Damage: 1d8 (piercing)
Speed Factor: 6
Proficiency Type: Spear
Type: Two-handed
Requires:
 5 Strength

Weight: 5"


	SAY NAME2 "Spear of Withering +4"
	SAY DESC "Carved from the heart of a rotten treant, this spear smells of death. When held in your hands, it groans a little, as if reluctant to allow a living thing to touch it. In battle, the Spear of Withering spits a foul poison into its target upon each successful hit.

STATISTICS:

Charge Abilities:
- Cast Poison once per day (at level 15)

THAC0: +4
Damage: 1d8+4, +4 poison damage
Damage type: Piercing
Speed Factor: 2
Proficiency Type: Spear
Type: Two-handed
Requires:
 5 Strength

Weight: 5" 


//SPEAR OF KULDAHAR +4 - valore 12000mo//
COPY "rick_bigg_mod/items/WASPEAR.itm" "override"
	SAY NAME1 "Spear"
	SAY UNIDENTIFIED_DESC "One of the earliest weapons, dating back to the most primitive of times, the first spears were simply wooden poles or sticks sharpened at one end. When the civilized races mastered metals, spearheads were made from iron and steel. Having reached this end, weaponsmiths began experimenting with different types of spearheads, thus leading to the development of certain polearm types.

STATISTICS:

Damage: 1d8 (piercing)
Speed Factor: 6
Proficiency Type: Spear
Type: Two-handed
Requires:
 5 Strength

Weight: 5"


	SAY NAME2 "Spear of Kuldahar +4"
	SAY DESC "This spear was forged by the druids who dwelt close to the great tree of Kuldahar. It was meant to be used by the warrior who was appointed as Kuldahar's defender.

STATISTICS:

Equipped abilities:
– Armor Class: +3
- Save vs Necromancy: +4

THAC0: +4
Damage: 1d8+4 (piercing)
Speed Factor: 2
Proficiency Type: Spear 
Type: Two-handed
Requires:
 5 Strength

Weight: 3" 



//IXIL'S NAIL +5 - valore 10000mo//
COPY "rick_bigg_mod/items/SPER11.itm" "override"
	SAY NAME1 "Spear"
	SAY UNIDENTIFIED_DESC "One of the earliest weapons, dating back to the most primitive of times, the first spears were simply wooden poles or sticks sharpened at one end. When the civilized races mastered metals, spearheads were made from iron and steel. Having reached this end, weaponsmiths began experimenting with different types of spearheads, thus leading to the development of certain polearm types.

STATISTICS:

Damage: 1d8 (piercing)
Speed Factor: 6
Proficiency Type: Spear
Type: Two-handed
Requires:
 5 Strength

Weight: 5"


	SAY NAME2 "Ixil's Nail +5"
	SAY DESC "For many generations, this magical shaft has been separated from Ixil's Spike, the enchanted head of the legendary spear. However, even incomplete, this artifact is still a weapon of great power. 

STATISTICS:

THAC0: +5
Damage: 1d8+5 (piercing)
Speed Factor: 1
Proficiency Type: Spear 
Type: Two-handed
Requires:
 5 Strength

Weight: 2" 




//IXIL'S NAIL +6 - 19000mo//
COPY "rick_bigg_mod/items/SPER12.itm" "override"
	SAY NAME1 "Spear"
	SAY UNIDENTIFIED_DESC "One of the earliest weapons, dating back to the most primitive of times, the first spears were simply wooden poles or sticks sharpened at one end. When the civilized races mastered metals, spearheads were made from iron and steel. Having reached this end, weaponsmiths began experimenting with different types of spearheads, thus leading to the development of certain polearm types.

STATISTICS:

Damage: 1d8 (piercing)
Speed Factor: 6
Proficiency Type: Spear
Type: Two-handed
Requires:
 5 Strength

Weight: 5"


	SAY NAME2 "Ixil's Nail +6"
	SAY DESC "With shaft and tip reunited, Ixil's Spike is a fearsome weapon. During the battle, the head can detach to pin opponents to the ground even as a new head magically reforms on the end of the spear.

STATISTICS:

Equipped abilities:
– 1 extra attack per round

Combat abilities:
– Hit target is pinned for 3 rounds and takes an additional 1d6+5 piercing damage each round (Save vs. Paralysis -4 negates)

THAC0: +6
Damage: 1d8+6 (piercing)
Speed Factor: 1 
Proficiency Type: Spear 
Type: Two-handed
Requires:
 5 Strength

Weight: 2" 