//STAFF +1 - 750mo//
COPY "rick_bigg_mod/items/STAF02.itm" "override"
	SAY NAME1 "Staff"
	SAY UNIDENTIFIED_DESC "The simplest and humblest of staff weapons, the quarterstaff is a length of wood ranging six to nine feet in length. High-quality quarterstaves are made of stout oak and are shod with metal at both ends. The quarterstaff must be wielded with both hands.

STATISTICS:

Damage: 1d6 (crushing)
Speed Factor: 4
Proficiency Type: Quarterstaff
Type: Two-handed
Requires:
 5 Strength

Weight: 4"

	SAY NAME2 "Staff +1"
	SAY DESC "The simplest of staff weapons is the quarterstaff, a length of wood six to nine feet in length. High quality quarterstaves are made of stout oak and are shod with metal at both ends. Enchantments during the making of this staff have improved its accuracy and the damage it can cause, but they bear no signature.

STATISTICS:

THAC0: +1
Damage: 1d6+1 (crushing)
Speed Factor: 3
Proficiency Type: Quarterstaff
Type: Two-handed
Requires:
 5 Strength

Weight: 3"








//STAFF +2- 1500mo//
COPY "rick_bigg_mod/items/STAF18.itm" "override"
	SAY NAME1 "Staff"
	SAY UNIDENTIFIED_DESC "The simplest and humblest of staff weapons, the quarterstaff is a length of wood ranging six to nine feet in length. High-quality quarterstaves are made of stout oak and are shod with metal at both ends. The quarterstaff must be wielded with both hands.

STATISTICS:

Damage: 1d6 (crushing)
Speed Factor: 4
Proficiency Type: Quarterstaff
Type: Two-handed
Requires:
 5 Strength

Weight: 4"

	SAY NAME2 "Staff +2"
	SAY DESC "The simplest of staff weapons is the quarterstaff, a length of wood six to nine feet in length. High quality quarterstaves are made of stout oak and are shod with metal at both ends. Powerful enchantments during the making of this staff have improved its accuracy and the damage it can cause, but they bear no signature.

STATISTICS:

THAC0: +2
Damage: 1d6+2 (crushing)
Speed Factor: 2
Proficiency Type: Quarterstaff
Type: Two-handed
Requires:
 5 Strength

Weight: 3"





//STAFF OF STRIKING +2 - 5000mo//
COPY "rick_bigg_mod/items/STAF05.itm" "override"
	SAY NAME1 "Staff"
	SAY UNIDENTIFIED_DESC "The simplest and humblest of staff weapons, the quarterstaff is a length of wood ranging six to nine feet in length. High-quality quarterstaves are made of stout oak and are shod with metal at both ends. The quarterstaff must be wielded with both hands.

STATISTICS:

Damage: 1d6 (crushing)
Speed Factor: 4
Proficiency Type: Quarterstaff
Type: Two-handed
Requires:
 5 Strength

Weight: 4"

	SAY NAME2 "Staff of Striking +2"
	SAY DESC "Staves of Striking are made by the gold elves of Drelagara on Evermeet. The staves have a life of their own and jump to attack in their bearer's hands. The elven craftsmen rarely sell them to other races, but these powerful melee weapons do surface occasionally in Faerûn.
	
Equipped abilities:
– Set attacks per round to 2	
	
STATISTICS:

THAC0: +2
Damage: 1d6+2 (crushing)
Speed Factor: 0
Proficiency Type: Quarterstaff
Type: Two-handed
Requires:
 5 Strength

Weight: 4"




//STAFF SPEAR +2 - 3500mo//
COPY "rick_bigg_mod/items/STAF07.itm" "override"
	SAY NAME1 "Staff"
	SAY UNIDENTIFIED_DESC "The simplest and humblest of staff weapons, the quarterstaff is a length of wood ranging six to nine feet in length. High-quality quarterstaves are made of stout oak and are shod with metal at both ends. The quarterstaff must be wielded with both hands.

STATISTICS:

Damage: 1d6 (crushing)
Speed Factor: 4
Proficiency Type: Quarterstaff
Type: Two-handed
Requires:
 5 Strength

Weight: 4"

	SAY NAME2 "Staff Spear +2"
	SAY DESC "When this seemingly ordinary quarterstaff is examined magically, it has an aura of alteration. Upon command, a long sharp spear blade will shoot forth from its upper end, making the staff into a spear. Likely made by a wizard or priest hoping to increase their melee abilities, it is usable by anybody capable of handling a staff.

STATISTICS:

THAC0: +2
Damage: 1d8+2 (piercing)
Speed Factor: 4
Proficiency Type: Quarterstaff
Type: Two-handed
Requires:
 5 Strength
"




//STAFF MACE +2 - 3500mo//
COPY "rick_bigg_mod/items/STAF06.itm" "override"
	SAY NAME1 "Staff"
	SAY UNIDENTIFIED_DESC "The simplest and humblest of staff weapons, the quarterstaff is a length of wood ranging six to nine feet in length. High-quality quarterstaves are made of stout oak and are shod with metal at both ends. The quarterstaff must be wielded with both hands.

STATISTICS:

Damage: 1d6 (crushing)
Speed Factor: 4
Proficiency Type: Quarterstaff
Type: Two-handed
Requires:
 5 Strength

Weight: 4"

	SAY NAME2 "Staff Mace +2"
	SAY DESC "This weapon appears to be a normal large walking staff, but it has a faint aura of alteration magic. Uttering the command word causes the staff to assume the attributes of a mace, allowing it to be wielded with one hand. This was likely designed for Clerics or Druids, though that does not preclude use by most others.

STATISTICS:

THAC0: +2
Damage: 2d4+2 (crushing)
Speed Factor: 2
Proficiency Type: Quarterstaff
Type: One-handed
Requires:
 5 Strength

Weight: 4
"




//ROD OF SMITING +2 - solo maghi e chierici - 7500mo//
COPY "rick_bigg_mod/items/RODS04.itm" "override"
	SAY NAME1 "Staff"
	SAY UNIDENTIFIED_DESC "Rods are about three feet long and as thick as your thumb. They are normally found in cases or similar storage places. Rods can be fashioned from metal, wood, ivory, or bone. They can be plain or decorated and carved, tipped, or not. Rods are powered by charges, unless noted otherwise in the description of a particular rod. Each time the rod is used, one or more charge may be expended.

STATISTICS:

Weight: 3"

	SAY NAME2 "Rod of Smiting +2"
	SAY DESC "This long, thin rod can be wielded as a staff. This rod has been designed to destroy golems. Any golem struck by the rod must make a Saving Throw or be destroyed. In the hands of any other than a cleric or mage, the rod becomes unusable.

STATISTICS:

Equipped abilities:
- Strikes golem as +5

Combat abilities:
– Struck golems must save vs. Death or be destroyed

THAC0: +2
Damage: 1d6+2, +10 vs. golems
Damage type: Crushing
Speed Factor: 2
Proficiency Type: Quarterstaff
Type: Two-handed

Weight: 3
"





//STAFF OF THUNDER AND LIGHTNING +2 - solo druidi - 6000mo//
COPY "rick_bigg_mod/items/STAF13.itm" "override"
	SAY NAME1 "Staff"
	SAY UNIDENTIFIED_DESC "The simplest and humblest of staff weapons, the quarterstaff is a length of wood ranging six to nine feet in length. High-quality quarterstaves are made of stout oak and are shod with metal at both ends. The quarterstaff must be wielded with both hands.

STATISTICS:

Damage: 1d6 (crushing)
Speed Factor: 4
Proficiency Type: Quarterstaff
Type: Two-handed
Requires:
 5 Strength

Weight: 4"

	SAY NAME2 "Staff of Thunder and Lighning +2"
	SAY DESC "There are stories that tell of these staves sprouting in the growth around druid groves when the forest is threatened. Fanciful tales, but truth or not, this staff is a powerful tool. It draws energy from storms, and there is a chance that any blow might trigger a thunderclap that knocks enemies down. It casts Lightning Bolt, and if circumstances warrant it, it can summon a lightning storm to blast enemies to dust. Some abilities are limited by charges.

STATISTICS:

Cast Lightning Bolt once per day
  Damage: 10d6 Electricity (Save vs. Spell at -4 for half)
  Area of Effect: Path of bolt
  Range: 25 ft.

Cast Call Lightning once per day
  Damage: 6d6 Electricity per strike (Save vs. Breath at -2 for half), three strikes
  Range: 80 ft.
  
Combat abilities:
– Thunderclap: 25% chance of stunning hit target for 2 rounds (Save vs. Wand negates)

THAC0: +2
Damage: 1d6+2 (crushing)
Speed Factor: 2
Proficiency Type: Quarterstaff
Type: Two-handed
Requires:
 5 Strength

Weight: 4
"





//STAFF OF CURING +2 - solo chierici paladini druidi e ranger- 5500mo//
COPY "rick_bigg_mod/items/STAF10.itm" "override"
	SAY NAME1 "Staff"
	SAY UNIDENTIFIED_DESC "The simplest and humblest of staff weapons, the quarterstaff is a length of wood ranging six to nine feet in length. High-quality quarterstaves are made of stout oak and are shod with metal at both ends. The quarterstaff must be wielded with both hands.

STATISTICS:

Damage: 1d6 (crushing)
Speed Factor: 4
Proficiency Type: Quarterstaff
Type: Two-handed
Requires:
 5 Strength

Weight: 4"

	SAY NAME2 "Staff of Curing +2"
	SAY DESC "Torm is said to manifest these items during times of great trouble, granting them to priests who care for the wounded, diseased, and poisoned. It is not to be taken for granted, however, as the enchantment, though useful, is fleeting. It must be used with all due care.

STATISTICS:

Equipped abilities:
– Armor Class: +2

Charge abilities:
– Cure two times per day
  Special: Heals 3d6+3 Hit Points and cures disease and poison
  Range: Touch
  Area of Effect: 1 creature

THAC0: +2
Damage: 1d6+2 (crushing)
Speed Factor: 2
Proficiency Type: Quarterstaff
Type: Two-handed
Requires:
 5 Strength

Weight: 3
"




//ROD OF TERROR +3 - 7000mo//
COPY "rick_bigg_mod/items/RODS05.itm" "override"
	SAY NAME1 "Rod"
	SAY UNIDENTIFIED_DESC "Rods are about three feet long and as thick as your thumb. They are normally found in cases or similar storage places. Rods can be fashioned from metal, wood, ivory, or bone. They can be plain or decorated and carved, tipped, or not. Rods are powered by charges, unless noted otherwise in the description of a particular rod. Each time the rod is used, one or more charge may be expended.

STATISTICS:

Weight: 3"

	SAY NAME2 "Rod of Terror +3"
	SAY DESC "When activated, this rod may be used as a Staff +3. Any creature hit by the rod must make a Saving Throw vs. Wand or flee in terror, fearing the wielder as if he or she were a flesh-eating demon from the Abyss. There is a drawback to using this rod, however: Each time the rod is used, there is a 10% chance that the wielder is scared instead.

STATISTICS:

Combat abilities:
– 80% target must save vs. Wand or flee in terror for 4 rounds
– 20% wielder must save vs. Wand or flee in terror for 4 rounds

THAC0: +3
Damage: 1d6+3 (crushing)
Speed Factor: 1
Proficiency Type: Quarterstaff
Type: Two-handed

Weight: 3
"





//STAFF OF AIR +3 - solo maghi, bardi e druidi - 80000mo//
COPY "rick_bigg_mod/items/STAF15.itm" "override"
	SAY NAME1 "Staff"
	SAY UNIDENTIFIED_DESC "The simplest and humblest of staff weapons, the quarterstaff is a length of wood ranging six to nine feet in length. High-quality quarterstaves are made of stout oak and are shod with metal at both ends. The quarterstaff must be wielded with both hands.

STATISTICS:

Damage: 1d6 (crushing)
Speed Factor: 4
Proficiency Type: Quarterstaff
Type: Two-handed
Requires:
 5 Strength

Weight: 4"

	SAY NAME2 "Staff of Air +3"
	SAY DESC "This staff seems to draw from elven artistic traditions, though tied less to the forest than is usually customary. It was apparently designed to control air elementals, being able to summon one as a servant to the wielder and potentially destroying creatures of the same type in a single blow. When necessary, it can also spawn a cloud of gas, causing anyone within the area of effect to fall into a deep slumber.

STATISTICS:

Equipped abilities:
- +30% Electricity resistance

Combat abilities:
– Struck air elementals save vs. Spell or be destroyed

Charge abilities:
– Summon 8-HD Lesser Air Elemental once per day
  Range: 20 ft.
  Duration: 1 hour

– Sleep Cloud (Save vs. Death negates) once per day
  Range: 40 ft.
  Duration: 3 rounds

THAC0: +3
Damage: 1d6+3 (crushing)
Speed Factor: 1
Proficiency Type: Quarterstaff
Type: Two-handed
Requires:
 5 Strength

Weight: 2
"





//STAFF OF EARTH +3 - solo maghi, bardi e druidi - 80000mo//
COPY "rick_bigg_mod/items/STAF16.itm" "override"
	SAY NAME1 "Staff"
	SAY UNIDENTIFIED_DESC "The simplest and humblest of staff weapons, the quarterstaff is a length of wood ranging six to nine feet in length. High-quality quarterstaves are made of stout oak and are shod with metal at both ends. The quarterstaff must be wielded with both hands.

STATISTICS:

Damage: 1d6 (crushing)
Speed Factor: 4
Proficiency Type: Quarterstaff
Type: Two-handed
Requires:
 5 Strength

Weight: 4"

	SAY NAME2 "Staff of Earth +3"
	SAY DESC "Linked to the Plane of Earth, this staff may have been fashioned by an ancient druidic sect. It can summon an earth elemental, though it also has the potential to slay such creatures in a single blow, possibly hinting at how difficult it is to control them. It can also free a person from the earth by casting Stone to Flesh.

STATISTICS:

Equipped abilities:
- +2 AC vs Slashing, Piercing and Missile

Combat abilities:
– Struck earth elementals must save vs Spell or be destroyed

Charge abilities:
– Summon 8-HD Lesser Earth Elemental once per day
  Range: 20 ft.
  Duration: 1 hour

– Stone to Flesh once per day
  Special: Revert effects of a petrification attack
  Range: Touch

THAC0: +3
Damage: 1d6+3 (crushing)
Speed Factor: 1
Proficiency Type: Quarterstaff
Type: Two-handed
Requires:
 5 Strength

Weight: 2
"






//STAFF OF WATER +3 - solo maghi, bardi e druidi - 80000mo//
COPY "rick_bigg_mod/items/TB#STAFW.itm" "override"
	SAY NAME1 "Staff"
	SAY UNIDENTIFIED_DESC "The simplest and humblest of staff weapons, the quarterstaff is a length of wood ranging six to nine feet in length. High-quality quarterstaves are made of stout oak and are shod with metal at both ends. The quarterstaff must be wielded with both hands.

STATISTICS:

Damage: 1d6 (crushing)
Speed Factor: 4
Proficiency Type: Quarterstaff
Type: Two-handed
Requires:
 5 Strength

Weight: 4"

	SAY NAME2 "Staff of Water +3"
	SAY DESC "Linked to the Plane of Water, this staff may have been fashioned by Sahuagin Priests. It can summon a water elemental, though it also has the potential to slay such creatures in a single blow, possibly hinting at how difficult it is to control them. It can also protects the wielder against spells.

STATISTICS:

Equipped abilities:
- +10% Magic Resistance

Combat abilities:
– Struck water elementals must save vs Spell or be destroyed

Charge abilities:
– Summon 8-HD Lesser Water Elemental once per day
  Range: 20 ft.
  Duration: 1 hour

– Spell deflection once per day

THAC0: +3
Damage: 1d6+3 (crushing)
Speed Factor: 1
Proficiency Type: Quarterstaff
Type: Two-handed
Requires:
 5 Strength

Weight: 2
"





//STAFF OF FIRE +3 - solo maghi, bardi e druidi - 80000mo//
COPY "rick_bigg_mod/items/STAF17.itm" "override"
	SAY NAME1 "Staff"
	SAY UNIDENTIFIED_DESC "The simplest and humblest of staff weapons, the quarterstaff is a length of wood ranging six to nine feet in length. High-quality quarterstaves are made of stout oak and are shod with metal at both ends. The quarterstaff must be wielded with both hands.

STATISTICS:

Damage: 1d6 (crushing)
Speed Factor: 4
Proficiency Type: Quarterstaff
Type: Two-handed
Requires:
 5 Strength

Weight: 4"

	SAY NAME2 "Staff of Fire +3"
	SAY DESC "This staff bears an ancient rune that may link it to the wizards of faraway Halruaa, but it is impossible to be certain. Drawing from the Plane of Fire, it can erupt in a Fire Shield that damages attackers, it can summon a fire elemental under the control of the wielder, and it can potentially draw all the energy from any fire elemental that it hits, destroying them instantly.

STATISTICS:

Equipped abilities:
- +30% Fire resistance

Combat abilities:
– Struck fire elementals must save vs. Spell or be destroyed

Charge abilities:
– Summon 8-HD Lesser Fire Elemental once per day
  Range: 20 ft.
  Duration: 1 hour

– Fireshield (Red) once per day
  Fire Resistance: +50%
  Special: Any who strike the user within a 5-ft. radius suffers 1d8+2 fire damage
  Duration: 13 rounds
  Area of Effect: The user

THAC0: +3
Damage: 1d6+3 (crushing)
Speed Factor: 1
Proficiency Type: Quarterstaff
Type: Two-handed
Requires:
 5 Strength

Weight: 2
"





//STAFF OF COMMAND +3 - 10000mo//
COPY "rick_bigg_mod/items/STAF09.itm" "override"
	SAY NAME1 "Staff"
	SAY UNIDENTIFIED_DESC "The simplest and humblest of staff weapons, the quarterstaff is a length of wood ranging six to nine feet in length. High-quality quarterstaves are made of stout oak and are shod with metal at both ends. The quarterstaff must be wielded with both hands.

STATISTICS:

Damage: 1d6 (crushing)
Speed Factor: 4
Proficiency Type: Quarterstaff
Type: Two-handed
Requires:
 5 Strength

Weight: 4"

	SAY NAME2 "Staff of Command +3"
	SAY DESC "Whispers in the dark corners of Faerûn speak of a slender, obsidian rod that hungers for the autonomy of others. Its origins are entirely lost to the mists of time; no sage can name the wizard who forged it, nor the kingdom where it first brought monarchs to their knees. What is certain is its lineage of blood and subjugation.This artifact has historically gravitated toward the hands of tyrants, cult leaders, and nefarious schemers. It does not merely compel obedience; it unravels the victim's agency, weaving the wielder's intent directly into their mind. Those who hold the staff feel a surge of magnetic presence, a dark charisma that bends the weak-willed before a single spell is even cast. It remains a relic of pure, unadulterated control.

STATISTICS:

Equipped abilities:
- Charisma: +1
- Saving Throws vs Enchantment School: +2

Charge abilities:
– Domination (Save vs. Wand -4 negates) three times per day
  Range: 40 ft.
  Duration: 12 hours
  Area of Effect: 1 creature

THAC0: +3
Damage: 1d6+3 (crushing)
Speed Factor: 1
Proficiency Type: Quarterstaff
Type: Two-handed
Requires:
 5 Strength

Weight: 2
"



//SERPENT SHAFT +4 - valore 10000mo//
COPY "rick_bigg_mod/items/STAF23.itm" "override"
	SAY NAME1 "Staff"
	SAY UNIDENTIFIED_DESC "The simplest and humblest of staff weapons, the quarterstaff is a length of wood ranging six to nine feet in length. High-quality quarterstaves are made of stout oak and are shod with metal at both ends. The quarterstaff must be wielded with both hands.

STATISTICS:

Damage: 1d6 (crushing)
Speed Factor: 4
Proficiency Type: Quarterstaff
Type: Two-handed
Requires:
 5 Strength

Weight: 4"

	SAY NAME2 "Serpent Shaft +4"
	SAY DESC "Adorned with serpentine designs, this powerful quarterstaff has a chance to release a lethal toxin against its opponents with every blow. 

STATISTICS:

Combat abilities:
– Poison opponents with every successful attack. The poison lasts for 2 rounds and does 2 HP of damage/second unless the target makes a save vs. Death.

THAC0: +4
Damage: 1d6+4 (crushing)
Speed Factor: 1
Proficiency Type: Quarterstaff
Type: Two-handed
Requires:
 5 Strength

Weight: 2
"





//STAFF OF RHYNN +4 - valore 14000mo//
COPY "rick_bigg_mod/items/STAF20.itm" "override"
	SAY NAME1 "Staff"
	SAY UNIDENTIFIED_DESC "The simplest and humblest of staff weapons, the quarterstaff is a length of wood ranging six to nine feet in length. High-quality quarterstaves are made of stout oak and are shod with metal at both ends. The quarterstaff must be wielded with both hands.

STATISTICS:

Damage: 1d6 (crushing)
Speed Factor: 4
Proficiency Type: Quarterstaff
Type: Two-handed
Requires:
 5 Strength

Weight: 4"

	SAY NAME2 "Staff of Rhynn +4"
	SAY DESC "There was a time when magic was distrusted even more so than now, and the burning of 'heretics' was woefully common. Delmarey, a witch from the swamplands near Myth Rhynn, faced just such a fate when she was blamed for an unseasonable drought. Taken by surprise and sentenced by a mob, she was put to the torch in the village square. With her dying breath she uttered a foul curse, fueling the fire to an unstoppable magnitude. By dawn, the entire village was reduced to black coal, save the burnt remnant of the pole Delmarey had been bound to. This staff has been imbued with some remnants of Delmarey's power, making it a highly enchanted weapon.

STATISTICS:

Equipped abilities:
- Magic Resistance: +10%

Combat abilities:
- Struck Humans must save vs Death or be killed

THAC0: +4
Damage: 1d6+4 (crushing)
Speed Factor: 1
Proficiency Type: Quarterstaff
Type: Two-handed
Requires:
 5 Strength

Weight: 3
"






//STAFF OF THE WOODLANDS +5 - 20000mo - solo druidi//
COPY "rick_bigg_mod/items/STAF14.itm" "override"
	SAY NAME1 "Staff"
	SAY UNIDENTIFIED_DESC "The simplest and humblest of staff weapons, the quarterstaff is a length of wood ranging six to nine feet in length. High-quality quarterstaves are made of stout oak and are shod with metal at both ends. The quarterstaff must be wielded with both hands.

STATISTICS:

Damage: 1d6 (crushing)
Speed Factor: 4
Proficiency Type: Quarterstaff
Type: Two-handed
Requires:
 5 Strength

Weight: 4"

	SAY NAME2 "Staff of the Woodlands +5"
	SAY DESC "Known only as the 'Wild Man of the Wood', the man that carried this staff was a legendary figure near Trademeet until the day he died and returned to the soil. Those who saw him remember his dark, bark-like skin, a feature that would fade if the staff were set aside. He would harass irresponsible loggers and poachers, and old-timers tell of mercenaries chasing him with a dozen hunting dogs or more. The animals seemed ready to rip the poor druid to pieces, but he quickly turned them on their former masters. Rushing forward in hopes of ending his influence, the men-at-arms saw the final power of the staff, and as the vegetation trembled with the 'Wild Man's' magical calling, there formed a green, rotting mix of life and death that shambled overtop of the terrified soldiers, killing them all.

STATISTICS:

Equipped abilities: 
– Barkskin on self
– AC bonus: +2
- Saving Throws bonus: +2

Charge abilities:
– Summon 8-HD Shambling Mound twice per day
  Range: 40 ft.
  Duration: 100 seconds

– Entangle at will

Combat abilities:
- Target is entangled (save vs Paralysis -4)

THAC0: +5
Damage: 1d6+5 (crushing)
Speed Factor: 1
Proficiency Type: Quarterstaff
Type: Two-handed
Requires:
 5 Strength

Weight: 2
"





//STAFF OF THE MAGI +5 - 25000mo - solo maghi//
COPY "rick_bigg_mod/items/STAF11.itm" "override"
	SAY NAME1 "Staff"
	SAY UNIDENTIFIED_DESC "The simplest and humblest of staff weapons, the quarterstaff is a length of wood ranging six to nine feet in length. High-quality quarterstaves are made of stout oak and are shod with metal at both ends. The quarterstaff must be wielded with both hands.

STATISTICS:

Damage: 1d6 (crushing)
Speed Factor: 4
Proficiency Type: Quarterstaff
Type: Two-handed
Requires:
 5 Strength

Weight: 4"

	SAY NAME2 "Staff of the Magi +5"
	SAY DESC "This type of staff is thoroughly linked to the image of the spellcasting profession, rare though it is. It is among the most powerful tools that a wizard can possess, the culmination of complex enchantments and endless study. This fantastic weapon can strike from range, grants immunity to Time Stop, and cast Magical Strike, a powerful attack that bypasses mages' protections. The quintessential Mage item.

STATISTICS:

Equipped abilities:
- Immunity to Time Stop
- Immunity to Charm

Combat abilities:
– Extended range
- Each hit makes the target receive a cumulative penalty for 2 turns: 
   -1 Saving Throws 
   -10% Magic Resistance 

Charge abilities:
– Magical Strike three times per day 
  Damage: 6d6 (magical), bypasses all protections
  Range: 40 ft.
  
- Dimension Jump at will
  
THAC0: +5
Damage: 1d6+5 (magical)
Speed Factor: 0
Proficiency Type: Quarterstaff
Type: Two-handed
Range: 6 yards
Requires:
 5 Strength

Weight: 4
"






//STAFF OF THE RAM +4 - 11000mo//
COPY "rick_bigg_mod/items/STAF21.itm" "override"
	SAY NAME1 "Staff"
	SAY UNIDENTIFIED_DESC "The simplest and humblest of staff weapons, the quarterstaff is a length of wood ranging six to nine feet in length. High-quality quarterstaves are made of stout oak and are shod with metal at both ends. The quarterstaff must be wielded with both hands.

STATISTICS:

Damage: 1d6 (crushing)
Speed Factor: 4
Proficiency Type: Quarterstaff
Type: Two-handed
Requires:
 5 Strength

Weight: 4"

	SAY NAME2 "Staff of the Ram +4"
	SAY DESC "The Staff of the Ram is a weapon of deceptive simplicity and earth-shattering force. Crafted from the wood of an iron-oak tree that grew atop the highest peak of the Mount Tozal, the staff was tempered in the crushing depths of the Elemental Plane of Earth. The name of the weapon comes from its unique enchantment: the tip of the staff is capped with an invisible, magical force shaped like a charging ram’s head. When the wielder strikes, this force is unleashed with a thunderous roar, magnifying the physical blow a hundredfold.

STATISTICS:

Combat abilities: 
– 10% chance opponent is knocked back and stunned (large creatures such as a dragons or giants will not be knocked back or stunned)

THAC0: +4
Damage: 1d6+4, +8 crushing damage
Damage Type: Crushing
Speed Factor: 1
Proficiency Type: Quarterstaff
Type: Two-handed
Requires:
 5 Strength

Weight: 3
"






//STAFF OF THE RAM +6 - 20000mo//
COPY "rick_bigg_mod/items/STAF22.itm" "override"
	SAY NAME1 "Staff"
	SAY UNIDENTIFIED_DESC "The simplest and humblest of staff weapons, the quarterstaff is a length of wood ranging six to nine feet in length. High-quality quarterstaves are made of stout oak and are shod with metal at both ends. The quarterstaff must be wielded with both hands.

STATISTICS:

Damage: 1d6 (crushing)
Speed Factor: 4
Proficiency Type: Quarterstaff
Type: Two-handed
Requires:
 5 Strength

Weight: 4"

	SAY NAME2 "Staff of the Ram +6"
	SAY DESC "The Staff of the Ram is a weapon of deceptive simplicity and earth-shattering force. Crafted from the wood of an iron-oak tree that grew atop the highest peak of the Mount Tozal, the staff was tempered in the crushing depths of the Elemental Plane of Earth. The name of the weapon comes from its unique enchantment: the tip of the staff is capped with an invisible, magical force shaped like a charging ram’s head. When the wielder strikes, this force is unleashed with a thunderous roar, magnifying the physical blow a hundredfold.
	
	Roranach's Horn augments the Staff of the Ram's already noteworthy abilities, creating a weapon few opponents are able to stand against.

STATISTICS:

Equipped abilities:
- Critical Hit Chance: +5% with this weapon 

Combat abilities:
– Deals extra 10 points of piercing damage on a critical hit
– 15% chance opponent is knocked back and stunned (large creatures such as a dragons or giants will not be knocked back or stunned)

THAC0: +6
Damage: 1d6+6, +12 crushing damage
Damage Type: Crushing
Speed Factor: 1
Proficiency Type: Quarterstaff
Type: Two-handed
Requires:
 5 Strength

Weight: 3
"