//STUDDED LEATHER ARMOR +1 - 1500mo//
COPY "rick_bigg_mod/items/LEAT05.itm" "override"
	SAY NAME1 "Studded Leather Armor"
	SAY UNIDENTIFIED_DESC "Studded leather armor has little in common with normal leather armor. Instead of a hardened shell, studded leather offers hundreds of metal rivets affixed to a supple backing. The numerous studs form a flexible coat of metal that helps to turn aside slashing and cutting attacks, while the leather is little more than a means of securing the rivets in place. 

STATISTICS:

Armor Class: 7 (5 vs. slashing, 6 vs. piercing and missile)
Speed Factor: -1
Requires:
 7 Strength

Weight: 25
"

	SAY NAME2 "Studded Leather Armor +1"
	SAY DESC "Chain mail is made of interlocking metal rings. It is always worn over a layer of padded fabric or soft leather to prevent chafing and lessen the impact of blows.  Extra protection is given by magical enchantments placed on this armor.

STATISTICS:

Armor Class: 6 (4 vs. slashing, 5 vs. piercing and missile)
Speed Factor: -1
Requires:
 7 Strength

Weight: 15
"




//STUDDED LEATHER ARMOR +2 - 3000mo//
COPY "rick_bigg_mod/items/LEAT07.itm" "override"
	SAY NAME1 "Studded Leather Armor"
	SAY UNIDENTIFIED_DESC "Studded leather armor has little in common with normal leather armor. Instead of a hardened shell, studded leather offers hundreds of metal rivets affixed to a supple backing. The numerous studs form a flexible coat of metal that helps to turn aside slashing and cutting attacks, while the leather is little more than a means of securing the rivets in place. 

STATISTICS:

Armor Class: 7 (5 vs. slashing, 6 vs. piercing and missile)
Speed Factor: -1
Requires:
 7 Strength

Weight: 25
"

	SAY NAME2 "Studded Leather Armor +2"
	SAY DESC "Chain mail is made of interlocking metal rings. It is always worn over a layer of padded fabric or soft leather to prevent chafing and lessen the impact of blows.  Extra protection is given by magical enchantments placed on this armor.

STATISTICS:

Armor Class: 5 (3 vs. slashing, 4 vs. piercing and missile)
Speed Factor: -1
Requires:
 7 Strength

Weight: 10
"





//ARMOR OF MISSILE ATTRACTION +2 - 3500mo//
COPY "rick_bigg_mod/items/LEAT06.itm" "override"
	SAY NAME1 "Studded Leather Armor"
	SAY UNIDENTIFIED_DESC "Studded leather armor has little in common with normal leather armor. Instead of a hardened shell, studded leather offers hundreds of metal rivets affixed to a supple backing. The numerous studs form a flexible coat of metal that helps to turn aside slashing and cutting attacks, while the leather is little more than a means of securing the rivets in place. 

STATISTICS:

Armor Class: 7 (5 vs. slashing, 6 vs. piercing and missile)
Speed Factor: -1
Requires:
 7 Strength

Weight: 25
"

	SAY NAME2 "Armor of Missile Attraction +2"
	SAY DESC "This odd-looking suit of studded leather cannot be removed once put on, except under intervention by a priest. While improving a great protection against all melee weapons, this armor actually becomes a target for missile weapons, and hence so does its wearer. The choice is simple: deadly arrows or deadly swords. 

STATISTICS:

Equipped abilities:
– May only be removed with a Remove Curse spell
– Crushing Damage Resistance: +10%
– Slashing Damage Resistance: +10%
– Piercing Damage Resistance: +10%

Armor Class: 5 (3 vs. slashing, 4 vs. piercing, 15 vs. missile)
Speed Factor: -1
Requires:
 7 Strength

Weight: 10"






//TELBAR'S STUDDED LEATHER +2 - 4500mo//
COPY "rick_bigg_mod/items/TB#LEA15.itm" "override"
	SAY NAME1 "Studded Leather Armor"
	SAY UNIDENTIFIED_DESC "Studded leather armor has little in common with normal leather armor. Instead of a hardened shell, studded leather offers hundreds of metal rivets affixed to a supple backing. The numerous studs form a flexible coat of metal that helps to turn aside slashing and cutting attacks, while the leather is little more than a means of securing the rivets in place. 

STATISTICS:

Armor Class: 7 (5 vs. slashing, 6 vs. piercing and missile)
Speed Factor: -1
Requires:
 7 Strength

Weight: 25
"

	SAY NAME2 "Telbar's Studded Leather +2"
	SAY DESC "This armor was the property of the famous rogue Telbar. How or why it left his possession is not known. 
It is well known that as long as he was in possession of this armor, fortune rarely turned its back on him.

STATISTICS:

Equipped abilites: 
Luck: +1

Armor Class: 5 (3 vs. slashing, 4 vs. piercing and missile)
Speed Factor: -1
Requires:
 7 Strength

Weight: 10
"







//SHADOW ARMOR +3 - solo ladri - 7000mo//
COPY "rick_bigg_mod/items/LEAT08.itm" "override"
	SAY NAME1 "Studded Leather Armor"
	SAY UNIDENTIFIED_DESC "Studded leather armor has little in common with normal leather armor. Instead of a hardened shell, studded leather offers hundreds of metal rivets affixed to a supple backing. The numerous studs form a flexible coat of metal that helps to turn aside slashing and cutting attacks, while the leather is little more than a means of securing the rivets in place. 

STATISTICS:

Armor Class: 7 (5 vs. slashing, 6 vs. piercing and missile)
Speed Factor: -1
Requires:
 7 Strength

Weight: 25
"

	SAY NAME2 "Shadow Armor +3"
	SAY DESC "This is a +3 studded leather armor that melds into shadows, created for use by the Shadowmasters of Amn. The Shadowmasters are of the highest order within the Shadow Thieves' hierarchy.

STATISTICS:

Equipped abilities:
– Hide In Shadows: +25%

Armor Class: 4 (2 vs. slashing, 3 vs. piercing and missile)
Speed Factor: -1
Requires:
 7 Strength

Weight: 8"






//ORC LEATHER +3 - 5000mo//
COPY "rick_bigg_mod/items/LEAT16.itm" "override"
	SAY NAME1 "Studded Leather Armor"
	SAY UNIDENTIFIED_DESC "Studded leather armor has little in common with normal leather armor. Instead of a hardened shell, studded leather offers hundreds of metal rivets affixed to a supple backing. The numerous studs form a flexible coat of metal that helps to turn aside slashing and cutting attacks, while the leather is little more than a means of securing the rivets in place. 

STATISTICS:

Armor Class: 7 (5 vs. slashing, 6 vs. piercing and missile)
Speed Factor: -1
Requires:
 7 Strength

Weight: 25
"

	SAY NAME2 "Orc Leather +3"
	SAY DESC "This ghastly armor was taken from an orc camp destroyed by barbarians. Instead of standard metal rivets, like normal studded leather, this orc leather is instead laced with hundreds of fire-hardened bones. Finger bones, ribs, and skulls cover the armor, acting much like the traditional metal rivets. Powerful orcish enchantments give the armor special resistance to missile attacks, but the repulsiveness of the armor reduces the wearer's Charisma.

STATISTICS:

Equipped abilities:
– Charisma: 2
– +20% resistance to missile damage

Armor Class: 4 (2 vs. slashing, 3 vs. piercing and missile)
Speed Factor: -1
Requires:
 7 Strength

Weight: 8"




//KRUNTUR'S ARMOR +4 - valore 6000mo//
COPY "rick_bigg_mod/items/BDCHAN02.itm" "override"
	SAY NAME1 "Studded Leather Armor"
	SAY UNIDENTIFIED_DESC "Studded leather armor has little in common with normal leather armor. Instead of a hardened shell, studded leather offers hundreds of metal rivets affixed to a supple backing. The numerous studs form a flexible coat of metal that helps to turn aside slashing and cutting attacks, while the leather is little more than a means of securing the rivets in place. 

STATISTICS:

Armor Class: 7 (5 vs. slashing, 6 vs. piercing and missile)
Speed Factor: -1
Requires:
 7 Strength

Weight: 25
"

	SAY NAME2 "Orc Leather +3"
	SAY DESC "Once worn by the dekanter goblin warlord Kruntur, this armor is of an unusually high quality considering the race of its owner. Kruntur prized this armor to such a degree that, upon his death, he refused to leave it. To this day, more than a hundred years later, his spirit still permeates the armor, whispering threats to all who dare wear it and generally making a nuisance of himself. He cannot directly harm the wearer, however the chance to have such fine protection might well make up for the aggravation the armor brings with it.

STATISTICS:

Equipped abilities:
– Wisdom: -1
– Immunity to stun

Armor Class: 3 (1 vs. slashing, 2 vs. piercing and missile)
Speed Factor: -1
Requires:
 7 Strength

Weight: 8"






//THE NIGHT'S EMBRACE +4 - 10000mo//
COPY "rick_bigg_mod/items/LEAT17.itm" "override"
	SAY NAME1 "Studded Leather Armor"
	SAY UNIDENTIFIED_DESC "Studded leather armor has little in common with normal leather armor. Instead of a hardened shell, studded leather offers hundreds of metal rivets affixed to a supple backing. The numerous studs form a flexible coat of metal that helps to turn aside slashing and cutting attacks, while the leather is little more than a means of securing the rivets in place. 

STATISTICS:

Armor Class: 7 (5 vs. slashing, 6 vs. piercing and missile)
Speed Factor: -1
Requires:
 7 Strength

Weight: 25
"

	SAY NAME2 "The Night's Embrace +4"
	SAY DESC "A thief from Iriaebor who feared being captured by the city guard was known to have favored this armor. She designed the suit so that if she were ever incapacitated in any way, she would be rendered temporarily invisible. The armor did its job, and the thief had a long and successful career in the city. When she retired, she gifted the armor to her younger brother, and it has changed hands many times since then.

STATISTICS:

Equipped abilities:
– If the wearer is rendered helpless (e.g. by a Hold Person spell), <PRO_HESHE> becomes invisible for 1 turn
- AC bonus at night: +2
- Saving Throws bonus at night: +2

Armor Class: 3 (1 vs. slashing, 2 vs. piercing and missile)
Speed Factor: -1
Requires:
 7 Strength

Weight: 7"




//SHADOW DRAGON SCALE - 12000mo//
COPY "rick_bigg_mod/items/LEAT19.itm" "override"
	SAY NAME1 "Studded Leather Armor"
	SAY UNIDENTIFIED_DESC "Studded leather armor has little in common with normal leather armor. Instead of a hardened shell, studded leather offers hundreds of metal rivets affixed to a supple backing. The numerous studs form a flexible coat of metal that helps to turn aside slashing and cutting attacks, while the leather is little more than a means of securing the rivets in place. 

STATISTICS:

Armor Class: 7 (5 vs. slashing, 6 vs. piercing and missile)
Speed Factor: -1
Requires:
 7 Strength

Weight: 25"

	SAY NAME2 "Shadow Dragon Scale"
	SAY DESC "This suit of armor is formed from interlocking shadow dragon scales. Elegant workmanship and practical considerations make this armor both beautiful and useful. The shadow dragon scales grant the wearer a powerful protection against negative plane.

STATISTICS:

Equipped abilities:
– Immunity to level drain

Armor Class: 2 (0 vs. slashing, 1 vs. piercing, -1 vs. missile)
Speed Factor: -1
Requires:
 7 Strength

Weight: 10
"





//GRANDMASTER'S ARMOR +5 - solo ladri e assassini (no spadaccini) - 16000mo//
COPY "rick_bigg_mod/items/LEAT24.itm" "override"
	SAY NAME1 "Studded Leather Armor"
	SAY UNIDENTIFIED_DESC "Studded leather armor has little in common with normal leather armor. Instead of a hardened shell, studded leather offers hundreds of metal rivets affixed to a supple backing. The numerous studs form a flexible coat of metal that helps to turn aside slashing and cutting attacks, while the leather is little more than a means of securing the rivets in place. 

STATISTICS:

Armor Class: 7 (5 vs. slashing, 6 vs. piercing and missile)
Speed Factor: -1
Requires:
 7 Strength

Weight: 25
"

	SAY NAME2 "Grandmaster's Armor +5"
	SAY DESC "This extraordinary suit of armor is the pinnacle of the leatherworker's craft, commissioned by the legendary Grandmaster of the Shadow Thieves of Athkatla. It was designed for an operative who required the protection of heavy plate but the silence and flexibility of a second skin. The Grandmaster's Armor is more than just a defensive garment; it is a masterpiece of kinetic enchantment. The suit is magically attuned to the wearer's movements, anticipating every dodge and roll, and actually enhancing the user's natural speed. It is whispered that the first master who wore this armor could walk through a room full of dry leaves without making a sound, and dance between raindrops during a storm.  

STATISTICS:

Equipped abilities:
– Doubles Movement Rate

Charge abilities:
- Dimension Door at will

Armor Class: 2 (0 vs. slashing, 1 vs. piercing and missile)
Speed Factor: -1
Requires:
 7 Strength

Weight: 5"
















