IF
    Global("tb#collectInnocentScalps","GLOBAL", 0)
    PartyHasItem("tb#scalp")
    CombatCounter(0)
THEN RESPONSE #100
    ActionOverride(Player1, StartDialog("tb#scalp", Player1))
END

IF
    Global("tb#collectInnocentScalps","GLOBAL", 1)
    PartyHasItem("tb#scalp")
    CombatCounter(0)
THEN RESPONSE #100
    ActionOverride(Player1, DestroyItem("tb#scalp"))
    ActionOverride(Player2, DestroyItem("tb#scalp"))
    ActionOverride(Player3, DestroyItem("tb#scalp"))
    ActionOverride(Player4, DestroyItem("tb#scalp"))
    ActionOverride(Player5, DestroyItem("tb#scalp"))
    ActionOverride(Player6, DestroyItem("tb#scalp"))
END

