COPY_EXISTING_REGEXP GLOB ~^.+\.cre$~ ~override~
                          ~^.+\.itm$~ ~override~
                          ~^.+\.spl$~ ~override~
  PATCH_IF ("%SOURCE_FILE%" STRING_COMPARE_REGEXP "^.+\.spl" = 0) BEGIN
    READ_LONG   0x64 "abil_off" ELSE 0
    READ_SHORT  0x68 "abil_num" ELSE 0
    READ_LONG   0x6a "fx_off"   ELSE 0
    SET "counter_offset" = 0x70
    SET "abil_length" = 0x28
    SET "global_loop" = 0
    SET "fx_type" = 0
    SET "min_size" = 0x72
  END ELSE
  PATCH_IF ("%SOURCE_FILE%" STRING_COMPARE_REGEXP "^.+\.itm" = 0) BEGIN
    READ_LONG   0x64 "abil_off" ELSE 0
    READ_SHORT  0x68 "abil_num" ELSE 0
    READ_LONG   0x6a "fx_off"   ELSE 0
    SET "counter_offset" = 0x70
    SET "abil_length" = 0x38
    SET "global_loop" = 1
    SET "fx_type" = 0
    SET "min_size" = 0x72
  END ELSE
  PATCH_IF ("%SOURCE_FILE%" STRING_COMPARE_REGEXP "^.+\.cre" = 0) BEGIN
    SET "abil_off" = 0
    SET "abil_num" = 0
    READ_LONG  0x2c4 "fx_off" ELSE 0
    SET "counter_offset" = 0x2c8
    SET "abil_length" = 0
    SET "global_loop" = 1
    READ_BYTE 0x33 "fx_type" ELSE 2
    SET "min_size" = 0x2d4
  END
  PATCH_IF (SOURCE_SIZE >= min_size) BEGIN // exclude joinable cre files
    FOR (index = (0 - global_loop) ; index < abil_num ; index = index + 1) BEGIN
      PATCH_IF ("%index%" < 0) BEGIN // if loop through globals needed
        SET "abil_fx_idx" = 0
      END ELSE BEGIN // otherwise normal ability
        SET "counter_offset" = ("%abil_off%" + 0x1e + ("%abil_length%" * "%index%"))
        READ_SHORT  ("%abil_off%" + 0x20 + ("%abil_length%" * "%index%")) "abil_fx_idx"
      END
      READ_SHORT "%counter_offset%" "counter" // fx_num on global loop, otherwise abil_fx_num
      FOR (index2 = 0 ; index2 < counter ; index2 = index2 + 1) BEGIN
        READ_SHORT ("%fx_off%"        + (0x08 * "%fx_type%") + (("%abil_fx_idx%" + "%index2%") * (0x30 + (0xd8 * "%fx_type%")))) "opcode"
        PATCH_IF (opcode = 233) BEGIN
          READ_SHORT  ("%fx_off%" + 0x08 + (0x10 * "%fx_type%") + (("%abil_fx_idx%" + "%index2%") * (0x30 + (0xd8 * "%fx_type%")))) "param2"
          PHP_EACH cd_prof_numeric_map AS old => new BEGIN
            PATCH_IF (param2 = old) BEGIN
              WRITE_SHORT  ("%fx_off%" + 0x08 + (0x10 * "%fx_type%") + (("%abil_fx_idx%" + "%index2%") * (0x30 + (0xd8 * "%fx_type%")))) new
              SET param2 = 0 // only make a change once
            END
          END
        END
      END
    END
  END
  BUT_ONLY

COPY_EXISTING_REGEXP GLOB ~^.+\.eff$~ ~override~
  READ_LONG 0x10 opcode
  PATCH_IF (opcode = 233) BEGIN
    READ_LONG  0x20 param2
    PHP_EACH cd_prof_numeric_map AS old => new BEGIN
      PATCH_IF (param2 = old) BEGIN
        WRITE_LONG 0x20 new
      END
    END
  END
  BUT_ONLY

COPY_EXISTING_REGEXP GLOB ~^.+\.bcs$~ ~override~
//                          ~^.+\.dlg$~ ~override~ // since triggers not compiled, updated stats.ids will point old IDS entries will point to new stats
  DECOMPILE_AND_PATCH BEGIN
    REPLACE_TEXTUALLY CASE_SENSITIVE ~\(CheckStat[GL]?T?([^,]+, *[0-9]+ *, *\)EXTRAPROFICIENCY1 *)~ ~\1%club_except%)~ // one-off for clubs
    PHP_EACH cd_prof_text_map AS old => new BEGIN
      REPLACE_TEXTUALLY CASE_SENSITIVE ~\(CheckStat[GL]?T?([^,]+, *[0-9]+ *, *\)PROFICIENCY%old% *)~ ~\1%new%)~
    END
  END
  BUT_ONLY
