
//DEFENSIVE HARMONY//
COPY "rick_bigg_mod/spell/SPPR406.spl" "override"
	SAY NAME1 "Defensive Harmony"
	SAY UNIDENTIFIED_DESC 
"Defensive Harmony
Level: 4
School: Enchantment
Sphere: Law
Range: Personal
Duration: 1 turn
Casting Time: 1
Area of Effect: 10' radius
Saving Throw: None

Defensive Harmony grants affected creatures a defensive bonus by enhancing the coordination of their attacks and defenses. This allows a group of creatures to act as a cohesive unit for a single battle or encounter. The effect is always centered on the caster, but affects all those within a 10 foot radius. The affected creatures can move outside of this radius after the spell is cast and still enjoy the benefits of the Harmony. While the spell is in effect, each affected creature gains a +4 bonus to her armor class. Multiple castings of this spell are not cumulative.
"




//MAGIC CIRCLE AGAINST EVIL//
COPY "rick_bigg_mod/spell/SPPR408.spl" "override"
	SAY NAME1 "Magic Circle against Evil"
	SAY UNIDENTIFIED_DESC 
"Magic Circle against Evil
Level: 4
School: Abjuration
Sphere: Protection
Range: Personal
Duration: 5 turns
Casting Time: 5
Area of Effect: 30' radius
Saving Throw: None

Upon casting this spell, the priest causes all friendly creatures within the area of effect to be affected by the spell Protection from Evil. Creatures leaving the area are still subject to the spell's effect; those entering the area after the casting is completed are not.
"






