//PROTECTION FROM PETRIFICATION//
COPY "rick_bigg_mod/spell/SPWI108.spl" "override"
	SAY NAME1 "Protection From Petrification"
	SAY UNIDENTIFIED_DESC 
"Protection from Petrification
Level: 1
School: Abjuration
Range: Touch
Duration: 5 turns
Casting Time: 1
Area of Effect: 1 creature
Saving Throw: None

This spell grants the recipient immunity to all petrification attacks. This includes basilisk and medusa gaze, cursed scrolls of petrification, etc.
"





//GLITTERDUST//
COPY "rick_bigg_mod/spell/SPWI224.spl" "override"
	SAY NAME1 "Glitterdust"
	SAY UNIDENTIFIED_DESC 
"Glitterdust
Level: 2
School: Conjuration
Range: Medium
Duration: 5 rounds
Casting Time: 2
Area of Effect: 10' radius
Saving Throw: Special

This spell creates a cloud of glittering golden particles within the area of effect. The sparkling dust dazzles all opponents in the area (-2 penalty to attack rolls) for 5 rounds and reveals any opponents who are invisible. Those affected must also save vs. breath at to avoid becoming completely covered by the dust, which cannot be removed and continues to sparkle for 5 rounds. Those failing the save remain unable to successfully hide themselves until the dust fades.
"




//GREASE//
COPY "rick_bigg_mod/spell/SPWI101.spl" "override"
	SAY NAME1 "Grease"
	SAY UNIDENTIFIED_DESC 
"Grease
Level: 1
School: Conjuration
Range: Medium
Duration: 1 turn
Casting Time: 1
Area of Effect: 10' radius
Saving Throw: Breath partial

A Grease spell covers a material surface with a slippery layer of a fatty, greasy nature. Any creature caught in it when the spell is cast must save vs. breath at +2 bonus (+1 bonus at 5th level and no bonus at 9th level) or fall to the ground for one round. Those who enter the area or remain within it must make a save each round until they reach the nearest non-greased surface. A creature that succeeds on their saving throw can walk within or through the area of grease but will have their movements slowed considerably. Incorporeal and flying creatures are unaffected by this spell, as are exceptionally large creatures who suffer little to no distress from the greasy coating. 
"




//MAGE ARMOR//
COPY "rick_bigg_mod/spell/SPWI102.spl" "override"
	SAY NAME1 "Mage Armor"
	SAY UNIDENTIFIED_DESC 
"Mage Armor
Level: 1
School: Conjuration
Range: Personal
Duration: 8 hours
Casting Time: 1 round
Area of Effect: Caster
Saving Throw: None

By means of this spell, the wizard creates a magical field of force that sets its base armor class to 6. This improves by 1 AC for every four levels of the caster, up to a minimum base armor class of 4 at 9th level. This armor does not hinder movement, adds no weight or encumbrance, nor does it prevent spellcasting. It lasts until successfully dispelled or until the duration runs out.
"




//CHILL TOUCH//
COPY "rick_bigg_mod/spell/SPWI117.spl" "override"
	SAY NAME1 "Chill Touch"
	SAY UNIDENTIFIED_DESC 
"Chill Touch
Level: 1
School: Necromancy
Range: Personal
Duration: Special
Casting Time: 1
Area of Effect: Special
Saving Throw: Special

When the caster completes this spell, a blue glow encompasses his hand. This energy attacks the life force of any living creature upon which the wizard makes a successful melee attack. The touched creature suffers 1d8 points of cold damage and loses one point of strength. There is no ability drain if the victim saves vs. spell and the effect lasts 1 hour. The spell expires once the caster makes a successful melee attack or after 1 turn has passed. The wizard gains a +4 bonus to hit the target.

At higher levels:
- the damage increases by 1d8 every two levels, up to 5d8 at 9th level
- the strength drain increases by one point every four level, up to three at 9th level
- the saving throws are made at -1 penalty at 5th level and -2 penalty at 9th
"



//SPOOK//
COPY "rick_bigg_mod/spell/SPWI125.spl" "override"
	SAY NAME1 "Spook"
	SAY UNIDENTIFIED_DESC 
"Spook
Level: 1
School: Necromancy
Range: Long
Duration: 5 rounds
Casting Time: 1
Area of Effect: 1 creature
Saving Throw: Spell negates

A Spook spell enables the wizard to play upon natural fears to cause the target creature to perceive the spellcaster as someone or something inimical which then appears to advance upon it in a threatening manner. If the creature does not make a successful saving throw vs. spell, it turns and flees at maximum speed as far from the wizard as possible. Although the caster does not actually pursue the fleeing creature, a phantasm from its own mind does. Undead creatures, certain powerful creatures who can easily discern the illusion, such as dragons, and those with no intelligence score are unaffected by this spell, as are creatures under the effect of a True Seeing spell."




//BLUR - per Valerio, da livello 2 a livello 1//
COPY "rick_bigg_mod/spell/SPWI201.spl" "override"
	SAY NAME1 "Blur"
	SAY UNIDENTIFIED_DESC 
"Blur
Level: 1
School: Illusion
Range: Personal
Duration: 5 turns
Casting Time: 1
Area of Effect: Caster
Saving Throw: None

A Blur spell causes the mage's form and spirit to become blurred, shifting and wavering. This distortion causes all melee and missile attacks against the caster to be made with -2 penalties, whereas all saves vs. breath are made by the caster with a +2 bonus. Multiple castings of this spell are not cumulative."





//DETECT ALIGNMENT //
COPY "rick_bigg_mod/spell/SPWI122.spl" "override"
	SAY NAME1 "Detect Alignment"
	SAY UNIDENTIFIED_DESC 
"Detect Alignment
Level: 1
School: Divination
Range: Personal
Duration: Instant
Casting Time: 1
Area of Effect: Special
Saving Throw: None

This spell allows the wizard to search out the feelings of all creatures within the current area. When affected by this spell, a target will briefly glow red if he's evil, green if he's good, and white if he's neutral. Magic resistance does not affect this spell."





//TRUE STRIKE//
COPY "rick_bigg_mod/spell/SPWI111.spl" "override"
	SAY NAME1 "True Strike"
	SAY UNIDENTIFIED_DESC 
"True Strike
Level: 1
School: Divination
Range: Medium
Duration: 5 rounds
Casting Time: 1
Area of Effect: 1 person
Saving Throw: None

This spell grants the creature touched otherworldly sight, resulting in preternatural accuracy for a short period. While the spell is in effect attack rolls are made with a +3 THAC0 bonus and the chance to score critical hits is increased by 5%."




//CHARM PERSON//
COPY "rick_bigg_mod/spell/SPWI104.spl" "override"
	SAY NAME1 "Charm Person"
	SAY UNIDENTIFIED_DESC 
"Charm Person
Level: 1
School: Enchantment
Range: Long
Duration: 5 rounds
Casting Time: 1
Area of Effect: 1 person
Saving Throw: Spell negates

Charm Person affects any single person it is cast upon. The term person includes any bipedal human, demihuman, or humanoid of man-size or smaller, such as dwarves, elves, gnolls, gnomes, half-elves, halflings, half-orcs, hobgoblins, humans, kobolds, and others. Thus, a 10th-level fighter could be charmed, but an ogre could not. If the recipient fails his saving throw vs. spell at +2 bonus (+1 bonus at 5th level and no bonus at 9th level), he regards the caster as a trusted friend and ally to be heeded and protected. The caster may give him orders, and the charmed creature will carry them out as quickly as possible.

If the caster harms, or attempts to harm, the charmed creature by some overt action, or if a dispel magic spell is successfully cast upon the charmed creature, the charm spell is broken. If two or more charm effects simultaneously affect a creature, the most recent charm takes precedence."



//REFLECTED IMAGE//
COPY "rick_bigg_mod/spell/SPWI120.spl" "override"
	SAY NAME1 "Reflected Image"
	SAY UNIDENTIFIED_DESC 
"Reflected Image
Level: 1
School: Illusion
Range: Personal
Duration: 3 rounds (4 rounds at 5th level, 5 rounds at 9th level)
Casting Time: 1
Area of Effect: Caster
Saving Throw: None

Upon casting this spell, the wizard creates one illusory image of himself that will travel alongside him. The image performs all of the actions that the wizard does, and seems to react normally to both physical and magical damage (such as appearing to be burned when hit by a fireball) so that if any enemies are trying to attack the wizard they will not know which one is real. There is a 50% chance that an attacker will attack the image and a 50% chance that he will attack the caster. If the image is struck, it is destroyed but it will be recreated after 6 seconds. The image is immune to all forms of damage, but will disappear if a dispel magic or a detect illusion spell is cast upon it, or when the spell duration runs out. This spell cannot be cast on anyone who is under the effects of a Mirror Image spell, and multiple castings of this spell will not create additional images."





//MALISON - icona e codice e scroll by Valerio//
COPY "rick_bigg_mod/spell/SPWI199.spl" "override"
	SAY NAME1 "Malison"
	SAY UNIDENTIFIED_DESC 
"Malison
Level: 1
School: Enchantment
Range: Long
Duration: 1 turn
Casting Time: 1
Area of Effect: 1 creature
Saving Throw: None

The spell allows the caster to adversely affect the saving throws of a target creature. Those under the influence of this spell make all their saving throws at a penalty of -2. Multiple castings of this spell are not cumulative."




//SHOCKING GRASP//
COPY "rick_bigg_mod/spell/SPWI115.spl" "override"
	SAY NAME1 "Shocking Grasp"
	SAY UNIDENTIFIED_DESC 
"Shocking Grasp
Level: 1
School: Invocation
Range: Personal
Duration: Special
Casting Time: 1
Area of Effect: 1 creature
Saving Throw: Special

When the wizard touches a creature while this spell is in effect, an electrical charge will deal 1d6 points of damage and stun the target for 1 round. If the target makes a successful saving throw vs. spell, he is not stunned. The spell expires once the caster makes a successful melee attack or after 1 turn has passed. The wizard gains a +4 bonus to hit the target.

At higher levels:
- the damage increases by 1d6 every two levels, up to 5d6 at 9th level
- the duration of the stun effect increases to 2 rounds at 5th and 3 rounds at 9th
"




//CHROMATIC ORB//
COPY "rick_bigg_mod/spell/SPWI118.spl" "override"
	SAY NAME1 "Chromatic Orb"
	SAY UNIDENTIFIED_DESC 
"Chromatic Orb
Level: 1
School: Transmutation
Range: Long
Duration: Special
Casting Time: 1
Area of Effect: 1 creature
Saving Throw: Special

This spell causes a 2-foot-diameter sphere to appear in the caster's hand. When thrown, the sphere heads unerringly towards its target. The sphere inflicts 1d3 magic damage and causes different effects depending upon its color. As the level of the caster improves the damage inflicted increases by 1d3 every two level (max 5d3 at 9th). The color of any given orb is chosen randomly. The orb is occasionally even multicolored, causing multiple effects. The victim can save against all special effects but gets no save against the damage. All special effects last for 5 rounds.

Orb colors:
Red: -3 penalty to saving throws and AC (save vs. spell negates)
Green: Poison 2hp/round (save vs. poison negates)
Yellow: Silence (save vs. spell negates)
Violet: Slow (save vs. polymorph negates)
Blue: Paralysis (save vs. paralysis negates)
"






//DIMENSION DOOR//
COPY "rick_bigg_mod/spell/SPWI121.spl" "override"
	SAY NAME1 "Dimension Door"
	SAY UNIDENTIFIED_DESC 
"Dimension Door
Level: 1
School: Generalist
Range: Personal
Duration: Instant
Casting Time: 1
Area of Effect: Caster
Saving Throw: None

This spell transports the caster to any place within sight. When the spell is cast, a dimensional portal opens up in front of the caster, which he immediately steps through. Upon passing through the portal, the caster finds himself at his chosen destination. The caster always arrives at exactly the spot desired, and the dimensional door doesn't allow anyone or anything else to pass through. Spells about to be cast upon the wizard will fail, and missiles about to hit him will instead hit thin air.
"




//FIND TRAPS//
COPY "rick_bigg_mod/spell/SPWI297.spl" "override"
	SAY NAME1 "Find Traps"
	SAY UNIDENTIFIED_DESC 
"Find Traps
Level: 1
School: Divination
Range: Personal
Duration: 5 turns
Casting Time: 1
Area of Effect: 30' radius
Saving Throw: None

When a wizard casts a find traps spell, all traps - concealed normally or magically - of magical or mechanical nature become apparent to him. Once per round, all traps within a 30 foot radius of the caster will be revealed. A trap is any device or magical ward that meets three criteria: it can inflict a sudden or unexpected result, the spellcaster would view the result as undesirable or harmful, and the creator specifically intended the harmful or undesirable result as such. Thus, traps include glyphs and similar spells or devices.
"