DEFINE_PATCH_FUNCTION add_cre_proficiency
	INT_VAR pips = 0
	STR_VAR proficiency = ""
BEGIN
	SET proficiency_code = IDS_OF_SYMBOL ("wprof" "%proficiency%")
	SET found = 0
    READ_LONG  0x2c4   eff_off
    READ_LONG  0x2c8   num_eff
	PATCH_IF num_eff > 0 THEN BEGIN
	  FOR (i=0; i<num_eff; i=i+1) BEGIN
		  READ_LONG eff_off + ((i * 264) + 0x08) "opcode"
		  READ_LONG eff_off + ((i * 264) + 0x18) "opcode_proficiency"
		  
		  PATCH_IF opcode = 233 AND opcode_proficiency = proficiency_code BEGIN
			SET found = 1
			WRITE_LONG eff_off + ((i * 264) + 0x14) pips
		  END
	  END
	END
	
	PATCH_IF NOT found BEGIN
		LAUNCH_PATCH_FUNCTION ADD_CRE_EFFECT
			INT_VAR opcode = 233
				timing = 9
				parameter1 = pips
				parameter2 = proficiency_code 
		END
	END
END
