
<<<<<<<< .../bhaalspawn-rules.2da
CHAPTER MAGIC_RESISTANCE REGENERATION_SEC DISEASE_IMMUNE POISON_IMMUNE NEW_GOOD_SPELL NEW_BAD_SPELL
2       5                18               0              0             SPIN101        SPIN104
3       10               15               0              0             TB#BA1G        SPIN105
4       15               12               1              0             TB#BA2G        SPIN106
5       20               9                1              0             TB#BA3G        TB#BA3E
6       25               6                1              0             TB#BA4G        TB#BA4E
7       30               3                1              1             TB#BA5G        TB#BA5E
>>>>>>>>

<<<<<<<< .../bhaalspawn-script.baf
IF
    HaveSpellRES("XXXg")
THEN RESPONSE #100
    ApplySpellRES("XXXg", Myself)
END

IF
    HaveSpellRES("XXXe")
THEN RESPONSE #100
    ApplySpellRES("XXXe", Myself)
END
>>>>>>>>

COPY_EXISTING ~SPPR103.spl~ ~override/SPIN101.spl~ // Cure Light Wounds
              ~SPPR201.spl~ ~override/TB#BA1G.spl~ // Aid
              ~SPPR315.spl~ ~override/TB#BA2G.spl~ // Cure Serious Wounds
              ~SPPR408.spl~ ~override/TB#BA3G.spl~ // Magic Circle Against Evil
              ~SPPR514.spl~ ~override/TB#BA4G.spl~ // Mass Cure
              ~SPPR612.spl~ ~override/TB#BA5G.spl~ // Bolt of Glory
              ~SPWI119.spl~ ~override/SPIN104.spl~ // Larloch's Minor Drain
              ~SPWI205.spl~ ~override/SPIN105.spl~ // Horror
              ~SPWI314.spl~ ~override/SPIN106.spl~ // Vampiric Bite
              ~SPPR416.spl~ ~override/TB#BA3E.spl~ // Cloak of Fear
              ~SPPR511.spl~ ~override/TB#BA4E.spl~ // Slay Kiving
              ~SPWI623.spl~ ~override/TB#BA5E.spl~ // Animake Skeleton Warrior
    WRITE_SHORT 0x1c 4 // innate
    WRITE_LONG  0x1e 0 // exclusions
    WRITE_LONG  0x34 1 // level
    GET_OFFSET_ARRAY ab_array SPL_V10_HEADERS
    PHP_EACH ab_array AS int => ab_off BEGIN
        WRITE_SHORT ab_off + 0x02 4 // ability
        WRITE_SHORT ab_off + 0x12 1 // casting time
    END
	READ_STRREF UNIDENTIFIED_DESC desc
	PATCH_IF ("%desc%" STRING_COMPARE_REGEXP ~<Invalid Strref -?[0-9]+>~) BEGIN // checking for valid content in string
		changed = 0
		INNER_PATCH_SAVE desc ~%desc%~ BEGIN
			PATCH_IF INDEX_BUFFER( ~^Level:[^%WNL%]*$~ ) > 0 BEGIN
				REPLACE_TEXTUALLY ~^Level:[^%WNL%]*[%WNL%]*~ ~~
				changed = 1
			END
			PATCH_IF INDEX_BUFFER( ~^Casting Time:[^%WNL%]*$~ ) > 0 BEGIN
				REPLACE_TEXTUALLY ~^Casting Time:[^%WNL%]*$~ ~Casting Time:1~
				changed = 1
			END
		END
		PATCH_IF changed BEGIN
			SAY_EVALUATED UNIDENTIFIED_DESC ~%desc%~
		END
	END

COPY - ~.../bhaalspawn-rules.2da~ ~.../bhaalspawn-rules.2da~
    READ_2DA_ENTRIES_NOW bhaalspawn_rules 1

OUTER_FOR (i = 0; i < 6; i += 1) BEGIN
    COPY - ~.../bhaalspawn-script.baf~ ~.../bhaalspawn-script-edit.baf~
        REPLACE_TEXTUALLY ~XXX~ ~tb#bh%i%~
    EXTEND_BOTTOM ~dplayer3.bcs~ ~.../bhaalspawn-script-edit.baf~

    OUTER_SET chapter = i + 2

    COPY_EXISTING ~drmtxt%chapter%.2da~ ~override~
        SET_2DA_ENTRY 4 1 3 ~tb#bh%i%g~
        SET_2DA_ENTRY 5 1 3 ~tb#bh%i%e~

    COPY ~rick_bigg_mod\spell\BLANK.SPL~ ~override/tb#bh%i%g.spl~
         ~rick_bigg_mod\spell\BLANK.SPL~ ~override/tb#bh%i%e.spl~
        FOR (j = 0; j < 6; j += 1) BEGIN
            LPF ADD_SPELL_EFFECT
                INT_VAR
                    opcode = 321 // remove by resource
                    target = 1
                    timing = 0
                STR_VAR
                    resource = EVALUATE_BUFFER ~tb#bh%j%g~
            END
            LPF ADD_SPELL_EFFECT
                INT_VAR
                    opcode = 321 // remove by resource
                    target = 1
                    timing = 0
                STR_VAR
                    resource = EVALUATE_BUFFER ~tb#bh%j%e~
            END
        END

        LPF ADD_SPELL_EFFECT
            INT_VAR
                opcode = 172 // remove spell
                target = 1
                timing = 0
            STR_VAR
                resource = EVALUATE_BUFFER ~tb#bh%i%g~
        END
        LPF ADD_SPELL_EFFECT
            INT_VAR
                opcode = 172 // remove spell
                target = 1
                timing = 0
            STR_VAR
                resource = EVALUATE_BUFFER ~tb#bh%i%e~
        END

        spell_column = 5
        PATCH_IF ~%DEST_RES%~ STRING_EQUAL_CASE ~TB#BH%i%E~ BEGIN
            spell_column = 6
        END

        FOR (j = 0; j <= i; j += 1) BEGIN
            READ_2DA_ENTRY_FORMER bhaalspawn_rules (j + 1) spell_column to_add
            LPF ADD_SPELL_EFFECT
                INT_VAR
                    opcode = 171 // give ability
                    target = 1
                    timing = 9
                STR_VAR
                    resource = EVALUATE_BUFFER ~%to_add%~
            END
        END

        READ_2DA_ENTRY_FORMER bhaalspawn_rules (i + 1) 1 magic_resistance
        READ_2DA_ENTRY_FORMER bhaalspawn_rules (i + 1) 2 regenerate_every
        READ_2DA_ENTRY_FORMER bhaalspawn_rules (i + 1) 3 immune_disease
        READ_2DA_ENTRY_FORMER bhaalspawn_rules (i + 1) 4 immune_poison

        LPF ADD_SPELL_EFFECT
            INT_VAR
                opcode = 166 // magic resistance
                parameter1 = magic_resistance
                target = 1
                timing = 9
        END

        LPF ADD_SPELL_EFFECT
            INT_VAR
                opcode = 142 // portrait icon
                parameter2 = 63 // magic resistance
                target = 1
                timing = 9
        END

        LPF ADD_SPELL_EFFECT
            INT_VAR
                opcode = 98 // regeneration
                parameter1 = regenerate_every
                parameter2 = 3
                target = 1
                timing = 9
        END

        LPF ADD_SPELL_EFFECT
            INT_VAR
                opcode = 142 // portrait icon
                parameter2 = 56 // regenerate
                target = 1
                timing = 9
        END

        PATCH_IF immune_disease BEGIN
            LPF ADD_SPELL_EFFECT
                INT_VAR
                    opcode = 101 // immunity to effect
                    parameter2 = 78 // disease
                    target = 1
                    timing = 9
            END

            LPF ADD_SPELL_EFFECT
                INT_VAR
                    opcode = 169 // immunity to icon
                    parameter2 = 7 // disease
                    target = 1
                    timing = 9
            END

            LPF ADD_SPELL_EFFECT
                INT_VAR
                    opcode = 206 // disable string
                    parameter1 = 54337 // diseased
                    target = 1
                    timing = 9
            END
            
            LPF ADD_SPELL_EFFECT
                INT_VAR
                    opcode = 206 // disable string
                    parameter1 = 39752 // diseased
                    target = 1
                    timing = 9
            END

            LPF ADD_SPELL_EFFECT
                INT_VAR
                    opcode = 206 // protection from spell
                    parameter1 = 0 - 1 // TEXT
                    target = 1
                    timing = 9
                STR_VAR resource = SPPR316 // Contagion
            END

            LPF ADD_SPELL_EFFECT
                INT_VAR
                    opcode = 206 // protection from spell
                    parameter1 = 0 - 1 // TEXT
                    target = 1
                    timing = 9
                STR_VAR resource = SPWI409 // Contagion
            END
        END

        PATCH_IF immune_poison BEGIN
            LPF ADD_SPELL_EFFECT
                INT_VAR
                    opcode = 173 // poison resistance
                    parameter1 = 100
                    target = 1
                    timing = 9
            END

            LPF ADD_SPELL_EFFECT
                INT_VAR
                    opcode = 101 // immunity to effect
                    parameter2 = 25 // poison
                    target = 1
                    timing = 9
            END

            LPF ADD_SPELL_EFFECT
                INT_VAR
                    opcode = 142 // display portrait icon
                    parameter2 = 30 // immunity to poison
                    target = 1
                    timing = 9
            END

            LPF ADD_SPELL_EFFECT
                INT_VAR
                    opcode = 169 // prevent portrait icon
                    parameter2 = 6 // poison
                    target = 1
                    timing = 9
            END

            LPF ADD_SPELL_EFFECT
                INT_VAR
                    opcode = 206 // protection from spell
                    parameter1 = 0 - 1 // TEXT
                    target = 1
                    timing = 9
                STR_VAR resource = SPPR411 // Poison
            END

            LPF ADD_SPELL_EFFECT
                INT_VAR
                    opcode = 206 // protection from spell
                    parameter1 = 0 - 1 // TEXT
                    target = 1
                    timing = 9
                STR_VAR resource = SPWI502 // Cloudkill
            END

            LPF ADD_SPELL_EFFECT
                INT_VAR
                    opcode = 206 // protection from spell
                    parameter1 = 0 - 1 // TEXT
                    target = 1
                    timing = 9
                STR_VAR resource = SPIN979 // Gas Cloud
            END

            LPF ADD_SPELL_EFFECT
                INT_VAR
                    opcode = 206 // disable string
                    parameter1 = 14017 // poison
                    target = 1
                    timing = 9
            END
            LPF ADD_SPELL_EFFECT
                INT_VAR
                    opcode = 206 // disable string
                    parameter1 = 14662 // poisoned
                    target = 1
                    timing = 9
            END
        END
END
