
//deletes the equipping effect the with specified opcode from the item. need parameters: opcode_to_delete
DEFINE_PATCH_FUNCTION ~DELETE_ITEM_EQEFFECT_BY_VALUES~ BEGIN
  PATCH_IF (BUFFER_LENGTH > 0x71) THEN BEGIN
    READ_LONG 0x64 ___#abil_off
    READ_SHORT 0x68 ___#abil_num
    READ_LONG 0x6a ___#fx_off
    READ_SHORT 0x6e ___#eqfx_off
    READ_SHORT 0x70 ___#eqfx_num
    FOR (___#index1 = 0 ; ___#index1 < ___#eqfx_num ; ___#index1 = ___#index1 + 1) BEGIN //cycle though global effects
	  ___#curoff = (___#fx_off + (___#index1 + ___#eqfx_off) * 0x30)
      READ_SHORT  ___#curoff ___#opcode
      READ_SHORT  ___#curoff + 0x04 ___#value1
      READ_SHORT  ___#curoff + 0x08 ___#value2
      PATCH_IF ( (___#opcode = opcode_to_delete) OR (opcode_to_delete = (0 - 1)) )
	       AND ( (___#value1 = value1_to_delete) OR (value1_to_delete = (0 - 1)) )
	       AND ( (___#value2 = value2_to_delete) OR (value2_to_delete = (0 - 1)) )
	  BEGIN

        DELETE_BYTES ___#curoff 0x30
        SET ___#eqfx_num = (___#eqfx_num - 1)
        WRITE_SHORT 0x70 ___#eqfx_num

        //correcting 1st effect indexes
        FOR (___#index2 = 0 ; ___#index2 < ___#abil_num ; ___#index2 = ___#index2 + 1) BEGIN
          READ_SHORT (___#abil_off + ___#index2 * 0x38 + 0x20) ___#1effect_index
          PATCH_IF (___#1effect_index > ___#index1) BEGIN //if abilility after current effect
            WRITE_SHORT (___#abil_off + ___#index2 * 0x38 + 0x20) (___#1effect_index - 1) //decrease 1 effect ___#index1 by 1
          END
        END
        //no offsets to correct
        SET ___#index1 = (___#index1 - 1)
      END
    END //end of searching
  END
END






DEFINE_PATCH_FUNCTION add_cre_proficiency
	INT_VAR pips = 0
	STR_VAR proficiency = ""
BEGIN
	SET proficiency_code = IDS_OF_SYMBOL ("wprof" "%proficiency%")
	SET found = 0
    READ_LONG  0x2c4   eff_off
    READ_LONG  0x2c8   num_eff
	PATCH_IF num_eff > 0 THEN BEGIN
	  FOR (i=0; i<num_eff; i=i+1) BEGIN
		  READ_LONG eff_off + ((i * 264) + 0x08) "opcode"
		  READ_LONG eff_off + ((i * 264) + 0x18) "opcode_proficiency"
		  
		  PATCH_IF opcode = 233 AND opcode_proficiency = proficiency_code BEGIN
			SET found = 1
			WRITE_LONG eff_off + ((i * 264) + 0x14) pips
		  END
	  END
	END
	
	PATCH_IF NOT found BEGIN
		LAUNCH_PATCH_FUNCTION ADD_CRE_EFFECT
			INT_VAR opcode = 233
				timing = 9
				parameter1 = pips
				parameter2 = proficiency_code 
		END
	END
END


