DEFINE_ACTION_FUNCTION duplicate_spell_change_save
	INT_VAR save_bonus = 0
	STR_VAR source_file = ~~
		destination_file = ~~
		destination_save = ~~
BEGIN
	ACTION_DEFINE_ASSOCIATIVE_ARRAY save_types BEGIN
		DEATH => BIT2
		POLYMORPH => BIT4
		BREATH => BIT1
		WAND => BIT3
		SPELL => BIT0
	END

	COPY_EXISTING ~%source_file%.spl~ ~override/%destination_file%.spl~
		SET all_save_flags = BIT0 BOR BIT1 BOR BIT2 BOR BIT3 BOR BIT4
	
		GET_OFFSET_ARRAY ab_array SPL_V10_HEADERS
		PHP_EACH ab_array AS int => ab_off BEGIN
			GET_OFFSET_ARRAY2 fx_array ab_off SPL_V10_HEAD_EFFECTS 
			PHP_EACH fx_array AS int => fx_off BEGIN
				READ_LONG fx_off + 0x24 save_flags
				PATCH_IF save_flags BAND all_save_flags BEGIN
					WRITE_LONG fx_off + 0x24 save_flags BAND BNOT all_save_flags BOR $save_types(~%destination_save%~)
					WRITE_LONG fx_off + 0x28 save_bonus
				END
			END
		END
END
