OUTER_SET ignore_ma = BIT10 BOR BIT29
OUTER_SET ignore_u1 = BIT0 BOR BIT1 BOR BIT2 BOR BIT3 BOR BIT4 BOR BIT5 BOR BIT6 BOR BIT7
OUTER_SET ignore_u2 = BIT0 BOR BIT1 BOR BIT3 BOR BIT5 BOR BIT6 BOR BIT7
OUTER_SET ignore_u3 = BIT7
OUTER_SET ignore_u4 = BIT2 BOR BIT3 BOR BIT4 BOR BIT5
OUTER_SET cleric_ranger = BIT7 BOR BIT21
OUTER_SET alignment = BIT0 BOR BIT1 BOR BIT2 BOR BIT3 BOR BIT4 BOR BIT5


DEFINE_PATCH_MACRO ~fix_unusabilities~ BEGIN
    PATCH_IF (LONG_AT 0x18 BAND BIT2) BEGIN
        // usable by trueclass fighters, not an armor or a shield
        PATCH_IF NOT (LONG_AT 0x1e BAND BIT11) AND NOT (BYTE_AT 0x2d BAND BIT6) AND NOT (SHORT_AT 0x1c == 12 OR SHORT_AT 0x1c == 2)  BEGIN
            // usable by Wizard Slayers
            WRITE_SHORT 0x2f (BYTE_AT 0x2f BAND (BNOT BIT1))
        END

        LAUNCH_PATCH_FUNCTION DELETE_ITEM_EQEFFECT_BY_VALUES INT_VAR opcode_to_delete = 319 value1_to_delete = 11 value2_to_delete = 5 END
        LAUNCH_PATCH_FUNCTION DELETE_ITEM_EQEFFECT_BY_VALUES INT_VAR opcode_to_delete = 319 value1_to_delete = 21 value2_to_delete = 5 END

        WRITE_BYTE 0x29 BYTE_AT 0x29 BAND BNOT ignore_u1
        WRITE_BYTE 0x2b BYTE_AT 0x2b BAND BNOT ignore_u2
        WRITE_BYTE 0x2d BYTE_AT 0x2d BAND BNOT ignore_u3
        WRITE_BYTE 0x2f BYTE_AT 0x2f BAND BNOT ignore_u4
        
        PATCH_IF (LONG_AT 0x1e BAND cleric_ranger) == cleric_ranger BEGIN
            WRITE_LONG 0x1e LONG_AT 0x1e BOR BIT10
        END ELSE PATCH_IF (BNOT LONG_AT 0x1e BAND cleric_ranger) == cleric_ranger BEGIN
            WRITE_LONG 0x1e LONG_AT 0x1e BAND BNOT BIT10
        END

        // Helmet-specific rules for droppable items (type 0x07)
        PATCH_IF (SHORT_AT 0x1c == 0x07) BEGIN
            // If Thief can't use it, but Fighter can, make it unusable by Fighter/Thief and Fighter/Mage/Thief
            PATCH_IF (LONG_AT 0x1e BAND BIT22) AND NOT (LONG_AT 0x1e BAND BIT11) BEGIN
                WRITE_LONG 0x1e LONG_AT 0x1e BOR BIT17 BOR BIT18
            END

            // If Thief can't use it, but Cleric can, make it unusable by Cleric
            PATCH_IF (LONG_AT 0x1e BAND BIT22) AND NOT (LONG_AT 0x1e BAND BIT15) BEGIN
                WRITE_LONG 0x1e LONG_AT 0x1e BOR BIT15
            END

            // If Mage can't use it, but Fighter can, make it unusable by Fighter/Mage, Fighter/Mage/Cleric, and Fighter/Mage/Thief
            PATCH_IF (LONG_AT 0x1e BAND BIT14) AND NOT (LONG_AT 0x1e BAND BIT11) BEGIN
                WRITE_LONG 0x1e LONG_AT 0x1e BOR BIT13 BOR BIT19 BOR BIT18
            END

            // If Druid can't use it, but Fighter can, make it unusable by Fighter/Druid
            PATCH_IF (LONG_AT 0x1e BAND BIT21) AND NOT (LONG_AT 0x1e BAND BIT11) BEGIN
                WRITE_LONG 0x1e LONG_AT 0x1e BOR BIT12
            END
        END
    END
END
