
// fix for bows/xbows/slings with nonsense Enchantment
COPY_EXISTING ~xbow03.itm~ ~override~
	WRITE_LONG 0x60 2



ACTION_BASH_FOR ~rick_bigg_mod/lib/items~ ~^.*\.tpa$~ BEGIN
	ACTION_IF ~%BASH_FOR_RES%~ STRING_EQUAL_CASE ~items_override~ BEGIN
		PRINT ~SKIP %BASH_FOR_FILESPEC%~
	END ELSE BEGIN
		PRINT ~EXECUTE %BASH_FOR_FILESPEC%~
		INCLUDE ~%BASH_FOR_FILESPEC%~
	END
END

INCLUDE ~rick_bigg_mod/lib/items/items_overwrite.tpa~







//MOONBLADE +3 - 0//
COPY "rick_bigg_mod/items/sw1h13.itm" "override"
	SAY NAME1 "Long Sword"
	SAY UNIDENTIFIED_DESC "These swords are usually referred to as double-edged swords, war swords, or military swords. In many cases, the long sword has a single-edged blade. There is no single version of the long sword; the design and length vary from culture to culture and may vary within the same culture depending on the era. Among the most common characteristics of all long swords is their length, which ranges from thirty-five inches to forty-seven inches. In the latter case, the blade is known to take up forty inches of the total length. Most long swords have a double-edged blade and a sharp point at the tip. Despite the tip, the long sword is designed for slashing, not thrusting.

STATISTICS:

Damage: 1d8 (slashing)
Speed Factor: 5
Proficiency Type: Long Sword
Type: One-handed
Requires:
 6 Strength

Weight: 4"

	SAY NAME2 "Moonblade +3"
	SAY DESC "This potent weapon was created by the smiths of ancient Myth Drannor. Moonblades are used in the long process of selecting a ruler for the isle of Evermeet. A moonblade chooses its owner, and in the case of this sword it has chosen the elf, Xan. Only Xan can use this blade; anyone else who tries will find themselves unable to lift it. This particular moonblade gives resistance to fire and a bonus to the user's Armor Class.

STATISTICS:

Equipped abilities:
– Armor Class: +1
- Saving Throws: +1
– Fire Resistance: +50%

THAC0: +3
Damage: 1d8+3 (slashing)
Speed Factor: 2
Proficiency Type: Long Sword
Type: One-handed

Weight: 3"






//OLD SLIPPERS - 0mo//
COPY "rick_bigg_mod/items/PLOT01P.itm" "override"
	SAY NAME1 "Old Slippers"
	SAY UNIDENTIFIED_DESC "It is a miracle that this moldy, misshapen footwear has not already dissolved into a pile of rancid dust.

STATISTICS:

Weight: 1"

	SAY NAME2 "Old Slippers"
	SAY DESC "It is a miracle that this moldy, misshapen footwear has not already dissolved into a pile of rancid dust.

STATISTICS:

Weight: 1"




//ALGERNON'S CLOACK - 500mo//
COPY "rick_bigg_mod/items/CLCK08.itm" "override"
	SAY NAME1 "Cloack"
	SAY UNIDENTIFIED_DESC "The cloak can be made in every possible shape with just about every type of fabric. The most common forms are a circular piece of fabric with a hole in the center for the head, and fabric draped from neck, connected by a chain, brooch, cord, or pins.

STATISTICS:

Weight: 3"

	SAY NAME2 "Algernon's Cloack"
	SAY DESC "This is the cloack of the fat man Algernon.
	
STATISTICS:

Weight: 3"







//DURLAG'S PRIDE - 0//
COPY "rick_bigg_mod/items/SW2H08_.itm" "override"
	SAY NAME1 "Two-Handed Sword"
	SAY UNIDENTIFIED_DESC "The two-handed sword is a derivative of the long sword. Weaponsmiths have always looked for ways to improve existing weapons. In an effort to improve the long sword, the blade was lengthened. Eventually, the handle had to be extended and two hands became necessary to properly swing the sword. The primary function of two-handed swords is cleaving mounted knights and breaking up pike formations.

STATISTICS:

Damage: 2d6 (slashing)
Speed Factor: 10
Proficiency Type: Two-handed Sword
Type: Two-handed
Requires:
 14 Strength

Weight: 15"

	SAY NAME2 "Durlag's Pride"
	SAY DESC "Durlag's Pride

STATISTICS:

Damage: 2d6 (slashing)
Speed Factor: 8
Proficiency Type: Two-handed Sword
Type: Two-handed
Requires:
 14 Strength

Weight: 15"






//CLOACK OF THE HIGH FOREST - 0//
COPY "rick_bigg_mod/items/NPCLCK.itm" "override"
	SAY NAME1 "Cloack"
	SAY UNIDENTIFIED_DESC "The cloak can be made in every possible shape with just about every type of fabric. The most common forms are a circular piece of fabric with a hole in the center for the head, and fabric draped from neck, connected by a chain, brooch, cord, or pins.

STATISTICS:

Weight: 3"

	SAY NAME2 "Cloack of the High Forest"
	SAY DESC "When younger, Cernd spent a cycle of seasons meditating on his role within nature. He made no shelter, wanting to feel the land unhindered. Nature may have appreciated the intent, for she also knows that for all their dedication, at times her children can be foolish. Cernd found this cloak before the cold season set in, seemingly woven to fit him from the very undergrowth. The message was clear: He can appreciate the rain while still seeking shelter from it. Only Cernd may use this cloak.

STATISTICS:

Equipped abilities:
– Armor Class: +2
– Saving Throws: +2
– Protects against critical hits

Weight: 3"










//RING OF WIZARDRY - 10000mo//
COPY "rick_bigg_mod/items/RING40.itm" "override"
	SAY NAME1 "Ring"
	SAY DESC "A ring is a small band of precious metal that is used as jewelry. Some rare rings have had enchantments placed upon them that confer various magical abilities. These rings are highly sought after, especially by those of the adventuring profession.

STATISTICS:

Weight: 0"

	SAY NAME2 "Ring of Wizardry"
	SAY DESC "The origins of this ring are unclear, and while its enchantments share similarities with historical examples of Rings of Wizardry, there is something strange in how it feels, either in the weight of the metal or in the aura it projects, and it does not function the same. It was likely found on some distant plane and, as such, its maker will remain a mystery to you.

STATISTICS:

Equipped abilities:
– The wearer can memorize 1 extra spell per level

Weight: 0"




//RING OF HUMAN INFLUENCE - 2500mo//
COPY "rick_bigg_mod/items/RING30.itm" "override"
	SAY NAME1 "Ring"
	SAY DESC "A ring is a small band of precious metal that is used as jewelry. Some rare rings have had enchantments placed upon them that confer various magical abilities. These rings are highly sought after, especially by those of the adventuring profession.

STATISTICS:

Weight: 0"

	SAY NAME2 "Ring of Human Influence"
	SAY DESC "For seven years, Count Fisfnilt searched the realms for a suitable bride for his son Ewnin. Unfortunately, all the women that Fisfnilt found were not up to the standards set by Ewnin, an impossibly spoiled man. Desiring an heir and impatient with his son, the Count had the court mage fashion this ring. He gifted the ring to a woman of no small courtly influence and Ewnin was instantly smitten. They wed three weeks later.

STATISTICS:

Equipped abilities:
– Charisma +1

Charge abilities:
– Charm Person once per day (Save vs. Spell negates)
  Range: 60 ft.
  Duration: 100 seconds
  Area of Effect: 1 creature

Weight: 0"






//RING OF INFRAVISION - 1500mo//
COPY "rick_bigg_mod/items/RING21.itm" "override"
	SAY NAME1 "Ring"
	SAY DESC "A ring is a small band of precious metal that is used as jewelry. Some rare rings have had enchantments placed upon them that confer various magical abilities. These rings are highly sought after, especially by those of the adventuring profession.

STATISTICS:

Weight: 0"

	SAY NAME2 "Ring of Infravision"
	SAY DESC "Merchants that dare the risks of trading with the drow of the Great Rift are often given these items to aid in their movements underground. 

STATISTICS:

Equipped abilities:
– Infravision up to 120 ft.
- +1 THAC0

Weight: 0"

























//RING OF CLUMSINESS - 1500mo//
COPY "rick_bigg_mod/items/RING04.itm" "override"
	SAY NAME1 "Ring"
	SAY UNIDENTIFIED_DESC "A ring is a small band of precious metal that is used as jewelry. Some rare rings have had enchantments placed upon them that confer various magical abilities. These rings are highly sought after, especially by those of the adventuring profession.

STATISTICS:

Weight: 0"

	SAY NAME2 "Ring of Clumsiness"
	SAY DESC "The most notorious owner of this ring made a substantial living exploiting its cursed nature. Gregoria the Foole, a Jester by trade, would use his incomparable sleight of hand to switch this ring with that of a patsy taken from his audience. The rest of his performance would involve the mocking of the newly clumsy individual, much to the delight of their comrades. The ring was removed (by a method known only to the wily Jester) only once the stooge had promised no reprisals for the treatment he had received, though Gregoria frequently still had to make a hasty retreat. What he didn't know was that the ring also held hidden abilities, which were revealed by an angry mage during her final performance at Zhentil Keep... 


STATISTICS:

Equipped abilities:
– Dexterity: -50% penalty
– May only be removed with a Remove Curse spell

Charge abilities twice a day:
- Lighting Bolt (level 10) three times per day

Weight: 0"






//RING OF FOLLY - 4000mo//
COPY "rick_bigg_mod/items/RING23.itm" "override"
	SAY NAME1 "Ring"
	SAY UNIDENTIFIED_DESC "A ring is a small band of precious metal that is used as jewelry. Some rare rings have had enchantments placed upon them that confer various magical abilities. These rings are highly sought after, especially by those of the adventuring profession.

STATISTICS:

Weight: 0"

SAY NAME2 "Ring of Folly"
	SAY DESC "Oft the bane of the careless mage, this ring was actually used to promote humility. Hergat Norin, a grand wizard of Narfell, would give the this ring, also known as Discipliner,to his most skilled and most lazy students. Drastically weakening their learning abilities, the ring required all their willpower to unleash its true potential.

STATISTICS:

Equipped abilities:
– Intelligence: -50% penalty
- Casting level: -2
- Casting speed: +2
- The wearer can memorize one more spell per level

– May only be removed with a Remove Curse spell

Weight: 0 " 








//XZAR'S RING OF MENTAL DEFENCE - 0//
COPY "rick_bigg_mod/items/X#XZRING.itm" "override"
	SAY NAME1 "Ring"
	SAY UNIDENTIFIED_DESC "A ring is a small band of precious metal that is used as jewelry. Some rare rings have had enchantments placed upon them that confer various magical abilities. These rings are highly sought after, especially by those of the adventuring profession.

STATISTICS:

Weight: 0"


	SAY NAME2 "Xzar's Ring of Mental Defence"
	SAY DESC "This is the ring that Xzar covets. Enchanted with the blood of a murdered dryad, this ring protects the wearer against Charm Person spells and boosts Saving Throws against all Enchantment spells. It also enables the wearer to cast Dire Charm once per day.

STATISTICS:

Equipped Abilities:
- Immunity to Charm Person
– AC bonus: +2
- Saving Throws bonus: +2

Charge Abilities:
- Cast Dire Charm once per day

Weight: 0" 







//JAHEIRA'S GIRDLE - 0//
COPY "rick_bigg_mod/items/BDBELT02.itm" "override"
	SAY NAME1 "Girdle"
	SAY UNIDENTIFIED_DESC "Girdles are generally similar to belts. Unlike belts, girdles are not used to hold up pants and dungarees, but to carry pouches, scabbards, and the like. 

STATISTICS:

Weight: 2"


	SAY NAME2 "Jaheira's Girdle"
	SAY DESC "This is Jaheira's Girdle, a legacy from her druid masters. It will protect her in the quest for balance.

STATISTICS:

Equipped abilities:
– Protects against critical hits
- Armor Class: +1
- Saving Throws: +1

Weight: 2" 






//MYR'CUTIO'S BARDIC CHAIN +1 - 0//
COPY "rick_bigg_mod/items/X#GARCH.itm" "override"
	SAY NAME1 "Chain Mail"
	SAY UNIDENTIFIED_DESC "Chain mail is made of interlocking metal rings. It is always worn over a layer of padded fabric or soft leather to prevent chafing and lessen the impact of blows. 

STATISTICS:

Armor Class: 5 (3 vs. slashing, 7 vs. crushing)
Requires:
 8 Strength

Weight: 40"


	SAY NAME2 "Myr'Cutio's Bardic Chain +1"
	SAY DESC "This bardic chainmail has an illustrious past, being the armor of the noted half-elven bard Myr'Cutio. He wandered the Realms seeking adventure, and so restless was his nature that on his death his spirit, and those of his companions, continued to roam...

Until they were put to rest by the party of <CHARNAME>, that is. Adventurers tend not to have respect for noteworthy figures of the past. Still, the armor is yours: lightweight, shiny and stylish. What more could Garrick hope for?

STATISTICS:

Equipped abilities:
- Armor Class: 4 (2 vs. slashing, 6 vs. crushing)
- Does not interfere with arcane spellcasting

Requires: 8 Strength

Weight: 20" 





//MYR'CUTIO'S BARDIC CHAIN +2 - 0//
COPY "rick_bigg_mod/items/X#GARCH2.itm" "override"
	SAY NAME1 "Chain Mail"
	SAY UNIDENTIFIED_DESC "Chain mail is made of interlocking metal rings. It is always worn over a layer of padded fabric or soft leather to prevent chafing and lessen the impact of blows. 

STATISTICS:

Armor Class: 5 (3 vs. slashing, 7 vs. crushing)
Requires:
 8 Strength

Weight: 40"


	SAY NAME2 "Myr'Cutio's Bardic Chain +2"
	SAY DESC "This bardic chainmail has an illustrious past, being the armor of the noted half-elven bard Myr'Cutio. He wandered the Realms seeking adventure, and so restless was his nature that on his death his spirit, and those of his companions, continued to roam...

Until they were put to rest by the party of <CHARNAME>, that is. Adventurers tend not to have respect for noteworthy figures of the past. Still, the armor is yours: lightweight, shiny and stylish. What more could Garrick hope for?

This armor was further improved by Halbazzer Drin of the Sorcerous Sundries store in Baldur's Gate. Combination with a pair of golden pantaloons has afforded an increased measure of protection, while keeping the suit as fashionable as ever.

STATISTICS:

Equipped abilities:
- Armor Class: 3 (1 vs. slashing, 5 vs. crushing)
- Does not interfere with arcane spellcasting

Requires: 7 Strength

Weight: 15" 






//ILVASTARR FAMILY SHIELD +1 - 0//
COPY "rick_bigg_mod/items/x#ajshld.itm" "override"
	SAY NAME1 "Medium Shield"
	SAY UNIDENTIFIED_DESC "A medium shield is carried in the same manner as a small shield.  Its weight prevents the character from using his shield hand for anything other than carrying the medium shield.  Medium shields are usually made of metal, range from 3'-4' in diameter, and can be of any shape, from round to square to a spread dragon's wings.  A typical medieval shield resembles a triangle with one point facing downward.

STATISTICS:

Equipped abilities:
– Armor Class: +1

Requires:
 12 Strength

Weight: 7"


	SAY NAME2 "Ilvastarr Family Shield +1"
	SAY DESC "This is Ajantis' family shield. It shows the coat of arms of the noble Ilvastarr family of Waterdeep. It was specifically enchanted to protect the knight from bandits' arrows.

STATISTICS:

Equipped Abilties:
- Armor Class: +2, an extra +2 vs. missile attacks

Requires:
 12 Strength

Weight: 7"






//HANDMAIDEN'S MACE +4 - 0//
COPY "rick_bigg_mod/items/HLOLTH.itm" "override"
	SAY NAME1 "Mace"
	SAY UNIDENTIFIED_DESC "The mace is a direct descendant of the basic club, being nothing more than a wooden shaft with a stone or iron head mounted on the end. The head design varies: Some are spiked, others flanged, and still others have pyramidal knobs.

STATISTICS:

Damage: 1d6+1 (crushing)
Speed Factor: 7
Proficiency Type: Mace
Type: One-handed
Requires:
 10 Strength

Weight: 10"

	SAY NAME2 "Handmaiden's Mace +4"
	SAY DESC "This mace has been crafted finely by the drow and specially treated to survive the glare of the sun. It was made for surface raids by the subterranean race... and its black metal glistens with a dark poison that seems to be generated from within and causes incredible damage upon a successful impact.

The mace seems almost alive and warm to the touch, and slithers away from those whom it does not like... namely drow or those who are similar enough to not make a difference. In the hands of anyone else, the mace becomes mere dead weight.

STATISTICS:

Equipped abilities:
- Magic Resistance: +10%

Combat abilities:
– Hit target must save vs. Poison -4 or suffer 2 points of damage per round for 1 turn

THAC0: +4
Damage: 1d6+5 (crushing)
Speed Factor: 4
Proficiency Type: Mace
Type: One-handed
Requires:
 9 Strength

Weight: 5"






//ARROW OF BITING//
COPY "rick_bigg_mod/items/AROW05.itm" "override"
	SAY NAME1 "Arrow"
	SAY UNIDENTIFIED_DESC "The flight arrow, as its name implies, is built for distance. These are lightweight arrows and are often used for hunting. Most of these arrows are made of ash or birch and are thirty to forty inches long.

STATISTICS:

Damage: 1d6 (missile)
Launcher: Bow

Weight: 0"


	SAY NAME2 "Arrow of Biting"
	SAY DESC "The Arrow of Biting was designed as a deadly compliment to the archer. Poison smeared on the barbed arrowhead infiltrates the bloodstream of its victims, causing agony and often death.

STATISTICS:

Combat abilities:
– Target must save vs. Death or take 30 points of poison damage in 15 seconds

Damage: 1d6 (missile)
Launcher: Bow

Weight: 0" 




//ARROW OF BITING//
COPY "rick_bigg_mod/items/AROW12.itm" "override"
	SAY NAME1 "Arrow"
	SAY UNIDENTIFIED_DESC "The flight arrow, as its name implies, is built for distance. These are lightweight arrows and are often used for hunting. Most of these arrows are made of ash or birch and are thirty to forty inches long.

STATISTICS:

Damage: 1d6 (missile)
Launcher: Bow

Weight: 0"


	SAY NAME2 "Arrow of Biting"
	SAY DESC "The Arrow of Biting was designed as a deadly compliment to the archer. Poison smeared on the barbed arrowhead infiltrates the bloodstream of its victims, causing agony and often death.

STATISTICS:

Combat abilities:
– Target must save vs. Death or take 30 points of poison damage in 15 seconds

Damage: 1d6 (missile)
Launcher: Bow

Weight: 0" 




//ELDOTH'S POISONED ARROW//
COPY "rick_bigg_mod/items/AROW14.itm" "override"
	SAY NAME1 "Arrow"
	SAY UNIDENTIFIED_DESC "The flight arrow, as its name implies, is built for distance. These are lightweight arrows and are often used for hunting. Most of these arrows are made of ash or birch and are thirty to forty inches long.

STATISTICS:

Damage: 1d6 (missile)
Launcher: Bow

Weight: 0"


	SAY NAME2 "Eldoth's Poisoned Arrow"
	SAY DESC "These are Eldoth's personal poisoned arrows. He learned how to use poison at a young age and can create enough venom for about 5 arrows per day. He is the only person who can safely handle these arrows.

STATISTICS:

Combat abilities:
– Hit target takes 1 point of poison damage every 3 seconds for 40 seconds (Save vs. Poison negates)

Damage: 1d6 (missile)
Launcher: Bow

Weight: 0" 






//ARROW OF ACID//
COPY "rick_bigg_mod/items/AROW04.itm" "override"
	SAY NAME1 "Arrow"
	SAY UNIDENTIFIED_DESC "The flight arrow, as its name implies, is built for distance. These are lightweight arrows and are often used for hunting. Most of these arrows are made of ash or birch and are thirty to forty inches long.

STATISTICS:

Damage: 1d6 (missile)
Launcher: Bow

Weight: 0"


	SAY NAME2 "Arrow of Acid"
	SAY DESC "This enchanted arrow coated in acid. When it strikes an enemy, it not only pierces flesh but also eats it away, enlarging and deepening the wound.

STATISTICS:

Damage: 1d6, +1d6 acid damage
Damage type: Missile
Launcher: Bow

Weight: 0" 









//ARROW OF DETONATION//
COPY "rick_bigg_mod/items/AROW06.itm" "override"
	SAY NAME1 "Arrow"
	SAY UNIDENTIFIED_DESC "The flight arrow, as its name implies, is built for distance. These are lightweight arrows and are often used for hunting. Most of these arrows are made of ash or birch and are thirty to forty inches long.

STATISTICS:

Damage: 1d6 (missile)
Launcher: Bow

Weight: 0"


	SAY NAME2 "Arrow of Detonation"
	SAY DESC "This arrow doesn't physically harm the target, but upon impact, it explodes into a huge ball of fire and shrapnel affecting all within the area.

STATISTICS:

Damage: 0d6, 3d6 explosion upon impact
Damage type: Missile
Launcher: Bow

Weight: 0" 




//ARROW OF PIERCING//
COPY "rick_bigg_mod/items/AROW10.itm" "override"
	SAY NAME1 "Arrow"
	SAY UNIDENTIFIED_DESC "The flight arrow, as its name implies, is built for distance. These are lightweight arrows and are often used for hunting. Most of these arrows are made of ash or birch and are thirty to forty inches long.

STATISTICS:

Damage: 1d6 (missile)
Launcher: Bow

Weight: 0"


	SAY NAME2 "Arrow of Piercing"
	SAY DESC "This arrow is long and thin, imbued with magical properties that allow it to push itself through armor, striking out towards the heart of the victim.

STATISTICS:

THAC0: +4
Damage: 1d6, +6 piercing damage (Save vs. Death for none)
Damage type: Missile
Launcher: Bow

Weight: 0" 




//ARROW OF FIRE//
COPY "rick_bigg_mod/items/AROW08.itm" "override"
	SAY NAME1 "Arrow"
	SAY UNIDENTIFIED_DESC "The flight arrow, as its name implies, is built for distance. These are lightweight arrows and are often used for hunting. Most of these arrows are made of ash or birch and are thirty to forty inches long.

STATISTICS:

Damage: 1d6 (missile)
Launcher: Bow

Weight: 0"


	SAY NAME2 "Arrow of Fire"
	SAY DESC "This is a magical arrow that will burst into flames as it is fired at an enemy. The effect is similar to an arrow doused in oil and set to flame.

STATISTICS:

Damage: 1d6, +1d6 fire damage
Damage type: Missile
Launcher: Bow

Weight: 0" 







//ARROW OF FIRE//
COPY "rick_bigg_mod/items/AROWKC.itm" "override"
	SAY NAME1 "Arrow"
	SAY UNIDENTIFIED_DESC "The flight arrow, as its name implies, is built for distance. These are lightweight arrows and are often used for hunting. Most of these arrows are made of ash or birch and are thirty to forty inches long.

STATISTICS:

Damage: 1d6 (missile)
Launcher: Bow

Weight: 0"


	SAY NAME2 "Arrow of Fire"
	SAY DESC "This is a magical arrow that will burst into flames as it is fired at an enemy. The effect is similar to an arrow doused in oil and set to flame.

STATISTICS:

Damage: 1d6, +1d6 fire damage
Damage type: Missile
Launcher: Bow

Weight: 0" 





//ARROW OF ICE//
COPY "rick_bigg_mod/items/AROW09.itm" "override"
	SAY NAME1 "Arrow"
	SAY UNIDENTIFIED_DESC "The flight arrow, as its name implies, is built for distance. These are lightweight arrows and are often used for hunting. Most of these arrows are made of ash or birch and are thirty to forty inches long.

STATISTICS:

Damage: 1d6 (missile)
Launcher: Bow

Weight: 0"


	SAY NAME2 "Arrow of Ice"
	SAY DESC "This arrow is magically enhanced so as to burst into a rolling ball of ice and cold when fired. When the arrow strikes its victim, a shock of cold will travel through its body, both burning and numbing to the very core.

STATISTICS:

Damage: 1d6, +1d8 cold damage
Damage type: Missile
Launcher: Bow

Weight: 0" 



//BOLT OF LIGHTNING//
COPY "rick_bigg_mod/items/BOLT03.itm" "override"
	SAY NAME1 "Bolt"
	SAY UNIDENTIFIED_DESC "Quarrels or bolts are the ammunition fired by crossbows regardless of the weapon's size.

STATISTICS:

Damage: 1d8 (missile)
Launcher: Crossbow

Weight: 0"


	SAY NAME2 "Bolt of Lightning"
	SAY DESC "This bolt seems to crackle with energy as it is held in the hand. When shot from the crossbow, it seems to leap towards its target, leaving behind an electrical sulfuric smell. As it hits, there is a crackle as the energy stored is released into the target's wound.

STATISTICS:

Damage: 1d8, +4d4 electrical damage (Save vs. Breath for half)
Damage type: Missile
Launcher: Crossbow

Weight: 0" 








//PARALYTIC BOLT//
COPY "rick_bigg_mod/items/BOLT05.itm" "override"
	SAY NAME1 "Bolt"
	SAY UNIDENTIFIED_DESC "Quarrels or bolts are the ammunition fired by crossbows regardless of the weapon's size.

STATISTICS:

Damage: 1d8 (missile)
Launcher: Crossbow

Weight: 0"


	SAY NAME2 "Paralytic Bolt"
	SAY DESC "Any target hit by this bolt must make a Saving Throw or be paralyzed for 5 rounds.

STATISTICS:

Combat abilities:
– Hit target must save vs. Paralyzation or be stunned for 5 rounds

Damage: 1d8 (missile)
Launcher: Crossbow

Weight: 0"

