INCLUDE ~rick_bigg_mod/lib/change_itm_icon.tpa~



ACTION_BASH_FOR ~rick_bigg_mod/lib/items~ ~^.*\.tpa$~ BEGIN
	ACTION_IF ~%BASH_FOR_RES%~ STRING_EQUAL_CASE ~items_override~ BEGIN
		PRINT ~SKIP %BASH_FOR_FILESPEC%~
	END ELSE BEGIN
		PRINT ~EXECUTE %BASH_FOR_FILESPEC%~
		INCLUDE ~%BASH_FOR_FILESPEC%~
	END
END

INCLUDE ~rick_bigg_mod/lib/items/items_overwrite.tpa~







//KIEL'S BUCKLER +2 - 4000mo//
COPY "rick_bigg_mod/items/SHLD20.itm" "override"
	SAY NAME1 "Buckler"
	SAY UNIDENTIFIED_DESC "A buckler, also known as a target shield, is a small round shield of wood or metal that fastens to the forearm. Because of its size, it is light and can be worn with very little restriction to movement.

STATISTICS:

Equipped abilities:
– Armor Class: +1
– No protection against missile and piercing attacks

Requires:
 4 Strength

Weight: 2"

	SAY NAME2 "Kiel's Buckler +2"
	SAY DESC "This is the buckler of Kiel the Legion Killer, firstborn son of Durlag Trollkiller and Clan-prince of his father's ill-fated tower. Its light weight and excellent craftsmanship increase the Dexterity of all who bear it by a single point.

STATISTICS:

Equipped abilities:
– Dexterity: +1
– Armor Class: +3
– No protection against missile and piercing attacks

Requires:
 4 Strength

Weight: 2
"






//THE PRACTICAL DEFENSE + 2 - 7500mo//
COPY "rick_bigg_mod/items/PLAT08.itm" "override"
	SAY NAME1 "Plate Mail"
	SAY UNIDENTIFIED_DESC "Plate mail is a combination of chain armor with metal plates covering the vital areas such as the chest, abdomen, and groin. Similar in construction to bronze plate mail, true plate mail comprises chain and leather.

STATISTICS:

Armor Class: 3 (0 vs. slashing)
Requires:
 12 Strength

Weight: 50"

	SAY NAME2 "The Practical Defense +3"
	SAY DESC %
The traveling adventurer could ask for no better a suit of armor in all the land. Specially commissioned by Bolhur "Thunderaxe" at GREAT expense, this suit was his most prized, even if not his most ornate. Eminently practical, Bolhur demanded armor that would offer superior protection while hampering him in the least. By "hampering" he did not just mean in movement or weight, though this suit is just over one-third the weight of normal plate mail: His ideal suit should also be able to withstand the rigors of his wanderings with little maintenance. This is not to say that Bolhur "Thunderaxe" neglected his armors (to say as such would get your ears boxed) but the regime of spit and polish required for a "gentleman's" suit was beyond his caring. Save the tassels and gilding of full plate for kings and heads of state; a working dwarf cares more for utility than looks.

STATISTICS:

Equipped abilities:
- +1 Charisma

Armor Class: 0 (-3 vs. slashing)

Requires:
 11 Strength

Weight: 18
%



//MOONBLADE +3 - 0//
COPY "rick_bigg_mod/items/sw1h13.itm" "override"
	SAY NAME1 "Long Sword"
	SAY UNIDENTIFIED_DESC "These swords are usually referred to as double-edged swords, war swords, or military swords. In many cases, the long sword has a single-edged blade. There is no single version of the long sword; the design and length vary from culture to culture and may vary within the same culture depending on the era. Among the most common characteristics of all long swords is their length, which ranges from thirty-five inches to forty-seven inches. In the latter case, the blade is known to take up forty inches of the total length. Most long swords have a double-edged blade and a sharp point at the tip. Despite the tip, the long sword is designed for slashing, not thrusting.

STATISTICS:

Damage: 1d8 (slashing)
Speed Factor: 5
Proficiency Type: Long Sword
Type: One-handed
Requires:
 6 Strength

Weight: 4"

	SAY NAME2 "Moonblade +3"
	SAY DESC "This potent weapon was created by the smiths of ancient Myth Drannor. Moonblades are used in the long process of selecting a ruler for the isle of Evermeet. A moonblade chooses its owner, and in the case of this sword it has chosen the elf, Xan. Only Xan can use this blade; anyone else who tries will find themselves unable to lift it. This particular moonblade gives resistance to fire and a bonus to the user's Armor Class.

STATISTICS:

Equipped abilities:
– Armor Class: +1
- Saving Throws: +1
– Fire Resistance: +50%

THAC0: +3
Damage: 1d8+3 (slashing)
Speed Factor: 2
Proficiency Type: Long Sword
Type: One-handed

Weight: 3"










//CLOAK OF BALDURAN - 12000mo//
COPY "rick_bigg_mod/items/CLCK05.itm" "override"
	SAY NAME1 "Cloak"
	SAY UNIDENTIFIED_DESC "The cloak can be made in every possible shape with just about every type of fabric. The most common forms are a circular piece of fabric with a hole in the center for the head, and fabric draped from neck, connected by a chain, brooch, cord, or pins.

STATISTICS:

Weight: 3"

	SAY NAME2 "Cloak of Balduran"
	SAY DESC "This cloak was reputedly worn by Balduran, the founder of Baldur's Gate. Though it was never used in combat, it provides protection worthy of any great leader.

STATISTICS:

Equipped abilities:
– Armor Class: +1
– Saving Throws: +1
– Magic Resistance: +20%

Weight: 3"








//RAINBOW AMULET - 4500mo//
COPY "rick_bigg_mod/items/AMUL18.itm" "override"
	SAY NAME1 "Amulet"
	SAY UNIDENTIFIED_DESC "Amulets are usually magical devices that are commonly worn around the neck, suspended from a chain. The type of chain that comes with an amulet generally increases the item's aesthetic value, not its magical properties. Only one amulet can be dangled from the neck at a time.

STATISTICS:

Weight: 1"


	SAY NAME2 "Rainbow Amulet"
	SAY DESC "The story goes that Evander Delight, an extravagant gold prospector from Sembia, followed every rainbow tail, convinced he'd find the legendary pot of gold. He never reached the end of any rainbow, and, of course, never found any pot of gold, but during his traveling he found this amulet next to the corpse of an old gypsy woman. Since then, he became one of the richest men in the region, and no one dared mock him again.

STATISTICS:

Equipped abilities:
– Saving Throws vs Breath: +2
– Luck +2

Weight: 1"









//PELLAN'S SHIELD +2 - 4500mo//
COPY "rick_bigg_mod/items/SHLD19A.itm" "override"
	SAY NAME1 "Large Shield"
	SAY UNIDENTIFIED_DESC "	A large shield inlaid with a golden griffin. This shield, also known as the kite or tower shield, is a massive metal shield reaching nearly from the chin to the toe of the user. It must be firmly fastened to the forearm and the shield hand must firmly grip it at all times. Naturally, this precludes use of the shield hand for anything but holding the body shield in place. Strangely enough, this shield feels unusually light for its size.

STATISTICS:

Equipped abilities:
– Armor Class: +1, an extra +1 vs. missile attacks

Requires:
 10 Strength

Weight: 4"

	SAY NAME2 "Pellan's Shield +2"
	SAY DESC "This dwarven-made shield was commissioned by Pellan of Tyr, a brash paladin known for unquestioning courage and an almost total lack of common sense. Upon hearing that a red dragon was ravaging the countryside, Pellan mounted his horse and rode off to do battle. As it happened, Pellan and his armor digested readily enough, but the shield gave the dragon severe stomach cramps. Subsequently coughed up, it lay in a hoard for years until retrieved by Pellan's son, a warrior who knew when to sneak.

Superior craftsmanship is supplemented by a permanent lightness spell, which makes the shield very easy to wield.

STATISTICS:

Equipped abilities:
– Armor Class: +3, an extra +1 vs. missile attacks
- Attack Speed Factor: +2

Requires:
 10 Strength

Weight: 4"






//PELLAN'S SHIELD +2 - 4500mo//
COPY "rick_bigg_mod/items/SHLD19.itm" "override"
	SAY NAME1 "Large Shield"
	SAY UNIDENTIFIED_DESC "	A large shield inlaid with a golden griffin. This shield, also known as the kite or tower shield, is a massive metal shield reaching nearly from the chin to the toe of the user. It must be firmly fastened to the forearm and the shield hand must firmly grip it at all times. Naturally, this precludes use of the shield hand for anything but holding the body shield in place. Strangely enough, this shield feels unusually light for its size.

STATISTICS:

Equipped abilities:
– Armor Class: +1, an extra +1 vs. missile attacks

Requires:
 10 Strength

Weight: 4"

	SAY NAME2 "Pellan's Shield +2"
	SAY DESC "This dwarven-made shield was commissioned by Pellan of Tyr, a brash paladin known for unquestioning courage and an almost total lack of common sense. Upon hearing that a red dragon was ravaging the countryside, Pellan mounted his horse and rode off to do battle. As it happened, Pellan and his armor digested readily enough, but the shield gave the dragon severe stomach cramps. Subsequently coughed up, it lay in a hoard for years until retrieved by Pellan's son, a warrior who knew when to sneak.

Superior craftsmanship is supplemented by a permanent lightness spell, which makes the shield very easy to wield.

STATISTICS:

Equipped abilities:
– Armor Class: +3, an extra +1 vs. missile attacks
- Attack Speed Factor: +2

Requires:
 10 Strength

Weight: 4"




//DURLAG'S PRIDE - 0//
COPY "rick_bigg_mod/items/SW2H08_.itm" "override"
	SAY NAME1 "Two-Handed Sword"
	SAY UNIDENTIFIED_DESC "The two-handed sword is a derivative of the long sword. Weaponsmiths have always looked for ways to improve existing weapons. In an effort to improve the long sword, the blade was lengthened. Eventually, the handle had to be extended and two hands became necessary to properly swing the sword. The primary function of two-handed swords is cleaving mounted knights and breaking up pike formations.

STATISTICS:

Damage: 2d6 (slashing)
Speed Factor: 10
Proficiency Type: Two-handed Sword
Type: Two-handed
Requires:
 14 Strength

Weight: 15"

	SAY NAME2 "Durlag's Pride"
	SAY DESC "Durlag's Pride

STATISTICS:

Damage: 2d6 (slashing)
Speed Factor: 8
Proficiency Type: Two-handed Sword
Type: Two-handed
Requires:
 14 Strength

Weight: 15"






//CLOACK OF THE HIGH FOREST - 0//
COPY "rick_bigg_mod/items/NPCLCK.itm" "override"
	SAY NAME1 "Cloack"
	SAY UNIDENTIFIED_DESC "The cloak can be made in every possible shape with just about every type of fabric. The most common forms are a circular piece of fabric with a hole in the center for the head, and fabric draped from neck, connected by a chain, brooch, cord, or pins.

STATISTICS:

Weight: 3"

	SAY NAME2 "Cloack of the High Forest"
	SAY DESC "When younger, Cernd spent a cycle of seasons meditating on his role within nature. He made no shelter, wanting to feel the land unhindered. Nature may have appreciated the intent, for she also knows that for all their dedication, at times her children can be foolish. Cernd found this cloak before the cold season set in, seemingly woven to fit him from the very undergrowth. The message was clear: He can appreciate the rain while still seeking shelter from it. Only Cernd may use this cloak.

STATISTICS:

Equipped abilities:
– Armor Class: +2
– Saving Throws: +2
– Protects against critical hits

Weight: 3"






//RING OF WIZARDRY - 10000mo//
COPY "rick_bigg_mod/items/RING40.itm" "override"
	SAY NAME1 "Ring"
	SAY DESC "A ring is a small band of precious metal that is used as jewelry. Some rare rings have had enchantments placed upon them that confer various magical abilities. These rings are highly sought after, especially by those of the adventuring profession.

STATISTICS:

Weight: 0"

	SAY NAME2 "Ring of Wizardry"
	SAY DESC "The origins of this ring are unclear, and while its enchantments share similarities with historical examples of Rings of Wizardry, there is something strange in how it feels, either in the weight of the metal or in the aura it projects, and it does not function the same. It was likely found on some distant plane and, as such, its maker will remain a mystery to you.

STATISTICS:

Equipped abilities:
– The wearer can memorize 1 extra spell per level

Weight: 0"




//RING OF HUMAN INFLUENCE - 2500mo//
COPY "rick_bigg_mod/items/RING30.itm" "override"
	SAY NAME1 "Ring"
	SAY DESC "A ring is a small band of precious metal that is used as jewelry. Some rare rings have had enchantments placed upon them that confer various magical abilities. These rings are highly sought after, especially by those of the adventuring profession.

STATISTICS:

Weight: 0"

	SAY NAME2 "Ring of Human Influence"
	SAY DESC "For seven years, Count Fisfnilt searched the realms for a suitable bride for his son Ewnin. Unfortunately, all the women that Fisfnilt found were not up to the standards set by Ewnin, an impossibly spoiled man. Desiring an heir and impatient with his son, the Count had the court mage fashion this ring. He gifted the ring to a woman of no small courtly influence and Ewnin was instantly smitten. They wed three weeks later.

STATISTICS:

Equipped abilities:
– Charisma +1

Charge abilities:
– Charm Person once per day (Save vs. Spell negates)
  Range: 60 ft.
  Duration: 100 seconds
  Area of Effect: 1 creature

Weight: 0"






//RING OF INFRAVISION - 1500mo//
COPY "rick_bigg_mod/items/RING21.itm" "override"
	SAY NAME1 "Ring"
	SAY DESC "A ring is a small band of precious metal that is used as jewelry. Some rare rings have had enchantments placed upon them that confer various magical abilities. These rings are highly sought after, especially by those of the adventuring profession.

STATISTICS:

Weight: 0"

	SAY NAME2 "Ring of Infravision"
	SAY DESC "Merchants that dare the risks of trading with the drow of the Great Rift are often given these items to aid in their movements underground. 

STATISTICS:

Equipped abilities:
– Infravision up to 120 ft.
- +1 THAC0

Weight: 0"




















//CLOACK OF THE WOLF - valore 5000mo//
COPY "rick_bigg_mod/items/CLCK04.itm" "override"
	SAY NAME1 "Cloack"
	SAY UNIDENTIFIED_DESC "The cloak can be made in every possible shape with just about every type of fabric. The most common forms are a circular piece of fabric with a hole in the center for the head, and fabric draped from neck, connected by a chain, brooch, cord, or pins.

STATISTICS:

Weight: 3"

	SAY NAME2 "Cloack of the Wolf"
	SAY DESC "A great amount of irony surrounds the creation of this magical cloak. Relair was a mage who overestimated the amount of control he had over magic, and in the course of creating this garment, he apparently inflicted lycanthropy upon himself. The wearer can change form whenever <PRO_HESHE> wishes. Relair was not so lucky.

STATISTICS:

Charge abilities:
– Polymorph into a Werewolf once per day

Weight: 3"







//SHIELD AMULET - 1250mo//
COPY "rick_bigg_mod/items/AMUL15.itm" "override"
	SAY NAME1 "Amulet"
	SAY UNIDENTIFIED_DESC "Amulets are usually magical devices that are commonly worn around the neck, suspended from a chain. The type of chain that comes with an amulet generally increases the item's aesthetic value, not its magical properties. Only one amulet can be dangled from the neck at a time.

STATISTICS:

Weight: 1"

	SAY NAME2 "Shield Amulet"
	SAY DESC "This amulet can be activated by a simple command word and a touch once per day. The effect is a duplication of the 1st-level wizard spell Shield.

STATISTICS:

Charge abilities:
– Shield once per day

Weight: 1"






//EVERYMEMORY - 5000mo//
COPY "rick_bigg_mod/items/AMUL16.itm" "override"
	SAY NAME1 "Amulet"
	SAY UNIDENTIFIED_DESC "Amulets are usually magical devices that are commonly worn around the neck, suspended from a chain. The type of chain that comes with an amulet generally increases the item's aesthetic value, not its magical properties. Only one amulet can be dangled from the neck at a time.

STATISTICS:

Weight: 1"

	SAY NAME2 "Everymemory"
	SAY DESC "Long ago, a grand wizard from Amn was rumored to have defied Mystra's limitations on the magical arts. Legends spoke of this wizard being able to cast spells without the limitation of memorization. In the end it was found that his powers stemmed from the several magical amulets that he had made for himself. His proclaimed Everlasting Memory was a hoax, though his rings continue to be one of the most sought after items in the realms.

STATISTICS:

Equipped abilities:
– Can memorize double the amount of 1st-level wizard spells

Weight: 1"





//THE ONE GIFT LOST - 2500mo//
COPY "rick_bigg_mod/items/AMUL01.itm" "override"
	SAY NAME1 "Necklace"
	SAY UNIDENTIFIED_DESC "A necklace is a piece of ornamental metal jewelry usually made of silver, gold, platinum, or other precious metal, and adorned with gems. A necklace is always worn on the neck and can be of any length.

STATISTICS:

Weight: 1"


	SAY NAME2 "The One Gift Lost"
	SAY DESC "The naming of this necklace originates from its only owner, Ikaida Mourneve, who quested to regain his kidnapped daughter. Not many would help the determined father, but a kind and generous mage bestowed this item on him to aid his cause. Alas, the necklace was lost when Ikaida dropped it into the Immerflow River while fending off bandits upon a suspension bridge. Fortunately, it is rumored that the item was not needed to reunite the family once again. 

STATISTICS:

Charge abilities:
– Missile Blast once per day
  Damage: 6d6 fire (Save vs. Spell for half)
  Range: 50 ft.
  Area of Effect: 15-ft. radius

Weight: 1" 




//ALGERNON'S CLOACK - 500mo//
COPY "rick_bigg_mod/items/CLCK08.itm" "override"
	SAY NAME1 "Cloack"
	SAY UNIDENTIFIED_DESC "The cloak can be made in every possible shape with just about every type of fabric. The most common forms are a circular piece of fabric with a hole in the center for the head, and fabric draped from neck, connected by a chain, brooch, cord, or pins.

STATISTICS:

Weight: 3"

	SAY NAME2 "Algernon's Cloack"
	SAY DESC "This is the cloack of the fat man Algernon.
	
STATISTICS:

Weight: 3"




//BRACERS OF FRENZY - 4000mo//
COPY "rick_bigg_mod/items/BRAC11.itm" "override"
	SAY NAME1 "Bracers"
	SAY UNIDENTIFIED_DESC "Bracers are thick bands of metal or leather that are strapped, belted, or tied to a character's forearm.

STATISTICS:

Weight: 2"

	SAY NAME2 "Bracers of Frenzy"
	SAY DESC "These bracers are reserved for the most formidable drow warriors. Once worn, the hands can move at unimaginable speed, but this comes at the expense of accuracy and defense. Over the centuries, many drow warriors have died in battle, overconfident in their ability to wield these powerful artifacts.

STATISTICS:

Equipped abilities:
- One extra attack per round
– Armor Class: -3 penalty
- Thac0: -3 penalty

Weight: 1"



//BRACERS OF UNDEAD CONTROL - 2500mo//
COPY "rick_bigg_mod/items/BRAC08.itm" "override"
	SAY NAME1 "Bracers"
	SAY UNIDENTIFIED_DESC "Gauntlets are armored gloves. They can be made of leather, metal plates, or chain mail. Every suit of armor is assumed to include gauntlets of an appropriate type. Magical gauntlets tend to be finer, lighter, and more easily worn than normal varieties.

STATISTICS:

Weight: 2"

	SAY NAME2 "Bracers of Undead Control"
	SAY DESC "These powerful gauntlets were created by the clerics of Myrkul of Kagarr, intent on controlling an undead horde destabilizing the region. The bracers draw their power from the wearer's sanity, completely detaching them from reality, yet granting them the power to sympathize with the undead.


STATISTICS:

Equipped abilities:
– Wisdom: -3 penalty
- Turn Undead: +3 cleric level


Weight: 0"





//ARMOR OF MISSILE ATTRACTION +2 - 2500mo//
COPY "rick_bigg_mod/items/LEAT06.itm" "override"
	SAY NAME1 "Studded Leather Armor"
	SAY UNIDENTIFIED_DESC "Studded leather armor has little in common with normal leather armor. Instead of a hardened shell, studded leather offers hundreds of metal rivets affixed to a supple backing. The numerous studs form a flexible coat of metal that helps to turn aside slashing and cutting attacks, while the leather is little more than a means of securing the rivets in place. 

STATISTICS:

Armor Class: 7 (5 vs. slashing, 6 vs. piercing and missile)
Requires:
 6 Strength

Weight: 25"

	SAY NAME2 "Armor of Missile Attraction +2"
	SAY DESC "This odd-looking suit of studded leather cannot be removed once put on, except under intervention by a priest. While improving a great protection against all melee weapons, this armor actually becomes a target for missile weapons, and hence so does its wearer. The choice is simple: deadly arrows or deadly swords. 

STATISTICS:

Equipped abilities:
– May only be removed with a Remove Curse spell
– Crushing Damage Resistance: +10%
– Slashing Damage Resistance: +10%
– Piercing Damage Resistance: +10%

Armor Class: 5 (3 vs. slashing, 4 vs. piercing, 15 vs. missile)
Requires:
 6 Strength

Weight: 8"




//RING OF CLUMSINESS - 1500mo//
COPY "rick_bigg_mod/items/RING04.itm" "override"
	SAY NAME1 "Ring"
	SAY UNIDENTIFIED_DESC "A ring is a small band of precious metal that is used as jewelry. Some rare rings have had enchantments placed upon them that confer various magical abilities. These rings are highly sought after, especially by those of the adventuring profession.

STATISTICS:

Weight: 0"

	SAY NAME2 "Ring of Clumsiness"
	SAY DESC "The most notorious owner of this ring made a substantial living exploiting its cursed nature. Gregoria the Foole, a Jester by trade, would use his incomparable sleight of hand to switch this ring with that of a patsy taken from his audience. The rest of his performance would involve the mocking of the newly clumsy individual, much to the delight of their comrades. The ring was removed (by a method known only to the wily Jester) only once the stooge had promised no reprisals for the treatment he had received, though Gregoria frequently still had to make a hasty retreat. What he didn't know was that the ring also held hidden abilities, which were revealed by an angry mage during her final performance at Zhentil Keep... 


STATISTICS:

Equipped abilities:
– Dexterity: -50% penalty
– May only be removed with a Remove Curse spell

Charge abilities twice a day:
- Lighting Bolt (level 10) three times per day

Weight: 0"






//RING OF FOLLY - 4000mo//
COPY "rick_bigg_mod/items/RING23.itm" "override"
	SAY NAME1 "Ring"
	SAY UNIDENTIFIED_DESC "A ring is a small band of precious metal that is used as jewelry. Some rare rings have had enchantments placed upon them that confer various magical abilities. These rings are highly sought after, especially by those of the adventuring profession.

STATISTICS:

Weight: 0"

SAY NAME2 "Ring of Folly"
	SAY DESC "Oft the bane of the careless mage, this ring was actually used to promote humility. Hergat Norin, a grand wizard of Narfell, would give the this ring, also known as Discipliner,to his most skilled and most lazy students. Drastically weakening their learning abilities, the ring required all their willpower to unleash its true potential.

STATISTICS:

Equipped abilities:
– Intelligence: -50% penalty
- Worsens caster level by 2
- Improves casting speed by 2
- The wearer can memorize one more spell per level

– May only be removed with a Remove Curse spell

Weight: 0 " 








//XZAR'S RING OF MENTAL DEFENCE - 0//
COPY "rick_bigg_mod/items/X#XZRING.itm" "override"
	SAY NAME1 "Ring"
	SAY UNIDENTIFIED_DESC "A ring is a small band of precious metal that is used as jewelry. Some rare rings have had enchantments placed upon them that confer various magical abilities. These rings are highly sought after, especially by those of the adventuring profession.

STATISTICS:

Weight: 0"


	SAY NAME2 "Xzar's Ring of Mental Defence"
	SAY DESC "This is the ring that Xzar covets. Enchanted with the blood of a murdered dryad, this ring protects the wearer against Charm Person spells and boosts Saving Throws against all Enchantment spells. It also enables the wearer to cast Dire Charm once per day.

STATISTICS:

Equipped Abilities:
- Immunity to Charm Person
– AC bonus: +2
- Saving Throws bonus: +2

Charge Abilities:
- Cast Dire Charm once per day

Weight: 0" 



//JAHEIRA'S GIRDLE - 0//
COPY "rick_bigg_mod/items/BDBELT02.itm" "override"
	SAY NAME1 "Girdle"
	SAY UNIDENTIFIED_DESC "Girdles are generally similar to belts. Unlike belts, girdles are not used to hold up pants and dungarees, but to carry pouches, scabbards, and the like. 

STATISTICS:

Weight: 2"


	SAY NAME2 "Jaheira's Girdle"
	SAY DESC "This is Jaheira's Girdle, a legacy from her druid masters. It will protect her in the quest for balance.

STATISTICS:

Equipped abilities:
– Protects against critical hits
- Armor Class: +1
- Saving Throws: +1

Weight: 2" 




//MYR'CUTIO'S BARDIC CHAIN +1 - 0//
COPY "rick_bigg_mod/items/X#GARCH.itm" "override"
	SAY NAME1 "Chain Mail"
	SAY UNIDENTIFIED_DESC "Chain mail is made of interlocking metal rings. It is always worn over a layer of padded fabric or soft leather to prevent chafing and lessen the impact of blows. 

STATISTICS:

Armor Class: 5 (3 vs. slashing, 7 vs. crushing)
Requires:
 8 Strength

Weight: 40"


	SAY NAME2 "Myr'Cutio's Bardic Chain +1"
	SAY DESC "This bardic chainmail has an illustrious past, being the armor of the noted half-elven bard Myr'Cutio. He wandered the Realms seeking adventure, and so restless was his nature that on his death his spirit, and those of his companions, continued to roam...

Until they were put to rest by the party of <CHARNAME>, that is. Adventurers tend not to have respect for noteworthy figures of the past. Still, the armor is yours: lightweight, shiny and stylish. What more could Garrick hope for?

STATISTICS:

Equipped abilities:
- Armor Class: 4 (2 vs. slashing, 6 vs. crushing)
- Does not interfere with arcane spellcasting

Requires: 8 Strength

Weight: 20" 





//MYR'CUTIO'S BARDIC CHAIN +2 - 0//
COPY "rick_bigg_mod/items/X#GARCH2.itm" "override"
	SAY NAME1 "Chain Mail"
	SAY UNIDENTIFIED_DESC "Chain mail is made of interlocking metal rings. It is always worn over a layer of padded fabric or soft leather to prevent chafing and lessen the impact of blows. 

STATISTICS:

Armor Class: 5 (3 vs. slashing, 7 vs. crushing)
Requires:
 8 Strength

Weight: 40"


	SAY NAME2 "Myr'Cutio's Bardic Chain +2"
	SAY DESC "This bardic chainmail has an illustrious past, being the armor of the noted half-elven bard Myr'Cutio. He wandered the Realms seeking adventure, and so restless was his nature that on his death his spirit, and those of his companions, continued to roam...

Until they were put to rest by the party of <CHARNAME>, that is. Adventurers tend not to have respect for noteworthy figures of the past. Still, the armor is yours: lightweight, shiny and stylish. What more could Garrick hope for?

This armor was further improved by Halbazzer Drin of the Sorcerous Sundries store in Baldur's Gate. Combination with a pair of golden pantaloons has afforded an increased measure of protection, while keeping the suit as fashionable as ever.

STATISTICS:

Equipped abilities:
- Armor Class: 3 (1 vs. slashing, 5 vs. crushing)
- Does not interfere with arcane spellcasting

Requires: 7 Strength

Weight: 15" 






//ILVASTARR FAMILY SHIELD +1 - 0//
COPY "rick_bigg_mod/items/x#ajshld.itm" "override"
	SAY NAME1 "Medium Shield"
	SAY UNIDENTIFIED_DESC "A medium shield is carried in the same manner as a small shield.  Its weight prevents the character from using his shield hand for anything other than carrying the medium shield.  Medium shields are usually made of metal, range from 3'-4' in diameter, and can be of any shape, from round to square to a spread dragon's wings.  A typical medieval shield resembles a triangle with one point facing downward.

STATISTICS:

Equipped abilities:
– Armor Class: +1

Requires:
 12 Strength

Weight: 7"


	SAY NAME2 "Ilvastarr Family Shield +1"
	SAY DESC "This is Ajantis' family shield. It shows the coat of arms of the noble Ilvastarr family of Waterdeep. It was specifically enchanted to protect the knight from bandits' arrows.

STATISTICS:

Equipped Abilties:
- Armor Class: +2, an extra +2 vs. missile attacks

Requires:
 12 Strength

Weight: 7"






//HANDMAIDEN'S MACE +4 - 0//
COPY "rick_bigg_mod/items/HLOLTH.itm" "override"
	SAY NAME1 "Mace"
	SAY UNIDENTIFIED_DESC "The mace is a direct descendant of the basic club, being nothing more than a wooden shaft with a stone or iron head mounted on the end. The head design varies: Some are spiked, others flanged, and still others have pyramidal knobs.

STATISTICS:

Damage: 1d6+1 (crushing)
Speed Factor: 7
Proficiency Type: Mace
Type: One-handed
Requires:
 10 Strength

Weight: 10"

	SAY NAME2 "Handmaiden's Mace +4"
	SAY DESC "This mace has been crafted finely by the drow and specially treated to survive the glare of the sun. It was made for surface raids by the subterranean race... and its black metal glistens with a dark poison that seems to be generated from within and causes incredible damage upon a successful impact.

The mace seems almost alive and warm to the touch, and slithers away from those whom it does not like... namely drow or those who are similar enough to not make a difference. In the hands of anyone else, the mace becomes mere dead weight.

STATISTICS:

Equipped abilities:
- Magic Resistance: +10%

Combat abilities:
– Hit target must save vs. Poison -4 or suffer 2 points of damage per round for 1 turn

THAC0: +4
Damage: 1d6+5 (crushing)
Speed Factor: 4
Proficiency Type: Mace
Type: One-handed
Requires:
 9 Strength

Weight: 5"












//ARROW OF BITING//
COPY "rick_bigg_mod/items/AROW05.itm" "override"
	SAY NAME1 "Arrow"
	SAY UNIDENTIFIED_DESC "The flight arrow, as its name implies, is built for distance. These are lightweight arrows and are often used for hunting. Most of these arrows are made of ash or birch and are thirty to forty inches long.

STATISTICS:

Damage: 1d6 (missile)
Launcher: Bow

Weight: 0"


	SAY NAME2 "Arrow of Biting"
	SAY DESC "The Arrow of Biting was designed as a deadly compliment to the archer. Poison smeared on the barbed arrowhead infiltrates the bloodstream of its victims, causing agony and often death.

STATISTICS:

Combat abilities:
– Target must save vs. Death or take 30 points of poison damage in 15 seconds

Damage: 1d6 (missile)
Launcher: Bow

Weight: 0" 




//ARROW OF BITING//
COPY "rick_bigg_mod/items/AROW12.itm" "override"
	SAY NAME1 "Arrow"
	SAY UNIDENTIFIED_DESC "The flight arrow, as its name implies, is built for distance. These are lightweight arrows and are often used for hunting. Most of these arrows are made of ash or birch and are thirty to forty inches long.

STATISTICS:

Damage: 1d6 (missile)
Launcher: Bow

Weight: 0"


	SAY NAME2 "Arrow of Biting"
	SAY DESC "The Arrow of Biting was designed as a deadly compliment to the archer. Poison smeared on the barbed arrowhead infiltrates the bloodstream of its victims, causing agony and often death.

STATISTICS:

Combat abilities:
– Target must save vs. Death or take 30 points of poison damage in 15 seconds

Damage: 1d6 (missile)
Launcher: Bow

Weight: 0" 




//ELDOTH'S POISONED ARROW//
COPY "rick_bigg_mod/items/AROW14.itm" "override"
	SAY NAME1 "Arrow"
	SAY UNIDENTIFIED_DESC "The flight arrow, as its name implies, is built for distance. These are lightweight arrows and are often used for hunting. Most of these arrows are made of ash or birch and are thirty to forty inches long.

STATISTICS:

Damage: 1d6 (missile)
Launcher: Bow

Weight: 0"


	SAY NAME2 "Eldoth's Poisoned Arrow"
	SAY DESC "These are Eldoth's personal poisoned arrows. He learned how to use poison at a young age and can create enough venom for about 5 arrows per day. He is the only person who can safely handle these arrows.

STATISTICS:

Combat abilities:
– Hit target takes 1 point of poison damage every 3 seconds for 40 seconds (Save vs. Poison negates)

Damage: 1d6 (missile)
Launcher: Bow

Weight: 0" 






//ARROW OF ACID//
COPY "rick_bigg_mod/items/AROW04.itm" "override"
	SAY NAME1 "Arrow"
	SAY UNIDENTIFIED_DESC "The flight arrow, as its name implies, is built for distance. These are lightweight arrows and are often used for hunting. Most of these arrows are made of ash or birch and are thirty to forty inches long.

STATISTICS:

Damage: 1d6 (missile)
Launcher: Bow

Weight: 0"


	SAY NAME2 "Arrow of Acid"
	SAY DESC "This enchanted arrow coated in acid. When it strikes an enemy, it not only pierces flesh but also eats it away, enlarging and deepening the wound.

STATISTICS:

Damage: 1d6, +1d6 acid damage
Damage type: Missile
Launcher: Bow

Weight: 0" 









//ARROW OF DETONATION//
COPY "rick_bigg_mod/items/AROW06.itm" "override"
	SAY NAME1 "Arrow"
	SAY UNIDENTIFIED_DESC "The flight arrow, as its name implies, is built for distance. These are lightweight arrows and are often used for hunting. Most of these arrows are made of ash or birch and are thirty to forty inches long.

STATISTICS:

Damage: 1d6 (missile)
Launcher: Bow

Weight: 0"


	SAY NAME2 "Arrow of Detonation"
	SAY DESC "This arrow doesn't physically harm the target, but upon impact, it explodes into a huge ball of fire and shrapnel affecting all within the area.

STATISTICS:

Damage: 0d6, 3d6 explosion upon impact
Damage type: Missile
Launcher: Bow

Weight: 0" 




//ARROW OF PIERCING//
COPY "rick_bigg_mod/items/AROW10.itm" "override"
	SAY NAME1 "Arrow"
	SAY UNIDENTIFIED_DESC "The flight arrow, as its name implies, is built for distance. These are lightweight arrows and are often used for hunting. Most of these arrows are made of ash or birch and are thirty to forty inches long.

STATISTICS:

Damage: 1d6 (missile)
Launcher: Bow

Weight: 0"


	SAY NAME2 "Arrow of Piercing"
	SAY DESC "This arrow is long and thin, imbued with magical properties that allow it to push itself through armor, striking out towards the heart of the victim.

STATISTICS:

THAC0: +4
Damage: 1d6, +6 piercing damage (Save vs. Death for none)
Damage type: Missile
Launcher: Bow

Weight: 0" 




//ARROW OF FIRE//
COPY "rick_bigg_mod/items/AROW08.itm" "override"
	SAY NAME1 "Arrow"
	SAY UNIDENTIFIED_DESC "The flight arrow, as its name implies, is built for distance. These are lightweight arrows and are often used for hunting. Most of these arrows are made of ash or birch and are thirty to forty inches long.

STATISTICS:

Damage: 1d6 (missile)
Launcher: Bow

Weight: 0"


	SAY NAME2 "Arrow of Fire"
	SAY DESC "This is a magical arrow that will burst into flames as it is fired at an enemy. The effect is similar to an arrow doused in oil and set to flame.

STATISTICS:

Damage: 1d6, +1d6 fire damage
Damage type: Missile
Launcher: Bow

Weight: 0" 







//ARROW OF FIRE//
COPY "rick_bigg_mod/items/AROWKC.itm" "override"
	SAY NAME1 "Arrow"
	SAY UNIDENTIFIED_DESC "The flight arrow, as its name implies, is built for distance. These are lightweight arrows and are often used for hunting. Most of these arrows are made of ash or birch and are thirty to forty inches long.

STATISTICS:

Damage: 1d6 (missile)
Launcher: Bow

Weight: 0"


	SAY NAME2 "Arrow of Fire"
	SAY DESC "This is a magical arrow that will burst into flames as it is fired at an enemy. The effect is similar to an arrow doused in oil and set to flame.

STATISTICS:

Damage: 1d6, +1d6 fire damage
Damage type: Missile
Launcher: Bow

Weight: 0" 





//ARROW OF ICE//
COPY "rick_bigg_mod/items/AROW09.itm" "override"
	SAY NAME1 "Arrow"
	SAY UNIDENTIFIED_DESC "The flight arrow, as its name implies, is built for distance. These are lightweight arrows and are often used for hunting. Most of these arrows are made of ash or birch and are thirty to forty inches long.

STATISTICS:

Damage: 1d6 (missile)
Launcher: Bow

Weight: 0"


	SAY NAME2 "Arrow of Ice"
	SAY DESC "This arrow is magically enhanced so as to burst into a rolling ball of ice and cold when fired. When the arrow strikes its victim, a shock of cold will travel through its body, both burning and numbing to the very core.

STATISTICS:

Damage: 1d6, +1d8 cold damage
Damage type: Missile
Launcher: Bow

Weight: 0" 



//BOLT OF LIGHTNING//
COPY "rick_bigg_mod/items/BOLT03.itm" "override"
	SAY NAME1 "Bolt"
	SAY UNIDENTIFIED_DESC "Quarrels or bolts are the ammunition fired by crossbows regardless of the weapon's size.

STATISTICS:

Damage: 1d8 (missile)
Launcher: Crossbow

Weight: 0"


	SAY NAME2 "Bolt of Lightning"
	SAY DESC "This bolt seems to crackle with energy as it is held in the hand. When shot from the crossbow, it seems to leap towards its target, leaving behind an electrical sulfuric smell. As it hits, there is a crackle as the energy stored is released into the target's wound.

STATISTICS:

Damage: 1d8, +4d4 electrical damage (Save vs. Breath for half)
Damage type: Missile
Launcher: Crossbow

Weight: 0" 








//PARALYTIC BOLT//
COPY "rick_bigg_mod/items/BOLT05.itm" "override"
	SAY NAME1 "Bolt"
	SAY UNIDENTIFIED_DESC "Quarrels or bolts are the ammunition fired by crossbows regardless of the weapon's size.

STATISTICS:

Damage: 1d8 (missile)
Launcher: Crossbow

Weight: 0"


	SAY NAME2 "Paralytic Bolt"
	SAY DESC "Any target hit by this bolt must make a Saving Throw or be paralyzed for 5 rounds.

STATISTICS:

Combat abilities:
– Hit target must save vs. Paralyzation or be stunned for 5 rounds

Damage: 1d8 (missile)
Launcher: Crossbow

Weight: 0"



















 
//ORC LEATHER +3//
COPY "rick_bigg_mod/items/LEAT16.itm" "override"
	SAY NAME1 "Studded Leather Armor"
	SAY UNIDENTIFIED_DESC "Studded leather armor has little in common with normal leather armor. Instead of a hardened shell, studded leather offers hundreds of metal rivets affixed to a supple backing. The numerous studs form a flexible coat of metal that helps to turn aside slashing and cutting attacks, while the leather is little more than a means of securing the rivets in place. 

STATISTICS:

Armor Class: 7 (5 vs. slashing, 6 vs. piercing and missile)
Requires:
 6 Strength

Weight: 25"

	SAY NAME2 "Orc Leather +3"
	SAY DESC "This ghastly armor was taken from an orc camp destroyed by barbarians. Instead of standard metal rivets, like normal studded leather, this orc leather is instead laced with hundreds of fire-hardened bones. Finger bones, ribs, and skulls cover the armor, acting much like the traditional metal rivets. Powerful orcish enchantments give the armor special resistance to missile  and piercing attacks, but the repulsiveness of the armor reduces the wearer's Charisma.

STATISTICS:

Equipped abilities:
– Charisma: -1
– +10% resistance to missile damage
– +10% resistance to piercing damage

Armor Class: 4 (2 vs. slashing, 3 vs. piercing and missile)
Requires:
 6 Strength

Weight: 7"

























//HAWKSIGHT +2//
COPY "rick_bigg_mod/items/OHRSW1H1.itm" "override"
	SAY NAME1 "Scimitar"
	SAY UNIDENTIFIED_DESC "The long, curved, single-edged blade is characteristic of both the saber and the scimitar, even though their origins lie in different parts of Faerûn. Whereas the saber was intended chiefly for horsemen, mainly due to its versatility, the scimitar has a heavier oriental influence. The 'shamshir', as it was originally called, is larger, more highly curved, and tapered to an elongated, sharp point. This makes the weapon slightly slower but more effective and deadly in combat.

STATISTICS:

Damage: 1d8+1 (slashing)
Speed Factor: 5
Proficiency Type: Scimitar/Wakizashi/Ninjatō
Type: One-handed
Requires:
 10 Strength

Weight: 4"

	SAY NAME2 "Hawksight +2"
	SAY DESC "This scimitar has been magically enhanced to give it greater accuracy in combat. Any wielder who picks up the sword immediately feels their senses becoming keener, their reflexes sharper.

STATISTICS:

Equipped abilities:
– Dexterity: +1
- Thac0: +1

THAC0: +2
Damage: 1d8+3 (slashing)
Speed Factor: 3
Proficiency Type: Scimitar/Wakizashi/Ninjatō
Type: One-handed
Requires:
 10 Strength

Weight: 3"





//DERVISH CRESCENT +2//
COPY "rick_bigg_mod/items/BDSW1H08.itm" "override"
	SAY NAME1 "Scimitar"
	SAY UNIDENTIFIED_DESC "The long, curved, single-edged blade is characteristic of both the saber and the scimitar, even though their origins lie in different parts of Faerûn. Whereas the saber was intended chiefly for horsemen, mainly due to its versatility, the scimitar has a heavier oriental influence. The 'shamshir', as it was originally called, is larger, more highly curved, and tapered to an elongated, sharp point. This makes the weapon slightly slower but more effective and deadly in combat.

STATISTICS:

Damage: 1d8+1 (slashing)
Speed Factor: 5
Proficiency Type: Scimitar/Wakizashi/Ninjatō
Type: One-handed
Requires:
 10 Strength

Weight: 4"

	SAY NAME2 "Dervish Crescent +2"
	SAY DESC "The length of this blade is etched with flames, genies, and whirlwinds. Small glittering particles along its length evoke a sandstorm. The style and quality of the blade indicates it was made in Calimshan.

STATISTICS:

-Charge abilities:
– Fireshield (Red) two times per day (at level 10)

THAC0: +2
Damage: 1d8+3, +1 fire
Damage Type: Slashing
Speed Factor: 3
Proficiency Type: Scimitar/Wakizashi/Ninjatō
Type: One-handed
Requires:
 10 Strength

Weight: 3"




//TWINKLE +3//
COPY "rick_bigg_mod/items/SW1H16.itm" "override"
	SAY NAME1 "Scimitar"
	SAY UNIDENTIFIED_DESC "The long, curved, single-edged blade is characteristic of both the saber and the scimitar, even though their origins lie in different parts of Faerûn. Whereas the saber was intended chiefly for horsemen, mainly due to its versatility, the scimitar has a heavier oriental influence. The 'shamshir', as it was originally called, is larger, more highly curved, and tapered to an elongated, sharp point. This makes the weapon slightly slower but more effective and deadly in combat.

STATISTICS:

Damage: 1d8+1 (slashing)
Speed Factor: 5
Proficiency Type: Scimitar/Wakizashi/Ninjatō
Type: One-handed
Requires:
 10 Strength

Weight: 4"

	SAY NAME2 "Twinkle +3"
	SAY DESC "This is the magical scimitar +3 that bears the name Twinkle. It is one of the personal weapons of Drizzt. Due to its magical nature, only those pure of heart can use it.

STATISTICS:

Equipped abilities:
– Armor Class: +2

THAC0: +3
Damage: 1d8+4 (slashing)
Speed Factor: 2
Proficiency type: Scimitar/Wakizashi/Ninjatō
Type: One-handed
Requires:
 8 Strength

Weight: 4"




//ICINGDEATH +3//
COPY "rick_bigg_mod/items/SW1H15.itm" "override"
	SAY NAME1 "Scimitar"
	SAY UNIDENTIFIED_DESC "The long, curved, single-edged blade is characteristic of both the saber and the scimitar, even though their origins lie in different parts of Faerûn. Whereas the saber was intended chiefly for horsemen, mainly due to its versatility, the scimitar has a heavier oriental influence. The 'shamshir', as it was originally called, is larger, more highly curved, and tapered to an elongated, sharp point. This makes the weapon slightly slower but more effective and deadly in combat.

STATISTICS:

Damage: 1d8+1 (slashing)
Speed Factor: 5
Proficiency Type: Scimitar/Wakizashi/Ninjatō
Type: One-handed
Requires:
 10 Strength

Weight: 4"

	SAY NAME2 "Icingdeath +3"
	SAY DESC "This is the Frostbrand scimitar Icingdeath. It is one of Drizzt's personal weapons.

STATISTICS:

Equipped abilities:
– Fire Resistance: +50%

THAC0: +3
Damage: 1d8+4 (slashing), +2d10 against cold damage against fire creatures (bypass MR)
Speed Factor: 2
Proficiency Type: Scimitar/Wakizashi/Ninjatō
Type: One-handed
Requires:
 8 Strength

Weight: 4"





//BELM +3//
COPY "rick_bigg_mod/items/SW1H30.itm" "override"
	SAY NAME1 "Scimitar"
	SAY UNIDENTIFIED_DESC "The long, curved, single-edged blade is characteristic of both the saber and the scimitar, even though their origins lie in different parts of Faerûn. Whereas the saber was intended chiefly for horsemen, mainly due to its versatility, the scimitar has a heavier oriental influence. The 'shamshir', as it was originally called, is larger, more highly curved, and tapered to an elongated, sharp point. This makes the weapon slightly slower but more effective and deadly in combat.

STATISTICS:

Damage: 1d8+1 (slashing)
Speed Factor: 5
Proficiency Type: Scimitar/Wakizashi/Ninjatō
Type: One-handed
Requires:
 10 Strength

Weight: 4"

	SAY NAME2 "Belm +3"
	SAY DESC "This enchanted scimitar bears the mark of Taka Kobe, an honored swordsmith of Kara-Tur, though how it came to be here is unknown. Perfectly balanced, it affords quick recovery in combat and even allows the wielder time for an additional attack.

STATISTICS:

Combat abilities:
– 20% chance to have 1 extra attack for two rounds

THAC0: +3
Damage: 1d8+4 (slashing)
Speed Factor: 0
Proficiency Type: Scimitar/Wakizashi/Ninjatō
Type: One-handed
Requires:
 10 Strength

Weight: 2"




//SOUL REAVER +4//
COPY "rick_bigg_mod/items/SW2H08.itm" "override"
	SAY NAME1 "Scimitar"
	SAY UNIDENTIFIED_DESC "The long, curved, single-edged blade is characteristic of both the saber and the scimitar, even though their origins lie in different parts of Faerûn. Whereas the saber was intended chiefly for horsemen, mainly due to its versatility, the scimitar has a heavier oriental influence. The 'shamshir', as it was originally called, is larger, more highly curved, and tapered to an elongated, sharp point. This makes the weapon slightly slower but more effective and deadly in combat.

STATISTICS:

Damage: 1d8+1 (slashing)
Speed Factor: 5
Proficiency Type: Scimitar/Wakizashi/Ninjatō
Type: One-handed
Requires:
 10 Strength

Weight: 4"

	SAY NAME2 "Soul Reaver +4"
	SAY DESC "A social faux pas placed upstart Andor Licon in a duel with Baron Eeirk, heir to a warrior king. Though they seemed of even skill, Andor grew oddly weaker with each hit of the Baron's family blade. Panicking, he bade his bodyguards kill Eeirk. Despite his claims of morality, some noted that the young noble had positioned his men before the duel was even underway, and though he professed disdain for its dark magic, Andor made a tidy fortune off the sale of the evil blade. 

STATISTICS:

Combat abilities:
– Each hit makes the target receive a cumulative 2 point penalty to their THAC0 for 2 turns

THAC0: +4
Damage: 1d8+5 (slashing)
Speed Factor: 1
Proficiency Type: Scimitar/Wakizashi/Ninjatō
Type: One-handed
Requires:
 8 Strength

Weight: 2"






//SPECTRAL BLADE +5//
COPY "rick_bigg_mod/items/SW1H69.itm" "override"
	SAY NAME1 "Scimitar"
	SAY UNIDENTIFIED_DESC "The long, curved, single-edged blade is characteristic of both the saber and the scimitar, even though their origins lie in different parts of Faerûn. Whereas the saber was intended chiefly for horsemen, mainly due to its versatility, the scimitar has a heavier oriental influence. The 'shamshir', as it was originally called, is larger, more highly curved, and tapered to an elongated, sharp point. This makes the weapon slightly slower but more effective and deadly in combat.

STATISTICS:

Damage: 1d8+1 (slashing)
Speed Factor: 5
Proficiency Type: Scimitar/Wakizashi/Ninjatō
Type: One-handed
Requires:
 10 Strength

Weight: 4"

	SAY NAME2 "Spectral Blade +5"
	SAY DESC "Drawing on the necromancy of the Skull of the Lich, Spectral Brand is now an instrument of unholy death that should never have been unleashed upon the realms.

STATISTICS:

Equipped abilities:
– Negative Plane Protection

Combat abilities:
- -10% Slashing and Cold Damage Resistance on target for 2 rounds

Charge abilities:
– Armor Piercing Strike once per day
  Special: +10 THAC0 bonus
  Duration: 3 rounds

– Summon Spectral Blade once per day
  This dancing sword fights on behalf of the one who wields Spectral Brand for 4 rounds, attacking once per round and doing 1d8+3 slashing damage with each hit.

THAC0: +5
Damage: 1d8+6, +1d6 cold damage
Damage type: Slashing
Speed Factor: 0
Proficiency Type: Scimitar/Wakizashi/Ninjatō
Type: One-handed
Requires:
 8 Strength

Weight: 2"



//MALAKAR +2//
COPY "rick_bigg_mod/items/SW1H45.itm" "override"
	SAY NAME1 "Katana"
	SAY UNIDENTIFIED_DESC "The katana is a single-edged, slightly curved sword that ends with a chisel point. The katana is perhaps one of the finest swords ever made, the steps to its creation a long and secret process that is more art form than anything else. This blade is an important facet of Kara-Turan culture. To touch or wield a samurai's katana is to insult the samurai and to incite his wrath. For a gaijin, or foreigner, to own such a blade is a rare occurrence. Either the gaijin is a greatly honored friend of an important minister, or the gaijin has murdered a samurai.

STATISTICS:

Damage: 1d8 (slashing)
Speed Factor: 4
Proficiency Type: Katana
Type: One-handed
Requires:
 6 Strength

Weight: 6"

	SAY NAME2 "Malakar +2"
	SAY DESC "This sleek katana radiates magical energy when carried. The Malakar, or Dueling Steel, was used by a less-than-honorable samurai during duels against other samurai. As if of its own volition, it will swoop down and deflect the slashing attacks of other weapons. It is perfect for the warrior concerned about defense as well as offense.

STATISTICS:

Equipped abilities:
– Armor Class: +3 vs. slashing weapons

THAC0: +2
Damage: 1d8+2 (slashing)
Speed Factor: 2
Proficiency Type: Katana
Type: One-handed
Requires:
 6 Strength

Weight: 4"





//USUNO'S BLADE +3//
COPY "rick_bigg_mod/items/SW1H67.itm" "override"
	SAY NAME1 "Katana"
	SAY UNIDENTIFIED_DESC "The katana is a single-edged, slightly curved sword that ends with a chisel point. The katana is perhaps one of the finest swords ever made, the steps to its creation a long and secret process that is more art form than anything else. This blade is an important facet of Kara-Turan culture. To touch or wield a samurai's katana is to insult the samurai and to incite his wrath. For a gaijin, or foreigner, to own such a blade is a rare occurrence. Either the gaijin is a greatly honored friend of an important minister, or the gaijin has murdered a samurai.

STATISTICS:

Damage: 1d8 (slashing)
Speed Factor: 4
Proficiency Type: Katana
Type: One-handed
Requires:
 6 Strength

Weight: 6"

	SAY NAME2 "Usuno's Blade +3"
	SAY DESC "The daughter of a high ranking official within the bureaucratic society of Kara-Tur, Usuno rejected her family's station and carved a legend for herself among the yakuza of the underworld. The blade of this enchanted katana drips acid.

STATISTICS:

Combat abilities: 
– 20% chance per hit that the target takes 1 extra point of acid damage per round during the next 3 rounds

THAC0: +3
Damage: 1d8+3, +2 acid
Speed Factor: 1
Proficiency Type: Katana
Type: One-handed
Requires:
 6 Strength

Weight: 2"






//YAMATO +4//
COPY "rick_bigg_mod/items/SW1H66.itm" "override"
	SAY NAME1 "Katana"
	SAY UNIDENTIFIED_DESC "The katana is a single-edged, slightly curved sword that ends with a chisel point. The katana is perhaps one of the finest swords ever made, the steps to its creation a long and secret process that is more art form than anything else. This blade is an important facet of Kara-Turan culture. To touch or wield a samurai's katana is to insult the samurai and to incite his wrath. For a gaijin, or foreigner, to own such a blade is a rare occurrence. Either the gaijin is a greatly honored friend of an important minister, or the gaijin has murdered a samurai.

STATISTICS:

Damage: 1d8 (slashing)
Speed Factor: 4
Proficiency Type: Katana
Type: One-handed
Requires:
 6 Strength

Weight: 6"

	SAY NAME2 "Yamato +4"
	SAY DESC "The name of the mighty Wu Jen who fashioned this katana is long forgotten. However, the name Yamato, loosely translated, means 'Guardian' or 'Defender'.

STATISTICS:

Equipped abilities:
– Armor Class: +2

THAC0: +4
Damage: 1d8+4 (slashing)
Speed Factor: 0
Proficiency Type: Katana
Type: One-handed
Requires:
 6 Strength

Weight: 2"




//CELESTIAL FURY +4//
COPY "rick_bigg_mod/items/SW1H51.itm" "override"
	SAY NAME1 "Katana"
	SAY UNIDENTIFIED_DESC "The katana is a single-edged, slightly curved sword that ends with a chisel point. The katana is perhaps one of the finest swords ever made, the steps to its creation a long and secret process that is more art form than anything else. This blade is an important facet of Kara-Turan culture. To touch or wield a samurai's katana is to insult the samurai and to incite his wrath. For a gaijin, or foreigner, to own such a blade is a rare occurrence. Either the gaijin is a greatly honored friend of an important minister, or the gaijin has murdered a samurai.

STATISTICS:

Damage: 1d8 (slashing)
Speed Factor: 4
Proficiency Type: Katana
Type: One-handed
Requires:
 6 Strength

Weight: 6"

	SAY NAME2 "Celestial Fury +4"
	SAY DESC "Many centuries ago, a trumpet archon named Chin Yi fell in love with a mortal man in Shou Lung and swore to protect him from enemies should he ever ride to war. When that time came, however, Chin Yi's patron goddess Kwan Ying forbade her to intervene, not wishing to contribute to the bloodshed. When Chin Yi's beloved was cut down by a yuan-ti warlord, her grief was terrible and her wrath immediate: Ignoring Kwan Ying's warnings, she flew onto the battlefield and took up her beloved's katana, using the blade to cut down the warlord and all those who served him. She continued the slaughter of the yuan-ti army until Kwan Ying herself appeared before her, arms open and eyes full of sympathy. 'If it will stop this slaughter, I will ease your pain and end your suffering.'

'I do not wish to end my suffering,' replied Chin Yi. 'I wish for my fury to sound throughout the ages, now and forever.' Wanting to help her servant, but not wishing to unleash such powerful fury on the world, Kwan Ying bound Chin Yi's spirit to the blade of the man she had failed to protect and then hid the weapon in a warrior's tomb. The tomb was later infiltrated and the weapon stolen, and although Chin Yi's cries could no longer be heard through the steel of the blade, her vengeance was as brutal as ever.

STATISTICS:

Combat abilities:
– Booming Thunder: Hit target must save vs. Spell or be stunned for 1 round
– Shocking Blow: 5% chance of an extra 20 electrical damage to hit target

Charge abilities:
– Lightning Strike two times per day

THAC0: +4
Damage: 1d8+4 (slashing)
Speed Factor: 0
Proficiency Type: Katana
Type: One-handed
Requires:
 6 Strength

Weight: 2"





//HINDO'S DOOM +3//
COPY "rick_bigg_mod/items/SW1H70.itm" "override"
	SAY NAME1 "Katana"
	SAY UNIDENTIFIED_DESC "The katana is a single-edged, slightly curved sword that ends with a chisel point. The katana is perhaps one of the finest swords ever made, the steps to its creation a long and secret process that is more art form than anything else. This blade is an important facet of Kara-Turan culture. To touch or wield a samurai's katana is to insult the samurai and to incite his wrath. For a gaijin, or foreigner, to own such a blade is a rare occurrence. Either the gaijin is a greatly honored friend of an important minister, or the gaijin has murdered a samurai.

STATISTICS:

Damage: 1d8 (slashing)
Speed Factor: 4
Proficiency Type: Katana
Type: One-handed
Requires:
 6 Strength

Weight: 6"

	SAY NAME2 "Hindo's Doom +3"
	SAY DESC "Hindo was a samurai of great renown, a staunch defender of his people against the evil undead that often ravaged his homelands. 

STATISTICS:

Equipped abilities:
– Magic Resistance: +10%

Charge abilities:
– Lesser Restoration once per day
  Range: Touch
  Area of Effect: 1 creature

THAC0: +3
Damage: 1d8+3, +3 vs evil (slashing)
Speed Factor: 1
Proficiency Type: Katana
Type: One-handed
Requires:
 6 Strength

Weight: 3"





//HINDO'S DOOM +5//
COPY "rick_bigg_mod/items/SW1H71.itm" "override"
	SAY NAME1 "Katana"
	SAY UNIDENTIFIED_DESC "The katana is a single-edged, slightly curved sword that ends with a chisel point. The katana is perhaps one of the finest swords ever made, the steps to its creation a long and secret process that is more art form than anything else. This blade is an important facet of Kara-Turan culture. To touch or wield a samurai's katana is to insult the samurai and to incite his wrath. For a gaijin, or foreigner, to own such a blade is a rare occurrence. Either the gaijin is a greatly honored friend of an important minister, or the gaijin has murdered a samurai.

STATISTICS:

Damage: 1d8 (slashing)
Speed Factor: 4
Proficiency Type: Katana
Type: One-handed
Requires:
 6 Strength

Weight: 6"

	SAY NAME2 "Hindo's Doom +5"
	SAY DESC "Reunited with the hand of its original owner, Hindo's Doom is a katana worthy of the greatest of samurai. 

STATISTICS:

Equipped abilities:
– Magic Resistance: +20%
– Immunity to all forms of death magic
- Defensive Harmony always active

Charge abilities:
– Greater Restoration once per day
  Area of Effect: 1 creature

THAC0: +5
Damage: 1d8+5, +5 vs evil (slashing)
Speed Factor: 0
Proficiency Type: Katana
Type: One-handed
Requires:
 6 Strength

Weight: 2"








//SPIDER'S BANE +2//
COPY "rick_bigg_mod/items/SW2H06.itm" "override"
	SAY NAME1 "Two-Handed Sword"
	SAY UNIDENTIFIED_DESC "The two-handed sword is a derivative of the long sword. Weaponsmiths have always looked for ways to improve existing weapons. In an effort to improve the long sword, the blade was lengthened. Eventually, the handle had to be extended and two hands became necessary to properly swing the sword. The primary function of two-handed swords is cleaving mounted knights and breaking up pike formations.

STATISTICS:

Damage: 2d6 (slashing)
Speed Factor: 10
Proficiency Type: Two-handed Sword
Type: Two-handed
Requires:
 14 Strength

Weight: 15"

SAY NAME2 "Spider's Bane +2"
	SAY DESC "This sword was originally forged by the dwarves of the Orothiar tribe in Cloakwood. They created the blade to help foster goodwill between them and the Grand Dukes of Baldur's Gate. Wielded by the Grand Dukes for about a century, the sword was eventually lost, ironically in a fight against ettercaps and spiders. Who wields the blade is now unknown, but its recovery would aid greatly in fighting the current spider infestation that plagues the Cloakwood.

STATISTICS:

Equipped abilities:
– Protects the wielder from any magics that affect movement, such as Hold and Web.

THAC0: +2, +4 vs Spiders and Ettercaps
Damage: 2d6+2, +4 vs Spiders and Ettercaps
Damage Type: Slashing
Speed Factor: 8
Proficiency Type: Two-handed Sword
Type: Two-handed
Requires:
 14 Strength

Weight: 10" 





//BERSERKERING SWORD +3//
COPY "rick_bigg_mod/items/SW2H03.itm" "override"
	SAY NAME1 "Two-Handed Sword"
	SAY UNIDENTIFIED_DESC "The two-handed sword is a derivative of the long sword. Weaponsmiths have always looked for ways to improve existing weapons. In an effort to improve the long sword, the blade was lengthened. Eventually, the handle had to be extended and two hands became necessary to properly swing the sword. The primary function of two-handed swords is cleaving mounted knights and breaking up pike formations.

STATISTICS:

Damage: 2d6 (slashing)
Speed Factor: 10
Proficiency Type: Two-handed Sword
Type: Two-handed
Requires:
 14 Strength

Weight: 15"

SAY NAME2 "Berserkering Sword +3"
	SAY DESC "This sword performs perfectly under every test, save the heat of battle. Upon entering combat, the wielder have a lot o chance to go berserk, killing everything within reach until either calming down or falling unconscious. A very powerful sword, but one must decide whether or not it is worth the risk.

STATISTICS:

Combat abilities:
– Chance to go berserk 25% every hit (you have the same bonuses as a Berserker Rage, but cannot be controlled).

THAC0: +3
Damage: 2d6+3 (slashing)
Speed Factor: 7
Proficiency Type: Two-handed Sword
Type: Two-handed
Requires:
 14 Strength

Weight: 12" 






//FLAME OF THE NORTH +2//
COPY "rick_bigg_mod/items/SW2H12.itm" "override"
	SAY NAME1 "Two-Handed Sword"
	SAY UNIDENTIFIED_DESC "The two-handed sword is a derivative of the long sword. Weaponsmiths have always looked for ways to improve existing weapons. In an effort to improve the long sword, the blade was lengthened. Eventually, the handle had to be extended and two hands became necessary to properly swing the sword. The primary function of two-handed swords is cleaving mounted knights and breaking up pike formations.

STATISTICS:

Damage: 2d6 (slashing)
Speed Factor: 10
Proficiency Type: Two-handed Sword
Type: Two-handed
Requires:
 14 Strength

Weight: 15"

SAY NAME2 "Flame of the North +2"
	SAY DESC "The title does not refer to the blade itself, but rather to the woman who originally wielded it in the icy hinterlands of Faerûn. Her name was Carerra, and she was a veritable firestorm that swept across arctic trolls and the northern orcish tribes. She was a hated enemy of many a shaman whose magic often floundered against her fury. After a lifetime of raucous battle, it was old age that eventually claimed her. The sword was passed to her granddaughter, an adventurer, who presumably brought it to Amn.

STATISTICS:

Equipped abilities:
– Magic Resistance: +10%

THAC0: +2, +4 vs. evil
Damage: 1d10+2, +4 vs. evil
Damage type: Slashing
Speed Factor: 8
Proficiency Type: Two-handed sword
Type: Two-handed
Requires:
 14 Strength

Weight: 10" 







//SWORD OF CHAOS +2//
COPY "rick_bigg_mod/items/SW2H16.itm" "override"
	SAY NAME1 "Two-Handed Sword"
	SAY UNIDENTIFIED_DESC "The two-handed sword is a derivative of the long sword. Weaponsmiths have always looked for ways to improve existing weapons. In an effort to improve the long sword, the blade was lengthened. Eventually, the handle had to be extended and two hands became necessary to properly swing the sword. The primary function of two-handed swords is cleaving mounted knights and breaking up pike formations.

STATISTICS:

Damage: 2d6 (slashing)
Speed Factor: 10
Proficiency Type: Two-handed Sword
Type: Two-handed
Requires:
 14 Strength

Weight: 15"

SAY NAME2 "Sword of Chaos +2"
	SAY DESC "The blade of Sarevok, brother of <CHARNAME>, used in the battle they fought in faraway Baldur's Gate. <CHARNAME> prevailed, destroying Sarevok's plans and rescuing the Sword Coast from the brink of war. The sword itself defies identification, likely forged specifically for Sarevok to best focus the infernal energy he hoped to control. Much of its power died with him.

STATISTICS:

Equipped abilities:
- +10% Magic Resistance

Combat abilities:
– Each hit drains 1 Hit Point from the target and transfers it to the wielder. This will not heal beyond the wielder's maximum.

THAC0: +2
Damage: 1d10+2 (slashing)
Speed Factor: 8
Proficiency Type: Two-handed Sword
Type: Two-handed
Requires:
 14 Strength

Weight: 10" 



//SILVER SWORD +3//
COPY "rick_bigg_mod/items/SW2H15.itm" "override"
	SAY NAME1 "Two-Handed Sword"
	SAY UNIDENTIFIED_DESC "The two-handed sword is a derivative of the long sword. Weaponsmiths have always looked for ways to improve existing weapons. In an effort to improve the long sword, the blade was lengthened. Eventually, the handle had to be extended and two hands became necessary to properly swing the sword. The primary function of two-handed swords is cleaving mounted knights and breaking up pike formations.

STATISTICS:

Damage: 2d6 (slashing)
Speed Factor: 10
Proficiency Type: Two-handed Sword
Type: Two-handed
Requires:
 14 Strength

Weight: 15"

SAY NAME2 "Silver Sword +3"
	SAY DESC "This vorpal Silver Sword radiates a dark aura when you examine it, and the blade is so finely sharpened it could likely sever a head in a single blow.

STATISTICS:

Combat abilities:
– 15% chance per hit that target must save vs. Death at -4 or die

THAC0: +3
Damage: 1d10+3 (slashing)
Speed Factor: 7
Proficiency Type: Two-handed Sword
Type: Two-handed
Requires:
 14 Strength

Weight: 15"



//PSION'S BLADE +3//
COPY "rick_bigg_mod/items/SW2H21.itm" "override"
	SAY NAME1 "Two-Handed Sword"
	SAY UNIDENTIFIED_DESC "The two-handed sword is a derivative of the long sword. Weaponsmiths have always looked for ways to improve existing weapons. In an effort to improve the long sword, the blade was lengthened. Eventually, the handle had to be extended and two hands became necessary to properly swing the sword. The primary function of two-handed swords is cleaving mounted knights and breaking up pike formations.

STATISTICS:

Damage: 2d6 (slashing)
Speed Factor: 10
Proficiency Type: Two-handed Sword
Type: Two-handed
Requires:
 14 Strength

Weight: 15"

SAY NAME2 "Psion's Blade +3"
	SAY DESC "Some believe this massive blade to be of drow origin, though others dispute this claim. However, all agree this great sword was fashioned with a single purpose... to rid the world of the illithid. Those who wield the Psion's Blade are immune to the mind flayer's psionic attacks. The bewildering gaze of umber hulks, often found serving the illithid, are similarly rendered harmless.

STATISTICS:

Equipped abilities:
– Immunity to confusion and all psionic attacks

THAC0: +3
Damage: 2d6+3 (slashing)
Speed Factor: 7
Proficiency Type: Two-handed Sword
Type: Two-handed
Requires:
 14 Strength

Weight: 11"





//WORLD'S EDGE +4//
COPY "rick_bigg_mod/items/SW2H09.itm" "override"
	SAY NAME1 "Two-Handed Sword"
	SAY UNIDENTIFIED_DESC "The two-handed sword is a derivative of the long sword. Weaponsmiths have always looked for ways to improve existing weapons. In an effort to improve the long sword, the blade was lengthened. Eventually, the handle had to be extended and two hands became necessary to properly swing the sword. The primary function of two-handed swords is cleaving mounted knights and breaking up pike formations.

STATISTICS:

Damage: 2d6 (slashing)
Speed Factor: 10
Proficiency Type: Two-handed Sword
Type: Two-handed
Requires:
 14 Strength

Weight: 15"

SAY NAME2 "World's Edge +4"
	SAY DESC "This is a legendary weapon of heroic proportions, especially among the far-northern tribes of barbarians. Champion after champion has wielded this blade against countless enemies, and the blood it has spilled could fill a small sea. History will not admit that such a blade could be forged and each consecutive owner seems to tie its origin to whatever creation myth they believe. The most grandiose of these tales is that of a great chieftain who sailed to the cliffs that supposedly bordered the world. There he reached into the void, and his will shaped the blade from nothing. Whatever the truth, in the right hands this sword is a fearsome thing.

STATISTICS:

Equipped abilities:
- Immunity to fatigue
- Doubles movement rate
- +5% chance to score a critical hit

Combat abilities:
- On a critical hit the wielder gains 2 extra attacks per round for twelve seconds

THAC0: +4
Damage: 1d10+4 (slashing)
Speed Factor: 6
Proficiency Type: Two-handed Sword
Type: Two-handed
Requires:
 13 Strength

Weight: 7" 




//GRAM THE SWORD OF GRIEF +5//
COPY "rick_bigg_mod/items/SW2H17.itm" "override"
	SAY NAME1 "Two-Handed Sword"
	SAY UNIDENTIFIED_DESC "The two-handed sword is a derivative of the long sword. Weaponsmiths have always looked for ways to improve existing weapons. In an effort to improve the long sword, the blade was lengthened. Eventually, the handle had to be extended and two hands became necessary to properly swing the sword. The primary function of two-handed swords is cleaving mounted knights and breaking up pike formations.

STATISTICS:

Damage: 2d6 (slashing)
Speed Factor: 10
Proficiency Type: Two-handed Sword
Type: Two-handed
Requires:
 14 Strength

Weight: 15"

SAY NAME2 "Gram the Sword of Grief +5"
	SAY DESC "This is one of the many weapons of the great hero Siegfried. The blade is particularly sharp and well-balanced, and in a certain light one can see the faint image of a serpent within the hilt.

STATISTICS:

Equipped abilities:
– Magic Resistance: +5%

Combat abilities:
– Inflicts 10 points of bleeding damage per hit (two point per round)

THAC0: +5
Damage: 2d6+5 (slashing)
Speed Factor: 5
Proficiency Type: Two-handed Sword
Type: Two-handed
Requires:
 14 Strength

Weight: 9" 






//GRAM THE SWORD OF GRIEF +6//
COPY "rick_bigg_mod/items/SW2H18.itm" "override"
	SAY NAME1 "Two-Handed Sword"
	SAY UNIDENTIFIED_DESC "The two-handed sword is a derivative of the long sword. Weaponsmiths have always looked for ways to improve existing weapons. In an effort to improve the long sword, the blade was lengthened. Eventually, the handle had to be extended and two hands became necessary to properly swing the sword. The primary function of two-handed swords is cleaving mounted knights and breaking up pike formations.

STATISTICS:

Damage: 2d6 (slashing)
Speed Factor: 10
Proficiency Type: Two-handed Sword
Type: Two-handed
Requires:
 14 Strength

Weight: 15"

SAY NAME2 "Gram the Sword of Grief +6"
	SAY DESC "Siegfried's fearsome blade is even more powerful with the Heart of the Damned set into its pommel.

STATISTICS:

Equipped abilities:
– Magic Resistance: +10%

Combat abilities:
– Inflicts 10 points of bleeding damage per hit (two point per round)
– 20% chance to drain 2 points of Strength from the target and transfer them to the wielder for 5 rounds

THAC0: +6
Damage: 2d6+6 (slashing)
Speed Factor: 4
Proficiency Type: Two-handed Sword
Type: Two-handed
Requires:
 14 Strength

Weight: 9" 



//CARSOMYR + 5//
COPY "rick_bigg_mod/items/sw2h10.itm" "override"
	SAY NAME1 "Two-Handed Sword"
	SAY UNIDENTIFIED_DESC "The two-handed sword is a derivative of the long sword. Weaponsmiths have always looked for ways to improve existing weapons. In an effort to improve the long sword, the blade was lengthened. Eventually, the handle had to be extended and two hands became necessary to properly swing the sword. The primary function of two-handed swords is cleaving mounted knights and breaking up pike formations.

STATISTICS:

Damage: 2d6 (slashing)
Speed Factor: 10
Proficiency Type: Two-handed Sword
Type: Two-handed
Requires:
 14 Strength

Weight: 15"

	SAY NAME2 "Carsomyr +5"
	SAY DESC "Carsomyr is a weapon of legend, perhaps one of the most powerful blades ever forged on Faerûn, though its origin and history is thought purposefully forgotten so that the sword itself shall never overshadow the importance of the struggles that must be fought today. It is infused with the very essence of virtue and requires as much from any Paladin who would hope to wield it. The evils of the realms must truly stand aside when this weapon is brought to bear, their magic dispelled with a word, steadfastly resisted with ease. Carsomyr also harbors a special distaste for the forces of evil and chaos, and such creatures must fear additional damage from its touch in battle.

STATISTICS:

Equipped abilities:
– Magic Resistance: +50%

Combat abilities:
– Dispel Magic at level 30 on each hit

Charge abilities:
– Dispel Magic at level 20 three times per day
  Range: 40 ft.
  Area of Effect: 15-ft. radius

THAC0: +5
Damage: 2d6+5, +5 extra vs. evil
Damage type: Slashing
Speed Factor: 5
Proficiency Type: Two-handed Sword
Type: Two-handed
Requires:
 14 Strength

Weight: 7"






//CARSOMYR + 6//
COPY "rick_bigg_mod/items/sw2h19.itm" "override"
	SAY NAME1 "Two-Handed Sword"
	SAY UNIDENTIFIED_DESC "The two-handed sword is a derivative of the long sword. Weaponsmiths have always looked for ways to improve existing weapons. In an effort to improve the long sword, the blade was lengthened. Eventually, the handle had to be extended and two hands became necessary to properly swing the sword. The primary function of two-handed swords is cleaving mounted knights and breaking up pike formations.

STATISTICS:

Damage: 2d6 (slashing)
Speed Factor: 10
Proficiency Type: Two-handed Sword
Type: Two-handed
Requires:
 14 Strength

Weight: 15"

	SAY NAME2 "Carsomyr +6"
	SAY DESC "Even a holy relic as powerful as Carsomyr is made even greater when combined with the Eye of Tyr.

STATISTICS:

Equipped abilities:
– Magic Resistance: +50%

Combat abilities: 
– Dispel Magic at level 40 on each hit

Charge abilities:
– Dispel Magic at level 30 three times per day
  Range: 40 ft.
  Area of Effect: 15-ft. radius

THAC0: +6
Damage: 2d6+6, +6 extra vs. evil
Damage type: Slashing
Speed Factor: 4
Proficiency Type: Two-handed Sword 
Type: Two-handed
Requires:
 14 Strength

Weight: 6"



