/*
Shield description redescriber.
Handles shields (AC is a string like "+3", armor_class goes under "Equipped abilities").
Removes "Armor Class: xxx" that appears before "Requires:" line.
*/

DEFINE_PATCH_FUNCTION redescribe_shield
    INT_VAR
        min_strength = 0
        arcane_spells = 0
        armor_class = 0
		speed_factor = 0
    STR_VAR
        physical_resistance = 0
        slashing_ac = 0
        piercing_ac = 0
        missile_ac = 0
        crushing_ac = 0
        locks = 0
        traps = 0
        pick_pockets = 0
        move_silently = 0
        hide = 0
BEGIN
	shield = 1
	LAUNCH_PATCH_MACRO common_preprocess
	LAUNCH_PATCH_MACRO minimum_strength
	LAUNCH_PATCH_MACRO build_armor_class
	LAUNCH_PATCH_MACRO armor_shield_shared_logic
	LAUNCH_PATCH_MACRO common_postprocess
END
