INCLUDE ~rick_bigg_mod/lib/change_itm_icon.tpa~

COPY ~rick_bigg_mod/2da/items_overwrite.2da~ ~weidu_external~
    READ_2DA_ENTRIES_NOW items_overwrite 4
    FOR (row = 1; row < items_overwrite; row += 1) BEGIN
        READ_2DA_ENTRY_FORMER items_overwrite row 0 new_item
        READ_2DA_ENTRY_FORMER items_overwrite row 1 item_to_replace
        READ_2DA_ENTRY_FORMER items_overwrite row 2 new_icon
        READ_2DA_ENTRY_FORMER items_overwrite row 3 type

        INNER_ACTION BEGIN
            COPY_EXISTING ~%new_item%.itm~ ~override/%item_to_replace%.itm~
                PATCH_IF ~%new_icon%~ STRING_COMPARE ~_~ BEGIN
                    WRITE_EVALUATED_ASCII 0x3a "%new_icon%" #8

                    PATCH_IF IS_AN_INT ~%type%~ BEGIN
                        LAUNCH_PATCH_FUNCTION change_itm_icon
                            INT_VAR type = type
                            STR_VAR icon_name = EVALUATE_BUFFER "%new_icon%"
                        END
                    END
                END
        END
    END
BUT_ONLY

COPY_EXISTING_REGEXP ~^inn26.*\.sto$~ ~override~
    GET_OFFSET_ARRAY items_array STO_V10_ITEMS_SOLD

    FOR (row = 1; row < items_overwrite; row += 1) BEGIN
        READ_2DA_ENTRY_FORMER items_overwrite row 0 new_item

        SET $store_item_detail(~%new_item%~ ~exists~) = 0
        SET $store_item_detail(~%new_item%~ ~charge1~) = 0
        SET $store_item_detail(~%new_item%~ ~charge2~) = 0
        SET $store_item_detail(~%new_item%~ ~charge3~) = 0
        SET $store_item_detail(~%new_item%~ ~flags~) = 0
        SET $store_item_detail(~%new_item%~ ~stack~) = 0
        SET $store_item_detail(~%new_item%~ ~unlimited~) = 0
        SET $store_item_detail(~%new_item%~ ~replace~) = 0
        SET $store_item_detail(~%new_item%~ ~at_position~) = 0
        TEXT_SPRINT $store_item_detail(~%new_item%~ ~position~)  ~~
    END

    PHP_EACH items_array AS item_idx => item_off BEGIN
        READ_ASCII item_off item_name

        FOR (row = 1; row < items_overwrite; row += 1) BEGIN
            READ_2DA_ENTRY_FORMER items_overwrite row 0 new_item
            READ_2DA_ENTRY_FORMER items_overwrite row 1 item_to_replace

            PATCH_IF ~%item_to_replace%~ STRING_EQUAL_CASE ~%item_name%~ OR 
                    (~%new_item%~ STRING_EQUAL_CASE ~%item_name%~ AND NOT $store_item_detail(~%new_item%~ ~replace~)) BEGIN
                PATCH_IF ~%new_item%~ STRING_EQUAL_CASE ~%item_name%~ BEGIN
                    SET $store_item_detail(~%new_item%~ ~replace~) = 1
                    SET $store_item_detail(~%new_item%~ ~at_position~) = 0
                END

                READ_SHORT item_off + 0xa  charge1
                READ_SHORT item_off + 0xc  charge2
                READ_SHORT item_off + 0xe  charge3
                READ_LONG  item_off + 0x10 flags
                READ_LONG  item_off + 0x14 stack
                READ_LONG  item_off + 0x18 unlimited

                SET $store_item_detail(EVALUATE_BUFFER ~%new_item%~ ~exists~) = $store_item_detail(EVALUATE_BUFFER ~%new_item%~ ~exists~) + 1
                SET $store_item_detail(EVALUATE_BUFFER ~%new_item%~ ~charge1~) = $store_item_detail(EVALUATE_BUFFER ~%new_item%~ ~charge1~) > charge1 ? $store_item_detail(EVALUATE_BUFFER ~%new_item%~ ~charge1~) : charge1
                SET $store_item_detail(EVALUATE_BUFFER ~%new_item%~ ~charge2~) = $store_item_detail(EVALUATE_BUFFER ~%new_item%~ ~charge2~) > charge2 ? $store_item_detail(EVALUATE_BUFFER ~%new_item%~ ~charge2~) : charge2
                SET $store_item_detail(EVALUATE_BUFFER ~%new_item%~ ~charge3~) = $store_item_detail(EVALUATE_BUFFER ~%new_item%~ ~charge3~) > charge3 ? $store_item_detail(EVALUATE_BUFFER ~%new_item%~ ~charge3~) : charge3
                SET $store_item_detail(EVALUATE_BUFFER ~%new_item%~ ~flags~)  = $store_item_detail(EVALUATE_BUFFER ~%new_item%~ ~flags~)  BOR flags

                old_stack = $store_item_detail(EVALUATE_BUFFER ~%new_item%~ ~stack~)
                SET $store_item_detail(EVALUATE_BUFFER ~%new_item%~ ~stack~) = $store_item_detail(EVALUATE_BUFFER ~%new_item%~ ~stack~) + stack
                new_stack = $store_item_detail(EVALUATE_BUFFER ~%new_item%~ ~stack~)
//                PATCH_PRINT ~%SOURCE_RES% - item %item_to_replace% replace by %new_item%, old stack: %old_stack% stack: %stack% new stack: %new_stack%~

                old_unlimited = $store_item_detail(EVALUATE_BUFFER ~%new_item%~ ~unlimited~)
                SET $store_item_detail(EVALUATE_BUFFER ~%new_item%~ ~unlimited~)    = $store_item_detail(EVALUATE_BUFFER ~%new_item%~ ~unlimited~)    OR unlimited
                new_unlimited = $store_item_detail(EVALUATE_BUFFER ~%new_item%~ ~unlimited~)
//                PATCH_PRINT ~%SOURCE_RES% - item %item_to_replace% replace by %new_item%, old unlimited: %old_unlimited% unlimited: %unlimited% new unlimited: %new_unlimited%~

                PATCH_IF ~%item_to_replace%~ STRING_EQUAL_CASE ~%item_name%~ AND $store_item_detail(~%new_item%~ ~at_position~) = 0 AND $store_item_detail(~%new_item%~ ~replace~) = 0 BEGIN
                    SET $store_item_detail(~%new_item%~ ~at_position~) = 1
                    TEXT_SPRINT $store_item_detail(~%new_item%~ ~position~)  ~%item_to_replace%~
                END
            END
        END
    END

    FOR (row = 1; row < items_overwrite; row += 1) BEGIN
        READ_2DA_ENTRY_FORMER items_overwrite row 0 new_item
        READ_2DA_ENTRY_FORMER items_overwrite row 1 item_to_replace

        SET count = $store_item_detail(~%new_item%~ ~exists~)
        SET stack = $store_item_detail(~%new_item%~ ~stack~)
        SET charge1 = $store_item_detail(~%new_item%~ ~charge1~)
        SET charge2 = $store_item_detail(~%new_item%~ ~charge2~)
        SET charge3 = $store_item_detail(~%new_item%~ ~charge3~)
        SET flags = $store_item_detail(~%new_item%~ ~flags~)
        SET unlimited = $store_item_detail(~%new_item%~ ~unlimited~)

        PATCH_IF count BEGIN

            TEXT_SPRINT position ~~
            PATCH_IF $store_item_detail(~%new_item%~ ~at_position~) BEGIN
                TEXT_SPRINT position $store_item_detail(~%new_item%~ ~position~)
                TEXT_SPRINT position ~AFTER %position%~
//                PATCH_PRINT ~%SOURCE_RES% %new_item% %item_to_replace%~
            END

            SET overwrite = $store_item_detail(~%new_item%~ ~replace~)

            PATCH_SILENT
            LAUNCH_PATCH_FUNCTION ADD_STORE_ITEM_EX
                INT_VAR 
                    charge1 = charge1
                    charge2 = charge2
                    charge3 = charge3
                    stack = unlimited ? 0 : stack
                    unlimited = unlimited
                    overwrite = overwrite
                    expiration = 0
                STR_VAR
                    item_name = EVALUATE_BUFFER ~%new_item%~
                    position = EVALUATE_BUFFER ~%position%~
                    flags = EVALUATE_BUFFER ~%flags%~
            END
            PATCH_VERBOSE

            SET $store_item_detail(~%new_item%~ ~exists~) = 0
        END
    END
    FOR (row = 1; row < items_overwrite; row += 1) BEGIN
        READ_2DA_ENTRY_FORMER items_overwrite row 0 new_item
        READ_2DA_ENTRY_FORMER items_overwrite row 1 item_to_replace

        PATCH_IF ~%new_item%~ STRING_COMPARE_CASE ~%item_to_replace%~ BEGIN
            REMOVE_STORE_ITEM ~%item_to_replace%~
        END
    END
BUT_ONLY

