
COPY ~rick_bigg_mod/copy~ ~override~


INCLUDE ~rick_bigg_mod/lib/items.tpa~
INCLUDE ~rick_bigg_mod/lib/spells.tpa~
INCLUDE ~rick_bigg_mod/lib/creatures.tpa~
INCLUDE ~rick_bigg_mod/lib/eff.tpa~
INCLUDE ~rick_bigg_mod/lib/stores.tpa~

INCLUDE ~rick_bigg_mod/lib/replace_items.tpa~


INCLUDE ~rick_bigg_mod/lib/races.tpa~
INCLUDE ~rick_bigg_mod/lib/styles.tpa~
INCLUDE ~rick_bigg_mod/lib/weapon_rules.tpa~
INCLUDE ~rick_bigg_mod/lib/weaponproficiencies.tpa~
INCLUDE ~rick_bigg_mod/lib/fix_unusabilities.tpa~

