
COPY ~rick_bigg_mod/copy~ ~override~


INCLUDE ~rick_bigg_mod/lib/borrowed_from_cdtweaks/joinable_npc_array.tpa~


INCLUDE ~rick_bigg_mod/lib/items.tpa~
INCLUDE ~rick_bigg_mod/lib/spells.tpa~
INCLUDE ~rick_bigg_mod/lib/creatures.tpa~
INCLUDE ~rick_bigg_mod/lib/eff.tpa~
INCLUDE ~rick_bigg_mod/lib/stores.tpa~

INCLUDE ~rick_bigg_mod/lib/replace_items.tpa~


INCLUDE ~rick_bigg_mod/lib/races.tpa~
INCLUDE ~rick_bigg_mod/lib/styles.tpa~
/*
INCLUDE ~rick_bigg_mod/lib/item_rules.tpa~
INCLUDE ~rick_bigg_mod/lib/weaponproficiencies.tpa~
*/

COMPILE ~rick_bigg_mod/compile~

ACTION_BASH_FOR ~rick_bigg_mod/extend_bottom~ ~^.*\.baf$~ BEGIN
    EXTEND_BOTTOM ~%BASH_FOR_RES%.bcs~ ~%BASH_FOR_FILESPEC%~
END

ACTION_BASH_FOR ~rick_bigg_mod/extend_top~ ~^.*\.baf$~ BEGIN
    EXTEND_TOP ~%BASH_FOR_RES%.bcs~ ~%BASH_FOR_FILESPEC%~
END
