//CHILL TOUCH//
COPY "rick_bigg_mod/spell/SPWI117.spl" "override"
	SAY NAME1 "Chill Touch"
	SAY UNIDENTIFIED_DESC 
"Chill Touch
Level: 1
School: Necromancy
Range: Personal
Duration: 1 turn
Casting Time: 1
Area of Effect: Special
Saving Throw: Special

When the caster completes this spell, a blue glow encompasses his hand. This energy attacks the life force of any living creature upon which the wizard makes a successful melee attack. The touched creature suffers 1d6 points of cold damage and loses one point of strength for 1 hour (no ability drain if the victim saves vs. death). The wizard gains a +4 bonus to hit the target and his touch is considered to be of +1 enchantment to determine what it can hit."

COPY_EXISTING "SCRL82.itm" "override"
SAY DESC"Chill Touch
Level: 1
School: Necromancy
Range: Personal
Duration: 1 turn
Casting Time: 1
Area of Effect: Special
Saving Throw: Special

When the caster completes this spell, a blue glow encompasses his hand. This energy attacks the life force of any living creature upon which the wizard makes a successful melee attack. The touched creature suffers 1d6 points of cold damage and loses one point of strength for 1 hour (no ability drain if the victim saves vs. death). The wizard gains a +4 bonus to hit the target and his touch is considered to be of +1 enchantment to determine what it can hit.
"

//DEFENSIVE HARMONY//
COPY "rick_bigg_mod/spell/SPPR406.spl" "override"
	SAY NAME1 "Defensive Harmony"
	SAY UNIDENTIFIED_DESC 
"Defensive Harmony
Level: 4
School: Enchantment
Sphere: Law
Range: Personal
Duration: 1 turn
Casting Time: 1
Area of Effect: 10' radius
Saving Throw: None

Defensive Harmony grants affected creatures a defensive bonus by enhancing the coordination of their attacks and defenses. This allows a group of creatures to act as a cohesive unit for a single battle or encounter. The effect is always centered on the caster, but affects all those within a 10 foot radius. The affected creatures can move outside of this radius after the spell is cast and still enjoy the benefits of the Harmony. While the spell is in effect, each affected creature gains a +4 bonus to her armor class. Multiple castings of this spell are not cumulative.
"


