COPY_EXISTING ~weapprof.2da~ ~override~
	SET_2DA_ENTRY_LATER weapprof 29 3 ( RESOLVE_STR_REF ( "TWO-HANDED: This fighting style allows the character to use a two-handed melee weapon and receive special bonuses.

Proficient (1 slot): The wielder gets a +1 bonus to damage rolls, a -2 bonus to Speed Factor, and the ability to score critical hits on a roll of 19 or 20 (instead of just 20) when using a two-handed weapon.

Specialized (2 slots): The wielder gets a further +1 bonus to damage rolls, a further -2 bonus to Speed Factor, and the ability to score critical hits on a roll of 18, 19 or 20 (instead of just 20) when using a two-handed weapon.

NOTE: Magical two-handed weapons are more powerful than their single-handed counterparts. This counterbalances the fact that you can't use a second weapon or shield when using a two-handed weapon. The Holy Avenger and Vorpal Sword are examples of weapons that are two-handed." ))
	SET_2DA_ENTRY_LATER weapprof 30 3 ( RESOLVE_STR_REF ( "SWORD AND SHIELD: Anyone can pick up a shield and get its basic protection bonuses, but by spending slots on this fighting style, an adventurer can maximize the benefits received.

Proficient (1 slot): The wielder gets a -2 bonus to AC against missile weapons and a -1 bonus to Speed Factor.

Specialized (2 slots): The wielder gets a -4 bonus to AC against missile weapons and a -2 bonus to Speed Factor.

NOTE: Despite the name of this style, any one-handed melee weapon in combination with a shield will receive the aforementioned bonuses." ))
	SET_2DA_ENTRY_LATER weapprof 31 3 ( RESOLVE_STR_REF ( "SINGLE-WEAPON: This fighting style is for characters who do not wish to use a shield but want some bonus when using a one-handed melee weapon.

Proficient (1 slot): The wielder gets a -1 bonus to AC and THAC0, a +1 bonus to Speed Factor,and a +2 bonus to damage.

Specialized (2 slots): The wielder gets a -2 bonus to AC and THAC0, a +2 bonus to Speed Factor,and a +4 bonus to damage." ))
	SET_2DA_ENTRY_LATER weapprof 32 3 ( RESOLVE_STR_REF ( "TWO-WEAPON: This fighting style allows the character to use two melee weapons at the same time with fewer penalties. A character wielding two weapons without a slot in this fighting style would incur a -4 penalty to attack rolls with the main weapon and a -6 penalty with the off-hand weapon. 

Proficient (1 slot): The wielder's penalties are reduced to -2 with the main weapon and -4 with the off-hand weapon.

Specialized (2 slots): The wielder's penalties are reduced to 0 with the main weapon and -2 with the off-hand weapon." ))
	
	SET_2DA_ENTRIES_NOW weapprof 6
	PRETTY_PRINT_2DA
