
COPY ~rick_bigg_mod/2da/weapon_rules.2da~ ~weidu_external~
	READ_2DA_ENTRIES_NOW ~weapon_rules~ 20
BUT_ONLY


INCLUDE ~rick_bigg_mod/lib/redescribe_weapon.tpa~


			
OUTER_SET weapon_clericbits = BIT7 BOR BIT8 BOR BIT10 BOR BIT14 BOR BIT15
OUTER_SET weapon_druidbits = BIT12 BOR BIT30
OUTER_SET weapon_thiefbits = BIT9 BOR BIT16 BOR BIT17 BOR BIT19 BOR BIT22
OUTER_SET weapon_bardbits = BIT6
OUTER_SET weapon_magebits = BIT18
OUTER_SET weapon_shortiesbit = BIT26 BOR BIT28



DEFINE_PATCH_MACRO decode_attack_type BEGIN
	PATCH_MATCH ~%stype%~
		WITH MELEE BEGIN
			type = 1
		END
		RANGED BEGIN
			type = 2
		END
		LAUNCH BEGIN
			type = 4
		END
		DEFAULT
			PATCH_FAIL ~unknown type %stype%~
	END
END
DEFINE_PATCH_FUNCTION thrown RET is_matched BEGIN
	is_matched = 0
	FOR (head = 0; head < head_cnt; head += 1) BEGIN
		cur_off = head * 0x38 + head_off
		READ_BYTE cur_off weapon_type
		PATCH_IF weapon_type = 2 BEGIN
			is_matched = 1
		END
	END
END

DEFINE_PATCH_FUNCTION flail RET is_matched BEGIN
	is_matched = 0
	READ_ASCII 0x22 anim (2)
	PATCH_IF ("%anim%" STRING_COMPARE_REGEXP "[Ff][Ll013]" = 0) BEGIN
		is_matched = 1
	END
END

DEFINE_PATCH_FUNCTION heavy RET is_matched BEGIN
	READ_LONG 0x1e unusability
	is_matched = unusability BAND BIT22
END

DEFINE_PATCH_FUNCTION composite RET is_matched BEGIN
	READ_LONG 0x1e unusability
	is_matched = unusability BAND BIT6
END

DEFINE_PATCH_FUNCTION runic RET is_matched BEGIN
	READ_STRREF UNIDENTIFIED_DESC unidentified_description
	is_matched = INDEX (~dwarven runes~ ~%unidentified_description%~) > 0
END

DEFINE_PATCH_FUNCTION arrow RET is_matched BEGIN
	is_matched = 5 == SHORT_AT 0x1c
END

DEFINE_PATCH_FUNCTION bolt RET is_matched BEGIN
	is_matched = 31 == SHORT_AT 0x1c
END

DEFINE_PATCH_FUNCTION bullet RET is_matched BEGIN
	is_matched = 14 == SHORT_AT 0x1c
END

ACTION_DEFINE_ASSOCIATIVE_ARRAY weapon_damage_type_value BEGIN
	PIERCING    => 1
	CRUSHING    => 2
	SLASHING    => 3
	MISSILE     => 4
	CRUSH_PIERC => 6
	SLASH_PIERC => 7
END

ACTION_DEFINE_ASSOCIATIVE_ARRAY weapon_damage_type_description BEGIN
	PIERCING    => Piercing
	CRUSHING    => Crushing
	SLASHING    => Slashing
	MISSILE     => Missile
	CRUSH_PIERC => ~Crushing or Piercing~
	SLASH_PIERC => ~Slashing or Piercing~
END

DEFINE_PATCH_FUNCTION get_from_weapon_2da
	INT_VAR column_number = 0
			use_enchantment = 0
	RET value
	BEGIN
		TEXT_SPRINT value ~_~
		PATCH_IF special_rules_row > 0 BEGIN
			READ_2DA_ENTRY_FORMER weapon_rules special_rules_row column_number value
		END
		PATCH_IF general_rules_row > 0 AND (~%value%~ STRING_EQUAL_CASE ~_~) BEGIN
			READ_2DA_ENTRY_FORMER weapon_rules general_rules_row column_number value
			
			PATCH_IF IS_AN_INT ~%value%~ AND use_enchantment BEGIN
				value = value + enchantment * use_enchantment
			END
		END
END

DEFINE_PATCH_FUNCTION get_base_from_weapon_2da
	INT_VAR column_number = 0
	RET value
	BEGIN
		TEXT_SPRINT value ~_~
		PATCH_IF general_rules_row > 0 BEGIN
			READ_2DA_ENTRY_FORMER weapon_rules general_rules_row column_number value
		END
END

DEFINE_PATCH_FUNCTION get_special_from_weapon_2da
	INT_VAR column_number = 0
	RET value
BEGIN
	TEXT_SPRINT value ~~
	PATCH_IF special_rules_row > 0 BEGIN
		READ_2DA_ENTRY_FORMER weapon_rules special_rules_row column_number value
		PATCH_IF ~%value%~ STRING_EQUAL_CASE ~_~ BEGIN
			TEXT_SPRINT value ~~
		END ELSE BEGIN
			TEXT_SPRINT value ~ (*)~
		END
	END
END

DEFINE_PATCH_FUNCTION write_from_weapon_2da
	INT_VAR column_number = 0
			use_enchantment = 0
			offset = 0
	RET
		value
	BEGIN
		LAUNCH_PATCH_FUNCTION get_from_weapon_2da
			INT_VAR column_number = column_number
				use_enchantment = use_enchantment
			RET
				value
		END
		PATCH_IF IS_AN_INT ~%value%~ BEGIN
			PATCH_IF size = 4 BEGIN
				WRITE_LONG offset value
			END ELSE PATCH_IF size = 2 BEGIN
				WRITE_SHORT offset value
			END ELSE PATCH_IF size = 1 BEGIN
				WRITE_BYTE offset value
			END
		END
END







DEFINE_PATCH_MACRO weapon_rules BEGIN
	READ_SHORT 0x1c category
	READ_LONG 0x18 flags
	PATCH_IF ((category >= 15 AND category <= 30 ) OR category = 57 OR category = 69 OR category = 14 OR category = 5 OR category = 31) AND (LONG_AT 0x18 BAND BIT2) BEGIN
		READ_LONG 0x64 head_off
		READ_SHORT 0x68 head_cnt
		cannot_backstab = 0
		READ_BYTE 0x31 proficiency
		READ_LONG 0x60 enchantment
		has_melee = 0
		has_thrown = 0
		has_launcher = 0
		description = 0
		TEXT_SPRINT cleric ~_~
		TEXT_SPRINT druid ~_~
		TEXT_SPRINT thief ~_~
		TEXT_SPRINT bard ~_~
		TEXT_SPRINT mage ~_~
		TEXT_SPRINT shorties ~_~
		TEXT_SPRINT damage_type_desc ~~
		TEXT_SPRINT melee_damage_type_desc ~~
		TEXT_SPRINT thrown_damage_type_desc ~~
		TEXT_SPRINT launcher_damage_type_desc ~~
		
		FOR (head = 0; head < head_cnt; head += 1) BEGIN
			cur_off = head * 0x38 + head_off
			READ_BYTE cur_off weapon_type

			general_rules_row = 0
			special_rules_row = 0
			TEXT_SPRINT comment_general ~~
			TEXT_SPRINT comment_special ~~

			FOR (maybe = 1; maybe < weapon_rules AND special_rules_row = 0; maybe += 1 ) BEGIN
				READ_2DA_ENTRY_FORMER weapon_rules maybe 0 comment
				READ_2DA_ENTRY_FORMER weapon_rules maybe 1 maybe_file
				READ_2DA_ENTRY_FORMER weapon_rules maybe 3 stype
				LAUNCH_PATCH_MACRO decode_attack_type
				
				PATCH_IF ~%maybe_file%~ STRING_EQUAL_CASE ~%SOURCE_RES%~ AND type = weapon_type BEGIN
					special_rules_row = maybe
					TEXT_SPRINT comment_special ~%comment%~
				END
			END

			FOR (maybe = 1; maybe < weapon_rules AND general_rules_row = 0; maybe += 1 ) BEGIN
				READ_2DA_ENTRY_FORMER weapon_rules maybe 0 comment
				READ_2DA_ENTRY_FORMER weapon_rules maybe 1 maybe_proficiency
				READ_2DA_ENTRY_FORMER weapon_rules maybe 2 special_rule
				READ_2DA_ENTRY_FORMER weapon_rules maybe 3 stype
				
				LAUNCH_PATCH_MACRO decode_attack_type
				
				PATCH_IF IS_AN_INT ~%maybe_proficiency%~ AND (maybe_proficiency = proficiency OR maybe_proficiency < 80) AND type = weapon_type BEGIN
					general_rules_row = maybe
					TEXT_SPRINT comment_general ~%comment%~
					has_melee = has_melee OR type = 1
					has_thrown = has_thrown OR type = 2
					has_launcher = has_launcher OR type = 4
				END
				
				PATCH_IF general_rules_row > 0 AND NOT (~%special_rule%~ STRING_EQUAL_CASE ~_~) BEGIN
					PATCH_IF INDEX ( ~!~ ~%special_rule%~ ) = 0 BEGIN
						LAUNCH_PATCH_FUNCTION SUBSTRING INT_VAR start = 1 length = STRING_LENGTH ~%special_rule%~ - 1 STR_VAR string = EVALUATE_BUFFER ~%special_rule%~ RET special_rule_not = substring END
						LAUNCH_PATCH_FUNCTION ~%special_rule_not%~ RET is_matched = is_matched END
						is_matched = NOT is_matched
					END ELSE BEGIN
						LAUNCH_PATCH_FUNCTION ~%special_rule%~ RET is_matched = is_matched END
					END
					PATCH_IF NOT is_matched BEGIN
						general_rules_row = 0
						TEXT_SPRINT comment_general ~~
					END
				END
			END
			
			PATCH_IF general_rules_row > 0 OR special_rules_row > 0 BEGIN
				LAUNCH_PATCH_FUNCTION write_from_weapon_2da
					INT_VAR column_number = 4
						use_enchantment = 0
						offset = 0x0e + cur_off
						size = 2
					RET range = value
				END
				LAUNCH_PATCH_FUNCTION get_base_from_weapon_2da
					INT_VAR column_number = 4
					RET range_base = value
				END
				LAUNCH_PATCH_FUNCTION get_special_from_weapon_2da
					INT_VAR column_number = 4
					RET range_special = value
				END
				LAUNCH_PATCH_FUNCTION write_from_weapon_2da
					INT_VAR column_number = 5
						use_enchantment = 1
						offset = 0x14 + cur_off
						size = 2
					RET	thac0 = value
				END
				LAUNCH_PATCH_FUNCTION get_base_from_weapon_2da
					INT_VAR column_number = 5
					RET	thac0_base = value
				END
				LAUNCH_PATCH_FUNCTION get_special_from_weapon_2da
					INT_VAR column_number = 5
					RET	thac0_special = value
				END
				LAUNCH_PATCH_FUNCTION write_from_weapon_2da
					INT_VAR column_number = 6
						use_enchantment = 0
						offset = 0x18 + cur_off
						size = 1
					RET	dice_number = value
				END
				LAUNCH_PATCH_FUNCTION get_special_from_weapon_2da
					INT_VAR column_number = 6
					RET dice_number_special = value
				END
				LAUNCH_PATCH_FUNCTION get_base_from_weapon_2da
					INT_VAR column_number = 6
					RET	dice_number_base = value
				END
				LAUNCH_PATCH_FUNCTION write_from_weapon_2da
					INT_VAR column_number = 7
						use_enchantment = 0
						offset = 0x16 + cur_off
						size = 1
					RET	dice_type = value
				END
				LAUNCH_PATCH_FUNCTION get_base_from_weapon_2da
					INT_VAR column_number = 7
					RET	dice_type_base = value
				END
				LAUNCH_PATCH_FUNCTION get_special_from_weapon_2da
					INT_VAR column_number = 7
					RET dice_type_special = value
				END
				LAUNCH_PATCH_FUNCTION write_from_weapon_2da
					INT_VAR column_number = 8
						use_enchantment = 1
						offset = 0x1a + cur_off
						size = 2
					RET	damage = value
				END
				LAUNCH_PATCH_FUNCTION get_base_from_weapon_2da
					INT_VAR column_number = 8
					RET	damage_base = value
				END
				LAUNCH_PATCH_FUNCTION get_special_from_weapon_2da
					INT_VAR column_number = 8
					RET damage_bonus_special = value
				END
				LAUNCH_PATCH_FUNCTION get_from_weapon_2da
					INT_VAR column_number = 9
						use_enchantment = 0
					RET
						damage_type = value
				END
				LAUNCH_PATCH_FUNCTION get_base_from_weapon_2da
					INT_VAR column_number = 9
					RET	damage_type_base = value
				END
				LAUNCH_PATCH_FUNCTION get_from_weapon_2da
					INT_VAR column_number = 10
						use_enchantment = 0
					RET
						backstab_flag = value
				END
				LAUNCH_PATCH_FUNCTION get_from_weapon_2da
					INT_VAR column_number = 11
						use_enchantment = 0 - 1
					RET
						speed_factor = value
				END
				LAUNCH_PATCH_FUNCTION get_base_from_weapon_2da
					INT_VAR column_number = 11
					RET	speed_factor_base = value
				END
				LAUNCH_PATCH_FUNCTION get_special_from_weapon_2da
					INT_VAR column_number = 11
					RET speed_factor_special = value
				END
				LAUNCH_PATCH_FUNCTION get_from_weapon_2da
					INT_VAR column_number = 12
						use_enchantment = 0
					RET
						min_speed_factor = value
				END
				PATCH_IF IS_AN_INT ~%speed_factor%~ BEGIN
					PATCH_IF IS_AN_INT ~%min_speed_factor%~ AND speed_factor < min_speed_factor BEGIN
						speed_factor = min_speed_factor
					END ELSE PATCH_IF speed_factor < 0 BEGIN
						speed_factor = 0
					END
					WRITE_BYTE cur_off + 0x12 speed_factor
				END
				LAUNCH_PATCH_FUNCTION write_from_weapon_2da
					INT_VAR column_number = 13
						use_enchantment = 0
						offset = 0x26
						size = 1
					RET	min_strength = value
				END
				LAUNCH_PATCH_FUNCTION get_base_from_weapon_2da
					INT_VAR column_number = 13
					RET	min_strength_base = value
				END
				LAUNCH_PATCH_FUNCTION get_special_from_weapon_2da
					INT_VAR column_number = 13
					RET min_strength_special = value
				END
				LAUNCH_PATCH_FUNCTION get_from_weapon_2da
					INT_VAR column_number = 14
						use_enchantment = 0
					RET
						cleric = value
				END
				LAUNCH_PATCH_FUNCTION get_from_weapon_2da
					INT_VAR column_number = 15
						use_enchantment = 0
					RET
						druid = value
				END
				LAUNCH_PATCH_FUNCTION get_from_weapon_2da
					INT_VAR column_number = 16
						use_enchantment = 0
					RET
						thief = value
				END
				LAUNCH_PATCH_FUNCTION get_from_weapon_2da
					INT_VAR column_number = 17
						use_enchantment = 0
					RET
						bard = value
				END
				LAUNCH_PATCH_FUNCTION get_from_weapon_2da
					INT_VAR column_number = 18
						use_enchantment = 0
					RET
						mage = value
				END
				LAUNCH_PATCH_FUNCTION get_from_weapon_2da
					INT_VAR column_number = 19
						use_enchantment = 0
					RET
						shorties = value
				END
				LAUNCH_PATCH_FUNCTION get_base_from_weapon_2da
					INT_VAR column_number = 20
						use_enchantment = 0
					RET
						attacks_per_round_base = value
				END
				LAUNCH_PATCH_FUNCTION get_from_weapon_2da
					INT_VAR column_number = 20
						use_enchantment = 0
					RET
						attacks_per_round = value
				END
				LAUNCH_PATCH_FUNCTION get_special_from_weapon_2da
					INT_VAR column_number = 20
					RET attacks_per_round_special = value
				END
				LAUNCH_PATCH_FUNCTION get_from_weapon_2da
					INT_VAR column_number = 21
						use_enchantment = 0
					RET
						description = value
				END
				
				PATCH_IF IS_AN_INT ~%backstab_flag%~ AND IS_AN_INT ~%thief%~ AND thief AND NOT backstab_flag AND has_melee = 1 BEGIN
					cannot_backstab = 1
				END
				PATCH_IF ~%damage_type%~ STRING_COMPARE_CASE ~_~ BEGIN
					WRITE_SHORT cur_off + 0x1c $weapon_damage_type_value(~%damage_type%~)
					
					TEXT_SPRINT damage_type_desc $weapon_damage_type_description(~%damage_type%~)
					
					PATCH_IF type = 1 BEGIN
						TEXT_SPRINT melee_damage_type_desc $weapon_damage_type_description(~%damage_type%~)
					END ELSE PATCH_IF type = 2 BEGIN
						TEXT_SPRINT thrown_damage_type_desc $weapon_damage_type_description(~%damage_type%~)
					END ELSE PATCH_IF type = 4 BEGIN
						TEXT_SPRINT launcher_damage_type_desc $weapon_damage_type_description(~%damage_type%~)
					END
				END
			END

		END
		PATCH_IF cannot_backstab BEGIN
			LAUNCH_PATCH_FUNCTION ADD_ITEM_EQEFFECT
				INT_VAR opcode = 0x107
					parameter1 = 0
					parameter2 = 1
					target = 1
					timing = 2
			END
		END
		
		PATCH_IF has_melee AND has_thrown BEGIN
			has_melee = 0
			
			LAUNCH_PATCH_FUNCTION DELETE_ITEM_HEADER
				INT_VAR header_type = 1
			END
		END
		
		PATCH_IF IS_AN_INT ~%cleric%~ AND IS_AN_INT ~%druid%~ AND IS_AN_INT ~%thief%~ AND IS_AN_INT ~%bard%~ AND IS_AN_INT ~%mage%~ AND IS_AN_INT ~%shorties%~  AND NOT (LONG_AT 0x1e BAND BIT11) AND NOT (BYTE_AT 0x2d BAND BIT6) BEGIN
			READ_LONG 0x1e unusability
			
			unusability = cleric ? unusability BAND BNOT weapon_clericbits : unusability BOR weapon_clericbits
			unusability = druid  ? unusability BAND BNOT  weapon_druidbits : unusability BOR  weapon_druidbits
			unusability = thief  ? unusability BAND BNOT  weapon_thiefbits : unusability BOR  weapon_thiefbits
			unusability = bard   ? unusability BAND BNOT   weapon_bardbits : unusability BOR   weapon_bardbits
			unusability = mage   ? unusability BAND BNOT   weapon_magebits : unusability BOR   weapon_magebits
			unusability = shorties ? unusability BAND BNOT weapon_shortiesbit : unusability BOR weapon_shortiesbit
			
			WRITE_LONG 0x1e unusability

		END

		PATCH_IF IS_AN_INT ~%attacks_per_round%~ BEGIN
			LAUNCH_PATCH_FUNCTION DELETE_ITEM_EQEFFECT_BY_VALUES INT_VAR opcode_to_delete = 1 value1_to_delete = (0 - 1) value2_to_delete = (0 - 1) END
			
			PATCH_IF attacks_per_round > 0 BEGIN
				LAUNCH_PATCH_FUNCTION ADD_ITEM_EQEFFECT
					INT_VAR opcode = 1
						parameter1 = attacks_per_round
						parameter2 = 1
						target = 1
						timing = 2
				END
			END
		END
		
		READ_STRREF UNIDENTIFIED_DESC desc
		PATCH_IF ("%desc%" STRING_COMPARE_REGEXP ~<Invalid Strref -?[0-9]+>~) BEGIN // checking for valid content in string
			INNER_PATCH_SAVE desc ~%desc%~ BEGIN
				LAUNCH_PATCH_FUNCTION ~redescribe_weapon~
					INT_VAR thac0 = thac0_base
						dice_number = dice_number_base
						dice_type = dice_type_base
						damage = damage_base
						speed_factor = speed_factor_base
						min_strength = min_strength_base
						range = range_base
					STR_VAR
						attacks_per_round = EVALUATE_BUFFER ~%attacks_per_round_base%~
				END
			END
			SAY_EVALUATED UNIDENTIFIED_DESC ~%desc%~ // write changes
		END
		PATCH_IF description BEGIN
			READ_STRREF DESC desc

			PATCH_IF ("%desc%" STRING_COMPARE_REGEXP ~<Invalid Strref -?[0-9]+>~) BEGIN // checking for valid content in string
				TEXT_SPRINT ~damage_special~ ~ (*)~
				PATCH_IF ~%damage_bonus_special%%dice_type_special%%dice_number_special%~ STRING_EQUAL_CASE ~~ BEGIN
					TEXT_SPRINT ~damage_special~ ~~
				END
				INNER_PATCH_SAVE desc ~%desc%~ BEGIN
					LAUNCH_PATCH_FUNCTION ~redescribe_weapon~
						INT_VAR thac0 = thac0
							dice_number = dice_number
							dice_type = dice_type
							damage = damage
							speed_factor = speed_factor
							min_strength = min_strength
							range = range
						STR_VAR
							range_special = EVALUATE_BUFFER ~%range_special%~
							thac0_special = EVALUATE_BUFFER ~%thac0_special%~
							damage_special = EVALUATE_BUFFER ~%damage_special%~
							speed_factor_special = EVALUATE_BUFFER ~%speed_factor_special%~
							min_strength_special = EVALUATE_BUFFER ~%min_strength_special%~
							attacks_per_round = EVALUATE_BUFFER ~%attacks_per_round%~
							attacks_per_round_special = EVALUATE_BUFFER ~%attacks_per_round_special%~
					END
				END
				SAY_EVALUATED DESC ~%desc%~ // write changes
			END
		END
	END
END
