
COPY ~rick_bigg_mod/2da/weapon_rules.2da~ ~weidu_external~
	READ_2DA_ENTRIES_NOW ~weapon_rules~ 20
BUT_ONLY



DEFINE_PATCH_MACRO decode_type BEGIN
	PATCH_MATCH ~%stype%~
		WITH MELEE BEGIN
			type = 1
		END
		RANGED BEGIN
			type = 2
		END
		LAUNCH BEGIN
			type = 4
		END
		DEFAULT
			PATCH_FAIL ~unknown type %stype%~
	END
END

DEFINE_PATCH_FUNCTION melee_only RET is_matched BEGIN
	is_matched = 1
	FOR (head = 0; head < head_cnt; head += 1) BEGIN
		cur_off = head * 0x38 + head_off
		READ_BYTE cur_off weapon_type
		PATCH_IF weapon_type = 2 BEGIN
			is_matched = 0
		END
	END
END

DEFINE_PATCH_FUNCTION thrown RET is_matched BEGIN
	is_matched = 0
	FOR (head = 0; head < head_cnt; head += 1) BEGIN
		cur_off = head * 0x38 + head_off
		READ_BYTE cur_off weapon_type
		PATCH_IF weapon_type = 2 BEGIN
			is_matched = 1
		END
	END
END

DEFINE_PATCH_FUNCTION flail RET is_matched BEGIN
	is_matched = 0
	READ_ASCII 0x22 anim (2)
	PATCH_IF ("%anim%" STRING_COMPARE_REGEXP "[Ff][Ll013]" = 0) BEGIN
		is_matched = 1
	END
END

DEFINE_PATCH_FUNCTION morning_st RET is_matched BEGIN
	is_matched = 0
	READ_ASCII 0x22 anim (2)
	PATCH_IF ("%anim%" STRING_COMPARE_REGEXP "[Mm][SsCc2]" = 0) BEGIN
		is_matched = 1
	END
END

DEFINE_PATCH_FUNCTION heavy_xbow RET is_matched BEGIN
	READ_LONG 0x1e unusability
	is_matched = unusability BAND BIT22
END

DEFINE_PATCH_FUNCTION light_xbow RET is_matched BEGIN
	READ_LONG 0x1e unusability
	is_matched = NOT (unusability BAND BIT6)
END

DEFINE_PATCH_FUNCTION comp_lbow RET is_matched BEGIN
	READ_LONG 0x1e unusability
	is_matched = unusability BAND BIT22
END

DEFINE_PATCH_FUNCTION long_bow RET is_matched BEGIN
	READ_LONG 0x1e unusability
	is_matched = NOT (unusability BAND BIT6)
END

ACTION_DEFINE_ASSOCIATIVE_ARRAY damage_type_value BEGIN
	PIERCING    => 1
	CRUSHING    => 2
	SLASHING    => 3
	MISSILE     => 4
	CRUSH_PIERC => 6
	SLASH_PIERC => 7
END

ACTION_DEFINE_ASSOCIATIVE_ARRAY damage_type_description BEGIN
	PIERCING    => Piercing
	CRUSHING    => Crushing
	SLASHING    => Slashing
	MISSILE     => Missile
	CRUSH_PIERC => ~Crushing or Piercing~
	SLASH_PIERC => ~Slashing or Piercing~
END

DEFINE_PATCH_FUNCTION get_from_2da
	INT_VAR column_number = 0
			use_enchantment = 0
	RET value
	BEGIN
		SPRINT value ~_~
		PATCH_IF special_rules_row > 0 BEGIN
			READ_2DA_ENTRY_FORMER weapon_rules special_rules_row column_number value
		END
		PATCH_IF general_rules_row > 0 AND (~%value%~ STRING_EQUAL_CASE ~_~) BEGIN
			READ_2DA_ENTRY_FORMER weapon_rules general_rules_row column_number value
			
			PATCH_IF IS_AN_INT ~%value%~ AND use_enchantment BEGIN
				value = value + enchantment * use_enchantment
			END
		END
END


DEFINE_PATCH_FUNCTION get_base_from_2da
	INT_VAR column_number = 0
	RET value
	BEGIN
		SPRINT value ~_~
		PATCH_IF general_rules_row > 0 BEGIN
			READ_2DA_ENTRY_FORMER weapon_rules general_rules_row column_number value
		END
END

DEFINE_PATCH_FUNCTION write_from_2da
	INT_VAR column_number = 0
			use_enchantment = 0
			offset = 0
	RET
		value
	BEGIN
		LAUNCH_PATCH_FUNCTION get_from_2da
			INT_VAR column_number = column_number
				use_enchantment = use_enchantment
			RET
				value
		END
		PATCH_IF IS_AN_INT ~%value%~ BEGIN
			PATCH_IF size = 4 BEGIN
				WRITE_LONG offset value
			END ELSE PATCH_IF size = 2 BEGIN
				WRITE_SHORT offset value
			END ELSE PATCH_IF size = 1 BEGIN
				WRITE_BYTE offset value
			END
		END
END


DEFINE_PATCH_FUNCTION redescribe_weapon
	INT_VAR thac0 = 0
		dice_number = 0
		dice_type = 0
		damage = 0
		speed_factor = 0
		min_strength = 0
BEGIN

	PATCH_IF thac0 = 0 BEGIN
		SPRINT thac0_string ~\1~
	END ELSE PATCH_IF thac0 > 0 BEGIN
		SPRINT thac0_string ~THAC0: +%thac0%\1~
	END ELSE BEGIN
		SPRINT thac0_string ~THAC0: %thac0%\1~
	END
	PATCH_IF INDEX_BUFFER( ~THAC0:[^,%WNL%]*\(,?.*\)$~ ) > 0 BEGIN
		REPLACE_TEXTUALLY ~^THAC0:[^,%WNL%]*\(,?.*\)$~ ~%thac0_string%~
	END ELSE BEGIN
		REPLACE_TEXTUALLY ~^Damage:\(\)~ ~%thac0_string%%WNL%Damage:~
	END
	
	PATCH_IF damage = 0 AND dice_type * dice_number = 0 BEGIN
		SPRINT damage_string ~~
	END ELSE BEGIN
		PATCH_IF dice_type * dice_number = 0 AND NOT has_launcher BEGIN
			SPRINT damage_string ~Damage: %damage%\1%WNL%~
		END PATCH_IF dice_type * dice_number = 0 AND has_launcher BEGIN
			SPRINT damage_string ~Damage: +%damage%\1%WNL%~
		END ELSE PATCH_IF damage > 0 BEGIN
			SPRINT damage_string ~Damage: %dice_number%d%dice_type%+%damage%\1%WNL%~
		END ELSE PATCH_IF damage < 0 BEGIN
			SPRINT damage_string ~Damage: %dice_number%d%dice_type%%damage%\1%WNL%~
		END ELSE PATCH_IF damage = 0 BEGIN
			SPRINT damage_string ~Damage: %dice_number%d%dice_type%\1%WNL%~
		END
		
		PATCH_IF has_melee AND has_thrown BEGIN
			SPRINT damage_string ~%damage_string%Damage type (melee): %melee_damage_type_desc%%WNL%Damage Type (thrown): %thrown_damage_type_desc%~
		END ELSE BEGIN
			SPRINT damage_string ~%damage_string%Damage type: %damage_type_desc%~
		END
	END
	
	REPLACE_TEXTUALLY ~^Damage type: .*$~ ~~
	REPLACE_TEXTUALLY ~^Damage type (.*): .*$~ ~~
	
	PATCH_IF INDEX_BUFFER( ~Damage:[^,%WNL%]*\(,?.*\)$~ ) > 0 BEGIN
		REPLACE_TEXTUALLY ~^Damage:[^,%WNL%]*\(,?.*\)$~ ~%damage_string%~
	END ELSE BEGIN
		REPLACE_TEXTUALLY ~^Speed Factor:\(\)~ ~%damage_string%%WNL%Speed Factor:~
	END
	
	REPLACE_TEXTUALLY ~^Speed Factor:.*$~ ~Speed Factor: %speed_factor%~
	
	PATCH_IF INDEX_BUFFER ( ~Requires:[^_]* [0-9]+ Strength$~ ) > 0 BEGIN
		REPLACE_TEXTUALLY ~^Requires:\([^_]*\) [0-9]+ Strength$~ ~Requires:\1 %min_strength% Strength~
	END ELSE PATCH_IF INDEX_BUFFER ( ~Requires:$~ ) > 0 BEGIN
		REPLACE_TEXTUALLY ~^Requires:$~ ~Requires:%WNL% %min_strength% Strength~
	END ELSE BEGIN
		REPLACE_TEXTUALLY ~^Type:\(.*\)$~ ~Type:\1%WNL%Requires:%WNL% %min_strength% Strength~
	END
END



COPY_EXISTING_REGEXP ~^.*\.itm~ ~override~
	READ_LONG 0x64 head_off
	READ_SHORT 0x68 head_cnt
	cannot_backstab = 0
	READ_BYTE 0x31 proficiency
	READ_LONG 0x60 enchantment
	has_melee = 0
	has_thrown = 0
	has_launcher = 0
	description = 0
	SPRINT cleric ~_~
	SPRINT druid ~_~
	SPRINT thief ~_~
	SPRINT bard ~_~
	SPRINT mage ~_~
	SPRINT damage_type_desc ~~
	SPRINT melee_damage_type_desc ~~
	SPRINT thrown_damage_type_desc ~~
	
	FOR (head = 0; head < head_cnt; head += 1) BEGIN
		cur_off = head * 0x38 + head_off
		READ_BYTE cur_off weapon_type

		general_rules_row = 0
		special_rules_row = 0
		SPRINT comment_general ~~
		SPRINT comment_special ~~
	
		FOR (maybe = 1; maybe < weapon_rules AND special_rules_row = 0; maybe += 1 ) BEGIN
			READ_2DA_ENTRY_FORMER weapon_rules maybe 0 comment
			READ_2DA_ENTRY_FORMER weapon_rules maybe 1 maybe_file
			READ_2DA_ENTRY_FORMER weapon_rules maybe 3 stype
			LAUNCH_PATCH_MACRO decode_type
			
			PATCH_IF ~%maybe_file%~ STRING_EQUAL_CASE ~%SOURCE_RES%~ AND type = weapon_type BEGIN
				special_rules_row = maybe
				SPRINT comment_special ~%comment%~
			END
		END

		FOR (maybe = 1; maybe < weapon_rules AND general_rules_row = 0; maybe += 1 ) BEGIN
			READ_2DA_ENTRY_FORMER weapon_rules maybe 0 comment
			READ_2DA_ENTRY_FORMER weapon_rules maybe 1 maybe_proficiency
			READ_2DA_ENTRY_FORMER weapon_rules maybe 2 special_rule
			READ_2DA_ENTRY_FORMER weapon_rules maybe 3 stype
			
			LAUNCH_PATCH_MACRO decode_type
			
			PATCH_IF IS_AN_INT ~%maybe_proficiency%~ AND maybe_proficiency = proficiency AND type = weapon_type BEGIN
				general_rules_row = maybe
				SPRINT comment_general ~%comment%~
				has_melee = has_melee OR type = 1
				has_thrown = has_thrown OR type = 2
				has_launcher = has_launcher OR type = 4
			END
			
			PATCH_IF general_rules_row > 0 AND NOT (~%special_rule%~ STRING_EQUAL_CASE ~_~) BEGIN
				LAUNCH_PATCH_FUNCTION ~%special_rule%~ RET is_matched = is_matched END
				PATCH_IF NOT is_matched BEGIN
					general_rules_row = 0
					SPRINT comment_general ~~
				END
			END
		END
		
		PATCH_IF general_rules_row > 0 OR special_rules_row > 0 BEGIN
			LAUNCH_PATCH_FUNCTION write_from_2da
				INT_VAR column_number = 4
					use_enchantment = 0
					offset = 0x0e + cur_off
					size = 2
				RET range = value
			END
			LAUNCH_PATCH_FUNCTION write_from_2da
				INT_VAR column_number = 5
					use_enchantment = 1
					offset = 0x14 + cur_off
					size = 2
				RET	thac0 = value
			END
			LAUNCH_PATCH_FUNCTION get_base_from_2da
				INT_VAR column_number = 5
				RET	thac0_base = value
			END
			LAUNCH_PATCH_FUNCTION write_from_2da
				INT_VAR column_number = 6
					use_enchantment = 0
					offset = 0x18 + cur_off
					size = 1
				RET	dice_number = value
			END
			LAUNCH_PATCH_FUNCTION get_base_from_2da
				INT_VAR column_number = 6
				RET	dice_number_base = value
			END
			LAUNCH_PATCH_FUNCTION write_from_2da
				INT_VAR column_number = 7
					use_enchantment = 0
					offset = 0x16 + cur_off
					size = 1
				RET	dice_type = value
			END
			LAUNCH_PATCH_FUNCTION get_base_from_2da
				INT_VAR column_number = 7
				RET	dice_type_base = value
			END
			LAUNCH_PATCH_FUNCTION write_from_2da
				INT_VAR column_number = 8
					use_enchantment = 1
					offset = 0x1a + cur_off
					size = 2
				RET	damage = value
			END
			LAUNCH_PATCH_FUNCTION get_base_from_2da
				INT_VAR column_number = 8
				RET	damage_base = value
			END
			LAUNCH_PATCH_FUNCTION get_from_2da
				INT_VAR column_number = 9
					use_enchantment = 0
				RET
					damage_type = value
			END
			LAUNCH_PATCH_FUNCTION get_base_from_2da
				INT_VAR column_number = 9
				RET	damage_type_base = value
			END
			LAUNCH_PATCH_FUNCTION get_from_2da
				INT_VAR column_number = 10
					use_enchantment = 0
				RET
					backstab_flag = value
			END
			LAUNCH_PATCH_FUNCTION get_from_2da
				INT_VAR column_number = 11
					use_enchantment = 0 - 1
				RET
					speed_factor = value
			END
			LAUNCH_PATCH_FUNCTION get_base_from_2da
				INT_VAR column_number = 11
				RET	speed_factor_base = value
			END
			LAUNCH_PATCH_FUNCTION get_from_2da
				INT_VAR column_number = 12
					use_enchantment = 0
				RET
					min_speed_factor = value
			END
			PATCH_IF IS_AN_INT ~%speed_factor%~ BEGIN
				PATCH_IF IS_AN_INT ~%min_speed_factor%~ AND speed_factor < min_speed_factor BEGIN
					speed_factor = min_speed_factor
				END ELSE PATCH_IF speed_factor < 0 BEGIN
					speed_factor = 0
				END
				WRITE_BYTE cur_off + 0x12 speed_factor
			END
			LAUNCH_PATCH_FUNCTION write_from_2da
				INT_VAR column_number = 13
					use_enchantment = 0
					offset = 0x26
					size = 1
				RET	min_strength = value
			END
			LAUNCH_PATCH_FUNCTION get_base_from_2da
				INT_VAR column_number = 13
				RET	min_strength_base = value
			END
			LAUNCH_PATCH_FUNCTION get_from_2da
				INT_VAR column_number = 14
					use_enchantment = 0
				RET
					cleric = value
			END
			LAUNCH_PATCH_FUNCTION get_from_2da
				INT_VAR column_number = 15
					use_enchantment = 0
				RET
					druid = value
			END
			LAUNCH_PATCH_FUNCTION get_from_2da
				INT_VAR column_number = 16
					use_enchantment = 0
				RET
					thief = value
			END
			LAUNCH_PATCH_FUNCTION get_from_2da
				INT_VAR column_number = 17
					use_enchantment = 0
				RET
					bard = value
			END
			LAUNCH_PATCH_FUNCTION get_from_2da
				INT_VAR column_number = 18
					use_enchantment = 0
				RET
					mage = value
			END
			LAUNCH_PATCH_FUNCTION get_from_2da
				INT_VAR column_number = 19
					use_enchantment = 0
				RET
					description = value
			END
			
			PATCH_IF IS_AN_INT ~%backstab_flag%~ AND IS_AN_INT ~%thief%~ AND thief AND NOT backstab_flag AND has_melee = 1 BEGIN
				cannot_backstab = 1
			END
			PATCH_IF ~%damage_type%~ STRING_COMPARE_CASE ~_~ BEGIN
				WRITE_SHORT cur_off + 0x1c $damage_type_value(~%damage_type%~)
				
				SPRINT damage_type_desc $damage_type_description(~%damage_type%~)
				
				PATCH_IF type = 1 BEGIN
					SPRINT melee_damage_type_desc $damage_type_description(~%damage_type%~)
				END ELSE PATCH_IF type = 2 BEGIN
					SPRINT thrown_damage_type_desc $damage_type_description(~%damage_type%~)
				END
			END
		END
	END
	PATCH_IF cannot_backstab BEGIN
		LAUNCH_PATCH_FUNCTION ADD_ITEM_EQEFFECT
			INT_VAR opcode = 0x107
				parameter1 = 0
				parameter2 = 1
				target = 1
				timing = 2
		END
	END
	
	PATCH_IF IS_AN_INT ~%cleric%~ AND IS_AN_INT ~%druid%~ AND IS_AN_INT ~%thief%~ AND IS_AN_INT ~%bard%~ AND IS_AN_INT ~%mage%~ BEGIN
		READ_LONG 0x1e unusability
		
		clericbits = BIT7 BOR BIT8 BOR BIT10 BOR BIT14 BOR BIT15
		druidbits = BIT12 BOR BIT30
		thiefbits = BIT9 BOR BIT16 BOR BIT17 BOR BIT19 BOR BIT22
		bardbits = BIT6
		magebits = BIT18
		
		unusability = cleric ? unusability BAND BNOT clericbits : unusability BOR clericbits
		unusability = druid  ? unusability BAND BNOT  druidbits : unusability BOR  druidbits
		unusability = thief  ? unusability BAND BNOT  thiefbits : unusability BOR  thiefbits
		unusability = bard   ? unusability BAND BNOT   bardbits : unusability BOR   bardbits
		unusability = mage   ? unusability BAND BNOT   magebits : unusability BOR   magebits
		
		WRITE_LONG 0x1e unusability
	END
	
	PATCH_IF description BEGIN
		READ_STRREF UNIDENTIFIED_DESC desc
		PATCH_IF ("%desc%" STRING_COMPARE_REGEXP ~<Invalid Strref -?[0-9]+>~) BEGIN // checking for valid content in string
			INNER_PATCH_SAVE desc ~%desc%~ BEGIN
				LAUNCH_PATCH_FUNCTION ~redescribe_weapon~
					INT_VAR thac0 = thac0_base
						dice_number = dice_number_base
						dice_type = dice_type_base
						damage = damage_base
						speed_factor = speed_factor_base
						min_strength = min_strength_base
				END
			END
			SAY_EVALUATED UNIDENTIFIED_DESC ~%desc%~ // write changes
		END
		READ_STRREF DESC desc
		PATCH_IF ("%desc%" STRING_COMPARE_REGEXP ~<Invalid Strref -?[0-9]+>~) BEGIN // checking for valid content in string
			INNER_PATCH_SAVE desc ~%desc%~ BEGIN
				LAUNCH_PATCH_FUNCTION ~redescribe_weapon~
					INT_VAR thac0 = thac0
						dice_number = dice_number
						dice_type = dice_type
						damage = damage
						speed_factor = speed_factor
						min_strength = min_strength
				END
			END
			SAY_EVALUATED DESC ~%desc%~ // write changes
		END
	END
BUT_ONLY
